### ISSUE TITLE
Cannot find name 'Awaited'

### ISSUE THREAD

**Issue by lhlyu** [posva/pinia#1006]
### Reproduction

npm or pnpm run build in the vue project created by vite

### Steps to reproduce the behavior

1. npm or pnpm run build
2. see error

### Expected behavior

Shouldn't error

### Actual behavior

```shell
> vue-tsc --noEmit && vite build

node_modules/pinia/dist/pinia.d.ts:35:55 - error TS2304: Cannot find name 'Awaited'.

35 } ? F extends (value: infer V, ...args: any) => any ? Awaited<V> : never : T;
                                                         ~~~~~~~


Found 1 error.
```

### Additional information

- npm: `8.3.0`
- node: `17.3.0`
- typescript: `4.5.5`
- pinia: `2.0.10`

- package.json: 
```json
{
  "scripts": {
    "dev": "vite --host",
    "build": "vue-tsc --noEmit && vite build",
    "serve": "vite preview --host"
  },
  "license": "MIT",
  "dependencies": {
    "axios": "^0.24.0",
    "pinia": "^2.0.10",
    "vue": "^3.2.29",
    "vue-router": "^4.0.12"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.10.2",
    "@vue/compiler-sfc": "^3.2.29",
    "autoprefixer": "^10.4.2",
    "postcss": "^8.4.5",
    "prettier": "^2.5.1",
    "sass": "^1.49.0",
    "typescript": "^4.5.5",
    "vite": "^2.7.13",
    "vue-tsc": "^0.1.7"
  }
}
```

**Comment by posva** [comment]
Seem like a cache issue in your end. There is no typed names Awaited used in 2.0.10

**Comment by lhlyu** [comment]
> Seem like a cache issue in your end. There is no typed names Awaited used in 2.0.10

@posva 

[https://cdn.jsdelivr.net/npm/pinia@2.0.10/dist/pinia.d.ts](https://cdn.jsdelivr.net/npm/pinia@2.0.10/dist/pinia.d.ts)

`Awaited` appears on line 35.

[location of the source code](https://github.com/vuejs/pinia/blob/22512dad0db824335e6a358654579fa3b50137c6/packages/pinia/src/types.ts#L168)

I have cleared the cache and still have this problem.

**Comment by posva** [comment]
Thanks, GitHub search lied to me 😅

<img width="764" alt="Screenshot 2022-01-30 at 10 06 16" src="https://user-images.githubusercontent.com/664177/151693538-7ad04d68-6459-40da-a4a5-62ba8d4f56ac.png">
