### ISSUE TITLE
Mocking stores in component unit tests

### ISSUE THREAD

**Issue by rijkvanzanten** [posva/pinia#101]
Hi there! I had the need to mock an imported `useStore` function in my unit tests, and was having some trouble with setting up the mocks in the test properly. I came up with the following solution:

`component.vue`

```vue
<template>
    <button @click="addOne">Add 1</button>
</template>

<script lang="ts">
import { defineComponent } from '@vue/composition-api';
import { useCounterStore } from '../stores/counter';

export default defineComponent({
    setup() {
        const counterStore = useCounterStore();

        return { addOne };

        function addOne() {
            counterStore.add(1);
        }
    }
});
</script>
```

`component.test.js`

```js
import { shallowMount } from '@vue/test-utils';
import CounterComponent from './component.vue';
import { useCounterStore } from '../stores/counter';

describe('Component', () => {
    it('Calls the add method on the counter store', () => {
        const counterStore = useCounterStore({});
        jest.spyOn(counterStore, 'add');

        const component = shallowMount(CounterComponent);
        component.find('button').trigger('click');

        expect(counterStore.add).toHaveBeenCalledWith(1);
    });
});
```

**Comment by rijkvanzanten** [comment]
Do you have any other recommendations @posva? This works well for checking action calls, but gets a little tricky once you have a component that relies on a getter

**Comment by rijkvanzanten** [comment]
I also just realized another mistake I made: when testing / mocking two stores at the same time, make sure to pass them the same instance of `req` to make sure they're aware of each other's changes:

```js
it('Does not work', () => {
    const firstStore = useFirstStore({});
    const secondStore = useSecondStore({});

    firstStore.state.value = 'test';

    // secondStore won't be able to read this value from first store
});

it('Works', () => {
    const req = {};
    const firstStore = useFirstStore(req);
    const secondStore = useSecondStore(req);

    firstStore.state.value = 'test';

    // secondStore now correctly reads the `'test'` value from firstStore
});
```

**Comment by posva** [comment]
Your examples looks good. Getters are difficult to mock without overriding the actual store.

I think testing needs a bit more thinking for nested stores. Probably a helper function that allows to mock the original require of the store object similar to https://github.com/posva/vuex-mock-store

**Comment by MartinMalinda** [comment]
Maybe it would possible to use the `provide & inject` pattern to have your own wrappers functions for `useFirstStore()` and `useSecondStore`?

Some top level component (App) would do `provideFirstStore(firstStore)` `provideSecondStore(secondStore)`. Everywhere else you would use your own version of `useFirstStore()`, `useSecondStore()`.

In component tests you would be able to provide the actual stores or mocks in the `parentComponent`.

**Comment by MartinMalinda** [comment]
I've used this pattern for my `useStore()` for VueX.

```ts
export const storeKey = '__store';

export function provideStore(store): void {
  provide(storeKey, store);
}

export function useStore(): Store<any> {
  const store: Store<any> | void = inject(storeKey);
  if (!store) {
    throw new Error(`Store has not been provided!`);
  }

  return store;
}
```

```ts
export function createProviderComponent({
  $store,
  $auth,
}: ProvideOptions) {
  return createComponentStub('provider', (props, context) => {
    if ($store) {
      provideStore($store as Store<any>);
    }

    if ($auth) {
      provideAuth($auth as Auth);
    }
  });
}
```

```ts
wrapper = mount(SomeComponent, {
      parentComponent: createProviderComponent({ $store }),
    });
```

**Comment by BenShelton** [comment]
This workaround doesn't seem to work as of v0.5.1. First off, you cannot use an empty object as an argument for `useCounterStore` as it just throws `Cannot read property 'value' of undefined`.

Instead I've been trying to use `createPinia` and passing that, or simply passing nothing, but no matter what I do it seems that spying on the action never actually gets triggered if called from the component, so I guess it must be unique per instance? The _state_ DOES get updated though, so if you check `expect(counterStore.count).toBe(1)` the test passes.

The only way I've been able to accomplish something similar is mocking the entire import like so:

```ts
jest.mock('../counter', () => {
  const mockAdd = jest.fn()
  const { useCounterStore } = jest.requireActual('../counter')
  return {
    useCounterStore () {
      const store = useCounterStore()
      store.add = mockAdd
      return store
    }
  }
})
```

and then changing the test to the following passes:

```ts
 it('Calls the add method on the counter store', () => {
    const pinia = createPinia()
    const counterStore = useCounterStore(pinia)
    jest.spyOn(counterStore, 'add')

    const component = shallowMount(CounterComponent, {
      pinia
    })

    component.find('button').trigger('click')

    expect(counterStore.count).toBe(0) // <--- Note the state is not updated at all though
    expect(counterStore.add).toHaveBeenCalledWith(1)
  })
```

but this is far from ideal.

Any ideas on a better way to spy on an action or mock it's implementation?

**Comment by posva** [comment]
Mocking stores is still in my roadmap but I haven't been able to get there yet. Ideally, there would be a global plugin, package, or setting that makes it easy and automatically spies on actions similar to https://github.com/posva/vuex-mock-store

**Comment by BenShelton** [comment]
Looking more into the source code it seems that the actions are wrapped which makes sense because of the ability to register callbacks in an action's lifecycle. So spying on the action itself is spying on this wrapper, not the original action.

So to access the unwrapped actions, we can use a plugin which just adds another property to each store called `originalActions` with an extra declaration, then create a reusable function which can be used in any spec file to create a store with actions we can spy on:

```ts
// pinia.d.ts (or another declaration file in scope)
import 'pinia'

declare module 'pinia' {
  export interface PiniaCustomProperties<Id, S, G, A> {
    originalActions: A
  }
}

// unit-test-helpers.ts (or similar)
const originalActionsPlugin: PiniaStorePlugin = ({ store, options }) => {
  store.originalActions = options.actions!
}
export function createTestPinia (): Pinia {
  const pinia = createPinia()
  pinia.use(originalActionsPlugin)
  return pinia
}

// Test.spec.ts
it('Calls the add method on the counter store', () => {
    const pinia = createTestPinia()
    const component = shallowMount(CounterComponent, {
      pinia // must be provided as a component option (I think?)
    })
    const counterStore = useCounterStore(pinia) // I didn't need to provide pinia here, but it might be needed in some cases (?)

    // spy but still allow original action to run
    jest.spyOn(counterStore.originalActions, 'add')

    component.find('button').trigger('click')

    expect(counterStore.count).toBe(1) // state was updated as the original action still runs ✅ 
    expect(counterStore.originalActions.add).toHaveBeenCalledWith(1)

    counterStore.$reset()

    jest.spyOn(counterStore.originalActions, 'add')
      .mockClear()
      .mockReturnValue() // stop original action implementation from running

    component.find('button').trigger('click')

    expect(counterStore.count).toBe(0) // state was not updated, the original action did not run ✅ 
    expect(counterStore.originalActions.add).toHaveBeenCalledWith(1)
  })
```

This seems like the simplest and most type safe way to do this currently, though I'd be interested in any other ideas 😄

**Comment by posva** [comment]
Working on a doc page at https://pinia.esm.dev/cookbook/testing.html 

Current usage can be seen at https://github.com/posva/pinia/blob/v2/__tests__/testing.spec.ts. **Feedback welcome!**

This will likely become an external module

**Comment by posva** [comment]
Has anybody tried the `createTestingPinia()`? I will move the functions to a new package in the future once I move pinia to a mono repo and was looking for some feedback/issues people have encountered (apart from the still non-existent docs 😄 )

**Comment by BenShelton** [comment]
> Has anybody tried the `createTestingPinia()`? I will move the functions to a new package in the future once I move pinia to a mono repo and was looking for some feedback/issues people have encountered (apart from the still non-existent docs 😄 )

I haven't yet as we've instead wrote our own helper which has made testing a dream so just wanted to share what we found to be helpful that could improve `createTestingPinia`.

The syntax we use is providing an optional callback function, the arguments to that function are extra helper methods which allow creating spies (which I see already exists) and seeding a default state to stores which is **really helpful**. It looks a bit like this:

```ts
let actionSpy: jest.SpyInstance
const wrapper = shallowMount(Component, {
  pinia: createTestPinia(({ setState, spyAction }) => {
    setState(createSomeStore,  { key: 'value' })
    actionSpy = spyAction(createAnotherStore, 'actionName').mockResolvedValue(null)
  })
  // ...
}
```

I would definitely request having some way to set initial state, the function itself just uses `store.$patch` and of course is type safe. You can create a test Pinia instance before mounting, set the state, and then mount, but this kind of shorthand is really nice to work with.

Apart from that the current implementation of `createTestingPinia` shares pretty much the same features we've found helpful, thanks for making Pinia so simple to customise and extend ❤️

**Comment by posva** [comment]
Thanks for the feedback! Setting an initial state for testing could be useful. Maybe I can find a way to have autocompletion when passing the initial state:

```js
createTestingPinia({
  state: {
    auth: {
      // autocomplete
    }
  }
})
```

It would all be about making the function aware of existing stores like `createTestingPinia(options, useAuthStore, useOtherStore, etc)` (which I haven't tested)

**Comment by BenShelton** [comment]
I tried that sort of syntax initially and it was a nightmare to get TS to infer the types without being verbose (such as declaring every store up front which I wanted to avoid) hence the callback function syntax which was much easier to implement and type correctly. But I do agree that syntax is more user friendly in general so if it's possible it'd be preferable.

To be honest our implementation of `setState` is just a wrapper around `$patch` so even just providing a hook of some sort would provide equivalent behaviour:

```ts
createTestingPinia({
  afterCreate: () => {
    const someStore = useSomeStore()
    someStore.$patch({ key: 'value' })
  }
})
```

Then the user can do whatever they want with the stores but still be able to have everything initialised as they want before the pinia instance is used by the component.

**Comment by posva** [comment]
Right, but that `afterCreate` would then be the same as just running some code after creating the testing pinia (since there is no async code running).

I want to explore an option like you proposed. I think an initial version without autocompletion is fine too.

**Comment by posva** [comment]
Closing this as the package `@pinia/testing` has been released. It still needs to be documented better.

**Comment by fcomrqz** [comment]
Is there a way to initialize the state before mounting?

**Comment by posva** [comment]
```ts
const pinia = createTestingPinia()

pinia.state.value.myStore = newState
```
