### ISSUE TITLE
Remove internal properties (start with _) from interfaces

### ISSUE THREAD

**Issue by posva** [posva/pinia#1013]
Types like `Store` and `Pinia` still include some of the internal properties (marked as `@internal`). This shouldn't happen as they should be removed thanks to api-extractor but something is likely blocking it.

This would prevent polluting public interfaces as said in

- #937 

A working example is vue reactivity:

```ts
export declare class ReactiveEffect<T = any> {
    fn: () => T;
    scheduler: EffectScheduler | null;
    active: boolean;
    deps: Dep[];
    parent: ReactiveEffect | undefined;
    /* Excluded from this release type: computed */
    /* Excluded from this release type: allowRecurse */
    onStop?: () => void;
    onTrack?: (event: DebuggerEvent) => void;
    onTrigger?: (event: DebuggerEvent) => void;
    constructor(fn: () => T, scheduler?: EffectScheduler | null, scope?: EffectScope);
    run(): T | undefined;
    stop(): void;
}
```

Notice the "Excluded from ..." vs leaving the `@internal` flag in pinia types:

```ts
 * Every application must own its own pinia to be able to create stores
 */
export declare interface Pinia {
    install: (app: App) => void;
    /**
     * root state
     */
    state: Ref<Record<string, StateTree>>;
    /**
     * Adds a store plugin to extend every store
     *
     * @param plugin - store plugin to add
     */
    use(plugin: PiniaPlugin): Pinia;
    /**
     * Installed store plugins
     *
     * @internal
     */
    _p: PiniaPlugin[];
// ...
}
```

**Comment by suyingtao** [comment]
> Types like Store and Pinia still include some of the internal properties (marked as @internal). This shouldn't happen as they should be removed thanks to api-extractor but something is likely blocking it.

I think we can use `publicTrimmedFilePath` instead of `untrimmedFilePath` in `api-extractor.json` to remove internal properties. But now `@internal` is overused so pinia.d.ts file has a lot of errors when we use `publicTrimmedFilePath`.

**Comment by posva** [comment]
@suyingtao Thanks, I didn't see I wasn't using the right option 🤦‍♂️
