### ISSUE TITLE
Pinia bundle size increased after version 2

### ISSUE THREAD

**Issue by sarayourfriend** [posva/pinia#1015]
### Reproduction

https://stackblitz.com/edit/github-ef8lgu

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/github-ef8lgu
2. Run `yarn build` in the terminal
3. Inspect the output bundle size for `pinia`. It will look something like the following:

```
███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
file:            /node_modules/pinia/dist/pinia.esm-browser.js
bundle space:    6.75 %
rendered size:   15.961 KB
original size:   70.567 KB
code reduction:  77.38 %
dependents:      2
  - /src/stores/counter.ts
  - /src/main.ts
```

### Expected behavior

Pinia's website says the library weighs around 1kb.

### Actual behavior

I'm not sure why this particular build generates a nearly 16 kb file. In particular I'm confused because Bundlephobia says it's 11kb: https://bundlephobia.com/package/pinia@2.0.11

Even still, the gzipped version of the library is at least 4 times bigger than the advertized size, if not actually more than that in the typical use case.

### Additional information

Based on the bundlephobia graph, it seems like the switch to version 2 came with a doubling of the library size.

Compared to Vuex, Pinia is actually slightly bigger currently based on Bundlephobia's numbers.

Also: **I may be reading all of this incorrectly** in which case please let me know what the correct way for estimating Pinia's bundle size impact would be compared to Vuex. I was excited by Pinia's promise of being only 1kb but I'm confused where that claim comes from at this point.

**Comment by posva** [comment]
16kb is during dev to include all of the devtools features (which actually weight more than pinia itself). Pinia is around 1.5kb during production build. Bundlephobia isn't able to build in production mode like a vite app. You can check the `size` script in this repo for more info.

**Comment by sarayourfriend** [comment]
Thanks for the explanation! What's the correct way to build Pinia for production then? In the reproduction example I linked above, even if you build using `NODE_ENV=production yarn build` Pinia's size is still reported as 16kb. I couldn't find anything in the Pinia documentation website indicating how to exclude the dev tools; forgive me if I am missing this or if it is obvious!
