### ISSUE TITLE
Reactivity lost when calling useStore() before state hydration

### ISSUE THREAD

**Issue by epistemery** [posva/pinia#1029]
### Reproduction

The Test `keeps getters reactive when hydrating` in https://github.com/vuejs/pinia/blob/v2/packages/pinia/__tests__/getters.spec.ts fails when changing the order of state hydration and `useStore()`: https://github.com/epistemery/pinia/commit/c055624d5f09e9198696717ea14e0a0a06a39836

### Steps to reproduce the behavior

Clone https://github.com/epistemery/pinia/tree/failing-reactivity-after-state-replacement and run tests

### Expected behavior

Tests should pass, store should keep reactivity even if `useStore()` is called before hydration. Am I wrong in assuming that Pinia should behave this way?

### Actual behavior

Test fails with `store.name` being `Eduardo` instead of `Jack`.

### Additional information

Related Isssue: https://github.com/vuejs/pinia/issues/619

**Comment by posva** [comment]
This is expected behavior. State hydration must happen before mounting the app and therefore before starting using any store
