### ISSUE TITLE
Obtaining type of the store's instance through `typeof`

### ISSUE THREAD

**Issue by DamianGlowala** [posva/pinia#1052]
### What problem is this solving

Allowing to declare a variable's type in TS enviroment (in advance) equal to the exact representation of the Pinia store, before the variable's value is assigned (of which type otherwise would be naturally inferred by the `useStore()` return type).

### Proposed solution

Would it be possible to leverage `typeof` and, instead of obtaining `StoreDefinition`, provide a TS helper to turn it into a `Store` type? Is this even feasible?

```
class AuthenticationManager {
    private readonly $axios: NuxtAxiosInstance;
    private readonly authenticationStore: typeof useAuthenticationStore; // ERROR: got StoreDefinition instead of Store

    constructor($axios: NuxtAxiosInstance, $pinia: Pinia) {
        this.$axios = $axios;
        this.authenticationStore = useAuthenticationStore($pinia);
    }
}
```

### Describe alternatives you've considered

I tried using `typeof useAuthenticationStore`, but the type is `StoreDefinition` and not `Store` which `useAuthenticationStore($pinia)` returns.

Is there any already-exisiting way to achieve what I highlighted in the above snippet?

**Comment by soc221b** [comment]
Is this what you need? 🤔 

```ts
const useCounterStore = defineStore('counter', () => {
  const current = ref(0)
  const double = computed(() => current.value * 2)
  const increment = () => current.value++

  return {
    current,
    double,
    increment,
  }
})

type UseNullStore = ReturnType<typeof defineStore>
type NullStore = ReturnType<UseNullStore>
type CounterStore = ReturnType<typeof useCounterStore>
type CounterStoreSGA = Omit<CounterStore, keyof NullStore>
```

<img width="639" alt="截圖 2022-02-14 09 50 53" src="https://user-images.githubusercontent.com/22850435/153786750-ba570053-6530-4fdf-9c3f-1cd778ce6bdb.png">

> SGA: State, Getter, Action
