### ISSUE TITLE
Clear all stores

### ISSUE THREAD

**Issue by ahmedelghandour1** [posva/pinia#1056]
### Discussed in https://github.com/vuejs/pinia/discussions/911

<div type='discussions-op-text'>

<sup>Originally posted by **darthf1** December 20, 2021</sup>
Hi!

I'm trying to create a function / plugin to reset all stores, which is also described in https://github.com/vuejs/pinia/discussions/693. I'm using Nuxt, so this is my plugin:

```ts
import { defineNuxtPlugin } from '@nuxtjs/composition-api'
import { Store } from 'pinia'

declare module 'pinia' {
  export interface PiniaCustomProperties {
    resetAllStores: () => void
  }
}

let stores: Store[] = []

const resetAllStores = () => {
  for (const store of stores) {
    store.$reset()
  }
  stores = []
}

export default defineNuxtPlugin(({ $pinia }) => {
  $pinia.use(({ store }) => {
    stores.push(store)
  })

  $pinia.use(resetAllStores)
})
```

However, this leads to the following error:
```
🍍: Store "organisation" is build using the setup syntax and does not implement $reset().
```

I would expect that this function is always there, because I can run 
```ts
const store = useMyStore()
store.$reset()
```

</div>

**Comment by posva** [comment]
This is a technical limitation. You have to implement `$reset` yourself and return it within the setup store
