### ISSUE TITLE
State not reactive when updating from external function

### ISSUE THREAD

**Issue by rijkvanzanten** [posva/pinia#106]
Maybe I'm using it wrong, but I thought something like this should work:

// component.vue
```js
import { defineComponent } from '@vue/composition-api';

export default defineComponent({
  setup() {
    const app = useAppStore();

    const loading = app.state.loading;

    return { loading };
  })
});
```

// external function
```js
function startLoading() {
    const app = useAppStore();
    app.state.loading = true;
}
```

Whenever this external function is called, my component doesn't update based on the state change. Only if I wrap the `state` in `toRefs` does it update correctly when being changed "from the outside":

```js
import { defineComponent, toRefs } from '@vue/composition-api';

export default defineComponent({
  setup() {
    const app = useAppStore();

    // now it updates correctly when startLoading() is called somewhere else
    const loading = toRefs(app.state).loading;
    return { loading };
  })
});
```

Am I misunderstanding something here, or is this a bug?

I made a CodeSandbox with an example:
https://codesandbox.io/s/pinia-example-rbb44

**Comment by rijkvanzanten** [comment]
For full reference: updating the value in the same context works (and is reactive):

```js
import { defineComponent } from '@vue/composition-api';

export default defineComponent({
  setup() {
    const app = useAppStore();

    const loading = app.state.loading;

    return { loading, startLoading };

    function startLoading() {
      app.state.loading = true;
    }
  })
});
```

**Comment by posva** [comment]
You cannot do `const loading = app.state.loading;` and then return `loading` inside `setup` because you are returning the raw value instead of a reactive value (like ref or reactive). Wrapping it into a ref is necessary. You can also use a computed, or return the whole store to access the state trough a reactive property

**Comment by rijkvanzanten** [comment]
Thanks for that insight. On second thought, that makes total sense 👍 

Moving forward, I'll be using

```js
const { loading } = toRefs(app.state);
```

which seems to be working as expected 🙂

**Comment by EspressoCode** [comment]
Hey guys, I should say thanks since you saved me! I have a question:
You could also write:

```const loading = toRe(app.state, "loading");```
This way you can assign a different name to your variable and also you don't need to use object notation (no need to put it in {} )

**Comment by Fanoflix** [comment]
Its worth mentioning (because I basically was pulling my hair over this) that:

```js
let isDark = storeToRefs(themeStore);
```
 will NOT work. It will not result in any errors or warnings either.

but

```js
let { isDark } = storeToRefs(themeStore);
```
 is how it is supposed to work. I had a brain fart, and I am mentioning this here for my fellow overworked programmers. 👍🏼

**Comment by rijkvanzanten** [comment]
> and I am mentioning this here for my fellow overworked programmers. 👍🏼

Make sure to take a break every now and again my friend; personal health is more important than anything ❤️

**Comment by hjJunior** [comment]
Something important to notice, even using `storeToRefs` I was facing same issue, the problem was the spread operator I was using to separate functions

Wrong way:
````ts
    const { login, ...store }= useAuthStore();
    const { user, isAuthenticated } = storeToRefs(store);
````

Correct way:
````ts
    const store = useAuthStore();
    const { user, isAuthenticated } = storeToRefs(store);
    const { login } = store;
````

**Comment by ismailthasreef** [comment]
oh god this answers saved my day, thanks to @hjJunior @rijkvanzanten 
i spent around 2 days working on this, my issue was component is not rendering rest all things was ok, "storeToRefs" saved my day
