### ISSUE TITLE
error in getter not handled in devtools

### ISSUE THREAD

**Issue by guillaumeduliscouet** [posva/pinia#1062]
### Reproduction

https://github.com/guillaumeduliscouet/pinia-error-getter

### Steps to reproduce the behavior

1. Run (`yarn serve`) and open the app
2. Click on the store in vue devtools (v6)

### Expected behavior

- Having access to the rest of the store even if a getter throws an error (it is the current behaviour with Vue 3 from my test)

Nice to have, but not critical:
- No `getInspectorState` error, only keep the 2nd one
- Even better would be to remove both errors from the console, and have the real error details, with stack trace, in the devtools, but maybe it is a lot of work for not that much benefit

### Actual behavior

The page in the devtools is blank for this store

![image](https://user-images.githubusercontent.com/11506108/154073250-05e08a7f-c5ac-4887-a484-5c25cfb85123.png)

2 errors appear in the console

![image](https://user-images.githubusercontent.com/11506108/154073163-291cc238-483d-47c2-bc58-09492eff3abe.png)

### Additional information

You may find it strange to have getters that are expected to return an error ? But we have a good usecase for this in our approach, maybe we are not the only ones ?

**Comment by posva** [comment]
This is because devtools try to display all computed properties. We could use a try catch around the getter in getInspectorState to set the error as the value of the getter like it happens with a computed:

![Screenshot 2022-02-15 at 18 40 00](https://user-images.githubusercontent.com/664177/154118120-0b5d59a7-df7e-41db-9189-4d10fdbe3513.png)

```js
const data = ref<any>(null)
const stuff = computed(() => data.value.thing)
```
