### ISSUE TITLE
What is needed to support getters with parameters?

### ISSUE THREAD

**Issue by rijkvanzanten** [posva/pinia#107]
Hi there!

What would need to be done in order to support getters with parameters, and how should they work ideally?

How do they differ from actions? Is there a way where you could return a `computed` from an action in order to mimic the same functionality?

**Comment by posva** [comment]
hello. I don't think getters with parameters are worth anymore. They are just methods. Otherwise it would mean creating some kind of internal Map of computed properties depending on the parameters

**Comment by rijkvanzanten** [comment]
Do you have an alternative to make a similar thing work with actions? Would something like this in a component do the trick?:

```js
const bookmarksStore = useBookmarksStore();

const bookmark = computed(() => bookmarksStore.getBookmarkForUser(15));
```

**Comment by posva** [comment]
yes, that should work, the 15 could also be a local `ref` or similar

**Comment by rijkvanzanten** [comment]
I'm sorry if these questions are a bit ignorant, but are you saying:

```js
const userID = ref(15);

const bookmark = bookmarksStore.getBookmarkForUser(userID);

userID.value = 21;

// bookmark is updated now??
```

I'm still trying to wrap my head around how refs/reactives actually work.. (instead of just how to use them)

**Comment by posva** [comment]
It's fine, lol

I was more thinking about replacing that 15 in the example with the `computed`:

```js
const bookmarksStore = useBookmarksStore();
const userID = ref(15);

const bookmark = computed(() => bookmarksStore.getBookmarkForUser(userID.value)
```

But sometimes that's not possible because the variable comes from a loop, so you have to use the action in the template, in that case you return a function that calls the action in `setup`:

```js
function getBookmarkForUser(id) {
  return bookmarStore.getBookmarkStore(id)
}

return { getBookmarkForUser }
```

and then use it in the template
