### ISSUE TITLE
Typescript with setup store

### ISSUE THREAD

**Issue by bartenra** [posva/pinia#1104]
### Reproduction

Typescript support for setup store is not working.

store.ts
```ts
import { ref } from 'vue';
import { defineStore } from 'pinia';

export const useStore = defineStore('store', () => {
  const name = ref('name');

  const setName = () => {
    name.value += '1';
  };
  return {
    name,
    setName
  };
});
```

Component.vue
```vue
<template>{{ state.name }}</template>

<script setup lang="ts">
import { useStore } from '../store';

const state = useStore();
</script>
```

Type of `state.$state` is `{} & PiniaCustomStateProperties<{}>`.

Type of `state` is `const state: Store<"store", {}, {}, {}>`...

**Comment by bartenra** [comment]
Needs to be a `ComputedRef` apparantly.

**Comment by tvld** [comment]
Can you show what you meant with that "ComputedRef" ? I am stuck in same way ))
