### ISSUE TITLE
Mistyped computed getters with parameters using setup function

### ISSUE THREAD

**Issue by extrem7** [posva/pinia#1139]
### Discussed in https://github.com/vuejs/pinia/discussions/1065

<div type='discussions-op-text'>

<sup>Originally posted by **Glandos** February 15, 2022</sup>
I followed https://github.com/vuejs/pinia/issues/978 using the exact same store.
I am using a Vue 2 project, in an SFC with vue-class-component (yes, this is an already started project…):
```typescript
<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { useStoreCounter } from '@/stores/counter'


@Component
export default class UserDetails extends Vue {
  store = useStoreCounter()

  mounted() {
    this.$log.warn('Store', this.store.isEven, this.store.messageIfEven("ahah"))
  }
}
</script>
```

However, both Vetur in VSCode and the Typescript checker complain on the `messageIfEven` saying that:
```
(property) messageIfEven: string | undefined
Cannot invoke an object which is possibly 'undefined'.Vetur(2722)
This expression is not callable.
  Type 'String' has no call signatures.Vetur(2349)
```

So it seems that the getter is weirdly unwrapped, since it only retains its `Result`. But executing the code shows me that `messageIfEven` **is** a function.

What did I miss?</div>
I have the same issue with computed returned by store.
```typescript
const getNextDocument = computed(() => (id: number) => {
    const index = documents.findIndex((d) => d.id === id)

    return index !== -1 && index !== documents.length - 1
      ? documents[index + 1]
      : null
})
```
```vue
<script setup lang="ts">
const { getNextDocument } = usePassengerStore()
</script>
<template>{{ getNextDocument(1) }}</template>
```
`error TS2721: Cannot invoke an object which is possibly 'null'.`

**Comment by posva** [comment]
No duplicates please!
