### ISSUE TITLE
reset can get param of state key

### ISSUE THREAD

**Issue by robin-dongbin** [posva/pinia#1152]
### What problem is this solving

For only want to reset part of states

### Proposed solution

`$reset` can get param `String|Array`

### Describe alternatives you've considered

```
state: () => ({
  data: { foo: bar }
}),
actions: {
  func(){
    this.data = { foo: bar }
  }
}
```

**Comment by posva** [comment]
Reset is just a one line function. It's that way to keep the code functional and light. Any extension of the reset functionality should be added with a plugin but there is no intend in growing the core codebase to complexify further the `$reset` method.
