### ISSUE TITLE
Pinia's "Getting started" page lacks a basic example.

### ISSUE THREAD

**Issue by ffunenga** [posva/pinia#1195]
### Reproduction

https://pinia.vuejs.org/getting-started.html

### Steps to reproduce the bug

1. Go to the [_Getting started_ page](https://pinia.vuejs.org/getting-started.html)
2. Read the [_Installation_ section](https://pinia.vuejs.org/getting-started.html#installation). Try to do what is described there. Check that the given information is incomplete.
3. Read the [_What is a Store?_ section](https://pinia.vuejs.org/getting-started.html#what-is-a-store). Check terminology contradiction between "A Store (like Pinia) is..." and "Create a pinia (the root store)..." in the [_Installation_ section](https://pinia.vuejs.org/getting-started.html#installation). The same thing appears to have three differnet names: a "store", a "pinia" and a "root store".
4. Read the [_When should I use a Store_ section](https://pinia.vuejs.org/getting-started.html#when-should-i-use-a-store). Read general information given in this section.
5. Reach the end of the page. No clear example was provided. Recheck the page again: no success. Look at left bar for a possible salvation: no success.

### Expected behavior

The behavior I "expected" (in my opinion, which may be different from what is intended by Pinia's docs writer(s) ) was to read a documentation page that would enable a person with basic knowledge in Vue to carry out an introductory example of Pinia's usage.

### Actual behavior

See the explanation given in the [Installation section](https://pinia.vuejs.org/getting-started.html#installation) (emphasis added here):
> Create a pinia (the root store) and pass it to the app:
> ```js
> import { createPinia } from 'pinia'
>app.use(createPinia())
> ```
My (subjective) issues with this:
* "Create a pinia (the root store) (...) [js code is shown]"  Should I create a new file? Where?
* "...and pass it to **the app**" What "the" app? Where does `app` come from?

**Comment by posva** [comment]
Added to https://github.com/vuejs/pinia/issues/829
