### ISSUE TITLE
createPinia failed in Vue 2

### ISSUE THREAD

**Issue by Louis-Tian** [posva/pinia#1199]
### Reproduction

https://codesandbox.io/s/competent-tree-bvzyvk?file=/src/main.js

### Steps to reproduce the bug

Basic setup with latest vue2 
Follow the instruction here https://pinia.vuejs.org/getting-started.html
using
```
import { createPinia, PiniaVuePlugin } from 'pinia'

Vue.use(PiniaVuePlugin)
const pinia = createPinia()
```

### Expected behavior

should run without error

### Actual behavior

the store failed to initialize with error
```
TypeError
(0 , $csb__vue_demi.effectScope) is not a function
```an 

### Additional information

_No response_

**Comment by Liwoj** [comment]
Seems related to [this issue](https://github.com/vueuse/vue-demi/discussions/75) - ie. Vue Demi failing in Vue 2 mode in the environment that does not allow `postinstall` hook to run (as CodeSandbox or Stackblitz)

**Comment by posva** [comment]
You have starters at https://github.com/piniajs/example-vue-2-vite/

**Comment by ebisbe** [comment]
I have a similar error:
```
pinia.mjs:1005 Uncaught TypeError: undefined is not a function
    at createPinia (pinia.mjs:1005:1)
    at ./app/javascript/pos/index.js (index.js:44:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./app/javascript/packs/pos.js (ScreenSize.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at bootstrap:83:1
    at bootstrap:83:1 
```
With Vue 2 with webpack instead of Vite

**Comment by posva** [comment]
You probably need to tell webpack how to handle `.mjs` extensions: https://github.com/piniajs/vue-3-cli-webpack-4/blob/main/vue.config.js

- https://github.com/vuejs/pinia/issues/675
