### ISSUE TITLE
reactivity-transform $ref()/$computed() support

### ISSUE THREAD

**Issue by transtone** [posva/pinia#1210]
### What problem is this solving

add `$ref` for delete `.value`

### Proposed solution

use 
```js
let a = $ref('')
a = 'abc'
``` 
replace 
```js
const a = ref('')
a.value = 'abc'
``` 

my fault.
it must return `$$(abc)` to make it reactive.

**Comment by posva** [comment]
You already can. Check the appendix at https://github.com/vuejs/rfcs/discussions/369#appendix

**Comment by transtone** [comment]
> You already can. Check the appendix at [vuejs/rfcs#369 (comment)](https://github.com/vuejs/rfcs/discussions/369#appendix)

can I use it in `defineStore` ?

**Comment by webfanzc** [comment]
> You already can. Check the appendix at [vuejs/rfcs#369 (comment)](https://github.com/vuejs/rfcs/discussions/369#appendix)

when i use setup store, I can't use reactivity-transform syntax to define state. If i want. I just to code like that
```
defineStore(
  'future',
  () => {
    const symbolName = $ref('abc')

    return {
      symbolName: $$(symbolName)
    }
  }
)

```

**Comment by kansson** [comment]
Thanks @transtone had the same problem. The `setup` function must indeed return the data with `$$()`. Thanks!

**Comment by Ismaele-silla** [comment]
It would be super helpful to add this to https://pinia.vuejs.org/core-concepts/#setup-stores . It took me almost a day to understand that the problem I had in my code was caused by not adding $$() to the returned object. Still, I'm super glad I can use reactivity transform with pinia as well (<3 Pinia).
