### ISSUE TITLE
Type inference breaks in getters without return type annotations

### ISSUE THREAD

**Issue by stefnotch** [posva/pinia#1217]
### Reproduction

https://stackblitz.com/edit/github-earrk5?file=src%2Fstores%2Fcounter.ts

### Steps to reproduce the bug

1. Access a getter
2. Look at the inferred types

### Expected behavior

![image](https://user-images.githubusercontent.com/10220080/162610825-978a44bf-b9e1-4d2e-a44c-530dee041388.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/10220080/162610830-8708d4fc-7fdb-4db1-bfd5-aada6436f62e.png)

**Comment by posva** [comment]
This is an expected limitation of TS

**Comment by stefnotch** [comment]
Okay. I think it might be worthwhile to add a little warning about it in the documentation.
