### ISSUE TITLE
Actions should support arrow function expressions like Getters

### ISSUE THREAD

**Issue by andrewjhill9** [posva/pinia#1240]
### What problem is this solving

# Issue 1 - Syntax Consistency
Actions do not currently pass the "state" object into arrow function expressions. This imposes the following limitations:

1. Inconsistency with Getter coding style. Pinia's docs clearly state encouragement for utilizing the arrow function for Getters.  
   - https://pinia.vuejs.org/core-concepts/getters.html
   - `They receive the state as the first parameter to encourage the usage of arrow function`
1. Cannot easily use single functions for Actions (see example below)

It would be convenient to utilize single functions in Pinia cleanly and easily so that functions can be managed and tested elsewhere in isolation if needed. While the current implementation of Pinia does not prohibit this, as stated above, syntax consistency and cleanliness is lacking.

### Simple Pinia Store as Defined by Docs
```js
import { defineStore } from "pinia"

export const countStoreA = defineStore('countStoreA', {
    state: () => ({
        counter: 0,
    }),
    getters: {
        count: (state) => state.counter,
    },
    actions: {
        increment() {
            this.counter++
        },
    }
})
```

### Currently Supported - Simple Pinia Store with function
```js
import { defineStore } from "pinia"

// This function could be imported from some other package.
// It is here to keep the example simple.
function incrementFunction(state: {counter: number}): void {
    state.counter++
}

export const countStoreA = defineStore('countStoreA', {
    state: () => ({
        counter: 0,
    }),
    getters: {
        count: (state) => state.counter,
    },
    actions: {
        increment() {
            incrementFunction(this.$state)
        },
    }
})
```

# Issue 2 - Store logic dependencies

The second issue at hand is the files that define the store composition must import the Pinia library to function correctly. With arrow function expressions, there is no assumption that `this` exists and that it points to the Pinia store instance. This allows someone to write a store definition that is a simple Javascript object and does not depend on Pinia. This allows unit tests to be written around just the logic defined in the store definition object before adding Pinia logic on top.

In the example below, this concept of a store definition object independent of Pinia is shown, along with unit tests for that store. This would allow us to then bring in this store object into a Pinia `defineStore` call and then test that store with confidence that the underlying logic is correct. 

### Proposed solution

# Solution

## Action Item(s)

1. Add arrow function expression support for Actions.

OR

1. Update Documentation for [Actions](https://pinia.vuejs.org/core-concepts/actions.html) stating why arrow functions are encouraged for Getters but not suitable for Actions.
    - It is not stated in documentation why one is supported but not the other.

### Desired - Simple Pinia Store with function
```js
import { defineStore } from "pinia"

// This function could be imported from some other package.
// It is here to keep the example simple.
function incrementFunction(state: {counter: number}): void {
    state.counter++
}

export const countStoreA = defineStore('countStoreA', {
    state: () => ({
        counter: 0,
    }),
    getters: {
        count: (state) => state.counter,
    },
    actions: {
        increment: (state) => incrementFunction(state)
    }
})
```

### Simple Store Definition
```js
export const countStore = {
    state: () => ({
        counter: 0,
    }),
    getters: {
        count: (state: {counter: number}) => state.counter
    },
    actions: {
        increment: (state: {counter: number}) => state.counter++
    }
}
```

### Unit Tests
```js
import { expect, test, describe } from 'vitest'
import { countStore } from '../src/stores/modules/count-store'

// Edit an assertion and save to see HMR in action
describe('Count Store should', () => {
  test('have a counter state', () => {
    expect(countStore.state().counter).toBeDefined()
  })
  test('have a default state of 0', () => {
    console.log(countStore.state().counter)
    expect(countStore.state().counter).toEqual(0)
  })
  test('have a getter for counter state', () => {
    expect(countStore.getters.count).toBeDefined()
  })
  test('have a getter for counter state that returns count', () => {
    expect(countStore.getters.count(countStore.state())).toEqual(0)
  })
  test('have an action for counter state', () => {
    expect(countStore.actions.increment).toBeDefined()
  })
  test('have an action for counter state that updates state value', () => {
    const state = countStore.state()
    countStore.actions.increment(state)
    expect(state.counter).toEqual(1)
  })
})
```

### Pinia Store Definition

```js
import { defineStore } from "pinia"

export const countStoreA = defineStore('countStoreA', countStore)
```

**Comment by posva** [comment]
There are two reasons actions do not take any parameters by default:

- Allow the user to define any parameters as they want
- Type support: passing the state wouldn't be enough in actions, we would need to pass the store but then actions wouldn't be automatically typed because of a limitation in TS

This is not stated in docs because it's an implementation detail and would confuse most users.

**Comment by strokirk** [comment]
Please re-evaluate this issue - currently this is a huge footgun for newer developer's that are still figuring out the difference between arrow functions and `function` functions. Even as an experienced developer, it's still very easy to make mistakes.

**Comment by MariuzM** [comment]
Yep agree it should be arrow functions across the board and not half backed its just more confusion and much less DX, another problem is with `this` is that there is unnecessary type definitions when i only want to get state 

<img width="297" alt="image" src="https://github.com/user-attachments/assets/73184692-11aa-4acc-8fed-2f2cd109683d">

vs 

<img width="386" alt="image" src="https://github.com/user-attachments/assets/d2fb0bc2-3968-4ea7-bc21-6f8c7fba62aa">
