### ISSUE TITLE
createTestingPinia doesn't mock actions using vitest vi.fn

### ISSUE THREAD

**Issue by dennybiasiolli** [posva/pinia#1249]
### Reproduction

https://github.com/dennybiasiolli/vuex-to-pinia-vue3/blob/moving-to-pinia/tests/unit/components/Counter.spec.js#L26-L27

### Steps to reproduce the bug

1. clone this repo: https://github.com/dennybiasiolli/vuex-to-pinia-vue3.git

    ```sh
    git clone https://github.com/dennybiasiolli/vuex-to-pinia-vue3.git
    # or
    git clone git@github.com:dennybiasiolli/vuex-to-pinia-vue3.git
    ```
2. enter the repo directory and switch to `moving-to-pinia` branch

    ```sh
    cd vuex-to-pinia-vue3
    git checkout moving-to-pinia
    ```

3. install dependencies with `npm install`

4. comment out the two lines of [`Counter.spec.js`](https://github.com/dennybiasiolli/vuex-to-pinia-vue3/blob/moving-to-pinia/tests/unit/components/Counter.spec.js#L26-L27)

    ```js
    // comment out this two lines
    store.increment = vi.fn() // FIXME: this should already by mocked
    store.incrementAsync = vi.fn() // FIXME: this should already by mocked    
    ```

5. run tests with `npm run test` and notice that tests are breaking with

    `TypeError: [Function] is not a spy or a call to a spy!`

    even if in the docs they say that they should be automatically stubbed with the `createSpy` function defined

### Expected behavior

Pinia actions should already be mocked with the `createSpy` function

### Actual behavior

Tests are breaking with

`TypeError: [Function] is not a spy or a call to a spy!`

even if in the docs they say that they should be automatically stubbed with the `createSpy` function defined

### Additional information

Using the same code with Vue 2, Pinia and Jest is working fine.
You can take a look at the parallel repository here: https://github.com/dennybiasiolli/vuex-to-pinia-vue2
(same branch)

**Comment by posva** [comment]
It works on my end:

<img width="740" alt="Screenshot 2022-04-24 at 12 29 41" src="https://user-images.githubusercontent.com/664177/164972180-ce4c239d-3593-44b7-8a43-29845193ddc5.png">

Moving to a discussion until this can be reproduced
