### ISSUE TITLE
Types are not preserved

### ISSUE THREAD

**Issue by florian-lefebvre** [posva/pinia#1279]
### Reproduction

https://stackblitz.com/edit/github-zrvb8t?file=src/App.vue

### Steps to reproduce the bug

Open the reproduction and see the browser view.

### Expected behavior

Since `product` type in `useStore` is `Ref<Product>`, I expect it to be:

- `Product` when doing `const { product } = useStore()`
- `Ref<Product>` when doing `const { product } = storeToRefs(useStore())`

### Actual behavior

`product` type is `object`.

### Additional information

The current workaround I found:
```ts
const store = useStore();
const { product }: { product: Ref<product>; } = storeToRefs(store) as any;
const {} = store; // actions
```
I think it doesn't change anything but I'm not using TypeScript in strict mode.

**Comment by posva** [comment]
You do need **strict: true** (default value). I tested on my end and the type isn't object.

**Comment by florian-lefebvre** [comment]
Thanks!

**Comment by florian-lefebvre** [comment]
Just tried it out and it doesn't seem to fix my issue on a Nuxt3 app. If you want to have a look @posva: https://github.com/florian-lefebvre/nuxt3-starter-medusa (strict type to false but doesn't work either with true).

**Comment by posva** [comment]
that's probably a config issue, some options might be overriding some of the rules set by strict true. You should be able to find some help in the discord chat :+1:

**Comment by crouchingHamster** [comment]
My current workaround
`const { product }: ToRefs<Pick<IStoreReturn, 'product'>> = storeToRefs(store);`

**Comment by patrickdorival** [comment]
I'm experiencing this currently, using strict types and all types are getting converted to objects.
What is the solution here?
Manually retyping everything coming out of the store isn't a solution

**Comment by ydwan** [comment]
```typescript
const projectManageStore = useProjectManageStore();
const { createProjectInfo } = storeToRefs(projectManageStore) as unknown as typeof projectManageStore; 
```
I implemented type inference using this method.
