### ISSUE TITLE
After the package is deployed, the parameter events in the callback of $subscribe is undefined, but normal in development mode

### ISSUE THREAD

**Issue by Lyonii** [posva/pinia#1313]
### Reproduction

https://github.com/piniajs/example-vue-3-vite

### Steps to reproduce the bug

// connectStore.ts
import { defineStore } from 'pinia';

const options = {
  state: () => ({
    status: false,
  }),
};

export default defineStore('connect', options);

// index.vue in setup
connectStore.$subscribe((result) => {
  console.log(result);
  (Array.isArray(result.events) ? result.events : [result.events]).some(
    ({ key }) => (key as string) === 'status',
  ) && onResetChatWrapper();
});

### Expected behavior

<img width="648" alt="image" src="https://user-images.githubusercontent.com/91267798/169636899-a791f425-097d-4b6e-866f-c001fad1342e.png">

### Actual behavior

<img width="660" alt="image" src="https://user-images.githubusercontent.com/91267798/169636918-0904be60-c203-4a59-b8d9-5c79829dfef4.png">

### Additional information

vue3 + typescript + pinia

**Comment by posva** [comment]
As said in docs, `events` only exists in Dev mode.
