### ISSUE TITLE
官方文档字体滥用

### ISSUE THREAD

**Issue by Andyfoo** [posva/pinia#1314]
### Reproduction

1

### Steps to reproduce the bug

https://pinia.vuejs.org/introduction.html#basic-example
官方文档字体滥用

![image](https://user-images.githubusercontent.com/864512/169678028-f6deeb50-c337-47b8-90e0-102aa00988e2.png)
![image](https://user-images.githubusercontent.com/864512/169678080-e32de8c9-3e16-4107-8a33-7a7d132c5b8a.png)

### Expected behavior

.

### Actual behavior

.

**Comment by tamarous** [comment]
same as https://github.com/vuejs/pinia/issues/873

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
