### ISSUE TITLE
Refs inside instantiated classes get dereferenced

### ISSUE THREAD

**Issue by greendrake** [posva/pinia#1346]
### Reproduction

https://stackblitz.com/edit/github-up8ud5-2r1oyy?file=src%2Fmain.ts

### Steps to reproduce the bug

1. Open the link.
2. Wait for the build to finish.
3. Open the resulting view in a new window and check the console. See "`Uncaught TypeError: Cannot create property 'value' on string 'bar'`"

### Expected behavior

It should be possible to run `setField('baz')` without any errors like it is possible at line 18. The `foo` object should be consistent no matter where it has come from.

### Actual behavior

Running `state.foo.setField('baz')` causes `Uncaught TypeError: Cannot create property 'value' on string 'bar'` because Pinia dereferences the `field` property on the `foo` object — even when called _inside_ `foo`.

**Comment by murongg** [comment]
This question seems from `vue reactive`! I find this problem was debugging `pinia`! `Pinia` store seems use `reactive` wrap direct

**Comment by murongg** [comment]
According to the hint of [yyx990803](https://github.com/yyx990803), you should probably do this:
```ts
class Foo {
  constructor() {
    this.field = '';
  }

  setField(value) {
    this.field = value;
  }
}


const useState = defineStore('main', {
  state: () => {
    return {
      foo: null,
    };
  },
});

const state = useState();
state.foo = reactive(new Foo());
state.foo.setField('baz');

```

**Comment by greendrake** [comment]
> ```ts
> reactive(new Foo())
> ```

Thanks but I'm not too sure about that. The `Foo` class in the given example is simplified. In reality, it is an extended class bearing a shitload of behaviour and properties that I don't need to be reactive. I'm concerned that making it reactive will interfere with all that (and/or affect the performance), although I have not tried it yet.

**Comment by murongg** [comment]
> > ```ts
> > reactive(new Foo())
> > ```
> 
> Thanks but I'm not too sure about that. The `Foo` class in the given example is simplified. In reality, it is an extended class bearing a shitload of behaviour and properties that I don't need to be reactive. I'm concerned that making it reactive will interfere with all that (and/or affect the performance), although I have not tried it yet.

This is a thorny problem.

**Comment by posva** [comment]
You need to mark the Class as raw:

```ts
state.foo = markRaw(foo);
```
