### ISSUE TITLE
能不能出一个class版本？

### ISSUE THREAD

**Issue by LengYXin** [posva/pinia#1368]
### What problem is this solving

装饰器版本的扩展也行

### Proposed solution

装饰器版本的扩展也行

**Comment by murongg** [comment]
I think probably not. Because they are now using functional programming.

**Comment by LengYXin** [comment]
> I think probably not. Because they are now using functional programming.

语法中的
 {
  state: () => ({ count: 0 }),
  getters: {
    double: (state) => state.count * 2,
  },
  actions: {
    increment() {
      this.count++
    },
  },
}
getters   actions 等等 使用 类语法 明明可以更清晰，对TS 定义 this 也更友好 在搭配装饰器 就更简洁了。

**Comment by murongg** [comment]
Maybe so. But I perfer functional programming.

**Comment by LengYXin** [comment]
> Maybe so. But I perfer functional programming.

函数式编程有函数式编程的好处，对于纯前端开发人员来说确实是入门简单，但是对于像后端开发人员来说OOP的方式在亲切不过了，而且本身就是标准化中的东西。虽然我是混写，但是复杂性业务场景抽象后的代码维护确实方便。

**Comment by LengYXin** [comment]
> Maybe so. But I perfer functional programming.

vue3 的官方仓库等等源码也看了看，里面一些模块也都是oop

**Comment by murongg** [comment]
> > Maybe so. But I perfer functional programming.
> 
> vue3 的官方仓库等等源码也看了看，里面一些模块也都是oop

Yeah! But isn't it better to keep it simple?

**Comment by murongg** [comment]
> > > Maybe so. But I perfer functional programming.
> > 
> > 
> > vue3 的官方仓库等等源码也看了看，里面一些模块也都是oop
> 
> Yeah! But isn't it better to keep it simple?

Maybe someone will develop one based on Pinia! But I think Pinia maintainers may not!

**Comment by LengYXin** [comment]
> > > > Maybe so. But I perfer functional programming.
> > > 
> > > 
> > > vue3 的官方仓库等等源码也看了看，里面一些模块也都是oop
> > 
> > 
> > Yeah! But isn't it better to keep it simple?
> 
> Maybe someone will develop one based on Pinia! But I think Pinia maintainers may not!

希望维护者来开发，第三方的会存在更新不及时和归档不维护等情况

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/pinia/issues/802

**Comment by wcldyx** [comment]
有时候想声明一个 private 的方法，不暴露到外部去
