### ISSUE TITLE
TypeScript: Adding a getter with store prop makes all store values undefined

### ISSUE THREAD

**Issue by alexmccabe** [posva/pinia#1372]
### Reproduction

https://codesandbox.io/s/modest-wood-fhujek?file=/src/store/example.store.ts

### Steps to reproduce the bug

1. Uncomment line 18
2. All store data values become undefined

![CleanShot 2022-06-15 at 16 12 27](https://user-images.githubusercontent.com/2529110/173862728-88401b46-fb38-4ad2-ba41-a4aa80616726.png)

### Expected behavior

Adding a getter to the store using the `state` prop should not cause all store values to be undefined

### Actual behavior

I'm able to add a getter to the store just fine using the `this` notation. However if using the function that accepts `state` as a prop, then the entire store contents becomes undefined. All values no longer exist on the store state

![CleanShot 2022-06-15 at 16 10 15](https://user-images.githubusercontent.com/2529110/173862253-9d566640-3f44-4b72-960c-ea4b8038b2ef.png)

### Additional information

I am able as a workaround to type the `state` parameter myself

```ts
double: (state: { count: number }) => state.count * 2,
```

**Comment by posva** [comment]
Use an arrow function for the state:

```ts
import { defineStore } from "pinia";

export const useExampleStore = defineStore("example", {
  state: () => ({
      count: 0
  }),

  getters: {
    getCount(): number {
      return this.count;
    },

    /**
     * Uncomment the following line to see the issue
     */
    double: (state): number => state.count * 2,
  },

  actions: {
    increment() {
      this.count += 1;
    }
  }
});
```

**Comment by alexmccabe** [comment]
@posva yeah that works! What's the reasoning that it has to be this way?
