### ISSUE TITLE
TypeScript not fully supported on classes with private fields

### ISSUE THREAD

**Issue by tcisof** [posva/pinia#1401]
### Reproduction

https://codesandbox.io/s/pinia-type-script-private-fields-thbiob?file=/src/index.ts

### Steps to reproduce the bug

Create typed action and return object with private fields from state.

### Expected behavior

No type error.

### Actual behavior

Type error about private fields. Like from example:
Property 'privateName' is missing in type '{ id: number; name: string; }' but required in type 'Car'

### Additional information

It can be walkaround by using type assertion.

**Comment by LinusBorg** [comment]
This is a limitation of Vue's Reactivity System, specifically the types for reflecting runtime ref unwrapping, and unrelated to pinia specifically.

**Comment by lsimone** [comment]
@LinusBorg we've experienced the same issue, so we solved it [through a not-really-nice workaround](https://codesandbox.io/s/pinia-type-script-private-fields-forked-8l8j82?file=/src/index.ts), that we think it's still better than a forced casting.

I share even if the issue is closed to help other people experiencing it.

**Comment by dulimarta** [comment]
I was able to use `markRaw` to fix [my own issue](https://github.com/dulimarta/spherical-easel/issues/103#issuecomment-3008908721). To give some background, we have a class that depends on another class from [TwoJS](https://github.com/jonobr1/two.js/). This TwoJS class declares some of its properties as `private` that caused Pinia to throw a runtime arrow "Uncaught TypeError: Cannot read from private field"

```
export const useMyStore = defineStore('xyz', () => {
  const someArray: Ref<MyObject[]> = ref([])

  function addNewObject(obj: MyObject) {
     //someArray.value.push(obj)           // This does not work
     someArray.value.push(markRaw(obj)).   // This WORKS
  }

  return {
    someArray,
    addNewObject
  }
})
```
