### ISSUE TITLE
Fulfill the `name` property of store actions

### ISSUE THREAD

**Issue by YehorPytomets** [posva/pinia#1408]
### What problem is this solving

Hello!

We propose to fulfill the `name` property of store actions to easily refer to the action from the `store` object when filtering actions by name in the `$onAction` callback.
This could prevent us from using raw string values as the action name may change in the future, and this place will become the source of hidden errors.
```js
userStore.$onAction(({name}) => {
    if (name == 'setUser') {
        // ...   
    }
}
```

Currently, the actions name is unset:

<img width="111" alt="Screenshot 2022-06-29 at 15 10 15" src="https://user-images.githubusercontent.com/40431853/176432945-a52f7253-8654-4666-bcf3-2c42a97e4955.png">

### Proposed solution

The solution assumes the action can easily be filtered by name using the `store` object of the `$onAction`callback:
```js
userStore.$onAction(({name, store}) => {
    if (name == store.setUser.name) {
        // ...   
    }
}
```

### Describe alternatives you've considered

As an alternative a similar object to `options` that is passed to [plugins](https://pinia.vuejs.org/core-concepts/plugins.html#introduction) may be used:
```js
// from plugins docs:
export function myPiniaPlugin(context) {
  context.pinia
  context.app
  context.store
  context.options // the options object defining the store passed to `defineStore()`. Contains actions
  // ...
}
```
```js
// if the same or similar `options` object was passed:
userStore.$onAction(({name, options}) => {
    if (name == options.actions.setUser.name) {
        // ...   
    }
}
```

As a temporary workaround, in the same file with the store definition, we declare and export an object that contains action names that are used specifically for this case. As the store may grow and change, we may forget to update raw string values across the project. Keeping the action name strings near the store is a good solution. But still, this approach brings duplications as we have to maintain the action name in two places.
```js
// stores/user-store.js
// imports...

export const USER_STORE = {
    ID: 'currentUser',
    ACTIONS: {
        SET_USER: 'setUser',
    },
};

const useUserStore = defineStore(USER_STORE.ID, {
    // state and getters
    actions: {
        setUser(value) {
            // ...
        } 
    },
});

export default useUserStore;
```
We could define store action like that: 
```js
actions: {
    [USER_STORE.ACTIONS.SET_USER](value) {
        // ...
    } 
},
```
but it would break the code completion in IDE and seems more like `Vuex` way.

So, I would be grateful to hear any feedback on that.

**Comment by posva** [comment]
it's already there: https://pinia.vuejs.org/api/interfaces/pinia._StoreOnActionListenerContext.html

**Comment by YehorPytomets** [comment]
@posva, I'll try to formulate it in another way. 

We have to declare action names outside of the store in constants specifically for filtering in the `$onAction` callbacks to find the right action. Instead of doing that we could use the name of the action declared in the `store` object, but it is empty.

```js
userStore.$onAction(({name, store}) => {
    console.log(store.setUser.name); // => '', but all JS functions typically have this property filled.
    if (name == 'setUser') { // we could use instead: store.setUser.name
        // ...   
    }
}
```

In Chrome:

<img width="111" alt="Screenshot 2022-06-29 at 15 10 15" src="https://user-images.githubusercontent.com/40431853/176432945-a52f7253-8654-4666-bcf3-2c42a97e4955.png">

It seems like a good feature for large projects that have dozens of `$onAction()` subscribers.

Would be grateful for your feedback.

**Comment by posva** [comment]
The name is already typesafe. There is no need to write something longer for no benefit
