### ISSUE TITLE
Vue 2.7 w/o @vue/composition-api?

### ISSUE THREAD

**Issue by BrandonlinU** [posva/pinia#1417]
### What problem is this solving

[Vue 2.7](https://github.com/vuejs/vue/releases/tag/v2.7.0) was just release yesterday, and it does not need support for the plugin @vue/composition-api, because it was integrated in the library.

### Proposed solution

It look like that vue-demi supports the Composition API without the need of the plugin, so it seems that it's a good idea check the support and update the docs.

**Comment by BrandonlinU** [comment]
Related #1380

**Comment by posva** [comment]
Added to https://github.com/vuejs/pinia/issues/829

A PR is welcome!
