### ISSUE TITLE
Typescript type of getter in composed store is wrong

### ISSUE THREAD

**Issue by DerZade** [posva/pinia#1430]
### Reproduction

https://github.com/DerZade/pinia-bug-report

### Steps to reproduce the bug

Open the `App.vue` in VS Code or any other editor, that supports typescript type-checking IntelliSense. `counter.nPlusX` is inferred as type `number`, although it actually is a `(x: number) => number`.

### Expected behavior

A computed property of a composed store, that returns a function (to achieve [the effect of a getter, to which I can pass arguments](https://pinia.vuejs.org/core-concepts/getters.html#passing-arguments-to-getters)) should have a correctly inferred Typescript type.

### Actual behavior

A computed property of a composed store, that returns a function, has a inferred type of the return type of said function.

**Comment by posva** [comment]
As a workaround use a regular function or an option store.

For anybody wanting to submit a fix, this has to deal with how Option Stores must extract the return type of their getters while setup store do not.

**Comment by DerZade** [comment]
> As a workaround use a regular function or an option store.

That may work for some, but not for all use cases. A function would be non-reactive and an option store does not have the possibility to use other stores as easily or call functions (actions) upon initialization. As a last resort, I added a `// @ts-ignore`- comment. Couldn't find a real workaround.

**Comment by Derhelios66** [comment]
Hello :smile:
i've already encounted this issue in an private repo and created an solution/workaround.
Maybe it helps.
