### ISSUE TITLE
inject is not a function PiniaNuxtPlugin 

### ISSUE THREAD

**Issue by aligzl** [posva/pinia#1432]
### Reproduction

https://stackblitz.com/edit/github-1xxy9u?file=package.json

### Steps to reproduce the bug
inject is not a function PiniaNuxtPlugin
Getting error on nuxt v3.0.0-rc.4-27620285.c95a48c update

### Expected behavior

Works as expected like previus version

### Actual behavior

Require update

**Comment by sharkfin009** [comment]
have this popping up  when trying to run my project on stackblitz

**Comment by Baiyuetribe** [comment]
Same error reporting, bad experience 🤦‍♂️

**Comment by shiva-prasad-reddy** [comment]
Same error, the plugin needs an update.

But till then i could add a file to nuxt plugins directory and get it to work
_pinia.client.ts_
```
import { createPinia } from "pinia";

export default defineNuxtPlugin((nuxtApp) => {
  const pinia = createPinia();
  nuxtApp.vueApp.use(pinia);
});
```

**Comment by Baiyuetribe** [comment]
@shiva-prasad-reddy 👍👍👍 Thank you very much, it almost made me autistic. Now it's working properly
