### ISSUE TITLE
Accessing payload is not yet supported in Nuxt 3.

### ISSUE THREAD

**Issue by stephenjason89** [posva/pinia#1442]
### Reproduction

Install @pinia/nuxt 0.2.0 together with pinia 2.0.15

### Steps to reproduce the bug

add @pinia/nuxt to modules:[]
run nuxt dev

I am getting this error
Accessing payload is not yet supported in Nuxt 3.

Rolling back to 0.1.9 without problems

Thanks

### Expected behavior

no errors

### Actual behavior

error
Accessing payload is not yet supported in Nuxt 3.

**Comment by DanielKaviyani** [comment]
When I put the `ssr: true` (or u can remove it if u set it to false) in nuxt.config.ts, the error is gone, it seems everything is working for me

**Comment by stephenjason89** [comment]
@DanielKaviyani thanks for the reply but this didn't fix it for me

**Comment by DanielKaviyani** [comment]
@stephenjason89 

Sorry, You are right.
i meant the 500 error was fixed for me (max call stack)
