### ISSUE TITLE
Nuxt3 - Cannot set properties of undefined (setting 'pinia')

### ISSUE THREAD

**Issue by aligzl** [posva/pinia#1449]
### Reproduction

https://stackblitz.com/edit/github-1xxy9u

### Steps to reproduce the bug

[warn] [nuxt] You are using a plugin with legacy Nuxt 2 format (context, inject) which is likely to be broken. In the future they will be ignored: PiniaNuxtPlugin

### Expected behavior

Works as expected

### Actual behavior

Can not start nuxt3 project

**Comment by posva** [comment]
There are some changes in the latest Nuxt 3 versions tha break the pinia plugin. Should be fixed once #1435 is ready and merged

**Comment by jkirkpatrick** [comment]
Problem regressed with Nuxt3-RC6 (using Pinia 2.0.16 / @pinia/nuxt 0.1.9)
