### ISSUE TITLE
[Nuxt 3] You are using a plugin with legacy Nuxt 2 format (context, inject) which is likely to be broken. In the future they will be ignored: PiniaNuxtPlugin

### ISSUE THREAD

**Issue by tntsoft** [posva/pinia#1470]
### Reproduction

-

### Steps to reproduce the bug

On a fresh Nuxt 3 installation, Nuxt throws a warning in the console
```[nuxt] You are using a plugin with legacy Nuxt 2 format (context, inject) which is likely to be broken. In the future they will be ignored: PiniaNuxtPlugin```

Pinia is still working properly at the moment, but I believe further changes are needed in order to ensure it will continue to be compatible in the future.

### Expected behavior

It shouldn't throw a warning in the console. 

### Actual behavior

The application is throwing a warning in the console. 🤷‍♂️

**Comment by posva** [comment]
Cannot reproduce: https://github.com/piniajs/example-nuxt-3. Maybe you are using an outdated version of `@pinia/nuxt`.

Open a new issue with a boiled down reproduction if you manage to reproduce it

**Comment by tntsoft** [comment]
> Cannot reproduce: https://github.com/piniajs/example-nuxt-3. Maybe you are using an outdated version of `@pinia/nuxt`.
> 
> Open a new issue with a boiled down reproduction if you manage to reproduce it

Thank you! Indeed I was using an old version of ```@pinia/nuxt``` 🤦‍♂️, apologies.
