### ISSUE TITLE
The font style of sample code in pinia docs

### ISSUE THREAD

**Issue by Userzhizhong** [posva/pinia#1482]
### What problem is this solving

Dear developer of pinia:
    Hello.The font of sample code in pinia docs is so curious that I could not focus on code itself.so, would you like to replace it.

### Proposed solution

replace the font-style with normal style

**Comment by posva** [comment]
Already opened multiple times. Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
