### ISSUE TITLE
esm-browser.js causes `process is not defined`

### ISSUE THREAD

**Issue by kaoet** [posva/pinia#1485]
### Reproduction

https://jsfiddle.net/as2n8e7o/

### Steps to reproduce the bug

Import `pinia.esm-browser.js` as module in browser. See my reproduce link.

### Expected behavior

Pinia imported correctly

### Actual behavior

Browser console says `Uncaught ReferenceError: process is not defined`

**Comment by posva** [comment]
It should indeed be replaced with `"development"`. Note the browser version should be avoided in production as it's way bigger due to including devtools
