### ISSUE TITLE
Typescript: Property $nuxt doesn't exist in Nuxt 2

### ISSUE THREAD

**Issue by theolavaux** [posva/pinia#1491]
The repro is not a Nuxt app but I have this exact error in my Nuxt app, does it mean that `@pinia/nuxt` isn't picked up by Typescript?

### Reproduction

https://stackblitz.com/edit/github-jp3cee-v12zs6?file=src/stores/counter.ts

### Steps to reproduce the bug

1. Initialize an app with `typescript@4.7.3` and `pinia@2.0.14`
2. Create a store
3. Inside actions, try to access `this.$nuxt`

### Expected behavior

Not have errors and infer types

### Actual behavior

Property '$nuxt' does not exist on type '{ test(): void; } & { n: number; } & _StoreWithState<"counter", { n: number; }, {}, { test(): void; }> & _StoreWithGetters<{}> & PiniaCustomProperties<string, StateTree, _GettersTree<...>, _ActionsTree>'.

**Comment by posva** [comment]
See https://github.com/vuejs/pinia/blob/v2/packages/nuxt/CHANGELOG.md#030-2022-07-13 and https://pinia.vuejs.org/ssr/nuxt.html#typescript

**Comment by theolavaux** [comment]
But I'm using `@pinia/nuxt` version `0.1.9`, so I don't think it's related
