### ISSUE TITLE
Getting warning: You are using a plugin with legacy Nuxt 2 format

### ISSUE THREAD

**Issue by safejace** [posva/pinia#1545]
### Reproduction

n/a

### Steps to reproduce the bug

upgrade from nuxt rc4 to rc 5 6 7 or 8 using `npx nuxi upgrade`

`yarn dev` to spin up dev server

### Expected behavior

no pinia errors

### Actual behavior

when i start the dev serve i get this error:

```
[warn] [nuxt] You are using a plugin with legacy Nuxt 2 format (context, inject) which is likely to be broken. In the future they will be ignored: PiniaNuxtPlugin

```

and then while the website it running this error pops up on every page load: 
```
[nuxt] [request error] [unhandled] [500] Cannot set properties of undefined (setting 'pinia')
  at PiniaNuxtPlugin (./.nuxt/dist/server/server.mjs:36760:31)  
  at ./.nuxt/dist/server/server.mjs:488:27  
  at fn (./.nuxt/dist/server/server.mjs:517:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:49:19)  
  at callWithNuxt (./.nuxt/dist/server/server.mjs:519:23)  
  at applyPlugin (./.nuxt/dist/server/server.mjs:463:29)  
  at Module.applyPlugins (./.nuxt/dist/server/server.mjs:473:11)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async createNuxtAppServer (./.nuxt/dist/server/server.mjs:46:7)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
  ```

**Comment by safejace** [comment]
ping @danielroe

**Comment by safejace** [comment]
just to add on, when running `yarn build` or `yarn generate` i get :

```
 ERROR  Rollup error: Could not load /Users/jace.bennest/Development/safecom-fmeuc/node_modules/pinia/dist/pinia.mjs/dist/pinia.mjs (imported by .nuxt/dist/server/server.mjs): ENOTDIR: not a directory, open '/Users/jace.bennest/Development/safecom-fmeuc/node_modules/pinia/dist/pinia.mjs/dist/pinia.mjs'

```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏  I'm particularly interested in what version of `@pinia/nuxt` you have installed.

**Comment by Denoder** [comment]
if you are still getting this add `pinia` to `build.transpile`

**Comment by safejace** [comment]
still trying to get a repro going here. but @Teranode adding `'pinia'` to `build.transpile` didn't help

**Comment by safejace** [comment]
@danielroe created the repro. so i think the issue, like you mentioned before was the `@pinia/nuxt` version. 

package.json had `^0.1.8` and `yarn.lock` showed `0.1.9` was installed.

when making the repro it looked like `0.4.0` is  the default now. 

i am about to go test that for my local project, i guess my question is why `npx nuxi upgrade` didn't also upgrade that? i worry that other packages i have might get stuck on old versions because of this

i suppose it was locked to `0.1.x` cuz of the `^`...

**Comment by danielroe** [comment]
`nuxi upgrade` will regenerate your lockfile (if used with --force) and upgrade Nuxt itself but won't upgrade other packages outside of the version constraints in your package.json.

**Comment by andresespinosapc** [comment]
> just to add on, when running `yarn build` or `yarn generate` i get :
> 
> ```
>  ERROR  Rollup error: Could not load /Users/jace.bennest/Development/safecom-fmeuc/node_modules/pinia/dist/pinia.mjs/dist/pinia.mjs (imported by .nuxt/dist/server/server.mjs): ENOTDIR: not a directory, open '/Users/jace.bennest/Development/safecom-fmeuc/node_modules/pinia/dist/pinia.mjs/dist/pinia.mjs'
> ```

I had that same problem. Adding `pinia` to `build.transpile` did solve the issue.
