### ISSUE TITLE
How to patch inside Composition Store

### ISSUE THREAD

**Issue by max5432112345** [posva/pinia#1557]
### Reproduction

---

### Steps to reproduce the bug

How to use store.$patch({ count: 24 })?
To pas store from component to itself in store (no this)?

I have a state

interface IStoreData {
  [key: string]: {
    items: Array<any>,
    }
}

and want to add/replace 

const addListItem = (payload) => {
    data[payload.type]  = payload.data
}

state = 1 not work in action

### Expected behavior

An normal example

### Actual behavior

nothing not work

**Comment by max5432112345** [comment]
may be data.value[payload.type] ?

**Comment by max5432112345** [comment]
yes it was fuc**king .value

**Comment by posva** [comment]
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
