### ISSUE TITLE
Add ability to reset within the store

### ISSUE THREAD

**Issue by axelthat** [posva/pinia#1558]
### What problem is this solving

As far as I know, it's only possible to reset a store outside that store: https://pinia.vuejs.org/core-concepts/state.html#resetting-the-state. However, it would be nice to have an option to reset a store within a store.

### Proposed solution

Something like,

```
export const useUserStore = defineStore('user', ({ reset }) => {
  const clear = () => {
    // some tasks..
    reset()
  }

  return {
    clear
  }
})
```

**Comment by posva** [comment]
This limitation is intentional: reset is only for option stores and it just calls the `state()` method.

**Comment by stevebauman** [comment]
Not sure if this helps you, but I do this right now by extracting out the state into a method:

```js
const getDefaultState = () => ({ '...' });

export const useUserStore = defineStore('user', {
    state: () => getDefaultState(),

    actions: {
        clear() {
            this.$state = getDefaultState();
        },
    },
});
``
