### ISSUE TITLE
$reset seems to be broken

### ISSUE THREAD

**Issue by ma-jahn** [posva/pinia#1565]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-vh6d9u?file=package.json,store%2Findex.ts,nuxt.config.ts,app.vue

### Steps to reproduce the bug

1. Open the reporduction repo
2. click on reset

### Expected behavior

The store will be set to it's initial state.

In this case a should print `a` instead of `test`

### Actual behavior

In the console you'll find the following error:
```
Uncaught TypeError: Cannot read properties of undefined (reading '$patch')
```

### Additional information

Am i creating the store wrong or am i misusing the `$reset` function?

**Comment by posva** [comment]
You cannot destructure $reset, it’s not an action. It has to be called as a method (store.$reset())

**Comment by ma-jahn** [comment]
@posva Thank you!
