### ISSUE TITLE
problem with linked dependency

### ISSUE THREAD

**Issue by digi604** [posva/pinia#159]
We have a package A with pinia dependency and we have a package B with a package A dependency.

If you install normally via npm it works. But if you link package A with npm link only the stores in package A still work. Packages in B are missing the "register module – ModuleName" console logs and do not show up in devtools. The mutations show up in devtools but no actual data is found as the store are not found. No error message is displayed.

**Comment by digi604** [comment]
If you remove pinia dependency from package A and add it to B then everything works even when linked.

**Comment by posva** [comment]
Yeah, this is probably the same problem coming from composition-api: you need to link `@vue/composition-api` inside `pinia` and the package using `pinia`.
I don't think there is anything we can do about it

**Comment by digi604** [comment]
how do you link that?

**Comment by posva** [comment]
inside `pinia` and inside the app using `pinia`: `yarn link @vue/composition-api` + `yarn link pinia` in the app as well

**Comment by digi604** [comment]
thank you
