### ISSUE TITLE
Why is Pinia disabling VueX in Nuxt?

### ISSUE THREAD

**Issue by MartinMalinda** [posva/pinia#160]
https://github.com/posva/pinia/blob/master/nuxt/index.js#L8

Is Pinia conflicting with VueX and it has to be turned off or is this just for the convienience?

This makes gradual migration from VueX to Pinia a bit difficult.

My guess is that Pinia is quite well encapsulated so it can totally live side by side to Vuex, there shouldn't be any conflicts on the context.

**Comment by posva** [comment]
You can indeed use both! I documented the `disableVuex` option on the readme

**Comment by MartinMalinda** [comment]
Awesome, I figured it out as well in the meantime 👍
