### ISSUE TITLE
Intellisense is broken when have more than one function in store

### ISSUE THREAD

**Issue by davidmeirlevy** [posva/pinia#1636]
### Reproduction

https://github.com/d-stuff/test-pinia-intellisense/blob/main/src/store.ts

### Steps to reproduce the bug

clone my repo to jump over steps 2-3:

1. use webstorm, not vscode. (it works well on vscode).
2. create a new vite project+ Vue + pinia.
3. add store using setup function store (https://github.com/d-stuff/test-pinia-intellisense/blob/main/src/store.ts).
4. use the store in any component (https://github.com/d-stuff/test-pinia-intellisense/blob/main/src/App.vue).

when the store has one function - the IntelliSense acknowledges the function and helps with interfaces and such.
when the store has 2 functions or more - neither of the functions is acknowledged.

when I open an object and put the functions inside it  - the IntelliSense works!

### Expected behavior

The IDE should acknowledge functions returned from the store setup function.

### Actual behavior

the functions are painted in red of gray.

### Additional information

those functions work and the build passed successfully. it's only an intellisense issue in webstorm.

**Comment by LinusBorg** [comment]
Hi!

If this is a Webstorm IDE problem, we won't be able to solve it. We are not affiliated with them or have any influence on their IDE support for Typescript or Vue. You will need to open a ticket with them.

**Comment by davidmeirlevy** [comment]
I also thought it might be, but they do acknowledge a function when you have only one function, so it made me wonder if that's some interface issue that I couldn't find.

**Comment by davidmeirlevy** [comment]
@LinusBorg can my screen recording change your mind about where is the bug in here?

https://user-images.githubusercontent.com/6875922/189086750-e3d42343-99f3-4c8b-a24c-79243c0ffc02.mov

**Comment by LinusBorg** [comment]
Not really. As you said it works in vscode. It does not work in webstorm. It also compiles successfully as I understand.

So why should I not assume the problem is with Webstorm?

**Comment by davidmeirlevy** [comment]
IDK. maybe some complex type definition makes it behave differently when it has more than 1 function?

**Comment by LinusBorg** [comment]
Then Intellisense in Webstorm needs to be fixed to correctly work with that type definition.

We won't change a correct type (correct as in: Vscode and a check with `tsc` don't show any type errors and don't have problems with it) to make it work with a shortcoming in webstorm's Intellisense.

**Comment by davidmeirlevy** [comment]
Thanks.
Webstorm assigned this bug to one of their developers:
https://youtrack.jetbrains.com/issue/WEB-57210/Intellisense-is-broken-when-have-more-than-one-function-in-store-vite-vue-pinia
