### ISSUE TITLE
Reactivity not triggering when whole store is patch (from empty initial state)

### ISSUE THREAD

**Issue by DarioRega** [posva/pinia#1639]
Hello, and first of all, thanks for the awesome tool !

### Reproduction

https://codesandbox.io/s/beautiful-maxwell-0hddi1?file=/src/stores/deal.ts

### Steps to reproduce the bug

1. Check the store/deal.ts file and in the _fetchSingle()_ method i've tried various way to 'patch' the whole state.
2. Go in the Home component and refresh the view, see that only the variation with _dealStore.$state.myProp_ is reactive, the others aren't.

### Expected behavior

that the two properties update accordingly

### Actual behavior

Only the dealStore.$state.myProp shows the update

### Additional information

My case is the following:
1. I have an empty state that i return as empty object with the _as IState_ to benefit auto completion.
2. fetchSingle is normally a async method that gives me back a complexe data object from the backend
3. I can benefit from all the typing everywhere
4. However when updating the whole store (with the huge object) it seems not reactive for the consumers of the store (in the Vue devtool it is updated)

Nb: If i declare the values with defaults in my state, the reactivity works, however, isn't it possible to avoid typing the whole thing as mentioned [here](https://pinia.vuejs.org/core-concepts/state.html#typescript).

I've tried aswell Object.assign() or others stuff. Maybe it is not a bug but am i missing something ? I would like to update the whole thing at once, and as seen in the doc, i've tried the patch method.

Codesandbox: https://codesandbox.io/s/beautiful-maxwell-0hddi1?file=/src/stores/deal.ts

Let me know if you need any additional informations.

Thanks in advance!

EDIT: Greeting like a proper human being

**Comment by posva** [comment]
This is indeed expected: state properties have to be defined initially in state or they will only be accessible in store.$state. I think we can talk shortly about this at https://pinia.vuejs.org/core-concepts/state.html#replacing-the-state. Maybe you want to PR? I added this to the docs issue

**Comment by DarioRega** [comment]
With pleasure, i could add  a small section that explains it. I'll try to submit something for next week !

Thanks for the time taken for the issue.
