### ISSUE TITLE
Pinia Nuxt not working

### ISSUE THREAD

**Issue by typhoon11** [posva/pinia#1642]
### Reproduction

Not working

### Steps to reproduce the bug

After installing @pinia/nuxt and starting the nuxt project it throws error  
Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs'   

### Expected behavior

It should work

### Actual behavior

It doesn't work

### Additional information

Nuxt version is 3.0.0-rc.9 and pinia nuxt version is 0.4.2

**Comment by a-toms** [comment]
I'm having this problem too on macos, Nuxt 3.0.0-rc.8. 

To replicate, simply create a new nuxt 3 project with nuxt/pinia listed as a dependency.

In the meantime, you can use composables in nuxt 3 to manage shared state: https://v3.nuxtjs.org/guide/features/state-management/
