### ISSUE TITLE
什么时候有中文的文档？

### ISSUE THREAD

**Issue by rjl-cli** [posva/pinia#1652]
### What problem is this solving

英文能力有限，只能借助谷歌翻译或第三方文档。但是这会导致一些问题，比如，第三方的更新慢，质量无法保证。

### Proposed solution

中文的文档我们可以 https://cn.pinia.vuejs.org/

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/pinia/pull/1193

**Comment by posva** [comment]
We are waiting for vitepress 1 to support i18n, upgrade and add the docs
