### ISSUE TITLE
Nuxt 3 + webpack + pinia => build fails Cannot find module pinia/dist/pinia

### ISSUE THREAD

**Issue by jeffcunat** [posva/pinia#1688]
### Reproduction

https://stackblitz.com/edit/github-k41ufy

### Steps to reproduce the bug

1. run in Terminal : yarn build
2. node .output/server/index.mjs
3. See that there is 500 error

### Expected behavior

That nuxt 3 with webpack builds work 

### Actual behavior

We get a 500 error
[nuxt] [request error] [unhandled] [500] Cannot find module '/home/projects/github-k41ufy/.output/server/node_modules/pinia/dist/pinia' imported from /home/projects/github-k41ufy/.output/server/chunks/app/server.mjs

### Additional information

seems to be related to the way pinia is exported in package.json
https://github.com/vuejs/pinia/blob/v2/packages/pinia/package.json#L10

It gives this webpack code in server.mjs
`import * as __WEBPACK_EXTERNAL_MODULE_pinia__ from 'pinia/dist/pinia';`

Without the 'node' section in package.json, build actually works
`import * as __WEBPACK_EXTERNAL_MODULE_pinia__ from 'pinia';`

**Comment by posva** [comment]
It works without Nuxt so I suspect you need to add support for `mjs` files like at https://github.com/piniajs/vue-3-cli-webpack-4
