### ISSUE TITLE
Production Build + Vue Devtool Plugin Error

### ISSUE THREAD

**Issue by zcrumbo** [posva/pinia#1693]
### Reproduction

https://codesandbox.io/s/cedarexamplesandbox-forked-idhgg3?file=/vite.config.js

### Steps to reproduce the bug

When attempting to use Vue Devtools in a production build by setting `__VUE_PROD_DEVTOOLS__: true`, there is an error when using Pinia

1. Go to https://codesandbox.io/s/cedarexamplesandbox-forked-idhgg3?file=/vite.config.js
2. Click on Terminal under preview pane
3. Click `+` to add another terminal instance
4. Execute a production build and start the server with `npm run build && npm run serve` (you should be prompted to open the new port in another browser pane)
![image](https://user-images.githubusercontent.com/16909348/192639011-f116af06-49ec-4a93-aede-47cbb4fb3f0e.png)
5. Open the production build instance in a new window 
![image](https://user-images.githubusercontent.com/16909348/192639124-9390b7ef-763e-415e-bd15-73a8c5b5e53e.png)
6. open the console and Vue devtools

### Expected behavior

Vue devtools should work as expected with no errors

### Actual behavior

Console error: 
```client-hook-6.js:1 TypeError: Cannot read properties of undefined (reading 'forEach')
    at index.b5e1fa3c.js:7:1055
    at addPlugin (VM240 backend.js:3068:7)
    at async Object.<anonymous> (VM240 backend.js:2229:5)
```
Looking through the stack trace, there is a [property that Pinia is adding in non-prod environments](https://github.com/vuejs/pinia/blob/v2/packages/pinia/src/store.ts#L454-L461), and is being referenced by the [devtools plugin code](https://github.com/vuejs/pinia/blob/v2/packages/pinia/src/devtools/plugin.ts#L386) 
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/16909348/192639330-2f0301c5-2fc2-4be3-a509-ff07cb9fd661.png">

**Comment by posva** [comment]
The code should be added if devtools is active. It's in multiple places. Contribution welcome!
