### ISSUE TITLE
doc: Use `Vue state management library` instead of `Vue Store` in docs

### ISSUE THREAD

**Issue by awxiaoxian2020** [posva/pinia#1697]
### What problem is this solving

In Vuex docs, we use `Vue state management library` to describe it's function. But in Pinia, We use "Store" capitalized, which seems to imply that it is a proper noun, and it is. I personally think this description is unfriendly to beginners and translators.

### Proposed solution

Use `Vue state management library` instead of `Vue Store` in docs.

**Comment by posva** [comment]
They are different words, they were used in different contexts. Feel free to send your PR, maybe it does improve the docs if changed in some places
