### ISSUE TITLE
Pass previous state to store.subscribe

### ISSUE THREAD

**Issue by MartinMalinda** [posva/pinia#171]
https://github.com/posva/pinia/blob/765e487a19a8563f5607d0fadd0ea4efce3e1f59/src/store.ts#L71

According to the the docs, `watch` should provide a previous value so it could be passed in subscriptions. It could then be used to create a diff in DevTools or logging utility.

**Comment by posva** [comment]
since pinia mutates the object, it will be the exact same object and cannot be used for diffs in devtools. What you can is create a custom function that creates snapshots of the states instead. Similar to what happens with devtools
