### ISSUE TITLE
Property '_s' does not exist on type 'Pinia'

### ISSUE THREAD

**Issue by Oleksii14** [posva/pinia#1716]
### Reproduction

https://github.com/Oleksii14/pinia-s-issue

### Steps to reproduce the bug

1. Open the attached codebase
2. Check the error

### Expected behavior

`_s` property is declared in the `Pinia` interface

### Actual behavior

`_s` property is not declared in the `Pinia` interface

### Additional information

The issue itself:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/36737084/195267567-e949d6b4-8efc-49e0-a74a-de4f06424478.png">

The `Pinia` interface (some properties as well as `_s` are excluded):

<img width="405" alt="image" src="https://user-images.githubusercontent.com/36737084/195267666-bb626dae-8789-4e79-b26c-d3720ad92297.png">

**Comment by posva** [comment]
The store map is internal and therefore application code shouldn’t rely on it. If you really want to use it, you will have to add a ts-expect-error or cast the variable. I doubt we will need to change that property name 🙂

**Comment by Oleksii14** [comment]
> The store map is internal and therefore application code shouldn’t rely on it. If you really want to use it, you will have to add a ts-expect-error or cast the variable. I doubt we will need to change that property name 🙂

In that case, is there a better example of how can I reset all the stores?

**Comment by Oleksii14** [comment]
@posva ping
