### ISSUE TITLE
check the object first

### ISSUE THREAD

**Issue by liwei8** [posva/pinia#1719]
### Reproduction

check the object first

### Steps to reproduce the bug

when ModuleFederationPlugin error。。。
change
if (!pinia._s.has(id)) {
to
if (!pinia || !pinia  || !pinia._s.has(id)) {

### Expected behavior

error

### Actual behavior

null

### Additional information

haha

**Comment by posva** [comment]
Issues must have a boiled down reproduction. Open a new one if you can provide a reproduction.
