### ISSUE TITLE
[Vue warn]: injection "Symbol(pinia)" not found. 

### ISSUE THREAD

**Issue by wonderfulMan** [posva/pinia#1730]
### Reproduction

you can use createVnode create functional component and use store in component，You get this warning

### Steps to reproduce the bug

package.json 
    - vue :  ^3.2.37
    - pinia: ^2.0.17

use :
1. createVNode create popup component

![image](https://user-images.githubusercontent.com/29673031/196362290-af2be830-315d-437e-b7a6-2fcf803a74e2.png)

![image](https://user-images.githubusercontent.com/29673031/196361368-f303b72b-a633-4d0c-902f-ccdffe34f46a.png)

usePopup can passing a parameter(component) then for internal use store

![image](https://user-images.githubusercontent.com/29673031/196362709-fe54bfa1-b188-49d3-b514-8822d6cda155.png)

![image](https://user-images.githubusercontent.com/29673031/196360944-3611f50b-a0fd-45a1-9519-c108c93f234b.png)

2. but i inject pinia in my main.ts

![image](https://user-images.githubusercontent.com/29673031/196362424-6511e395-638d-4e7b-bc42-54db64c391af.png)
![image](https://user-images.githubusercontent.com/29673031/196361140-978e3245-5645-465f-8693-c48401d1e747.png)

3. Is something wrong with me？please tell me，thank you

### Expected behavior

all nothing in console

### Actual behavior

console warning!

**Comment by LinusBorg** [comment]
Please provide a runnable reproduction as is required in the issue guidelines.
