### ISSUE TITLE
用setup-stores 方式定义非响应式数据为什么在组件中是响应的

### ISSUE THREAD

**Issue by daoke001** [posva/pinia#1735]
### Reproduction

https://github.com/daoke001/pinia_bug.git

### Steps to reproduce the bug

```
import { defineStore } from 'pinia';
import { reactive, toRefs } from 'vue';
export const useUserStore = defineStore('user', () => {
    let family = reactive({ sheep: 1 })

    // let { sheep } = toRefs(family);     //sheep 在组件中是响应的，在devtools 中也表现正常
    // let { sheep } = family;             //sheep 在组件中是响应的，在devtools 中不响应
    let sheep = 1;                      //sheep 在组件中是相应的，在devtools 中不响应
    return { family, sheep }
})
```

### Expected behavior

` let { sheep } = family;`
`let sheep = 1; `
以上两种方式在组件中不应该是响应式的数据

### Actual behavior

` let { sheep } = family;`
`let sheep = 1; `
以上两种方式在组件中表现为是响应式的数据，但devtools表现不正常

**Comment by posva** [comment]
it must be a ref if you want it to be state: `let sheep = ref(1)`
