### ISSUE TITLE
通过$subscribe订阅state更新的参数规格

### ISSUE THREAD

**Issue by meiguiyisenluo** [posva/pinia#1768]
### What problem is this solving

如果是使用赋值运算符同步更新多个state时，监听器只会被最后一次state更新触发，其中mutations.events是个对象。如果使用$patch更新state，所有的state更新都会被按更新顺序收纳进数组中，放到mutations.events。需要针对两种不同参数进行处理。

### Proposed solution

如果直接统一返回数组的形式会不会更好，这样直接遍历mutations.events做相应的state更新处理就可以了

**Comment by posva** [comment]
Use a different `flush` mechanism. Note events are dev only, as mentioned in docs. They come from what Vue is able to provide: https://vuejs.org/guide/extras/reactivity-in-depth.html#component-debugging-hooks

**Comment by meiguiyisenluo** [comment]
Thank you for your help

**Comment by meiguiyisenluo** [comment]
> Use a different `flush` mechanism. Note events are dev only, as mentioned in docs. They come from what Vue is able to provide: https://vuejs.org/guide/extras/reactivity-in-depth.html#component-debugging-hooks

Thank you for your help
