### ISSUE TITLE
mutations.events生产环境为undefined

### ISSUE THREAD

**Issue by meiguiyisenluo** [posva/pinia#1769]
### Reproduction

https://pinia.web3doc.top/core-concepts/state.html#%E8%AE%A2%E9%98%85%E7%8A%B6%E6%80%81

### Steps to reproduce the bug

官网上介绍的$subscribe：[https://pinia.web3doc.top/core-concepts/state.html#%E8%AE%A2%E9%98%85%E7%8A%B6%E6%80%81](url)

其中并没有提到回调函数的参数mutations.events，且在开发环境中为state更新的记录，在生产环境上却为undefined。

本是想通过mutations.events来判断是什么state变化。

### Expected behavior

希望生产环境保持与开发环境一致

### Actual behavior

在开发环境中为state更新的记录，在生产环境上却为undefined。

**Comment by posva** [comment]
This is documented and other issues: events is dev only, it comes from Vue's DebuggerEvent.

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://chat.vuejs.org/) to ask questions!

**Comment by posva** [comment]
I already said it at #1768 ...

Please use English in issues and questions in the repository

**Comment by edk24** [comment]
替代方案可以用 `$onAction`, 我的程序是调用 `actions` 更新 `state` 的, vue pinia 文档真的很坑, 没有说明这一点, 还好上线前发现了这个问题

can use `$onAction`, my program is called the `actions` to update the `state`

```js
// 订阅救护车数据更新
    ambulance.$onAction(
      ({
        name, // action 名称
        args, // 传递给 action 的参数数组
      }) => {
        if (name == 'updated') { // action name

          args.forEach(row => {
            const coord = [row.latest_longitude, row.latest_latitude];
            mapRef.value.updateAmbulance(row);
            console.info(`位置发生改变: ${row.car_number} => ` + coord.join(', '));
          })
          
        }
      }
    );
```

**Comment by meiguiyisenluo** [comment]
> 替代方案可以用 `$onAction`, 我的程序是调用 `actions` 更新 `state` 的, vue pinia 文档真的很坑, 没有说明这一点, 还好上线前发现了这个问题
> 
> can use `$onAction`, my program is called the `actions` to update the `state`
> 
> ```js
> // 订阅救护车数据更新
>     ambulance.$onAction(
>       ({
>         name, // action 名称
>         args, // 传递给 action 的参数数组
>       }) => {
>         if (name == 'updated') { // action name
> 
>           args.forEach(row => {
>             const coord = [row.latest_longitude, row.latest_latitude];
>             mapRef.value.updateAmbulance(row);
>             console.info(`位置发生改变: ${row.car_number} => ` + coord.join(', '));
>           })
>           
>         }
>       }
>     );
> ```

ok,Thank you for your help. It was very helpful
