### ISSUE TITLE
Sync plugin data initialization

### ISSUE THREAD

**Issue by tanghaojie** [posva/pinia#1779]
### What problem is this solving

Sync plugin install when initialization, for network data patch to store.
Now, this is async.

### Proposed solution

```js
async function piniaPlugin(context) {
  const initialData = await fetch('')
  context.store.$patch(initialData)
}
```

**Comment by posva** [comment]
Can you elaborate? Thanks

**Comment by tanghaojie** [comment]
I'm design a network pinia persist plugin. like this:
```js
function piniaNetworkPersistPlugin(context: PiniaPluginContext) {
  const { store } = context

  // Need sync restore network data
  fetch('https://get persisted value').then((persistedVal) => {
    store.$patch(persistedVal)
  })

  // async persist state is ok
  store.$subscribe(
    (mutation, state) => {
      networkPersistState(state)
    },
    { detached: true }
  )
}
```
When i useStore, i want initialize it from network data first.
But use the code above, store will initialize to defaut value, then change to `persistedVal` after `fetch` success.

**Comment by posva** [comment]
I see. Unfortunately, this is not possible. Plugins have to be sync otherwise the stores would be initialized partially by plugins while types could say otherwise and create other confusing problems. In your case you should gather the promises and let the user await them themselves:

```ts
export const pendingPromises: Promise<any>[] = []
export function isReady() {
  return Promise.all(pendingPromises)
}

// within pinia plugin:
pendingPromises.push(fetch(...))
```
