### ISSUE TITLE
Can mutation.event return the full path of the changed value in the $subscribe callback

### ISSUE THREAD

**Issue by Hansuku** [posva/pinia#1782]
### What problem is this solving

A example:
```javascript
import { defineStore } from 'pinia'

export const useFormData = defineStore('formData', {
  state: () => {
    return {
        arr: [{a:1}],
        obj: {a: 1}
    }
  }
})
```
```javascript
import { useFormData } from '...'

export default {
  setup() {
    const formDataStore = useFormData()
    formDataStore.$subscribe((mutation, state) => {
       console.log(mutation, state)
    })
  },
}
```
now, if  i change `formData.arr[0].a = 2`, mutation will callback `mutation.event.key = 'a'`, but i want get full path like `arr[0].a`

### Proposed solution

Can add an attribute to mutation.event to identify the direct's full path?

**Comment by posva** [comment]
`events` come from Vue: https://vuejs.org/guide/extras/reactivity-in-depth.html#reactivity-debugging

Note this is **development only**, it will be empty in production, it's only for debugging purposes

There are plans to make the display of it better in devtools already (See #732)
