### ISSUE TITLE
Cannot read property 'req' of undefined

### ISSUE THREAD

**Issue by MartinMalinda** [posva/pinia#179]
Seems to happen at `setActiveReq(context.ssrContext.req);`

```
"nuxt": "^2.11.0",
"nuxt-composition-api": "^0.9.0",
"@vue/composition-api": "^0.6.1",
"pinia": "0.0.6",
```

universal mode

**Comment by MartinMalinda** [comment]
This issue disappears if I uninstall `nuxt-composition-api` so I guess this is caused by `nuxt-composition-api` doing something to the `ssrContext`

**Comment by posva** [comment]
Apart from creating a different plugin for nuxt to override the app.context like they do, I can't see a different solution

**Comment by danielroe** [comment]
@posva I've now exposed a `onGlobalSetup` hook that could work for Nuxt users like:
```ts
// In a plugin file
import { onGlobalSetup } from 'nuxt-composition-api'
import { setActiveReq } from 'pinia' // if this is exposed

export default () => {
  onGlobalSetup((props, context) => {
    setActiveReq(context.ssrContext.req)
  })
}
```

Let me know if there is anything else I can do from the `nuxt-composition-api` end.

**Comment by posva** [comment]
I haven't looked and probably won't be able to for a while but the solution shouldn't need any extra code from the users 🤔

**Comment by danielroe** [comment]
It was intended for you :smile: 

But I may have fixed the issue; will submit PR.
