### ISSUE TITLE
Warning injection "Symbol(pinia)" not found in tests.

### ISSUE THREAD

**Issue by tadeas-vintrlik** [posva/pinia#1790]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-tnzadn?file=src/components/__tests__/HelloWorld.spec.js

### Steps to reproduce the bug

Run the tests:
``yarn test:unit``

### Expected behavior

No warning to be displayed.

### Actual behavior

The warning ``[Vue warn]: injection "Symbol(pinia)" not found. `` is displayed.

### Additional information

  The tests suceeds and works as expected.
  This does not happen when running the app.

**Comment by posva** [comment]
you have a typo: it's `plugins` with an s
