### ISSUE TITLE
Use of Pinia state inconsistent across dev environments

### ISSUE THREAD

**Issue by Matthew-E-Gould** [posva/pinia#1793]
### Reproduction

-

### Steps to reproduce the bug

When developing with Pinia, the team I work with will access a state by just writing out the states name to get the value that is inside of it.
When I am working with Pinia I have to write out the states name then .value to get the value that is inside of it.

For example  if we were to develop the counter at https://pinia.vuejs.org/core-concepts/state.html#usage-with-the-options-api

The rest of the team would have to do `store.count++` to iterate the counter.
I however have to do `store.count.value++` to iterate the counter.

### Expected behavior

To be able to access a store by doing `store.variable`

### Actual behavior

I need to add value to access my stores variable, like `store.variable.value`

### Additional information

I have freshly installed my environment and this issue persists, however it works fine on my laptop.

IDK if this is useful to know but my desktop has an AMD processor and my laptop, along with the rest of my teams devices have Intel processors.

**Comment by Matthew-E-Gould** [comment]
Sorry for not providing a reproducting link, repo is private and have a meeting soon so can't set up a codepen

**Comment by LinusBorg** [comment]
We really won't be able to help you without any details in the form of a runnable code example and reproduction steps.

We can re-open the issue once you provide hose.

**Comment by Matthew-E-Gould** [comment]
Here's a reproduction link :)

https://codepen.io/Matthew-E-Gould/pen/OJEpeGe
