### ISSUE TITLE
The new recreated store should not restore the last disposed store's state.

### ISSUE THREAD

**Issue by DevilTea** [posva/pinia#1821]
### Reproduction

https://stackblitz.com/github/DevilTea/repro-pinia-dispose-issue

### Steps to reproduce the bug

1. Click the "Toggle" button on the left, the first time the store is installed. 
![step 1](https://raw.githubusercontent.com/DevilTea/repro-pinia-dispose-issue/main/screenshots/1.png)

1. Click the "Increment" button on the right several times, and check the number of counts. 
![step 2](https://raw.githubusercontent.com/DevilTea/repro-pinia-dispose-issue/main/screenshots/2.png)

1. Click the "Toggle" button on the left again, the store is disposed. 
![step 3](https://raw.githubusercontent.com/DevilTea/repro-pinia-dispose-issue/main/screenshots/3.png)

1. Click the "Toggle" button on the left again, the store is installed, but its state is restored. 
![step 4](https://raw.githubusercontent.com/DevilTea/repro-pinia-dispose-issue/main/screenshots/4.png)

### Expected behavior

The new recreated store should not restore the last disposed store's state.

### Actual behavior

The new recreated store restored the last disposed store's state.

### Additional information

I think the `$dispose` function should also delete the state inside `pinia.state.value`

https://github.com/vuejs/pinia/blob/v2/packages/pinia/src/store.ts#L342-L347

**Comment by posva** [comment]
Thanks, but this is intended. One should delete the state themselves if needed. I think it's worth adding this to the `$dispose` comment in the source code so it gets documented in the API. Could you maybe PR that?

**Comment by DevilTea** [comment]
> Thanks, but this is intended. One should delete the state themselves if needed. I think it's worth adding this to the `$dispose` comment in the source code so it gets documented in the API. Could you maybe PR that?

Ok, I will make a PR for that. Thank you for your reply!

**Comment by niksy** [comment]
@posva is deleting store state as now mentioned in docs (`delete pinia.state.value[store.$id]`) similar to calling `$reset` method? I see that `$reset` will keep store in registry, but reset to initial state instead of deleting whole store object, but are there any fundamental differences when trying to achieve use case where you want fresh store state?
