### ISSUE TITLE
New "setup store" uses old values after removing the old one

### ISSUE THREAD

**Issue by Kimbo0o** [posva/pinia#1832]
### Reproduction

https://stackblitz.com/edit/vue3-script-setup-with-vite-hbao6u?file=src/stores/testStore.ts

### Steps to reproduce the bug

1. Increase number in input (value is written to localStorage)
2. Click button to create child component and store
3. Click button again to destroy component and dispose store
4. Increase number in input again
5. Click button create new component and store

### Expected behavior

The store should initialize with the new number and use the new number afterwards. The new number should be displayed in the child component.

### Actual behavior

The store initializes with the new number, but uses old value afterwards. If you repeat steps 3-5 you always get the number from the first initialization.

**Comment by LinusBorg** [comment]
https://pinia.vuejs.org/api/interfaces/pinia._StoreWithState.html#dispose

> Note this doesn't delete the state of the store, you have to do it manually with delete pinia.state.value[store.$id] if you want to. If you don't and the store is used again, it will reuse the previous state.

**Comment by jasonvarga** [comment]
The link provided by Linus now 404s.
Here's the updated one: https://pinia.vuejs.org/api/pinia/interfaces/StoreWithState.html#-dispose-

>  Note this doesn't delete the state of the store, you have to do it manually with delete pinia.state.value[store.$id] if you want to. 

Using the following works:

```js
import { getActivePinia } from 'pinia';

// ...

store.$dispose();
delete getActivePinia().state.value[store.$id];
```

@posva I would reply to the issue I recently opened but you closed and locked it. Is there a reason that `$dispose` doesn't delete the state? Or, would there be interest in a method/argument that also deletes the state as instructed? I've seen a few people run into this.
