### ISSUE TITLE
Disallow casting getter to Ref

### ISSUE THREAD

**Issue by Q-back** [posva/pinia#1851]
### What problem is this solving

In the [documentation](https://pinia.vuejs.org/core-concepts/#using-the-store) I'm being encouraged to use `storeToRefs` function to map my **`state` and `getters`** to reactive refs. But is it good and should it be legal to map `getters` to `refs`? I can abuse the `getter` state after it's mapped to `ref`. I can make temporary changes to this `ref`, please check out this PR: https://github.com/vuejs/pinia/pull/1850

```typescript
// store
export interface ObjectyState {
  didChangeIllegally: boolean
  didChangeLegally: boolean
}

export const useObjectStore = defineStore('testStore', () => {
  const testStatePrivate: Ref<ObjectyState> = ref({
    didChangeIllegally: false,
    didChangeLegally: false,
  })

  const testStateGetter: ComputedRef<ObjectyState> = computed(() => {
    return { ...testStatePrivate.value }
  })

  function modifyLegalValue(newValue: boolean) {
    testStatePrivate.value.didChangeLegally = newValue
  }

  return { testStateGetter, modifyLegalValue }
})

// test
 it("doesn't loose track of getter", () => {
    const store = useObjectStore()
    expect(store.testStateGetter.didChangeIllegally).toBe(false)

    const { testStateGetter: testStateGetterRef } = storeToRefs(store)

    testStateGetterRef.value.didChangeIllegally = true
    console.log(
      store.testStateGetter.didChangeIllegally, // true
      store.testStateGetter.didChangeLegally // false
    )
    expect(store.testStateGetter.didChangeIllegally).toBe(false) // test fails here
    expect(store.testStateGetter.didChangeLegally).toBe(false)

    store.modifyLegalValue(true)
    console.log(
      store.testStateGetter.didChangeIllegally, // false (Here's the issue. This value got reset implicitly)
      store.testStateGetter.didChangeLegally // true
    )
    expect(store.testStateGetter.didChangeIllegally).toBe(false)
    expect(store.testStateGetter.didChangeLegally).toBe(true)
  })
```

### Proposed solution

You can change `storeToRefs` function to disallow casting `getters` to `ref` to prevent unwanted and buggy/temporary changes to `getter` state.

### Describe alternatives you've considered

Documentation can elaborate about this problem and disallow such usage of `getters`

**Comment by posva** [comment]
Thanks! The types are just not precise enough, I opened https://github.com/vuejs/pinia/issues/1852 instead as we don't want to remove the possibility to get refs from a store (a computed is a read only ref)
