### ISSUE TITLE
Is it possible to access Nuxt context from a pinia sotre?

### ISSUE THREAD

**Issue by isneezy** [posva/pinia#186]
First of all thanks for this awesome library.

When I'm using nuxt to build my apps, I normally tend to use Nuxt axios and auth modules for instance and have my API methods wrapped around vuex accessing `this.$axios` to perform HTTP requests without being worried about authentication and other configuration stuff.

I want to know if it is possible to have nuxt context injected inside my pinia store so i can keep using this pattern? If so how can I achieve this?

Thanks.

**Comment by posva** [comment]
I don't think there is a way to have Nuxt's context injected somewhere, but it would be really useful

**Comment by isneezy** [comment]
Ok, after digging a bit I found that with [nuxt-composition-api](https://github.com/nuxt-community/composition-api) all you have to do is call `useContext` and everything works.

Note I'm doing in spa mode IDK if it work as intended on SSR but the docs says it does.

```ts
// store/Users.ts
import { createStore } from 'pinia'
import { useContext } from 'nuxt-composition-api'

export type User = {
  id: number
  name: String
  username: String
  email: String
  password: String
}

export const useUsersStore = createStore({
  id: 'users',
  state: () => ({
    users: {} as { [id: number]: User }
  }),
  actions: {
    fetchUsers() {
      const { $axios } = useContext() // 👈️ here
      return $axios.$get<User>('/api/users').then((user) => (this.state.users[user.id] = user))
    }
  }
})
```

**Comment by posva** [comment]
ah, that's perfect!

**Comment by isneezy** [comment]
I think the issue is still valid, today I got an error saying that `useContext` must be called within a setup function.
It is happening because even if i call `useUserStore()` inside the setup function the call to a action `createUser()` witch uses `useContext()` is done later after the component has been rendered.

**Comment by isneezy** [comment]
Ok its not the most beatiful way but it works like a charm

I've created a helper function like this
```ts
// store/createNuxtStore.ts

import { Context } from '@nuxt/types'
import { getCurrentInstance } from 'nuxt-composition-api'

type createStoreType<R> = (ctx: Context) => (reqKey?: object | undefined) => R

export default function createNuxtStore<R>(createStoreFn: createStoreType<R>) {
  return (context?: Context) => {
    if (!context) {
      context = getCurrentInstance()?.$nuxt.context
      if (context === undefined) {
        throw new Error(
          'This must be called within a setup function or you must manually pass Nuxt Context'
        )
      }
    }
    return createStoreFn(context)(context.req)
  }
}
```
You use it to create your pinia store (works even if you just want to inject the context somewhere else)

```ts
// store/useTaskStore.ts
// simpified for brevity

import { createStore } from 'pinia'
import createNuxtStore from '~/store/createNuxtStore'

export default createNuxtStore((ctx) => {
  return createStore({
    id: 'tasks',
    state: () => ({
      tasks: [] as Task[],
    }),
    actions: {
      fetchTasks(params: Record<string, any> = {}) {
        return ctx.$axios
          .$get<Task[]>('/api/v1/tasks', { params })
          .then((tasks) => (this.state.tasks = tasks))
      },
    },
  })
})
```
And finaly you can use it on your components like this
```vue
<script lang="ts">
import { defineComponent } from 'nuxt-composition-api'
import { Context } from '@nuxt/types'
import useTaskTore from '~/store/useTaskStore'

export default defineComponent({
  setup() {
    const store = useTaskTore() // on setup function
    // store.state.tasks
  },
  fetch(ctx: Context): Promise<void> | void {
    return useTaskTore(ctx).fetchTasks() // on fetch/async data you must pass the context manually
  },
})
</script>
```

Another thing that I haven't tried yet, is the idea of ​​having a module or plugin that builds all the stores using the method mentioned above and inject into the Nuxt Context, so the need to manually send the context completely disappears.

**Comment by posva** [comment]
I added `$nuxt` to the plugin: https://pinia.esm.dev/ssr/nuxt.html#using-the-nuxt-context-in-stores

**Comment by n3x7j2** [comment]
@posva When I move store folder into src folder. It said:
![image](https://user-images.githubusercontent.com/5088270/137853633-4a56126d-961e-4e9c-b3bb-41ad7022be46.png)

**Comment by awacode21** [comment]
@posva I think about the same problem with vue 3 but without nuxt ?

**Comment by theolavaux** [comment]
Is there a way to get the `this.$nuxt` support inside store files using Typescript as well?

<img width="206" alt="Screenshot 2022-03-13 at 23 07 41" src="https://user-images.githubusercontent.com/25274586/158081244-61e1fa60-8ab9-4b09-aa28-7e9319ad2b83.png">
<img width="331" alt="Screenshot 2022-03-13 at 23 09 07" src="https://user-images.githubusercontent.com/25274586/158081304-36d8f2f8-7b85-4989-b9cb-65c8df7d1d1c.png">

**Comment by bpingris** [comment]
@theolavaux did you update your tsconfig `"types"` property with this:
```js
// tsconfig.json
{
  ...,
  "types": [
    ...
    "@pinia/nuxt"
  ],
  ..
}

**Comment by theolavaux** [comment]
Yes, did it! @bpingris
I'm using the composition api inside store files by passing a function as the second parameter of `defineStore`, could this be related to `this.$nuxt` not being recognized?

Like so
<img width="742" alt="Screenshot 2022-03-14 at 11 09 06" src="https://user-images.githubusercontent.com/25274586/158151083-a2131bc1-147f-438c-9e4c-8eabbc35f15c.png">

**Comment by bpingris** [comment]
hmm odd, I was defining my stores like so:
```ts
defineStore({
  id: 'foo',
  state: {},
  actions: {
    bar() {
      this.$nuxt.$foobar // type checking works
    }
  }
}
```
I also tried with the way you describe (a function as a 2nd parameter) and it also seems to work

**Comment by theolavaux** [comment]
I managed to understand why, the `this` keyword doesn't work properly when using arrow functions 😄

**Comment by jswhisperer** [comment]
await this.$nuxt.$axios.$get()

**Comment by Pasha8914** [comment]
you can use __self__
<img width="979" alt="image" src="https://github.com/vuejs/pinia/assets/43392281/00da2bdd-8ba8-44b5-954a-55b2c51e85c0">
