### ISSUE TITLE
`watchEffect` within a Setup Store is stopped unexpectedly

### ISSUE THREAD

**Issue by 0x009922** [posva/pinia#1862]
### Reproduction

https://stackblitz.com/edit/github-u4jlt8

### Steps to reproduce the bug

1. Click "Negate `store.flag`" buttonn any times you like. You will see how `store.flag` negates, ang how its computed `store.negated` stays reactive.
2. Uncheck "Show `StoreUser`" input. The component will be unmounted.
3. Check it again, to mount the component back.
4. Click "Negate" button again - `store.negated` is not reactive anymore.

https://user-images.githubusercontent.com/43530070/206888917-94ba28ba-6507-4bfd-a034-1d9e744de4fc.mov

### Expected behavior

I expected the [`watchEffect()`](https://vuejs.org/api/reactivity-core.html#watcheffect), called within a Setup Store, to be active as long as the store's scope is active. It makes possible for utilities like [`computedEager()`](https://vueuse.org/shared/computedeager/) just work in setup stores.

### Actual behavior

The watch effect seems to bind not to the store's setup scope, but to the component where the initial `useStore` invocation happened. Thus, when the component is unmounted, the watch effect is cleared and stopped, leaving the store in a broken and hard-to-debug state.

**Comment by posva** [comment]
Created https://github.com/vuejs/core/issues/7319 to track it
