### ISSUE TITLE
Add `storeToRefs` to the auto imports in @pinia/nuxt

### ISSUE THREAD

**Issue by productdevbook** [posva/pinia#1876]
### What problem is this solving

![image](https://user-images.githubusercontent.com/38668796/207515738-83704cff-0636-41f1-a2d8-0aca9ccd9694.png)

### Proposed solution

it needs to be added to the auto import field

**Comment by Cyclodex** [comment]
Hi, I just came across this ( I am moving from Vue 2 to Vue 3 + Nuxt + Pinia and learning how to setup things).

I just tried something, which actually seems to work, but not sure if something else would still be needed etc.

Add the `storeToRefs`-function name to the `autoImports` within the `nuxt.config.ts`:

```
modules: [
    [
      '@pinia/nuxt',
      {
        autoImports: [
          'storeToRefs',
```

I am using
```
Nuxt Version:     `3.0.0`
Runtime Modules:  `@pinia/nuxt@0.4.6`
```

No need to import it again :)

**Comment by mrleblanc101** [comment]
Shouldn't this be the default ?

**Comment by KnifeFed** [comment]
`@pinia/nuxt` 0.5.0 removed the `autoImports` option which broke all my references to `storeToRefs`. In the [CHANGELOG](https://github.com/vuejs/pinia/blob/3eee3352c9fcabd9043df39380328c393d94ac3b/packages/nuxt/CHANGELOG.md) it says "the option `autoImports` has been removed as it offered no value compared to the existing `imports` option in Nuxt". But as far as I can tell, you can only add directories to that option. So I guess this is broken until #2427 is released?

**Comment by Q16solver** [comment]
Yes, 0.5.0 is breaking my builds as well. Any user that is using `storeToRefs` as an auto import will have this issue, I believe we'll have to wait till it's added back

**Comment by minkoonim** [comment]
why remove autoimports config anyway  
it was great option

**Comment by minkoonim** [comment]
> Yes, 0.5.0 is breaking my builds as well. Any user that is using `storeToRefs` as an auto import will have this issue, I believe we'll have to wait till it's added back

> `@pinia/nuxt` 0.5.0 removed the `autoImports` option which broke all my references to `storeToRefs`. In the [CHANGELOG](https://github.com/vuejs/pinia/blob/3eee3352c9fcabd9043df39380328c393d94ac3b/packages/nuxt/CHANGELOG.md) it says "the option `autoImports` has been removed as it offered no value compared to the existing `imports` option in Nuxt". But as far as I can tell, you can only add directories to that option. So I guess this is broken until #2427 is released?


@Q16solver @KnifeFed 
https://nuxt.com/docs/guide/concepts/auto-imports#auto-import-from-third-party-packages
```
//nuxt.config.ts
...
  imports: {
    presets: [{
      from: 'pinia',
      imports: ['defineStore', 'storeToRefs', 'acceptHMRUpdate'],
    }],
  },
```
