### ISSUE TITLE
Pinia deep object binding error

### ISSUE THREAD

**Issue by jbaubree** [posva/pinia#1877]
### Reproduction

https://github.com/jbaubree/pinia-object-binding-bug

### Steps to reproduce the bug

Hi, i have found an issue using pinia with deep objects and input model binding.
I have just created a repo with minimal reproduction.
Just clone it and run `pnpm install` and `pnpm dev`

### Expected behavior

I have created a store with objects and i set this objects in App.vue with input and v-model on value
```
// store/test.ts
export const useTestStore = defineStore('test', {
  state: () => ({
    workingObject1: {} as unknown as MyWorkingObjectType,
    workingObject2: {} as unknown as MyWorkingObjectType,
    notWorkingObject1: {} as unknown as MyNotWorkingObjectType,
    notWorkingObject2: {} as unknown as MyNotWorkingObjectType,
  }),
})
```

```
// App.vue
<script setup lang="ts">
const testStore = useTestStore()
onMounted(() => {
  const notWorkingObject = { sub: { sub2: 'test' } }
  testStore.$patch({
    notWorkingObject1: notWorkingObject,
    notWorkingObject2: notWorkingObject,
  })
})
</script>

<template>
  <input
      v-if="testStore.notWorkingObject1.sub?.sub2"
      v-model="testStore.notWorkingObject1.sub.sub2"
      type="text"
    >
</template>
```

Expected behavior is to update only testStore.notWorkingObject1.sub.sub2 and not testStore.notWorkingObject2.sub.sub2 too.

### Actual behavior

This setup is updating 2 values (notWorkingObject1 and notWorkingObject2) with only one data binded.

### Additional information

For a better understanding, i have created [repro](https://github.com/jbaubree/pinia-object-binding-bug) with example working and not working cases.
I hope I am reporting this bug in the right place.

**Comment by LinusBorg** [comment]
This is basic Javascript behavior. Assigning the same object to two different variables / properties does *not* create a copy of that object - it just creates **two references** to the same **single** object. Changing one also changes the "other" as it's *the same single object*.

That's how Javascript works, not related to Pinia, Vue or its Reactivity.

**Comment by jbaubree** [comment]
@LinusBorg Thanks for your reply ! I have tried to make Object.assign() to create "new Objects" but this issue is persisting.. Do you know how to create real copies of my starting object ? Thanks

**Comment by LinusBorg** [comment]
the easiest solution would be a factory function:
```js
function createMyObject() {
  return {
    // .....
  }
}

export const useTestStore = defineStore('test', {
  state: () => ({
    workingObject1: {} as unknown as MyWorkingObjectType,
    workingObject2: {} as unknown as MyWorkingObjectType,
    notWorkingObject1: createMyObject(),
    notWorkingObject2: createMyObject()
  }),
})
```

**Comment by jbaubree** [comment]
@LinusBorg Thanks for your response and speed ❤️
