### ISSUE TITLE
unwrap/warn if ref is passed to action

### ISSUE THREAD

**Issue by swoga** [posva/pinia#1882]
### Reproduction

https://stackblitz.com/edit/github-vl7ve8?file=src/App.vue

### Steps to reproduce the bug

1. Click "Set (not OK)"
2. Observe that counter and event count is unchanged
3. Click "Increment"
4. Observe that the event count remains unchanged and counter is now in sync with input (as they both share a single ref object)

### Expected behavior

I think the parameters should be unwrapped or alternatively a warning should be displayed.
Reactivity and subscriptions should not be broken.

### Actual behavior

When passing a ref as a parameter to an action, undefined behavior occurs.
If this ref is set as state, no mutation is displayed in the timeline and subscriptions do not receive an event.

### Additional information

I don't use TypeScript, maybe IDEs already show a warning when a ref is passed to an action?

**Comment by posva** [comment]
This could be valid usage as the user could do the unwrapping in their action so we cannot change this behavior.

It's the kind of error that is picked up by a type system
