### ISSUE TITLE
"New Vuex Backend" VueDevTools option doesn't allow time travel

### ISSUE THREAD

**Issue by kevinmarrec** [posva/pinia#19]
## Versions
pinia: **0.0.2**
Vue DevTools : **5.3.3**

## Description

In Vue DevTools there is an option named "New Vuex Backend" that is bringing performance boost.
But it seems there's an issue when using `pinia` and that it's enabled.

![image](https://user-images.githubusercontent.com/25272043/70522303-2a04c000-1b41-11ea-8943-d276434099ba.png)

New Vuex Backend **OFF**
![image](https://user-images.githubusercontent.com/25272043/70520798-6387fc00-1b3e-11ea-9280-f8b6ebbe17e1.png)

New Vuex Backend **ON**
![image](https://user-images.githubusercontent.com/25272043/70520889-903c1380-1b3e-11ea-8c41-c39bf06ef994.png)

It seems there's an issue about keeping the old state, which make "Commit", "Revert" & "Travel Time" not working.

Toggling off the option fix the issues.

I've inspected Vue DevTools code and it seems that the "old" one turned legacy, at least around variable names in `else` statements here :
https://github.com/vuejs/vue-devtools/blob/dev/packages/app-backend/src/vuex.js#L128
https://github.com/vuejs/vue-devtools/blob/dev/packages/app-backend/src/vuex.js#L207

So I don't know if it's planned to be removed, but I guess that for now :

- `pinia` isn't fully compatible when the the option is enabled
OR
- `vue-devtools` may have an issue around states when the option is enabled
OR
- The option is not supposed to be used with `pinia` (but dunno, as things turn to become legacy around `vue-devtools`) 
-----
Still, awesome work @posva !

**Comment by posva** [comment]
Thanks for diving into it! For the moment, it's necessary to use the old backend, so the option must be turned off...
It would be great to be able to use the new backend, support both if possible or the new one only if not.

If anybody wants to pick this up, feel free! There aren't any unit tests for this, it's more of a manual testing thing

**Comment by posva** [comment]
This seems to be fixed now

**Comment by posva** [comment]
This is still a problem. If anybody wants to pick it up, I recommend looking at how vue-devtools handle the vuex integration (https://github.com/vuejs/vue-devtools/blob/dev/packages/app-backend/src/vuex.js) and look at the `devtools.ts` file in pinia.

My guess is that I should be emitting/listening to additional events (maybe `vuex:commit`) and that the solution is not too far

**Comment by posva** [comment]
Fixed in 043ae2a
