### ISSUE TITLE
Any plans to make Pinia framework-agnostic? Would it be possible?

### ISSUE THREAD

**Issue by minenwerfer** [posva/pinia#1918]
### What problem is this solving

Reusing the same codebase alongside Vue, React, Angular, Svelte, etc.

### Proposed solution

Replace Vue's ref()'s by a non-Vue-dependant reactivity observer.

**Comment by posva** [comment]
There are currently no plans because pinia uses Vue's reactivity API, so other frameworks would need to also use Vue within their code
