### ISSUE TITLE
$patch function replace value in remote object

### ISSUE THREAD

**Issue by mathias22osterhagen22** [posva/pinia#1920]
### Reproduction

https://github.com/mathias22osterhagen22/vuejs-pinia-patch-issue.git

### Steps to reproduce the bug

1. Create an Enum with object as keys (or any object)
![image](https://user-images.githubusercontent.com/60438474/211343890-d8230a2f-70d2-4be4-81ee-0c0ea7933ef2.png)
2. Create a property in the state & assign a value from the enum object (or a prop of an object)
![image](https://user-images.githubusercontent.com/60438474/211344032-80b8332d-0921-429c-8f2f-a324e73b4771.png)
3. Patch the property of the state with an object having the same properties
![image](https://user-images.githubusercontent.com/60438474/211344132-0933ba06-2a26-4d7e-9414-36b891dc5a1e.png)

### Expected behavior

1. State updating ✅
2. Object values updating ❌

### Actual behavior

1. State updating ✅
2. Object values updating ✅ <--- this should not happend

### Additional information

Object before patch: 
![image](https://user-images.githubusercontent.com/60438474/211344574-cdf91b89-d3e6-4fb4-bb2c-c0f7cef1fcc5.png)

Patching "TEST" updating the state + the object values passed as ref: 
![image](https://user-images.githubusercontent.com/60438474/211344732-38edc7f4-9758-4da2-95d3-41e14a597b3d.png)

This seems to happened because the `$patch` method is updating from bottom to top recursively: 
https://github.com/vuejs/pinia/blob/78ec9a186dcbce3d583db332ae22094a182358cc/packages/pinia/src/store.ts#L83

I met this issue because of the Local storage "loading" (with the plugin [https://github.com/prazdevs/pinia-plugin-persistedstate]( https://github.com/prazdevs/pinia-plugin-persistedstate))

I'm storing an Enum object in the state, stored in the local storage. On page reload the  `$patch` function is called and come to replace the value Enum object value for the entire website.

**Comment by LinusBorg** [comment]
Assigning an object to a different variable/object property does not make a copy. it just makes a new reference to the same object. That's just how JS works.
