### ISSUE TITLE
Could not resolve "./api/index. js"

### ISSUE THREAD

**Issue by vin-ni** [posva/pinia#1940]
### Reproduction

https://github.com/vin-ni/nuxt-pinia-bug

### Steps to reproduce the bug

1. `yarn install`
2. `yarn dev`

### Expected behavior

The server spins up and mounts pinia.

### Actual behavior

It errors and logs: `Could not resolve "./api/index. js"`

<img width="640" alt="Screenshot 2023-01-19 at 20 09 51" src="https://user-images.githubusercontent.com/9806572/213540205-6c649653-ed7e-41f1-a636-23ffebaa9dde.png">

### Additional information

Node Version: 18.13.0
OS: MacOS Ventura
Device: Macbook Pro M1 2020

Not sure where to post this. If it is a vite error or a pinia error.

I already tried @nuxt/pinia `0.4.6`, `0.4.5`, `0.4.4`, `0.4.3`, `0.4.2` and node versions `19`, `18`, `16`, `14`

**Comment by posva** [comment]
You also need to add pinia package: https://pinia.vuejs.org/ssr/nuxt.html#installation

**Comment by vin-ni** [comment]
@posva I get the same error if pinia is also installed. Updated the git repo with the pinia package as well.

<img width="1093" alt="Screenshot 2023-01-20 at 12 40 48" src="https://user-images.githubusercontent.com/9806572/213687114-bb2fa9a1-c430-4679-9888-53cd1d4fd8ce.png">

**Comment by posva** [comment]
You can find an example project at https://github.com/piniajs/example-nuxt-3, it should help you set up 😀

**Comment by vin-ni** [comment]
I get the same bug in the example project:
<img width="1440" alt="Screenshot 2023-01-20 at 18 04 54" src="https://user-images.githubusercontent.com/9806572/213760440-0288c6c1-24f2-477a-a2f3-64b672f96b04.png">

I set up the project correctly and it also works on my Intel Mac. But on the M1 it just doesn't work. I think it's really a bug.

**Comment by vin-ni** [comment]
Why isn't this considered a bug?

**Comment by posva** [comment]
I also use an M1 and I cannot reproduce it so I think it's a configuration issue. That's why I moved your issue to the discussions at #1948 (also please don't open duplicates like that 😅).
Hopefully, someone would help you out with the problem you are facing 😃
Locking this thread to keep the discussion in one place.
