### ISSUE TITLE
destructured actions in options API computed throw warnings

### ISSUE THREAD

**Issue by jirizavadil** [posva/pinia#1949]
### Reproduction

https://codesandbox.io/p/sandbox/prod-bird-3kz767?file=%2Fsrc%2FApp.vue

### Steps to reproduce the bug

1. open codesandbox url
2. open browser console
3. observe warning in console

### Expected behavior

no warning

### Actual behavior

`[Vue warn]: Property "$id" was accessed during render but is not defined on instance.` thrown to browser console

### Additional information

can be fixed by changing
https://github.com/vuejs/pinia/blob/26b72f327dac9daa980fb018833804706eb7a962/packages/pinia/src/store.ts#L381
to 
`ret = action.apply(this && Object.hasOwn(this, '$id') && this.$id === $id ? this : store, args)`

**Comment by posva** [comment]
Thanks for the report but actions are not meant to be called from an object other than a store, that changes the context (`this`) creating the warning you see.

Mixing `setup()` and options API is also an antipattern and, as mentioned in vue docs, should be avoided.

You should either stick to `setup()` or use `mapActions()` in Options API

**Comment by jirizavadil** [comment]
Thank you @posva, but now i'm super confused.

I was following this from Pinia docs: "Note you can destructure actions directly from the store as they are bound to the store itself too:" mentioned here at bottom: https://pinia.vuejs.org/core-concepts/#using-the-store

What is the use of that, then? Only to call actions directly from within `<template></template>`?

Also, i understood the entire purpose of `setup()` is exactly to use it together with old Options API code, as per case 2) in https://vuejs.org/api/composition-api-setup.html - couldn't find any mention in Vue docs of this being an antipattern.

Thanks for any clarification on this!

**Comment by posva** [comment]
You can call the action directly `action()` but if you put it into an object and call it from the object: `object.action()`, the context of the action changes (this is js behavior). Pinia uses this to enable some dev only features and checks the `id` of the store. The warning you see **makes no harm**, so you can safely ignore it.

> Also, i understood the entire purpose of setup() is exactly to use it together with old Options API code

🙅‍♂️ This is something to avoid. It might work in many scenarios and it's certainly fine to have both while refactoring a component but there are some edge cases that you can find reported in vuejs/core
