### ISSUE TITLE
The requested module 'vue' does not provide an export named 'default'

### ISSUE THREAD

**Issue by stephenjason89** [posva/pinia#1953]
### Reproduction

https://github.com/nuxt/nuxt/issues/18544 

### Steps to reproduce the bug

This is what i added to my existing nuxt 3 project
![image](https://user-images.githubusercontent.com/3810177/214818918-321afb10-9598-41bc-83a9-9b4ef724b23b.png)

After installing @pinia/nuxt, running pnpm dev produces on nuxt 3 produces 
![image](https://user-images.githubusercontent.com/3810177/214818807-130e766b-3111-486f-bea0-5dace6bce262.png)

PS: Error only occures on PNPM (switching to YARN fixes the problem)

### Expected behavior

No errors

### Actual behavior

error

### Additional information

https://github.com/stephenjason89/nuxt-vuetify-graphql-pinia
just pnpm install then pnpm dev

**Comment by posva** [comment]
I updated the template at https://github.com/piniajs/example-nuxt-3 and everything works. I even tested with the auto import configs. Maybe this is related to the naming of the folder `client` in `client/stores` and Nuxt having special treatment of it?
If you manage to reproduce without extra dependencies like vuetify (like it was requested on the nuxt issue), I can take a look

**Comment by stephenjason89** [comment]
@posva Thank you for replying,
I updated my reproduction as well and have managed to find the culprit

PNPM causes the problem
switching to YARN fixes it.

Please let me know what to do to fix this with PNPM

Thank you

**Comment by stephenjason89** [comment]
@posva I have just tried cloning the project at https://github.com/piniajs/example-nuxt-3
and doing
pnpm install
pnpm dev 

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/3810177/214823153-e67092b0-cec1-4784-97c6-8234df22f949.png">
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/3810177/214823192-ae4831d3-2c10-4e2c-a03c-0d7144e2b436.png">


Please let me know if I can be of assistance.

Thank you

**Comment by stephenjason89** [comment]
please re-open the issue. Thank you

**Comment by posva** [comment]
In the project it fails because it requires a `.npmrc` file with:

```
shamefully-hoist=true
strict-peer-dependencies=false
```

I just tested and it works fine too

**Comment by stephenjason89** [comment]
Thank you @posva , i must have overlooked that on the example repo

On my reproduction repo i believe it already has a shamefully hoist =true

I'll try if adding 

strict-peer-dependencies=false

Will fix the problem

I'll get back to you in a while

Thank you

**Comment by stephenjason89** [comment]
Hello @posva , I think what happened to mine was an edge case scenario.
after adding strict-peer-dependencies=false
It was still failing with the same errors(your repro and my reproduction repo)

What fixed it was doing 
pnpm store prune
then removed node_modules again for safety measure 
then pnpm install


PS: pnpm store prune is a must
had removed and reinstalled node_modules folder several time but still had the error.


Thank you for your time to test this out with me.

**Comment by antlionguard** [comment]
i have same problem and the prune solutions doesnt work for me :////

**Comment by mrFANRA** [comment]
Some trouble =( Solutions doesnt work,

**Comment by AndreyYolkin** [comment]
> Some trouble =( Solutions doesnt work,


This happens in nuxt and I suppose this is because nitro running in node and taking pinia.prod.cjs.
Workaround for your project:

## Workaround

In `nuxt.config.ts`:
```ts
import { resolveSync } from 'mlly'

export default defineConfig({
  /* ... */
  alias: { 
    pinia: resolveSync('pinia')
  }
  /* ... */
})
```

~Maybe pinia.prod.mjs should also be added?~

UPD: removing pinia from build.transpile works as well and even better. I also should reconsider some addings into build.transpile

**Comment by mrFANRA** [comment]
Im remove pinia from 

```
 build:{
    transpile: []
  },
```

and restart browser

**Comment by gridsystem** [comment]
@posva This issue is still happening. I think when you install the Nuxt Pinia module, it still needs the latest Pinia to be installed as a dependency. In the [test repo you linked above](https://github.com/piniajs/example-nuxt-3), you're specifically installing Pinia as a top level dependency.

**Comment by AndreyYolkin** [comment]
> [@posva](https://github.com/posva) This issue is still happening. I think when you install the Nuxt Pinia module, it still needs the latest Pinia to be installed as a dependency. In the [test repo you linked above](https://github.com/piniajs/example-nuxt-3?rgh-link-date=2025-04-14T13%3A51%3A50.000Z), you're specifically installing Pinia as a top level dependency.

This is mentioned in docs: https://pinia.vuejs.org/ssr/nuxt.html#Installation

**Comment by posva** [comment]
Sometimes `nuxi` doesn't install the peerDeps but there is nothing I can do about that, as @AndreyYolkin said, there is a mention about this in docs.
