### ISSUE TITLE
unexpected token ... in low chrome

### ISSUE THREAD

**Issue by TristZz** [posva/pinia#1960]
### Reproduction

null

### Steps to reproduce the bug

in development  environment and use chrome 56，use pinia will report mistask (unexpected token ...)
but in production environment it is fine

### Expected behavior

If it wasn't used babel on pinia

### Actual behavior

Uncaught SyntaxError: Unexpected token ...
    at Object../node_modules/pinia/dist/pinia.mjs (chunk-vendors.js:3132)

### Additional information

when i use transpileDependencies: ['pinia'] in vue.config.js,chrome 56 not show the mistask

**Comment by posva** [comment]
Fixed at d2a4defc381ae8e023b45b05e4ac8588fe2add9e but note some dev tools code won’t work on very old versions or internet explorer
