### ISSUE TITLE
Pinia makes the whole app very slow

### ISSUE THREAD

**Issue by digi604** [posva/pinia#199]
So we have a very big and complicated order management app with 7 different stores and price recalculations on IE11 take up to 30s compared 200ms on iOS. When we removed pinia as a store and used Vue.observable() instead it went down to 30ms on IE11 and very fast on iOS

**Comment by posva** [comment]
This is partially related to the cost of using the composition api.

Without any code, any further analysis of the perf bottleneck, I cannot even give you a hint 😉
This is likely to also be related to the actual code you are writing

If you find more information about what’s causing the perf issues and can provide a boiled down reproduction, I can take a look
