### ISSUE TITLE
autoImports not working

### ISSUE THREAD

**Issue by Rednas83** [posva/pinia#1995]
### Reproduction

https://codesandbox.io/p/sandbox/nuxt-pinia-autoimports-imd5yf?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A17%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A17%7D%5D

### Steps to reproduce the bug

1 Open sandbox
2 Look in the terminal

### Expected behavior

https://pinia.vuejs.org/ssr/nuxt.html#auto-imports

### Actual behavior

nuxt.config is not accepting autoImports
![image](https://user-images.githubusercontent.com/25219229/218253777-f5b9fad4-6865-4c72-a8ca-d2b58d66faa0.png)
![image](https://user-images.githubusercontent.com/25219229/218253811-4d3761b3-be80-4734-a507-01968bbc3050.png)

**Comment by posva** [comment]
You seem to have extra dependencies that shouldn't be there. Refer to https://github.com/piniajs/example-nuxt-3 for a working example

**Comment by Rednas83** [comment]
Thanks. I got it working with the starter.

It's actually an issue with the documentation for https://pinia.vuejs.org/ssr/nuxt.html#auto-imports

**nuxt.config.js should be**
```
// nuxt.config.js
export default defineNuxtConfig({
  // ... other options
  modules:
    [
      '@pinia/nuxt'
    ],
  pinia:
  {
    autoImports: [
      // automatically imports `defineStore`
      'defineStore', // import { defineStore } from 'pinia'
      // automatically imports `defineStore` as `definePiniaStore`
      ['defineStore', 'definePiniaStore'], // import { defineStore as definePiniaStore } from 'pinia'
    ]
  }
})
```

**Comment by posva** [comment]
Can you open a PR to the docs? 👀
