### ISSUE TITLE
mapWritableState pollutes component definition

### ISSUE THREAD

**Issue by Demak** [posva/pinia#2014]
### Reproduction

https://github.com/Demak/pinia-bug

### Steps to reproduce the bug

Clone repository and open core directory in Visual Studio Code. Open src/App.vue file from explorer panel. Hover over "computed" property in component definition, tooltip should display that all properties from pinia's state are included in computed properties.

![image](https://user-images.githubusercontent.com/5584155/219974947-443dd46f-1d69-4c84-9b18-204ac03461f4.png)

Hover over "this.stuff" inside "created" hook, tooltip should display that this property is present in component and display its type as set in store, even though this property is not included in component.

![image](https://user-images.githubusercontent.com/5584155/219975081-711beade-2edd-41e4-aa4b-f911dbd0bfae.png)

Only properties which are provided to mapWritableState are actually added on runtime, problem seems to be exlusively with typescript type definitions.
I am using extensions TypeScript Vue Plugin (Volar) version 1.1.3 and Vue Language Features (Volar) version 1.1.3.
If mapWritableState is replaced with mapState, component definition appears to be correct.

![image](https://user-images.githubusercontent.com/5584155/219975327-f9403794-2f3d-4e63-9f34-e8361c04038d.png)

### Expected behavior

Only properties defined in second argument of mapWritableState appear in component definition type.

### Actual behavior

All properties from pinia state are extending component type definition and are considered present in editor.

**Comment by Demak** [comment]
Unfortunately recent fix seems to have lead to a new problem:

![image](https://user-images.githubusercontent.com/5584155/220213047-ffcd5942-cd63-4d0c-bfbb-98bc7477483a.png)

I am not sure what exactly is wrong now, VSCode doesn't give me much information about an error.

![image](https://user-images.githubusercontent.com/5584155/220213277-848eba67-75fa-4a98-bf53-68b00c80f343.png)

**Comment by posva** [comment]
fixed

**Comment by Demak** [comment]
Seems to be working as expected now, thank you.
