### ISSUE TITLE
Ability to access store context when using composable stores

### ISSUE THREAD

**Issue by Fl0r14n** [posva/pinia#2043]
### What problem is this solving

There is no way to access the plugins when defining stores using composable stores, though they are present when using the store

### Proposed solution

const pinia = createPinia().use(({ store }) => {
  store.router = markRaw(router)
})

const useMyStore = defineStore('MyStore', storeContext => {
  const {router} = storeContext
  console.log(router) 
  return {router}
})

**Comment by posva** [comment]
Duplicate of #1784
