### ISSUE TITLE
`$reset` cannot be overridden in plugins

### ISSUE THREAD

**Issue by its-lee** [posva/pinia#2052]
### Reproduction

https://github.com/its-lee/pinia--reset-issue

### Steps to reproduce the bug

After npm installing & npm run dev on the provided GitHub repository (https://github.com/its-lee/pinia--reset-issue)..

1. Click on the nonDollarAction button
2. Observe that in the console, that action invokation has led to the $onAction callback being run.
3. Click on the $reset button
4. Observe that in the console, the invokation of the $reset method *hasn't* led to the $onAction callback being run.

### Expected behavior

Both actions defined in defineStore and 'magic dollar' actions (notably $reset) should lead to the $onAction callback being invoked.

### Actual behavior

Only actions defined in defineStore appear to lead to the $onAction callback being invoked.

Any 'magic dollar' actions (notably $reset) do not lead to that occurring.

### Additional information

I encounted this issue when trying to write a plugin that followed this guide for adding new state (https://pinia.vuejs.org/core-concepts/plugins.html#adding-new-state). However, such state isn't reset by clients calling $reset.

The clear resolution was to add a $onAction callback in the plugin, that watched for when $reset would be called, and then led to the plugin resetting any state that it had added) - rather than doing something egregious like overwriting the generated $reset.

**Comment by its-lee** [comment]
If there's an existing alternative to detecting when $reset has been invoked rather than altering the behaviour of $onAction then that would be appreciated.

I can't see anything in the docs that would provide this and when using a subscription with $subscribe - $reset invokations just come through as an anonymous patch..

**Comment by posva** [comment]
It’s intended for $reset not to be called by onAction (unless you override it with an action)
In your case, it seems like overriding $reset is the most flexible way to also reset added state.
It’s worth noting that $reset is kept extremely simple, on purpose, for size reasons. That’s why it must be implemented by the user in setup stores.
Is there any technical reason that prevents you from overriding $reset?

**Comment by its-lee** [comment]
Hi - thanks for replying so promptly!

I was looking at the implementation of $reset earlier and I'd agree with your thoughts. In the scenario I have, I'd agree, I could implement it by defining a $reset that calls the original store.$reset and then resets the state added by the plugin.

The only issue I really have is that this is the expected pattern for 'extending' $reset and it's not documented that this pattern is expected and will continue to be supported by pinia if we go ahead with it. I could also see no unit tests in storePlugins.spec.ts or anywhere else cover this scenario -- so future updates to pinia could unexpectedly lose this feature? But this could just be paranoia!

Thanks again!

**Comment by its-lee** [comment]
Happy to raise a PR to update to docs and unit tests for this scenario if there's no reason not to?

**Comment by its-lee** [comment]
> It’s intended for $reset not to be called by onAction (unless you override it with an action) In your case, it seems like overriding $reset is the most flexible way to also reset added state. It’s worth noting that $reset is kept extremely simple, on purpose, for size reasons. That’s why it must be implemented by the user in setup stores. Is there any technical reason that prevents you from overriding $reset?

Specifically this:

> Is there any technical reason that prevents you from overriding $reset?

Yes, there's a few issues.

As you've outlined above - I've attempted to 'override' $reset in order to also reset any state that the plugin introduces - e.g. when returning from the plugin:
```js
  originalReset = store.$reset.bind(store);
  return {
    $reset: () => {
      // Reset any state already added by the original store definition & other plugins that have redefined $reset to reset their state too.
      originalReset();  // We can't just call store.$reset() here as that'd just recurse forever!
      // Reset any state added by *this* plugin.
      store.pluginState.value = /*initial value*/;
    }
```

However, there's a few issues preventing this from working:

1. In the pinia source code, plugins are added in `createSetupStore`, which is before the point that $reset is added to the store - so the approach above won't work as `originalReset === undefined`. 
2. Even if a plugin wanted to override the `$reset` method by returning it, `$reset` is written to after the call to `createSetupStore` - which means that any $reset method returned from the plugin is lost - see this code in `createOptionsStore`:

```js
  store = createSetupStore(id, setup, options, pinia, hot, true)

  store.$reset = function $reset() {
    const newState = state ? state() : {}
    // we use a patch to group all changes into one single subscription
    this.$patch(($state) => {
      assign($state, newState)
    })
  }
```

3. One argument would be to not call the original `$reset` anyway and instead reset the state using a copy of the code used to define $reset in pinia itself. However - this would break the case when multiple plugins introduce state that would want to be resettable. I.e. the following wouldn't play with other plugins nicely:

```js
  return {
    $reset: () => {
      // Copy the code from pinia's $reset to reset store defined in the original store definition:
      const newState = state ? state() : {}
      // we use a patch to group all changes into one single subscription
      this.$patch(($state) => {
        assign($state, newState)
      })

      // We then reset any state added by *this* plugin.
      store.pluginState.value = /*initial value*/;

      // But if another plugin is added, which also adds it's own state which it would want to be reset by $reset - then either:
      //   - this definition of $reset wouldn't reset *that* plugin's state!
      //   - that plugin would add a copy of this code, but then the resetting of *this* plugin's state would be missed!
    }
```

The pattern above (effectively calling store.$reset() at the start of the new $reset definition) seems the most natural (with analogy to class based languages calling the base class constructor at the start of a derived constructor). But issues #1 & #2 above break it.

One approach that could allow correct overriding of $reset is if pinia detects that it's creating a store from the options syntax in `createSetupStore` (i.e. `isOptionsStore` === true) so $reset would be generated, then to do so before adding plugins, rather than after. Then plugins adding state could follow the above pattern quoted in code to 'extend' $reset?

This looks like it could be done by changing this code in `createSetupStore` from:

```js
  const $reset = __DEV__
    ? () => {
        throw new Error(
          `🍍: Store "${$id}" is built using the setup syntax and does not implement $reset().`
        )
      }
    : noop
```

to

```js
  const $reset = isOptionsStore ? 
    function $reset() {
        const newState = state ? state() : {}
        // we use a patch to group all changes into one single subscription
        this.$patch(($state) => {
          assign($state, newState)
        })
      }
    : __DEV__
      ? () => {
          throw new Error(
            `🍍: Store "${$id}" is built using the setup syntax and does not implement $reset().`
          )
        }
      : noop
```

And then removing the assignment to store.$reset in `createOptionsStore` (+ adding unit tests).

But certainly open to other ideas rather than a pinia change, but otherwise I don't think you can 'override' `$reset` (at least in a way that would avoid not resetting state potentially introduced by other plugins).
