### ISSUE TITLE
DevTools: Undefined value for `oldValue` in mutation event using Setup Stores

### ISSUE THREAD

**Issue by lombervid** [posva/pinia#2061]
### Reproduction

https://codesandbox.io/p/sandbox/cocky-butterfly-51pk2y?file=%2Fsrc%2Fstores%2Fcounter.js

### Steps to reproduce the bug

1. Click  counter button
2. Check the `mutation` event on the Timeline tab in DevTools

### Expected behavior

`oldValue` shows the previous value.

### Actual behavior

`oldValue` shows an `undefined` value.

### Additional information

Hello.

When I try using `Setup Stores`, the field `oldValue` is shown as `undefined` in the mutation event. But if I use `Option Stores` it shows the value correctly.

I have a code like this:
`App.vue`
```htm
<script setup>
import { useCounterStore } from "./stores/counter";

const counter = useCounterStore();
</script>

<template>
  <div class="card">
    <button type="button" @click="counter.increment()">
      count is {{ counter.count }}
    </button>
  </div>
</template>
```

`Setup Stores: stores/counter.js`
```js
import { defineStore } from "pinia";
import { ref } from "vue";

export const useCounterStore = defineStore("counter", () => {
  const count = ref(0);

  function increment() {
    if (count.value < 10) {
      count.value++;
    }
  }

  return { count, increment };
});
```
![Setup Store](https://i.imgur.com/fvks6nl.png)

`Option Stores: stores/counter.js`
```js
import { defineStore } from "pinia";

export const useCounterStore = defineStore("counter", {
  state: () => ({
    count: 0,
  }),
  actions: {
    increment() {
      if (this.count < 10) {
        this.count++;
      }
    },
  },
});
```

![Options Store](https://i.imgur.com/9HDRpgA.png)

Regards!

**Comment by sandexplus** [comment]
hi. any news? i have same problem with my Vue 3 project. Tried 2.0.32 - 2.0.34
