### ISSUE TITLE
missing pinia tab and warn issue upon including pinia project composition API

### ISSUE THREAD

**Issue by RyaiStudio** [posva/pinia#2064]
### Reproduction

https://github.com/RyaiStudio/bug-report-pinia-devtool

### Steps to reproduce the bug

```javascript
// vue-init.js
import { createApp } from 'vue'
const app = createApp(AppContainer)
// additional settings here
export default app
```
```javascript
// entry.js
import app from './vue-init'
import router from '@/router/index' 
import { createPinia } from 'pinia'

const pinia = createPinia()

app.use(router)
app.use(pinia)

app.mount('#app')
// I also use app.use(createPinia()).mount('#app') - still devtool pinia not showing
```
```vue
<script setup>
import { cashierStore } from '@/stores/pinia/cashier'
const $cashier = cashierStore() // this create the warning
console.log('$cashier', $cashier)
</script>
<template>
  <div class="gcash-container">
    <router-view ></router-view>
  </div>
</template>
```

### Expected behavior

after setting up open devtool and this should be what I'm expecting
<img width="1108" alt="Screenshot 2023-03-09 at 2 45 09 PM" src="https://user-images.githubusercontent.com/16729019/223942849-72b8a429-53c6-4aec-9a88-220a9e95c600.png">

### Actual behavior

what I see on my development devtool
<img width="1421" alt="Screenshot 2023-03-09 at 2 35 13 PM" src="https://user-images.githubusercontent.com/16729019/223942917-8379c0b2-bb95-44f7-ad9f-0f3b20e37ae9.png">

### Additional information

```
System:
  OS: macOS 13.0
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 199.80 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 19.0.0 - ~/.nvm/versions/node/v19.0.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v19.0.0/bin/yarn
  npm: 9.4.2 - ~/.nvm/versions/node/v19.0.0/bin/npm
Browsers:
  Chrome: 111.0.5563.64
  Firefox: 110.0.1
  Safari: 16.1
  Safari Technology Preview: 16.4
npmPackages:
  vue: ^3.2.34 => 3.2.47
```

**Comment by posva** [comment]
I've seen this happen before but devtools code hasn't change in a long while. For those looking to fix this, the problem could come from the devtools-api package or some change needed here.

**Comment by RyaiStudio** [comment]
I figure something out after reset all my changes from scratch. the problem was on my package.json file script
previously my code was something like this
```json
 "script": {
     "dev": "cross-env NODE_ENV=test MOCK=true SPMLOG_ENABLE=false vite --config config/dev.config.js"
  }
```
and then after I create separate custom config settings without the node params I was confuse that the same script working on just fine on devtools. 
```json
"script": {
   "dev": "vite --config config/custom.config.js"
}
```
so after updating my command script and add `&&` bet node settings and Vite. build was working successful.
```json
 "script": {
     "dev": "cross-env NODE_ENV=test MOCK=true SPMLOG_ENABLE=false && vite --config config/dev.config.js"
  }
```
Sorry for the trouble guys big mistake on my side keeps me 1 night to figure this out thankyou for quick response
じゃあね
