### ISSUE TITLE
Cannot use generic values in defineStore with setup stores

### ISSUE THREAD

**Issue by Q16solver** [posva/pinia#2068]
### Reproduction

https://stackblitz.com/edit/github-wn9aqn-1ldb7t

### Steps to reproduce the bug

1. Run `npm i`
2. Go to `store/error.ts` to see the typescript error

### Expected behavior

Should have no typescript errors and be able to useStore normally after specifying generic with setup stores

### Actual behavior

Getting typescript error, maybe it is unable to unwrap types because of the generic

**Comment by posva** [comment]
This is indeed a limitation Vue refs due to unwrapping, note it has been mentioned in a couple issues before. Moving to a discussion
