### ISSUE TITLE
Vue3 Plugin import resolves to any in Nuxt 3

### ISSUE THREAD

**Issue by noook** [posva/pinia#2071]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-4b7cfk?file=app.vue

### Steps to reproduce the bug

Install `pinia` and `@nuxt/pinia`, run the dev server and let it generate the typings for the project.

Go to `.nuxt/types/plugins.d.ts`

See the following block:

```ts
type NuxtAppInjections = 
  // Here
  InjectionType<typeof import("../../node_modules/@pinia/nuxt/dist/runtime/plugin.vue3").default> &
  InjectionType<typeof import("../components.plugin").default> &
  InjectionType<typeof import("../../node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin").default> &
  InjectionType<typeof import("../../node_modules/nuxt/dist/app/plugins/router").default>
```

Visit the `../../node_modules/@pinia/nuxt/dist/runtime/plugin.vue3` file:

```ts
declare const _default: any;
export default _default;
```

```ts
// In a vue file
const app = useNuxtApp()
app.$pinia // any
```

### Expected behavior

The property `$pinia` should be visible in the returned object of `useNuxtApp()`

```ts
// In a vue file
const app = useNuxtApp()
app.$pinia // Should be Pinia
```

### Actual behavior

The vue 3 plugin type definitions are outputted as any

**Comment by posva** [comment]
I'm not sure if this is a misusage of the Nuxt module in Pinia, a regression in Nuxt, or something else. Feel free to pick it up and propose a Pull Request!

**Comment by noook** [comment]
I'm not very aware of how the modules work, but do you think it has something to do with the way the package is built ?
Given the output I gave in the initial message
```ts
declare const _default: any;
export default _default;
```

**Comment by danielroe** [comment]
Yes, this seems like an issue with the module builder to me.

**Comment by posva** [comment]
It needs to be updated here. I think it’s still using siroc

**Comment by danielroe** [comment]
Happy to pick this up.

**Comment by posva** [comment]
Feel free!

**Comment by dargmuesli** [comment]
Since `any`s are now `unknown`s in Nuxt 3.3, linting fails when accessing Nuxt app's `$pinia`: https://stackblitz.com/edit/github-acwmkj?file=app.vue (run `npm run lint`)

I see `color-mode` has [runtime type definition](https://github.com/nuxt-modules/color-mode/blob/master/src/runtime/types.ts), but `pinia` [has not](https://github.com/vuejs/pinia/tree/v2/packages/nuxt/src/runtime). Would it fix the issue if those types were added? Or is this issue different and creation of a separate issue would be good?
