### ISSUE TITLE
pixel.thesemetrics.org flagged as malware on pinia.vuejs.org

### ISSUE THREAD

**Issue by lorand-horvath** [posva/pinia#2080]
### Reproduction

https://pinia.vuejs.org

### Steps to reproduce the bug

Avast is flagging the `pixel.thesemetrics.org` url access from https://pinia.vuejs.org as malware.
I have already reported this to https://github.com/znckco/thesemetrics/issues/10 without any response.
Copying the report here as well, for future reference:

> One of your subdomains https://pixel.thesemetrics.org which is seemingly accessed by https://unpkg.com/thesemetrics@latest is being flagged as malware by at least 5 antivirus software, please see virustotal report below:
https://www.virustotal.com/gui/url/8110f0a1c991a53e5bee13d804f2bcf972d7da2f6b0fc9fd44160d8b912d1480

![image](https://user-images.githubusercontent.com/72015221/226104844-17fccbf3-c9c7-4feb-be5e-de33b765b60b.png)

### Expected behavior

The blacklisted malware should be removed/fixed.

### Actual behavior

Avast and other antivirus software reports this as malware.

**Comment by Surfytom** [comment]
I'm getting the same really annoying to get around the docs

**Comment by posva** [comment]
Thanks for the headsup. See https://github.com/vuejs/router/issues/1757

**Comment by lorand-horvath** [comment]
This has been fixed, see https://github.com/znckco/thesemetrics/issues/10#issuecomment-1498686986
