### ISSUE TITLE
storeToRefs() by default

### ISSUE THREAD

**Issue by nerdcave** [posva/pinia#2082]
### What problem is this solving

I use `storeToRefs` far more often than not, and it would be nice if there was a way to make it the default behavior.

For example, I want to simplify the store usage from this:
```js
const { posts, loading, error } = storeToRefs(usePostStore())
const { fetchPosts } = usePostStore()
```
To this:
```js
// no storeToRefs call, get actions too
const { posts, loading, error, fetchPosts } = usePostStore()
```

### Proposed solution

```js
const usePostStore = defineStore("post", () => {}, { asRefs: true })
```
Some option when defining the store that will eliminate the need to call `storeToRefs`.

### Describe alternatives you've considered

Global pinia config option?

**Comment by avinean** [comment]
Don't use `storeToRefs`

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/pinia/issues/718

**Comment by posva** [comment]
You can use https://github.com/vuejs/pinia/issues/718#issuecomment-1121544045.

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
