### ISSUE TITLE
[Nuxt/useLocalStorage]: Using useLocalStoage as state and hydrate function, TS2322: Type 'RemovableRef<{}>' is not assignable to type "xxx" or lost reactivity.

### ISSUE THREAD

**Issue by AnzhiZhang** [posva/pinia#2086]
### Reproduction

https://stackblitz.com/edit/github-1bnqyz?file=stores/counter.ts

### Steps to reproduce the bug

1. There is a state named `n`, its type is `number | undefined`.
2. Use `hydrate` function to set value `useLocalStorage('storage', 0)` to it (**IMPORTANT**: not `skipHydrate`)
3. Then will be a typescript erro "Type 'RemovableRef<number>' is not assignable to type 'string| undefined'".

### Expected behavior

Recognize the correct type of it.

### Actual behavior

Type error.

## skipHydrate

This issue will only work on `hydrate` function instead of `skipHydrate`, I created another store named `example.ts`. It works fine as in the document https://pinia.vuejs.org/cookbook/composables.html#ssr.

In other words, only the options API will have the issue, the composition API is fine.

## Did I write a wrong type of the `state`?

No I'm not. Remove the type and use same init value in the state option, the issue still exists. (There is a commented line in the reproduction)

## Try to useLocalStorage().value

The `useLocalStorage` returns a Ref, so assign it's `value` property to the state could work (also a commented line).

But the reactivity will be lost. Launch the reproduction and open a new tab of it, use F12 to view and edit the Local Storages, and try to change the Local Storages or the input element, you will see the reactivity by `useLocalStorage`. This reactivity will not be lost when using `useLocalStorage().value` to avoid this typescript error.

## An attempt to fin the reason

Since only `hydrate` has this problem, I noticed hydrate's first argument is `UnwrapRef<S>`, and this `S` is `StateTree`.

https://github.com/vuejs/pinia/blob/efe11b1fdccf8b4f54b81a4eff4b0b54c58ee86c/packages/pinia/src/types.ts#L619-L680

**Comment by posva** [comment]
This is what you need to make it work:

```ts
import { useLocalStorage } from '@vueuse/core';

export const useCounter = defineStore('counter', {
  state: () => ({
    n: useLocalStorage('storage', "test"),
  }),
  hydrate(state) {
    // @ts-expect-error: ref
    state.n = useLocalStorage('storage', 'test');
  },
});
```

The type difference is necessary because of a limitation of TypeScript and there is already an open issue on Vue core
