### ISSUE TITLE
remove skipped properties from serialized state

### ISSUE THREAD

**Issue by sinisterstumble** [posva/pinia#2102]
### What problem is this solving

Pinia has the ability to skip the hydration of certain properties with `skipHydrate()`. However, there is currently no way to remove skipped properties from the serialized state.

### Proposed solution

Pinia could provide a function `filterSkipped` that would go over `pinia.state.value` and remove the skipped properties.

**Comment by posva** [comment]
What are you really trying to do? You shouldn't need to remove any properties from the serialized state. If that's the case, they probably shouldn't be in the state in the first place
