### ISSUE TITLE
@testing/pinia unable to mock getters used within setup-style stores

### ISSUE THREAD

**Issue by fgarit-te** [posva/pinia#2109]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-aex5rl?file=src/stores/__tests__/useCounterSetup.spec.js

### Steps to reproduce the bug

Go to the console and run `npm test`.

### Expected behavior

All tests pass.

### Actual behavior

The test for `useCounterSetup` fails because the getter override isn't taken into consideration.

### Additional information

In https://github.com/vuejs/pinia/issues/945 the ability to override a getter when testing was gifted to us (it's referenced in the doc [here](https://pinia.vuejs.org/cookbook/testing.html#mocking-getters)).

It works wonderfully well when creating a Pinia store options style (this is such a useful feature for testing!).
Unfortunately it doesn't appear to work with the setup style stores.

It's too bad because setup style stores are a big improvement over options style in my opinion. But losing the ability to override a getter is a bummer.

**Comment by posva** [comment]
This is indeed a problem but unfortunately it cannot be fixed just with runtime code as the computed property accessed within a setup store cannot be overwritten from the outside. **Only the getter value used from the outside can be changed**.

In order to fix this, it would require to override the `computed()` function to return a custom computed property that can be overriden. This is only doable at buildtime by modifying the code. It's possible in Vite environment but not others, so I think we will have to mark this as just not possible. It should also be added to the docs.

**Comment by fgarit-te** [comment]
> In order to fix this, it would require to override the `computed()` function to return a custom computed property that can be overriden. This is only doable at buildtime by modifying the code. It's possible in Vite environment but not others, so I think we will have to mark this as just not possible. It should also be added to the docs.

Thanks for looking into this. I think people using Vite would find it extremely useful. I'm getting more and more of the Vue/Pinia community will migrate to it.

**Comment by posva** [comment]
I did some hacking and [it's easier than I thought](https://sfc.vuejs.org/#eNp1U8mO00AQ/ZWiL3YgsYdrlIxASAgOcBgJcWkJOXbZ8dCbegkCx/9OdXsJA0ykWF3Le7UP7K0xxSUg27ODq21vPDj0wdxz1UujrYcBLLZbqLU0wWOzBW/7rkP7gC2M0FotISOCjCuuaq2cB+k6OEZUnn1AITR81VY0L7LN4mDIvPDl+QaO9xFTXCoRsPD6izFo31UO8w1BFlD1Lyj7+HkPGbwCKiFik7dAD3VVn7F5T1IbVO17reCMPwk0cAXEopwWWAjd5YYwQPhviYBCfKr8ubA6qCZ/fXcHL2dFpRotUz6En9nhej0SFNsWa1+0FA2gLKG66L6BYJrKo5vYVxcKMKW+RJwwDZ5C7GmUbu1NyY1RF/9rJRad15aaM1UD0LeQLzklJfdR/TTsrSXR9qTkPxzzVGD8/ZVGVKVU6HMop02hHSHBozSCSiUJ4NArGhBcdlI3KI6c0Vw5S6ZkjnsVqYaBlmAc4RpfFb2StZzM6X0K3lOxb2rR19+JKM1vpgJ4SPPofyGsXTyUE+R5irVxN5pJ81+SQ7lWxrZsOoadrEzx6LSic0nN57PBcbZfxsEZnUOUKWnvjduXpWvreGSPrtC2K+lV2KB8L7FAJ3cnq384tETM2dzikY2/AWq+MSg=) in plain Vue.

It might be a bit more difficult in pinia but not impossible like I initially thought!

**Comment by fgarit-te** [comment]
Can confirm that this has been addressed in `"@pinia/testing": "0.0.16`
https://stackblitz.com/edit/vitejs-vite-aex5rl?file=package.json

Thanks a lot!

**Comment by SchDen** [comment]
Guys, could you please explain to me why I still get the error with this test?

Docs: https://pinia.vuejs.org/cookbook/testing.html#mocking-getters

Packages:
```
    "@pinia/testing": "^0.1.0",
    "pinia": "^2.0.36",
    "jest": "27.5.1",
```

```
import { defineStore } from 'pinia';
import { createTestingPinia } from '@pinia/testing';

const useCounterStore = defineStore('counter', {
    state: () => ({ n: 1 }),
    getters: {
        double: state => state.n * 2,
    },
});

describe('Pinia', () => {
    it('should override getter', () => {
        const pinia = createTestingPinia();
        const counter = useCounterStore(pinia);

        counter.double = 3;

        expect(counter.double).toBe(3);
    });

});
```
![image](https://github.com/vuejs/pinia/assets/1484977/45c911b7-1b73-4dd9-a674-cc3422f1e1e7)

**Comment by SchDen** [comment]
Writing into getter works well with `vitest`, but the result doesn't match expectations. I may have used it wrong.

![image](https://github.com/vuejs/pinia/assets/1484977/e16b811a-a8e1-46fa-9a48-d02448f48d72)

**Comment by mediafreakch** [comment]
This doesn't seem to work with computed getters: 

```
getters: {
  getFiltered:
      (state) =>
      (ids: string[]): string[] => {}
}
```

throws in Jest when spyed on with `jest.spyOn(store, 'getFiltered')`:

```
'set' on proxy: trap returned falsish for property 'getFiltered'
```
