### ISSUE TITLE
object not persist

### ISSUE THREAD

**Issue by agracia-foticos** [posva/pinia#2110]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-b3gnpr

### Steps to reproduce the bug

In theory, the storage loads the object only once and the second time, since it's already loaded, it doesn't load it again.

However, in both cases the application variable is empty, when it should already be full.

### Expected behavior

"application empty we assign" should be painted only once

### Actual behavior

"application empty we assign" should be painted many times

**Comment by posva** [comment]
This is because Nuxt executes the action on the server and on the client
