### ISSUE TITLE
Cannot Press any Button on Pinea Website

### ISSUE THREAD

**Issue by SamuelSilva2310** [posva/pinia#2111]
### Reproduction

Click on any button on Main Website Page

### Steps to reproduce the bug

![image](https://user-images.githubusercontent.com/67950280/228849306-4e42708f-90f7-417a-97e8-8e78f66020a0.png)

When Pressing any Button on Main Page, nothing happens. 

An error is visible on the console.

### Expected behavior

Execute button functionality.

### Actual behavior
When Pressing any Button on Main Page, nothing happens. 

### Additional information

Pressing on Links seems to work just fine

_No response_

**Comment by posva** [comment]
See https://github.com/vuejs/router/issues/1757
