### ISSUE TITLE
Pinia does not maintain types when using generics

### ISSUE THREAD

**Issue by rizen** [posva/pinia#2122]
### Reproduction

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGUbSpwC+c6UEIcA5GNsAIbUDcAUKJLHDAJ5hFIAqlgDuUBmABKGEmQpVqANwCuqaq1a9+cAIJYeAFQYAjADZEAvIlZxbcAM4xl6dAHVUAEQhYYAYQZQqDrGEMowAFxw0gDG0MgAPAz6ADRwSTwAfMk2dpiopsj2kTFx8Y5Q2ADmqelZrMQaWkSC9qhQALIQaKZwVgg5to7Obp7efgFBIWHFqLFQCek1+nV2ZMD5hZH9q6vAyJHlVdk7dsqtUFgMIKgHMBVY1QMk2Q1NugAKAJIA0qg8nd1etZVkMXO4vD5-IFgqEIlFZqVFmllsdcusCkVgSc4HtbvdHti4GAKooGDBUL8eHijk8Gg1NHwiO0GABrVAA-LMsDxAxwVAAD3JWEK8LmCUOD1SekMJnMGQyQO2dgA2t8cVg4GyeBB0HADABdLZPEH5WZwgyq-XK6h5DHUfVsVbENjOxqMuAc0xcoHMtmernxJW2FptSIhjpdfKOuw6L6UyKxn5-T0ujJsVixLCOOAgVl4AiBIE8vmC1DC+yav46j2Rr0SDIACgA9AAqIkBK4VltNgCUvQV-SemezlTLbTJlhQGGw+cIDeo9koqD21FSQZ2jgnkQbPaNhNWxIgYHsAH5Iu8AjBGKZ4v6JMqDdbWuZojB7XVjXZSBYFQ314TD2PLZiFRE5iB7UCdgYV9gG8TF-2xVoYHwCcG0CexlFMOEL1ga9b1rLkHytBdTVfd8+wQ-duAAC2AewADpAIrKx0Mw+AGArYQxAkaR0HiHCrwYG87zAIin1It99XlZg4CbJs4HiABaRSaLonEKxgaiiEPMxUBAT8wMgwlR2QpwXAAMXkHQ6B3LEqNWTS6PopCUPJP9ZLbexqIgEQqhLK4wHMOAzgYUc4G7EgewMnYGkJWKvx7dNVjktJTB6TSiFBXVgCncxyWQMhoFUisBQC8wNFWQInAuOBRxwcQ3MS+ogA

### Steps to reproduce the bug

If you create a generic type map and use that to type state in your Pinia store then Pinia ends up adding `UnwrapRef` to the type. 

Using the reproduction, if you replace the generic `T` with `'User'` so that it's no longer generic, then the `UnwrapRef` is not added to the type.

### Expected behavior

The state should maintain the type I set, not add its own wrapper.

### Actual behavior

If I type a state property to something like:

```ts
Partial<ModelMap[T]['select']>
```

Then Pinia actually sets the state to:

```ts
UnwrapRef<Partial<ModelMap[T]['select']>>
```

And then Typescript complains that the types are incompatible.

**Comment by posva** [comment]
This is a Vue thing and has been reported already.
Make sure to search existing issues before opening one 🙂

**Comment by rizen** [comment]
I did search the repo here. I didn't think to search Vue's repo for this. 

Is this the related issue? https://github.com/vuejs/core/issues/7278

Or is there something else?
