### ISSUE TITLE
Use V-model can add and modify a new state property

### ISSUE THREAD

**Issue by ParkerFiend** [posva/pinia#2145]
### Reproduction

https://stackblitz.com/edit/github-i1nwig-dydpjt

### Steps to reproduce the bug

1. change the input3
2. setupStore got new property

### Expected behavior

The setupStore property should not be add.

### Actual behavior

New Property 'b' add to store by input3 v-model.

### Additional information

In the doc

> Note you cannot add a new state property if you don't define it in state(), it must contain the initial state.

If the component can add and modify the properties of the store at any time, 
will the type definition for state lose its effectiveness？

And still got question in similar discussions: [Doubts about using v-model](https://github.com/vuejs/pinia/discussions/2144)

**Comment by posva** [comment]
This is how JavaScript works: objects are passed by reference, not by value.
You are not adding state this way, it won't work in other scenarios like SSR. There are other examples in docs.

**Comment by ParkerFiend** [comment]
Thanks for your reply.

> You are not adding state this way, it won't work in other scenarios like SSR.

If there is no SSR scenario in the project, any solution to avoid the above situation？
Compare to Vuex, v-model got the same result or not？
Looking forward to resolving doubts.
