### ISSUE TITLE
Nuxt 2 with Pinia and @nuxt/pinia not working

### ISSUE THREAD

**Issue by buglavecz** [posva/pinia#2150]
### Reproduction

https://stackblitz.com/github/piniajs/example-nuxt-2

### Steps to reproduce the bug

Hello,

I want to try Pinia with Nuxt 2. I found this: https://github.com/piniajs/example-nuxt-2 official example. But this is not working.
I got this error:
![image](https://user-images.githubusercontent.com/43108336/233041531-f7d41ae4-5da5-4376-ae12-5bc2c93c26ae.png)

### Expected behavior

That it is works.

### Actual behavior

Not working.

### Additional information

Thank you for helping.

**Comment by posva** [comment]
Make sure to install with the correct package manager to ensure the fixed versions are used. I tested locally and everything is working.

**Comment by buglavecz** [comment]
@posva yarn is not correct? I don't understand. Here: https://stackblitz.com/github/piniajs/example-nuxt-2 use yarn.

**Comment by buglavecz** [comment]
Can you update this stackblitz: https://stackblitz.com/github/piniajs/example-nuxt-2 with the working version? Thank you.

**Comment by buglavecz** [comment]
https://github.com/piniajs/example-nuxt-2/issues/42#issuecomment-1519066370

@posva It doesn't work for anyone else either. 
Pls. help. 

Thank you.
