### ISSUE TITLE
Pinia store breaks in nuxt3 composables since  v 3.4.0

### ISSUE THREAD

**Issue by jpengelbrecht** [posva/pinia#2154]
### Reproduction

https://stackblitz.com/edit/broken-pinia-store-in-composeables?file=app.vue,nuxt.config.ts

### Steps to reproduce the bug

1. import pinia store into nuxt composable on a nuxt version. 3.4.0 or later. 
2. receive error `getActivePinia was called with no active Pinia. `

### Expected behavior

expected to still work in composables, as it did on previous versions 

### Actual behavior

pinia store imports dont work in composables anymore

**Comment by posva** [comment]
This is explained in docs: https://pinia.vuejs.org/core-concepts/outside-component-usage.html

Move the useStore within the composable. Also it's `modules` not `buildModules` 😉
