### ISSUE TITLE
State leaking between concurrent sessions when useStore comes after an await on SSR 

### ISSUE THREAD

**Issue by iPrytz** [posva/pinia#2157]
### Reproduction

https://github.com/iPrytz/vue3-pinia-ssr-example

### Steps to reproduce the bug

1. Create a SSR Vue application
2. Create two stores, exampe `userStore` and `myDataStore`
- initialize userStore with some user data from session, example a sessionId
- in myDataStore get (and log) session data from userStore `useUserStore().sessionId`
- then do a fetch with await
- then get (and log) data from userStore `useUserStore().sessionId` again
3. When tested (for example with autocannon) with multiple different sessions fetching the SSR app at the same time, data will leak between the sessions. SessionId will be different the second time from useStore. 
4. It is solved if `const store = useUserStore()` and `store.sessionId` is used both before and after await, but in more complex cases it can still me a missmatch. 
For example, in our store, we fetch specific user data connected to the sessionId, but before we do that we need to fetch and await the users profile settings, then we can fetch the specific user data. From our store we call the API and in the API-handler we then add the sessionId/token from userStore, and now we have a missmatch because we do `useUserStore()` after the `await user profile` while we have multipe requests comming in to our node server. So the sessionId/token added to the request is now from another user and we get mixed up data.

I added a repo to reproduce the problem, instructions how to test this is found in the _README_

### Expected behavior

Data from useStore should be consistent in one session/request

### Actual behavior

Store data gets mixed up between the sessions/requests and the documentation is not clear about how to solve this issue.
It happens after an await 

### Additional information

I do understand that it might not be a bug specific to pinia, but i can't remember having this issue with vuex.
It should at least be well documented how to structure the stores and await calls to avoid this happening sonce it is a huge risk of data leaks. We have had this problem in multiple projects and we cant really find any good enough documentation on the issue.
And would also love to get some explanation on what is actually hapening and what is causing this behavior. 

Thank you to everyone working on this project, you're awesome!! 💯 🙌

**Comment by posva** [comment]
You should indeed call useStore before the await or pass the pinia instance to avoid sharing the state across request. This is already documented. Improvements to docs are welcome though 🙌

**Comment by iPrytz** [comment]
I don't agree, at least the documentation is not clear enough in the examples.  
I can definetly try to add some more examples to the domentation, but do you have time to have a look at the repo and give some feedback on how to best solve it in this scenario when a store is using another store after an await? How do i pass the pinia instance all the way to the api in the best way? Thank you for you time!
