### ISSUE TITLE
Change `acceptHMRUpdate` weird code (`if (!(process.env.NODE_ENV !== 'production'))`)

### ISSUE THREAD

**Issue by 0x00A1FA** [posva/pinia#2162]
### What problem is this solving

Helping developers understand the code better.

### Proposed solution

Use `if (if (process.env.NODE_ENV === 'production'))` instead.

### Describe alternatives you've considered

Off-topic: By the way, your issue form retained one element from what I presume is the old issue template from the Vue Router: `Before creating a feature request make sure that: This hasn't been [requested before](https://github.com/vuejs/router/issues).` (check out the `requested before` link).

**Comment by posva** [comment]
Thanks, I fixed the link! The code you are looking at is generated. The source code is just `if (!__DEV__)`
