### ISSUE TITLE
Issue with computed not being reactive

### ISSUE THREAD

**Issue by Ericlm** [posva/pinia#2179]
### Reproduction

https://stackblitz.com/edit/github-fxtqrt?file=src/App.vue

### Steps to reproduce the bug

Click on the `increment` button. You should see "counter" increment, and "reactive double count" increment too, but the "no reactive double count" should stay at 0.

Inspect the code by going to `App.vue`. Inside the `<script>`, you'll see two "doubleCount" declarations, one reactive and one breaking reactivity. 

### Expected behavior

According to [the documentation](https://pinia.vuejs.org/core-concepts/#using-the-store), both declarations should be equivalent, and declaring `store.doubleCount` instead of wrapping it into a computed should work. 

<img width="705" alt="Capture d’écran 2023-05-02 à 16 01 14" src="https://user-images.githubusercontent.com/19361503/235691702-18987189-3d14-4493-a7ad-0994f2ece4d1.png">

### Actual behavior

If the `doubleCount` is not wrapped into a computed, the reactivity won't work, and the double counter stays at 0. Wrapping it seems to be mandatory, as opposed to what is written in the documentation.

**Comment by cannap** [comment]
you can just use 

{{counter.doubleCount}}

**Comment by posva** [comment]
Your repro shows exactly what the documentation says 🙃

**Comment by Ericlm** [comment]
Oh yes 🤦 I understood this as "you can assign `store.doubleCount` directly". Maybe could this be rephrased ? It took me a while to understand what it meant. 😅

**Comment by posva** [comment]
Thanks for the suggestion but I believe the wording is just fine

**Comment by amexboy** [comment]
This is really confusing. I just started using pina and found out the hard way that the following also don't work 

```
const store = ....

const q = store.q

const other = computed(() => q) 
```
This doesn't work, as store.q needs to be accessed in the computed block. Took me a whille to get why it doesn't work. (I'm guessing because the subscription will be made on the wrong place)

**Comment by amexboy** [comment]
I however don't know why the following is not firing 

```
watch (store.q, (val) => console.log(val))
```
while the one below works. 

```
const p = computed(() => store.q)

watch(p, (val) => console.log(val))

```

**Comment by posva** [comment]
FYI it's all covered in Vue.js docs. Most of it in https://vuejs.org/guide/essentials/reactivity-fundamentals.html#limitations-of-reactive
