### ISSUE TITLE
pinia.iife.js without VueDemi ?

### ISSUE THREAD

**Issue by lefreet** [posva/pinia#2182]
### What problem is this solving

we have some global libs like : 

```html
    <!-- vue -->
    <script src="/libs/vue.global.js" import="vue" export="Vue"></script>
    <!-- pinia -->
    <script src="/libs/pinia.iife.js" import="pinia" export="Pinia"></script>
    <!-- vue-router -->
    <script src="/libs/vue-router.global.js" import="vue-router" export="VueRouter"></script>

    <script src="/resource/libs/system.js"></script>
    <script>
    define('vue', () => Vue)
    define('pinia', () => Pinia)
    define('vue-router', () => VueRouter)
    </script>
```

1. why `pinia's`  global file name is `pinia.iife.js` but `pinia.global.js`  ?  aha
2. if as a global file , can the `pinia.iife.js` build the `VueDemi` inner, so that we can use it without  others deps. 

> our project shoud shared pinia constuctor in the same memory，with the multi libs build， so we externals some global lib ahead of time，such as the attr `import / export` in scripts tag.

### Proposed solution

1. output the `pinia.global.js`.  （not matter）
2.  build the `VueDemi` inner,  or output the file only support vue3

### Describe alternatives you've considered

nothing.  some issue #1051  ， but we do not want to load a extra file like `vue-demi.js`

**Comment by posva** [comment]
1. Historic: not changed to avoid breaking changes or to increase the package size with yet an extra file
2. That won't work if you use another library that requires VueDemi and they do the same

What would be nice is to add a cookbook entry about CDN usage for Vue 2 and Vue 3, I added it to the docs list issue and as always, PR welcome!

**Comment by lefreet** [comment]
for the 2. , we has some others externals libs like：

https://cdn.jsdelivr.net/npm/vue-echarts@6.5.5/dist/index.umd.js
https://cdn.jsdelivr.net/npm/@vueuse/core@10.1.2/index.iife.js

builded the `VueDemi` inner. I can understand without it will bring little size（just a little）, but for global or iife used,  it to be a trouble, as `node_modules` use is easy.

**Comment by lefreet** [comment]
i will import the `vue-demi.iife.js` in pree script to resolve it first.  thx for your patience.
