### ISSUE TITLE
顶部导航栏错位了

### ISSUE THREAD

**Issue by noxussj2** [posva/pinia#2184]
### Reproduction

https://pinia.vuejs.org/zh/

### Steps to reproduce the bug

![a2fd7349f3d899811545bb3270058b1](https://user-images.githubusercontent.com/128458564/236366197-7ab37c99-5e74-4598-9d9d-a07b25ff6308.png)

### Expected behavior

应该是没有错位的

### Actual behavior

顶部导航栏错位了

**Comment by noxussj2** [comment]
是网站加载完一样东西之后才开始错位的。

**Comment by yixiaojiu** [comment]
It seems that the English docs have a similar problem.

**Comment by posva** [comment]
I can’t reproduce. It looks like the top banner is being blocked by a browser extension. Please don’t use extensions like Adblock on documentations, it’s possible to “trust” the site from the extension

**Comment by posva** [comment]
I actually think where this comes from. The changes should be applied during the day
