### ISSUE TITLE
Sticky header not working properly on Pinia.vuejs.org

### ISSUE THREAD

**Issue by vivekpal1** [posva/pinia#2185]
### What problem is this solving

The sticky header on [Pinia.vuejs.org](http://pinia.vuejs.org/) is not working as intended.
When scrolling down the page, the header should stick to the top of the viewport, but instead, it moves up and out of view, making it difficult to access the navigation links.

This issue is occurring on desktops.

Screenshots:

![Screenshot from 2023-05-05 12-50-00](https://user-images.githubusercontent.com/88021457/236399948-0adceb2f-d321-423c-afa7-1792202a70a8.png)
![Screenshot from 2023-05-05 12-50-07](https://user-images.githubusercontent.com/88021457/236399976-23880e69-3970-4961-a90a-f8a6008c81da.png)

### Proposed solution

- Adjust the properties of header
- Issue might be because of that 'Claim Offer' banner on the top.

**Comment by posva** [comment]
I think I found the origin of the problem. The fix should be applied and released soon (outside of this repo)
