### ISSUE TITLE
TS2551 error when calling an action from within a getter

### ISSUE THREAD

**Issue by Farnsi** [posva/pinia#2198]
### Reproduction

https://github.com/piniajs?q=example&type=source

### Steps to reproduce the bug

TS error 2551
```
Property 'callAnAction' does not exist on type '{ aStateVariable: boolean } & PiniaCustomStatePr...'. ts(2551)
```

I use vuetifys [v-switch](https://vuetifyjs.com/en/components/switches/), which uses a v-model that i map with `mapWritableState`

Some Template:

```js
...mapWritableState(myStore, ['aStateVariable', ...
```

To detect when the var changes, i use a getter and call an action

The Store:

```js
  state: () => ({
    aStateVariable: true
  }),
  getters: {
    myGetter(state) {
      if (state.aStateVariable) {
        state.callAnAction()
              ^^^^^^^^^^^^ TS(2551)
      }
    },
  },
  actions: {
    callAnAction() {
      console.log('i got called')
    }
  }

```

The code works, but i got the TS error

### Expected behavior

No error, or an explanation, that it is prohibited to call an action from a getter.

### Actual behavior

TS error

**Comment by posva** [comment]
This is intended. No side effects in getters
