### ISSUE TITLE
pinia@2.1.0在vue@3.2.47中报错

### ISSUE THREAD

**Issue by trry-hub** [posva/pinia#2215]
### Reproduction

https://github.com/trry-github/pinia-issues

### Steps to reproduce the bug

pnpm install 

pnpm run dev

Then it will report an error

![image](https://github.com/vuejs/pinia/assets/67309192/571a2ab6-2e26-4e3c-9943-1ed8228a033a)

### Expected behavior

It is expected to run normally in the dev environment

### Actual behavior

No matching export in "node_modules/.pnpm/vue-demi@0.14.4_vue@3.2.47/node_modules/vue-demi/lib/index.mjs" for import "hasInjectionContext"

    node_modules/.pnpm/pinia@2.1.0_typescript@5.0.2_vue@3.2.47/node_modules/pinia/dist/pinia.mjs:6:9:
      6 │ import { hasInjectionContext, inject, toRaw, watch, unref, markRaw, effectScope, ref, isVue2, is...

**Comment by posva** [comment]
As specified by peer deps, you need Vue 3.3

**Comment by trry-hub** [comment]
> As specified by peer deps, you need Vue 3.3

Thanks a lot, but how do I know the correct version mapping

**Comment by mhxnb13** [comment]
I also encountered it in 3.3.11

**Comment by mhxnb13** [comment]
I also encountered it on vue version 3.3.11, Vue-demi version 0.14.10
