### ISSUE TITLE
getcurrentInstance is not a function

### ISSUE THREAD

**Issue by lantianhaijiao** [posva/pinia#2217]
### Reproduction

error

### Steps to reproduce the bug

getcurrentInstance is not a function
![image](https://github.com/vuejs/pinia/assets/29088064/e210baed-006f-4f8d-b5a2-444a320de7bb)

### Expected behavior

Upgrade or downgrade to a stable version,Make getcurrentInstance available

### Actual behavior

getcurrentInstance is not a function

### Additional information

There is an error below vue-demi v0.14.5, please upgrade as soon as possible
https://github.com/vueuse/vue-demi/pull/232

**Comment by Archetipo95** [comment]
https://github.com/vueuse/vue-demi/issues/230

**Comment by posva** [comment]
The version will be bumped on the next release but note you can already update vue-demi in your project as it's just a dependency. Depending on your package manager npm update, etc
