### ISSUE TITLE
Could you give an example of how to access the Pinia stores under the node_module. 

### ISSUE THREAD

**Issue by mahanteshaCloudMPower** [posva/pinia#2220]
### Reproduction

access Store 

### Steps to reproduce the bug

How to get access pinia store  inside the node module

### Expected behavior

Am try to commit data to store but am not getting stores details in the node_module under 

this.viewStorage.commit( );

### Actual behavior

Am try to commit data to store but am not getting stores details in the node_module under 

this.viewStorage.commit( );

**Comment by posva** [comment]
Please check the documentation
