### ISSUE TITLE
Error in Nuxt 3.4.3 when upgrading Pinia to 2.1.3 (from 2.0.36) - Internal Server error

### ISSUE THREAD

**Issue by michaeljclegg** [posva/pinia#2230]
### Reproduction

No reproduction 

### Steps to reproduce the bug

After upgrading Pinia module in Nuxt 3.4.3 to Pinia version 2.1.3 (from version 2.0.36)
we get this error message :

The requested module 'vue-demi' does not provide an export named 'hasInjectionContext'            12:31:39 AM
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)

### Expected behavior

when running in app in dev mode (npm run dev) that application should open in browser 

### Actual behavior

Resulting in application does not open in browser.

### Additional information

When uninstalling Pinia and forcing back to version 3.0.36 problem is resolved.

**Comment by michaeljclegg** [comment]
see same problem
https://stackoverflow.com/questions/76295214/getting-500-internal-server-error-for-nuxt-3-and-pinia

**Comment by posva** [comment]
As pointed ou in other issues, you need to upgrade Vue to 3.3

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
