### ISSUE TITLE
Issue with BigInt serialization in setup store since Nuxt 3.5.0

### ISSUE THREAD

**Issue by lorado** [posva/pinia#2236]
### Reproduction

---

### Steps to reproduce the bug

1. Define simple setup store with BigInt:
```ts
import { defineStore } from "pinia";

export const useTestStore = defineStore("testStore", () => {
  const someBigInt = ref(0n);

  return {
    someBigInt,
  };
});
```

2. Import store into a page:
```ts
const testStore = useTestStore();
```

### Expected behavior

Serialize BigInt and hydrate in frontend

### Actual behavior

Nuxt throws 500 error with message "Do not know how to serialize a BigInt"

### Additional information

Interesting behaviour - if you would define store with options syntax, like

```ts
import { defineStore } from "pinia";

export const useTestStore = defineStore("testStore", {
  state: () => ({
    someBigInt: 0n,
  }),
});
``` 

then it works without issue.

Since 3.5.0 nuxt moved back to original devalue package, which seems to break setup store partially. What am I missing? Some information in docs how to fix this would be helpful, if the issue is on my side. I expect that pinia nuxt module covers it for me though.

**Comment by danielroe** [comment]
Would you provide a reproduction? I could only reproduce this when trying to _display_ a BigInt in a Vue component (coming from Vue itself), but had no issues at all when merely passing a BigInt in the payload.

<details>
<summary>Error log when trying to display a BigInt in a page</summary>

```
[nuxt] [request error] [unhandled] [500] Do not know how to serialize a BigInt                                                                                           10:24:16
  at JSON.stringify (<anonymous>)  
  at Object.toDisplayString (./node_modules/.pnpm/@vue+shared@3.3.4/node_modules/@vue/shared/dist/shared.cjs.js:390:154)  
  at Module.ssrInterpolate (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:178:35)  
  at _sfc_ssrRender (./test/fixtures/basic/pages/json-payload.vue:36:91)  
```

</details>

**Comment by lorado** [comment]
Hm, it is probably not pinia issue, but I would be glad if you could help me =)
I turned off my custom error nuxt page, and now I see this error log

```
500
Do not know how to serialize a BigInt

at EmptyRef (./node_modules/nuxt/dist/app/plugins/revive-payload.server.js:12:81)
at flatten (./node_modules/devalue/src/stringify.js:58:18)
at flatten (./node_modules/devalue/src/stringify.js:166:43)
at flatten (./node_modules/devalue/src/stringify.js:166:43)
at flatten (./node_modules/devalue/src/stringify.js:166:43)
at flatten (./node_modules/devalue/src/stringify.js:60:39)
at stringify (./node_modules/devalue/src/stringify.js:178:16)
at renderPayloadJsonScript (./.nuxt/dev/index.mjs:892:32)
at ./.nuxt/dev/index.mjs:815:29
```

I was also checking what is the difference between option and setup store, bc again, if I use option store - it works. I figured out so far, that if I use options store, then values are serialized as is, straight as bigint. But when I use setup store, I define `ref(0n)`, so that nuxt serializes a reference to bigint, and seem to have problem there.
I have no clue how to fix it =\

Gonna try to make reproduction...


---

UPDATE: ok this is really wild, I can't reproduce it on fresh project... gonna try to reinstall all dependencies from scratch in my project

**Comment by lorado** [comment]
Oh god, I found it... if I initialise bigint with `0n` its identified as EmptyRef, and then probably `JSON.stringify()` can't manage it... oh dear. So the issue is in the `nuxt:revive-payload:server` plugin in nuxt direclty, which uses falsy check and thinks `0n` is an empty ref, and tries to use `JSON.Stringify`.  Sorry for bothering =) I'll open issue there.
