### ISSUE TITLE
High cpu usage in Chromium 68 on Mac

### ISSUE THREAD

**Issue by zhangshine** [posva/pinia#2251]
### Reproduction

https://github.com/zhangshine/PiniaIssue

### Steps to reproduce the bug

1. clone my repo and `npm run serve` (You can create your own with vue-cli & vue3, do not use vite, since it does not support chromium 68)
2. open with chromium 68, download from https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/554687/

I have tested on Mac Os 13.3.1 with node.js 19 and Mac Os 10.14.6 with nodejs 16.14, both have the same issue.

### Expected behavior

the page should show `0`

### Actual behavior

tab got freeze and cpu is 100% used in the main thread

**Comment by posva** [comment]
Cannot reproduce…

**Comment by zhangshine** [comment]
Sorry about that. After careful testing again, we have found that this issue can only be reproduced on Chromium 68 snapshot position 554687. It may be a bug in Chromium.
