### ISSUE TITLE
中文文档无法在 Firefox 浏览器使用

### ISSUE THREAD

**Issue by hushoujier** [posva/pinia#2252]
### Reproduction

no

### Steps to reproduce the bug

操作系统：windows 10
Firefox：113.0.2 (64 位)

1. 浏览器输入地址：https://pinia.vuejs.org/zh/
2. 鼠标左键单击页面开始使用按钮
3. 页面没有任何反应

### Expected behavior

鼠标左键单击页面开始使用按钮后跳转到详情页面

### Actual behavior

鼠标左键单击页面开始使用按钮后没有任何响应

### Additional information

![报错信息](https://github.com/vuejs/pinia/assets/34603874/72aacedc-e35c-4e93-b278-c331e8c5bc54)

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/pinia/issues/2080
