### ISSUE TITLE
Could not resolve Pinia installation with Nuxt 3

### ISSUE THREAD

**Issue by miketests** [posva/pinia#2254]
### Reproduction

[nuxt-starter-2mvpus](https://stackblitz.com/edit/nuxt-starter-2mvpus?file=package.json)

### Steps to reproduce the bug

1) Install Nuxt 3 `npx nuxi init <project-name>`
2) Try to install Pinia `npm install pinia @pinia/nuxt`
3) Result: `npm ERR! ERESOLVE could not resolve`

### Expected behavior

Pinia installation success

### Actual behavior

Installation error

### Additional information

Node: v16.14.2
NPM: 9.4.2

**Comment by posva** [comment]
Don’t open issues without repro please 🙏 
The error you see is also not from Pinia or Nuxt but an npm error maybe related to your network
