### ISSUE TITLE
pinia/README.md extend installation 

### ISSUE THREAD

**Issue by mortifia** [posva/pinia#2263]
add installation for nuxt in the read me pls

### Reproduction

get started nuxt and try to install by the doc in https://nuxt.com/modules/pinia

### Expected behavior

add https://pinia.vuejs.org/ssr/nuxt.html#installation to the readme to find info or create a readme for https://nuxt.com/modules/pinia

### Actual behavior

only how to instal with vue not nuxt (generating an ERESOLVE could not resolve)

**Comment by posva** [comment]
Thanks for the suggestion but I believe the docs is the right place for that
