### ISSUE TITLE
pinia not working on safari and safari tech, working fine on chrome brave and firefox

### ISSUE THREAD

**Issue by anditsung** [posva/pinia#2264]
### Reproduction

https://github.com/anditsung/pinia-error

### Steps to reproduce the bug

open the page using safari or safari tech preview

### Expected behavior

working fine

### Actual behavior

Error: [🍍]: "getActivePinia()" was called but there was no active Pinia. Did you forget to install pinia?
	const pinia = createPinia()
	app.use(pinia)
This will fail in production.

### Additional information

compiling using vite will not work on safari and safari tech but will working fine on chrome, brave and firefox

compiling using webpack dont have this issue at all

**Comment by anditsung** [comment]
adding sync here
```html
<script type="module" async>
            window.App = createApp()
            App.countdown()
        </script>

        <script type="module" async>
            App.liftOff()
        </script>
```

will work on safari but not working on other browser

**Comment by posva** [comment]
You likely have multiple instances of Vue or Pinia causing the error you see.
Since it’s the tech preview, there could also be a bug causing it but this isn’t related to pinia per se
