### ISSUE TITLE
Next version of TypeScript type error in source code

### ISSUE THREAD

**Issue by posva** [posva/pinia#2278]
### Reproduction

this repo

### Steps to reproduce the bug

- Upgrading locally to the dev version of TS

### Expected behavior

no TS errors

### Actual behavior

Errors at

- https://github.com/vuejs/pinia/blob/eedb9b2eb37d868341255360c8a24114bd117b14/packages/pinia/src/store.ts#L476
- https://github.com/vuejs/pinia/blob/eedb9b2eb37d868341255360c8a24114bd117b14/packages/pinia/src/store.ts#L704
- https://github.com/vuejs/pinia/blob/eedb9b2eb37d868341255360c8a24114bd117b14/packages/pinia/src/store.ts#L719

### Additional information

- https://github.com/microsoft/TypeScript/issues/54757

**Comment by galaxy-s10** [comment]
hello，Is it the same as her: https://github.com/vuejs/pinia/issues/2353
