### ISSUE TITLE
建议扩展下$reset() 可以重置某个值

### ISSUE THREAD

**Issue by haobarry** [posva/pinia#2287]
### What problem is this solving

如题   有时并不想重置整个store，而只想改变其中某个值。

### Proposed solution

 现在reset 方法会重置整个store，虽然也可以自定义一个方法单独处理，但是毕竟要重复写代码，如果能重置store中定义的某个值，感觉这个$store()比较实用。

**Comment by posva** [comment]
As mentioned in other issues and in docs: reset is intentionally kept as just a function that creates the initial state. Any further custom implementation can be added as a plugin.
