### ISSUE TITLE
pinia.esm-browser.min.js  cannot use 

### ISSUE THREAD

**Issue by ruanye** [posva/pinia#2289]
### What problem is this solving

浏览器中直接引入不能使用，依赖了 vue-demi 但是我想直接使用，期望浏览器版本不要依赖任何第三方库，可以直接引入使用

### Proposed solution

anytime

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/pinia/issues/2205

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
