### ISSUE TITLE
Given a TestingPinia instance of a store with a watch, the watch actions are not stubbed

### ISSUE THREAD

**Issue by cadriel** [posva/pinia#2291]
### Reproduction & Steps to reproduce the bug

Given a composable store that has a watch - a `TestingPinia` instance of  that store will run the actions as if they were not stubbed. Actions outside of the watch are stubbed as expected.

```ts
# A real store..
export const useSomeStore = defineStore('somestore', () => {
  const someId = ref(10)

  watch(
    someId,
    () => { someAction() },
    { immediate: true }
  )

  async function someAction() {
    try {
      // Something here, like an API call.
    } catch (e) {
      console.error(e)
    }
  }
})
```

```ts
# A spec..
it('should pass', async () => {
  const pinia = createTestingPinia({ initialState, stubActions: true })
  const wrapper = mount(someComponent, {
    global: {
      plugins: [pinia, ...]
    }
  })

  // If the initial state has someId defined, or if you set someId .. the action is run unstubbed.
})
```

### Expected behavior

The action to have been stubbed and not run...

### Actual behavior

The original, unstubbed action is run.

### Additional information

It took me a while to figure out why I was getting a bunch of API calls making their way through until I realized the actual actions were being run from the watch.

**Comment by cadriel** [comment]
Also, I noticed this isn't immediately apparent until you fire `flushPromises` enough times that the watch is hit.

**Comment by posva** [comment]
Unfortunately it is simply not possible to stub a function this way. It would be great to document this. Feel free to open a PR!
