### ISSUE TITLE
Actions are not mocked anymore with 2.1.4

### ISSUE THREAD

**Issue by bodograumann** [posva/pinia#2296]
### Reproduction

https://github.com/bodograumann/pinia-testing-mock-actions

### Steps to reproduce the bug

I have tried to create a minimal reproduction, but the thing is that it occurs in the context of storybook, so using the storybook reproduction tool seemed the easiest way to show the issue. I can try reproducing it without storybook later if necessary.

1. Check out the repro repo
2. npm install
3. npm run storybook
4. Goto http://localhost:6006/?path=/docs/example-page--docs

### Expected behavior

The `getRandomNumber` action should be mocked with an implementation that always returns `42`.

### Actual behavior

The action is not a mock at all, so trying to define the implementation yields:

> Error: randomStore.getRandomNumber.mockImplementation is not a function

### Additional information

Confusingly, this only happens since pinia 2.1.4.
If you go one commit back in the reproduction to pinia 2.1.3 (and npm ci + restart the storybook) everything works as exepected and you can see `42` in the output.

**Comment by posva** [comment]
This is too much for a repro 😅 
Open one without storybook or even a PR with a failing unit test case

**Comment by bodograumann** [comment]
I have created a new issue here: https://github.com/vuejs/pinia/issues/2298
