### ISSUE TITLE
Pinia 2.1.4 devtools are incompatible with @pinia/testing

### ISSUE THREAD

**Issue by bodograumann** [posva/pinia#2298]
### Reproduction

https://github.com/bodograumann/pinia-testing-dev-tools-compat

### Steps to reproduce the bug

1. Clone the repo
2. `npm install`
3. `npm run dev`
4. Open browser at http://localhost:5173

### Expected behavior

The testing pinia instance is used and you can see `Counter: 0` in the output.

### Actual behavior

Nothing is rendered and the browser console shows

> Uncaught TypeError: store.increment.mockImplementation is not a function

### Additional information

I am only using `@storybook/jest` to be able to have mocking while running in the browser. (For that to work I also had to set `window.global = window`.)
Maybe using a simpler spy creation method is also possible, but I would not know how right now.

**Comment by posva** [comment]
I couldn't reproduce without the extra dependency... so I think the lib you are using is just missing the function in question. Let me know if you manage to reproduce it without the dependency but I don't think this is related to pinia.

**Comment by bodograumann** [comment]
It works when you downgrade to pinia 2.1.3 (or earlier) though!

When inspecting the store actions you can very clearly see that with pinia 2.1.3 the actions are mocks and with 2.1.4 they are not (so probably the real things). That is why they don't have the mock machinery on them anymore.

**Comment by bodograumann** [comment]
Could you please share your attempt to reproduce the issue without `@storybook/jest`?

**Comment by posva** [comment]
I checked with the unit tests in the repository 👀

If the action is not being mocked, it means the plugins added to mock actions didn’t take effect. That could lead somewhere maybe

**Comment by posva** [comment]
Oh I think the devtools might be overwriting something. Feel free to take a deeper look

**Comment by bodograumann** [comment]
One change in 2.1.4 is  the introduction of `wrapWithProxy` for `patchActionForGrouping`.
I tried converting the store to using options syntax, as that would enable `wrapWithProxy` and thus be more like the old behaviour, but that did not fix the issue.

**Comment by bodograumann** [comment]
What I see now, is that in 2.1.3 actions in setup-style stores where not patched at all.
So when testing with the options-style store in 2.1.3 the issue appears as well!

That means disabling `patchActionsForGrouping` within `createTestingPinia` would be a solution.
Though maybe it is possible to make patching work together with mocking :thinking:

**Comment by bodograumann** [comment]
Combining mocking and devtools grouping is not useful imho, because when an action is mocked no mutations are executed.
It is however possible to disable mocking actions in @pinia/testing. That means we should not simply disable `patchActionsForGrouping` in the context of `createTestingPinia`. Instead `patchActionsForGrouping` needs to detect when it is dealing with a mocked action and skip it.
So what would be a good way to distinguish regular actions from mocked actions...

**Comment by bodograumann** [comment]
Jest and vitest both have `mocked_action._isMockFunction` , but sinon and probably other mocking libraries don't. Do we want to set the marker ourselves when calling `createSpy` in `testing.ts`?

Alternatively we could try and use a `Proxy` for the action in `patchActionsForGrouping`. I don't understand all the magic that is happening in there though.

**Comment by bodograumann** [comment]
There is also this code: https://github.com/vuejs/pinia/blob/v2/packages/testing/src/testing.ts#L118-L119
It tries to move the @pinia/testing plugins at the end of the stack, but `createPinia` implicitely adds the `devtoolsPlugin` to `toBeInstalled`. That means it will only be installed later.

From this perspective it might be more natural to handle the situation properly in @pinia/testing. I haven't figured out how to enable the devtools during the unittests of @pinia/testing though.

Quite a lot of options of how to tackle the issue...
What would be your preferred approach?

**Comment by posva** [comment]
Nice analysis! I think that it's fine not to even have the devtools for the testing pinia, they were never meant to be used together. The easiest path would be to not patch the actions at all if the pinia is a testing one (https://github.com/vuejs/pinia/blob/v2/packages/pinia/src/store.ts#L901). This should be done within the devtools/plugin.ts file

**Comment by bodograumann** [comment]
I fixed it and even managed to add a regression test.
Please have a look at the PR, when you have some time, @posva
