### ISSUE TITLE
Add a way to subscribe to getters

### ISSUE THREAD

**Issue by dospunk** [posva/pinia#2307]
### What problem is this solving

With the new setup syntax, we can define getters that are also setters using `computed`. In my case, I'd like to use computed getter/setters to have state values that can start undefined but cannot be accessed until they are defined, like so

```ts
const useExampleStore = defineStore('example', () => {
  const internal_exValue = ref(1)

  const exValue = computed({
    get: () => {
      if (internal_exValue.value === undefined) {
        throw new Error('Cannot access exValue before it is defined.')
      } else {
        return internal_exValue.value
      }
    },
    set: (newValue: number) => {
      internal_exValue.value = newValue
    },
  })

  return { exValue }
})
```

I'd like to not expose `internal_exValue` because it shouldn't ever be used.

The problem comes if I want to be able to subscribe to the state. `exampleStore.$subscribe` won't work because technically nothing is in the state! 

### Proposed solution

Add a method like `$subscribe` or `$onAction` that allows us to subscribe to getters.

### Describe alternatives you've considered

I've written a plugin that uses vue's `watch` on my getter to detect changes, but it feels like a hack.

**Comment by posva** [comment]
You **have to return all the state**. This is what allows pinia to pick it up and handle the SSR
