### ISSUE TITLE
[Nuxt] Store is loaded too early so plugin initialization cannot catch up with them

### ISSUE THREAD

**Issue by kesoji** [posva/pinia#2313]
### Reproduction

I need firebase api key so I omitted this but I wrote steps in detail.

### Steps to reproduce the bug

With the setup below, access directly to http://localhost:3000/test causes `500 Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).` error.

<img width="874" alt="image" src="https://github.com/vuejs/pinia/assets/6465251/d533a292-6556-4a68-a945-55bd05084d35">

nuxt.config.ts
```typescript
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@pinia/nuxt'],
})
```

plugins/firebase.ts
```typescript
import { initializeApp } from '@firebase/app'

export default defineNuxtPlugin(() => {
  const config = {
    // firebase config
  }
  initializeApp(config)
  console.log('firebase: initializeApp')
})

```

store/tests.ts
```typescript
import { collection, getDocs, getFirestore } from 'firebase/firestore'
import { defineStore } from 'pinia'

// THIS CAUSES ERROR because plugins/firebase.ts is not called.
const db = getFirestore()
export const useTestsStore = defineStore('tests', () => {
  const tests = ref<any[]>([])
  const loadTests = async () => {
    const snapshot = await getDocs(collection(db, 'tests'))
    tests.value = snapshot.docs.map((d) => d.data())
  }
  return { tests, loadTests }
})

```

pages/test.vue
```vue
<script setup lang="ts">
import { useTestsStore } from '~/store/test'
import { storeToRefs } from 'pinia'

// THIS CAUSES ERROR. //////
const store = useTestsStore()
////////////////////////////////////////////
const { tests } = storeToRefs(store)
store.loadTests()
</script>

<template>
  <div>
    {{ tests }}
  </div>
</template>
```

### Expected behavior

No error.

### Actual behavior

`Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).` error

### Additional information

I think it comes from this commit https://github.com/vuejs/pinia/commit/3e4e63c1f4749ee09b045a771c546de33dd4c405

As of this console error, pinia starts before `plugins/firebase.ts` so firebase has not been initialized.

<img width="865" alt="image" src="https://github.com/vuejs/pinia/assets/6465251/9738e1bf-9029-41f8-88bb-2930d2b28dd2">

I found this behavior when using vuefire documented in https://vuefire.vuejs.org/cookbook/subscriptions-external.html#pinia . However, it is reproducible without vuefire so I wrote minimum reproducible codes. It is because pinia initialization is too early.

I think we can address to this issue using hooks to initialize firebase before pinia but it is a bit difficult for users.

**Comment by posva** [comment]
This is a Firebase question 😅 

Initialize the app outside of the store. You should use https://vuefire.vuejs.org/ btw

**Comment by kesoji** [comment]
@posva 
Thank you for taking a look at this.

I use `plugins/firebase.ts` to initialize firebase as descrived.

But pinia starts `before` the plugin.
Using vuefire doesn't resolve this.

Users expect plugins to be initialized before page script executed, but pinia is executed before plugins.

**Comment by blu14x** [comment]
Same problem for me :/
```javascript
// stores/auth.js
export const useAuthStore = defineStore('auth', () => {
  const { $api } = useNuxtApp()
  console.log($api)
  ...
}
``` 
```javascript
// stores/schema.js
export const useSchemaStore = defineStore('schema', () => {
  const { $api } = useNuxtApp()
  console.log($api)
  ...
}
```

![image](https://github.com/vuejs/pinia/assets/26022264/71dc14e7-f77d-477b-95a0-ad2b3407d134)

On the first store, *$api* is not ready yet.

**Comment by trandaison** [comment]
Hi @posva 
I'm sorry for posting a question here. But what if I need to access a pinia store in a nuxt plugin? is it possible? any workaround?

**Comment by chinmay-sheth** [comment]
Facing a similar issue, need to fetch the route url and use it as a key while declaring plugin, but the store is initialised and added to local storage even before the logic in plugin can be executed.
