### ISSUE TITLE
Docs website seems to be broken

### ISSUE THREAD

**Issue by Viicos** [posva/pinia#2317]
### Reproduction

Reproduction

### Steps to reproduce the bug

1. Try accessing this URL: https://pinia.vuejs.org/core-concepts/state.html
2. Try clicking on some links in the left-hand side menu

Some `TypeError`'s are logged in the console:

![image](https://github.com/vuejs/pinia/assets/65306057/8c98040a-9c94-499c-9d19-5d803a0b808b)

### Expected behavior

NA

### Actual behavior

NA

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Comment by posva** [comment]
https://github.com/vuejs/pinia/issues/2080
