### ISSUE TITLE
Should make use of navigator.userAgentData and not navigator.userAgent

### ISSUE THREAD

**Issue by 1Map** [posva/pinia#2321]
### Reproduction

Open Devtools in Chrome and see message

### Steps to reproduce the bug

Just view in Chrome devtools warning

### Expected behavior

No Message should be shown

### Actual behavior

<img width="1291" alt="image" src="https://github.com/vuejs/pinia/assets/1152458/96061083-7b7d-435b-874c-e1879e073126">

**Comment by posva** [comment]
The current solution has better support: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData
