### ISSUE TITLE
Loss of state after computer nap in chromium-based browsers

### ISSUE THREAD

**Issue by mdevDE** [posva/pinia#2323]
### Reproduction

example-vue-3-vite-main

### Steps to reproduce the bug

Hi there,
when using example-vue-3-vite-main locally, store state is lost after computer nap, however when using https://stackblitz.com/github/piniajs/example-vue-3-vite?file=README.md state is still there after the nap

Use example locally 
Put computer to sleep
Wake computer

<img width="1792" alt="Bildschirmfoto 2023-07-23 um 10 42 12" src="https://github.com/vuejs/pinia/assets/37185489/df07a683-22b5-4492-91e0-08a34bfd2ed4">
<img width="1792" alt="Bildschirmfoto 2023-07-23 um 10 42 15" src="https://github.com/vuejs/pinia/assets/37185489/eee35d7b-1e7f-4eb7-b839-f4df20d5bb31">
<img width="1792" alt="Bildschirmfoto 2023-07-23 um 10 42 22" src="https://github.com/vuejs/pinia/assets/37185489/c4b0c578-b1e2-41b0-bf0d-966c4cc66172">

### Expected behavior

After the nap, all entries are still there (Pinia, Apple)

<img width="1792" alt="Bildschirmfoto 2023-07-23 um 10 42 15" src="https://github.com/vuejs/pinia/assets/37185489/dbc148ab-4551-4980-a21b-8360b0c074ca">

### Actual behavior

All my entries are gone after the nap.
I experience this problem in Chrome-based browsers (Google Chrome (114 and 115), Brave, Edge, Opera), while everything is fine in Safari and Firefox.

<img width="1792" alt="Bildschirmfoto 2023-07-23 um 10 42 32" src="https://github.com/vuejs/pinia/assets/37185489/90348ee1-3063-4e71-92e9-02776f506273">

**Comment by posva** [comment]
The page probably reloads, this is unrelated to pinia or Vue. You can use a plugin to persist data to local storage
