### ISSUE TITLE
Private state does not trigger mutations in plugins

### ISSUE THREAD

**Issue by jmcooper** [posva/pinia#2324]
### Reproduction

https://codesandbox.io/s/pinia-private-state-dv6f29?file=/src/stores/cart.js

### Steps to reproduce the bug

1. Run the attached reproduction codesandbox.
2. Notice that there is a plugin console.logging all mutations
3. Notice that the cart store has productIds state property that is essentially private because it isn't returned from the store
4. In the embedded browser, click the "Add" buttons to add items to the cart which calls the addToCart action in the cart store and mutates the productIds array.
5. Notice that the mutation does NOT get logged
6. Export productIds from the cart store
7. Click the add buttons and notice the mutation DOES get logged.

### Expected behavior

I would expect all mutations of state to be logged including mutations that happen privately inside the store to state properties that are not exposed externally.

### Actual behavior

State properties that are not exported do not trigger mutations in plugins.

### Additional information

Perhaps this is intended behavior, but it was unexpected for me when I built a similar app.

**Comment by posva** [comment]
This is indeed intended, the state properties must be returned for pinia to pick them up. There isa trick to have private properties though, it's to put them into another store and use that that store state within the other store. In your example, the `productIds` would go within a `private-state` store (which does return it) and you consume it within the product store.
