### ISSUE TITLE
The content of the development document is inconsistent and some content is missing.

### ISSUE THREAD

**Issue by rich1e** [posva/pinia#2349]
### Reproduction

https://pinia.vuejs.org/zh/core-concepts/state.html#resetting-the-state

### Steps to reproduce the bug

In the development documentation, this content is all missing.
The sample code is also inconsistent.

1. In [Setup Stores](https://pinia.vuejs.org/core-concepts/#setup-stores), you need to create your own $reset() method:

2. 
    ```ts
    export const useCounterStore = defineStore('counter', () => {
      const count = ref(0)
    
      function $reset() {
        count.value = 0
      }
    
      return { count, $reset }
    })
    ```

[EN](https://pinia.vuejs.org/core-concepts/state.html#Resetting-the-state)
![image](https://github.com/vuejs/pinia/assets/29914689/b474b0a4-42c0-4b51-ae86-198ebc6039b2)

[CN](https://pinia.vuejs.org/zh/core-concepts/state.html#resetting-the-state)
![image](https://github.com/vuejs/pinia/assets/29914689/54dbb9f2-df3f-4e90-af6c-e37ef22de40d)

### Expected behavior

I want development documentation to be consistent, not multiple versions.

### Actual behavior

In the development documentation, this content is all missing.

**Comment by posva** [comment]
I imagine the translation team will pick it up at some point. You can also open a pull request to fix it
