### ISSUE TITLE
The left menu does not matches the right page in Official Documents

### ISSUE THREAD

**Issue by CherishTheYouth** [posva/pinia#2357]
### Reproduction

![image](https://github.com/vuejs/pinia/assets/41944818/686cc81a-9470-449e-9eb2-8e10a6184be7)

### Steps to reproduce the bug
https://pinia.vuejs.org/zh/ssr/
![image](https://github.com/vuejs/pinia/assets/41944818/686cc81a-9470-449e-9eb2-8e10a6184be7)

### Expected behavior

The left menu matches the right page

### Actual behavior

The left menu does not matches the right page

### Additional information

![image](https://github.com/vuejs/pinia/assets/41944818/686cc81a-9470-449e-9eb2-8e10a6184be7)

**Comment by CherishTheYouth** [comment]
I viewed a wrong website, I am so sorry!

**Comment by posva** [comment]
This is fine. You can always suggest an improvement as a Pull Request
