### ISSUE TITLE
`Getters` that use `route` are not working properly in setup stores

### ISSUE THREAD

**Issue by trandaison** [posva/pinia#2361]
### Reproduction

https://codesandbox.io/p/sandbox/sad-lake-cjxzvt?file=/stores/test.ts:10,6

### Steps to reproduce the bug

1. Visit the reproduction link
2. Click on any `/?id=1..n` button to change the `id` value on the route URL.
3. The value of `currentData` getter is updated correctly ✅ 
4. Click the `/home` link.
5. At the home page, click on any `/?id=1..n` button to navigate back to the `index` page.
6. Repeat step no. 2, but this time, the value of getter will not be updated ❌ 

### Expected behavior

The Getter value should be updated same as before.

### Actual behavior

The Getter value not updated after navigating.

### Additional information

- This happen when navigate to the page in client side. If you enter the page from URL, the getter still working.
- If I turn of the ssr from the nuxt config. And move the `useRoute` statement inside the computed/getter, it works.

```diff
- const route = useRoute();
  const currentData = computed(() => {
+   const route = useRoute();
    const index = Number(route.query.id || 1);
    return data.value[index];
  });
```

However this code never working on server side, cuz the `useRoute()` is call outside the setup context.

**Comment by posva** [comment]
You need to update the version of the packages you are using, namely pinia, its Nuxt plugin and ensure you are using Vue 3.3 (Nuxt should be already be doing this)

**Comment by trandaison** [comment]
@posva Thanks for replying.
I did upgraded the `pinia@2.1.6`, `@pinia/nuxt@0.4.11`, vue was 3.3.4 already. All the packages are now latest version, but the bug still happen. This issue should not been closed.

**Comment by posva** [comment]
I tried locally just in case but it works correctly. Could be something with Codesandbox.

**Comment by trandaison** [comment]
@posva You are right, it works on local in **dev** mode. However, it's not working in **production build**.
please run following commands and reproduce

```bash
npx nuxi generate
npx nuxi preview
```

![pinia](https://github.com/vuejs/pinia/assets/13447235/9201b18c-3654-4288-b614-9790d52000c3)

**Comment by posva** [comment]
It seems to only happen in Nuxt context with the **automatic import of `useRoute()`**, adding a manual import from vue-router fixes it:

```ts
import { useRoute } from 'vue-router'
```

You should report this to the Nuxt team
