### ISSUE TITLE
Pinia and Vue 3 + Vue-dev-tool-next

### ISSUE THREAD

**Issue by layanto** [posva/pinia#237]
Noticed that Pinia's next branch has not been updated in a while and is a few commits behind the master branch (for Vue 2). As Vue 3 should be released soon-ish, will Pinia's next branch be updated in particular to support the new Vue-dev-tool-next which has timeline and plugin support?

**Comment by posva** [comment]
Yes, there are plans to update it in the following weeks.

Keep in mind its API is almost identical to Vuex 5, so at some point, if both libraries end up having the same direction, same size and API, I will recommend people to use Vuex 5 and help there instead

**Comment by layanto** [comment]
Didn't know Vuex 5 is already in the works. If API is similar then hopefully migrating from Pinia-next to Vuex 5 won't be too difficult.
