### ISSUE TITLE
Firefox can't jump

### ISSUE THREAD

**Issue by rwerplus** [posva/pinia#2372]
### Reproduction

https://pinia.vuejs.org/zh/introduction.html

### Steps to reproduce the bug

Using Firefox to open the https://pinia.vuejs.org/zh/introduction.html page,clicking on any of the buttons fails to make the jump

### Expected behavior

Click to jump.

### Actual behavior

Click to jump.

**Comment by posva** [comment]
This has already been reported. Please search issues
