### ISSUE TITLE
Nuxt Layer support

### ISSUE THREAD

**Issue by marcelxpfeifer** [posva/pinia#2377]
### What problem is this solving

Allow the possibility to use pinia with nuxt layers.

### Proposed solution

It would be awesome to have Nuxt layer support similar to nuxt/i18n, where the default stores are extended from the base project, but can be overwritten in the layer on top.

### Describe alternatives you've considered

Currently all stores need to be copied into the extend layer as well.

**Comment by posva** [comment]
I really cant figure out what you mean. At first glance this looks like a project specific problem or at the very least like it could be hosted in another package so I’m moving this to a discussion for anybody who want to collaborate on it
