### ISSUE TITLE
Nuxt 3 - Referencing a store in a layout and a lazy loaded component stop layout component's styles being inlined on load

### ISSUE THREAD

**Issue by gavin667** [posva/pinia#2399]
### Reproduction

https://nuxt-3-layout-css.vercel.app/

### Steps to reproduce the bug

1. Load https://nuxt-3-layout-css.vercel.app/
2. You may need to throttle your network connection to notice it.

Notice the text for a component based in the layout flashes from black to blue.

### Expected behavior

The text for a component based in the layout should not flash black to blue on initial page load.

The styles for components referenced in a layout file should be inlined correctly like other page styles when a lazy loaded component that also references the same store in the layout is used.

### Actual behavior

It seems to be that if I call a Pinia store in a layout file and reference a lazy loaded component that also references the same store it fails to inline the styles correctly on initial page load.

Commenting out either references to the store fixes the issue.

Check [the repo I made](https://github.com/gavin667/nuxt-3-layout-css) but as a simplified version:

```
// layouts/default.vue
<template>
  <div>
    <div>This is text directly on the layout.</div>

    <!-- CSS inside this is not inlined and leads to FOUC -->
    <AnotherComponent/>

    <!-- This component also references const exampleStore = useExampleStore() -->
    <LazyTestComponent v-if="showLazyComponent"/>

    <div>
        <slot />
    </div>
  </div>
</template>
<script setup>
  const exampleStore = useExampleStore()
</script>
```

```
// components/TestComponent.vue
<template>
  <div class="test-component">
    <h1>This should be red on load</h1>
  </div>
</template>

<script setup>
  const exampleStore = useExampleStore()
</script>

<style lang="postcss">
  .test-component {
    color: red;
    font-size: 1.2rem;
  }
</style>  
```

```
// components/AnotherComponent.vue
<template>
    <h1 class="another-component">
        This should be blue on load
    </h1>
</template>
<style lang="postcss">
  // these styles are missing onload
  .another-component {
    color: blue;
  }
</style>
```

**Comment by posva** [comment]
This is unlikely to be related to pinia. I recommend you to open an issue on Nuxt. The problem could come from vite too
