### ISSUE TITLE
Feature request: subscribeAction()

### ISSUE THREAD

**Issue by MartinMalinda** [posva/pinia#240]
VueX has an option to `subscribeAction`. I think it would be even more relevant here. Pinia currently has `subscribe()` but it's just a simple wrapper over `watch()` and it often might not be precise enough.

Subscribing to actions would be more explicit.

https://vuex.vuejs.org/api/#subscribeaction

```ts
store.subscribeAction((action, state) => {
  console.log(action.type)
  console.log(action.payload)
})
```

Usecase:

In many places in the code you might want to react to `userStore.state.isLoggedIn`. Current `store.subscribe()` may fire multiple times, you'd need to check for truthy value of loggedIn, check if it's different from previous value and so on.

**Comment by rijkvanzanten** [comment]
What would `action.type` / `action.payload` be in the context of Pinia? AFAIK Pinia doesn't have actions right?

Also, how would this be different from something like

```ts
watch(() => store.state.isLoggedIn, (newLoggedInState) => { /* do something */ });
```

?

**Comment by posva** [comment]
I also wonder what is the actual use case behind a `beforeAction` and `afterAction`. Maybe some discussion can be found on Vuex. Note the can be added on userland by wrapping actions, so one could imagine a custom `createStore` that automatically extends each action to register these hooks

**Comment by MartinMalinda** [comment]
@posva I briefly tried to create this wrapper and I had a problem with `this` in actions. It no longer referred to he right thing. But I might give it another try.

> Also, how would this be different from something like `watch(() => store.state.isLoggedIn..`

@rijkvanzanten 

This fires also on setting isLoggedIn to false (on logout), so then you gotta add an if check. No big deal. But perhaps you're also setting it to on in

- automatic login after app boot (from cookie, token whatever)
- after redirecting back from OAuth page

And you don't wanna react in these cases actually because the whole app is just booting.

**Comment by MartinMalinda** [comment]
> I also wonder what is the actual use case behind a beforeAction and afterAction

To me `afterAction` makes more sense as you want to react after the action changed state.

**Comment by posva** [comment]
why not calling

```js
await store.myAction()
myAfterCode()
```

**Comment by MartinMalinda** [comment]
I could do that (and I'm doing that) in the same component where I'm logging in. But I need to react specifically to login at other places in the code. Completely different components need to react to login as well.

**Comment by posva** [comment]
if it always happens, then why not do it inside of myAction? This really needs more information regarding the motivation in order to go forward 😓

**Comment by MartinMalinda** [comment]
To me it's mostly more explicit `watch`. I'll try to expand upon the previous example.

1) App is booting
2) Auto authentication logic starts in the begining
3) There's components that right away in `setup()` right away wait for authentication and then fire AJAX requests

```ts
setup() {
  const data = ref(null);
  async fetchData() {
   await waitForAutoAuth();
   data.value = await someAjax();
  }

 fetchData();
}
```

4) isLoggedIn affects templates, but it also affects JSON responses
5) Components need to wait for auto authentication to finish, but they also need to react to email&password form to be submitted, besides rerendering some templates, they might also need to refire some ajax calls.

At this point I could use `watch`

If I did something like this:

```ts
setup() {
  const data = ref(null);
  async fetchData() {
   await waitForAutoAuth();
   data.value = await someAjax();
  }

 fetchData();
 watch(() => user.state.isLoggedIn, () => {
  if (user.state.isLoggedIn) {
  fetchData();
  }
 });
}
```

I'd have an issue that this `watch` would fire also for the initial auto authentication.
So I could refactor my code. Perhaps allow `isLoggedIn` to be `null` which would mean the authentication state is unresolved yet or add one more boolean like `hasAutoAthenticationFinished`:

```ts
setup() {
  const data = ref(null);
  async fetchData() {
   data.value = await someAjax();
  }

 watch(() => user.state.isLoggedIn, () => {
  if (user.state.hasAutoAuthFinished || user.state.isLoggedIn) {
  fetchData();
  }
 }, { immediate: true });
}
```

I guess this piece of code would do the trick. I'm not sure. Only isLoggedIn is watched, maybe I'd need to watch also `hasAutoAuthFinished`. I'm not super happy with this piece of code, it's not too self explanatory.

What I would love is something like this:

```ts
setup() {
  const data = ref(null);
  async fetchData() {
   await waitForAutoAuthentication();
   data.value = await someAjax();
  }

  fetchData(); // fire right away
  store.subscribeAction('loginWithUsername', () => {
   if (store.state.isLoggedIn) {
    fetchData(); // refire
  }
  });
```

I like this more, it's more self explanatory.

------

Perhaps it's an edgecase. It's the first place where I needed it, in a lot of cases it's ok for me to use `watch` or actually I can get away without any observer pattern. But I think there are cases where an explicit subscription is better than a `watch` with extra guard code.

**Comment by gjuchault** [comment]
@posva Use case: making plugins like persistance, logging, etc.

**Comment by posva** [comment]
I'm adding an `onAction` method to stores and wanted to have some feedback on the API: https://github.com/posva/pinia/blob/v2/src/types.ts#L327

I'm currently using it for devtools

**Comment by posva** [comment]
This has been released on both v1 and v2 and I would appreciate some feedback on the existing arguments before documenting the api 🙂

**Comment by posva** [comment]
The API has been documneted

**Comment by jods4** [comment]
@posva sorry I'm much too late to the party... Naming/API-wise isn't `after()` a bit strange?
Every Vue `setup` hooks, vue-router and pinia `onAction`, `onError` start with `on`.
Wouldn't it be more coherent that `after` starts with `on` as well, e.g. `onReturn`, or `onComplete`?

**Comment by posva** [comment]
Yeah, but onAfter doesn’t sound right because « after what » and complete and return do not really relate to something running after returning or resolving. Maybe there is a better name
We can deprecate it and remove it later on

**Comment by jods4** [comment]
I agree naming is hard!!

We're inside an action subscription (called `onAction`), so I suppose it's fairly natural that _the action_ "ran" or "completed" or "returned" a value (since there is a value passed to the callback)? 

The docs name the callback parameter `result`, so maybe `onResult`?

One more try: `onDone` or `onApplied`? We're inside an action subscription, `onDone` and `onError` don't seem ambiguous to me.

Maybe someone else can find a better name :)

**Comment by posva** [comment]
Removing the `after` seems like a good path to take to improve the naming. `onDone()` sounds good. Other similar options are `onFinished` / `onFinish`, `onSuccess`. Let's give this some time as the API would have to be deprecated for a couple of months anyway 😄 . Thanks a lot for the suggestions!
