### ISSUE TITLE
Adding @pinia/nuxt as a nuxt3 module breaks autofocus

### ISSUE THREAD

**Issue by jhughes-dev** [posva/pinia#2409]
### Reproduction

https://codesandbox.io/p/sandbox/serene-johnson-lrqrlk?file=/sandbox.config.json:11,1

### Steps to reproduce the bug

I was running into this and got a minimal reproduction with the following

package.json
```json 
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "^3.7.3"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.11",
    "pinia": "^2.1.6",
    "vue": "^3.3.4"
  }
}
```
nuxt.config.js
```js
export default defineNuxtConfig({
  modules: ['@pinia/nuxt']
})

```
app.vue
```html
<template>
  <div>
    <input autofocus/>
  </div>
</template>
```

run the dev server, and in the browser (I was using Chrome) open the dev-tools console.

At console, call 
`> document.activeElement`

### Expected behavior

You should see:
`<input autofocus="">`

You can see this by removing the @pinia/nuxt module from nuxt.config.js

### Actual behavior

You will see: 
`<body>...</body>`

This also seems to happen by manually calling element.focus() from onMounted callback.

**Comment by posva** [comment]
It auto focus when opening in a new tab (https://lrqrlk-3000.csb.app/).

Note this cannot be related to pinia, it does nothing to active element or inputs. I imagine you were seeing this on codesandbox as it works when opening the standalone view.

**Comment by jhughes-dev** [comment]
I see it in a local version of that setup. If I remove the module from nuxt.config, the behavior goes away. It's possible it's not Pinia, but nuxt "modules" in general. It might also be something in the loading of the pinia nuxt module.

I'll check it with a different nuxt module to make sure.

**Comment by jhughes-dev** [comment]
I tried with the eslint module, and that didn't trigger it, but it may not be calling the same things as the pinia module.

**Comment by jhughes-dev** [comment]
Now I cannot reproduce it at all, even in the local clone. So strange.

**Comment by posva** [comment]
It could also be a browser extension or how vue renders. There are some libs out there for a `v-focus` directive that are more effective guarantying the auto focus of elements
