### ISSUE TITLE
Creating an Array by reactive results in a BUG when using the setupFunction syntax.

### ISSUE THREAD

**Issue by Mr-LJQ** [posva/pinia#2410]
### Reproduction

https://codesandbox.io/s/intelligent-chatelet-523248?file=/src/App.vue

### Steps to reproduce the bug

When using reactive to create a dataList, pressing the update button cannot update the UI, while when using ref to create a dataList, pressing update can update the state, and the UI will respond.

### Expected behavior

The UI should update after calling store.$patch(dataList:[{name:&quot;Jack&quot;,age:20}])

### Actual behavior

no update

### Additional information

This is mainly because store.$patch() updates pinia.state.value[id], while the user uses store,pinia.state.value[id] and store are two reactive. When a user creates a dataList with a reactive using the setupFunction syntax, updating the pinia.state.value[id].dataList causes it to be disconnected from the store.dataList, whereas when a user creates a dataList with a ref, the pinia.state.value[id] points to the same ref as the store, so when you update the pinia.state.value[id].dataList, the store.dataList is also updated (they use the same source Ref). 
The main problem is that the setupFunction syntax of pinia using ref, reactive creating state have different logical reactions, which is strange. Pinia should ensure that users can update through store.$patch whether they use ref or reactive to create a state.

**Comment by posva** [comment]
Your deduction is correct: since the array is a `reactive()` object, it cannot be replaced, so the `$patch()` fails. The same happens if trying to directly set the array. For this case, you **must** use a `ref()` (or `shallowRef()`)
