### ISSUE TITLE
The pinia state value changes while the muted props value changes

### ISSUE THREAD

**Issue by suneethdev** [posva/pinia#2415]
### Reproduction

yes

### Steps to reproduce the bug

get value from store and provide to child component, implement event emit functionality to mutate the prop (value from parent) with the store value. try to change the prop value from parent component and the store state value in child component will change. 

### Expected behavior

the value fetched from pinia store should not change 

### Actual behavior

Parent component Props value is being interconnected with the child component pina store state value.  

### Additional information

In my application, i used pinia store and event emit implementation to mutate props value from child component to parent component, but now both values are reactive. while I change my value from the parent component the child component data (pinia store value) also changes.

**Comment by posva** [comment]
Don't post issues without reproductions. If you need help please use the Discussions 🙂
