### ISSUE TITLE
Store reactivity flow causes scoped style block to throw a `MutationObserver` error

### ISSUE THREAD

**Issue by StrikeAgainst** [posva/pinia#2428]
### Reproduction

https://codesandbox.io/s/determined-bird-jy525y

### Steps to reproduce the bug

Click the button rendered in the repro.

### Expected behavior

The app should continue working without an error being thrown.

### Actual behavior

An error `MutationObserver.observe: Argument 1 is not an object.` will be thrown. The app stops working.

### Additional information

I am not sure if this is actually Pinia related or a general Vue bug. So far I was not able to reproduce the faulty behavior outside of a Pinia store though.

Some takeaways on this issue:
1. The error does not appear if all store variables are declared in the `App` component.
2. The error does not appear if the scoped style block from `Icon` is removed.
3. The error does not appear if `store.foo && remoteData` is moved to a `computed` variable instead. This is not feasible in situations where one variable is the condition for a parent node of `Icon` instead, like in my production case.

I suppose there is some kind of inconsistency with the flow structure of reactivity here. `foo` gets toggled manually, causing a watcher to set a value for `bar`. A watcher for `bar` then resets `remoteData` to `null`, while a subsequent async request assigns new data to `remoteData`. The `Icon` component, which features scoped styling, renders only when both `foo` and `remoteData` are truthy. For a short moment it's triggered to render when `foo` becomes `true`, but through the `bar` watcher, `remoteData` consequently becomes `null`, instantly withdrawing the render. This doesn't stop an internal `onMounted` responsible for scoped style application though, but with the `Icon` element not appended to the DOM tree any more, the `MutationObserver` initialized in the `onMounted` call tries to observe the non-existent parent node of the element, causing it to throw an error.

**Comment by posva** [comment]
I checked your repro for a while. As you observed you seem to have a race condition, this might be a Vue bug but it doesn't seem related to pinia. You can reproduce it without pinia with this custom store:

```ts
export function useCustomStore() {
  const effect = effectScope()

  return effect.run(() => {
    const foo = ref(false);
    const bar = ref(null);
    watch(foo, () => {
      console.log('set foo')
      bar.value = {}
    });
  
    return reactive({
      foo,
      bar
    });
  })
}
```

A workaround (or intended fix) is to use a post flush watcher:

```ts
watch(
  () => store.bar,
  () => {
    console.log('store.bar watcher')
    remoteData.value = null;
  },
  { flush: 'post' }
);
```

I added a boiled down repro to https://github.com/vuejs/core/issues/9264 because I think it might be a duplicate but the existing issue currently has a very convoluted reproduction (and that's probably why it was ignored)

**Comment by StrikeAgainst** [comment]
Thank you very much, the post flush workaround works without issues in my case.
