### ISSUE TITLE
pinia provides singleton at component level

### ISSUE THREAD

**Issue by huajian123** [posva/pinia#2433]
### What problem is this solving

I created a vue3 component library project, which contains a table component. In this table component, I use pinia to manage the state and package it into an npm package. After packaging, I installed this package in the application project and used two identical table components. At this time, the two table components use the same pinia instance and share the state. What is expected is a state of independent scope under this table component

### Proposed solution

Provide component-level state singleton

**Comment by posva** [comment]
You actually don't need pinia for this! You can achieve what you want with https://vuejs.org/guide/components/provide-inject.html

**Comment by huajian123** [comment]
In fact, I use ag grid's custom rendering method to render table headers or cell components. Using the provider that comes with Vue will fail.
