### ISSUE TITLE
Mutation object key may be assigned an incorrect value when a store is created using the Composition syntax

### ISSUE THREAD

**Issue by rpaech** [posva/pinia#2434]
### Reproduction

None

### Steps to reproduce the bug

I've been playing around with Pinia to understand how to create a store, and subscribe to state changes.  In the process, I've observed an issue with mutation objects, created from a triggered subscription, that may impact identifying what state has changed.  

Specifically, it appears that, when the Options syntax is used to define a store, the `key` property correctly identifies the state that has changed; however, when the Composition syntax is used, the `key` is incorrectly identified as `value`.

The following code fragments show two implementations for a store to hold and modify the `size` of a font; with the first using the Options syntax, while the second is using the Composition syntax.

If I use the Options syntax, when the font size changes the console output shows that the value for `events.key` is correctly set to `size`. 

If I use the Composition syntax, the console output shows the value for `events.key` is instead set to `value`.  In this case, it appears that the mutation object is using the `value` property of the `ref` object rather the `size` state with the store.

Is this an issue with the Pinia implementation using the Composition syntax, or am I just doing something wrong?

### Store definition

```javascript
import { defineStore } from "pinia";

const useFontStateStore = defineStore("font-state-option-impl", {
  state: () => {
    return { size: 12, step: 0.5 };
  },
  getters: {
    getSize: (state) => state.size,
  },
  actions: {
    increase() {
      this.size += this.step;
    },
    decrease() {
      this.size -= this.step;
    },
  },
});

export default useFontStateStore;
```

### Store instantiation and subscription

```javascript
import useFontState_OptionImp from "@/stores/useFontStateStore_OptionImpl";

const fontState_OptionImp = useFontState_OptionImp();

fontState_OptionImp.$subscribe((mutation, state) => {
  console.log(mutation);
});

fontState_OptionImp.increase();
```

### Console log output

```javascript
{
  "storeId": "font-state-option-impl",
  "type": "direct",
  "events": {
    "effect": { ... },
    "target": { ... },
    "type": "set",
    "key": "size",
    "newValue": 12.5,
    "oldValue": 12
  }
}
```

### Store definition

```javascript
import { ref, computed } from "vue";
import { defineStore } from "pinia";

const useFontStateStore = defineStore("font-state-store-impl", () => {
  const size = ref(12);
  const step = ref(0.5);

  const getSize = computed(() => size.value);

  function increase() {
    size.value += step.value;
  }

  function decrease() {
    size.value -= step.value;
  }

  return { size, step, getSize, increase, decrease };
});

export default useFontStateStore;
```

### Store instantiation and subscription

```javascript
import useFontState_StoreImp from "@/stores/useFontStateStore";

const fontState_StoreImp = useFontState_StoreImp();

fontState_StoreImp.$subscribe((mutation, state) => {
  console.log(mutation);
});

fontState_StoreImp.increase();
```

### Console log output

```javascript
{
  "storeId": "font-state-store-impl",
  "type": "direct",
  "events": {
    "effect": { ... },
    "target": { ... },
    "type": "set",
    "key": "value",
    "newValue": 12.5
  }
}
```

### Expected behavior

When a subscription to a store is triggered, the `events.key` property of the mutation object identifed the state that has changed.

### Actual behavior

While a store implemented using the Options syntax produces the expected behaviour in the mutation object, if the store is implemented using the Composition syntax, the `events.key` property is always set to `value`.

**Comment by posva** [comment]
It outputs the proper key (at least in Vue 3). Note this `events` is dev only and comes from Vue:

![Screenshot 2023-10-03 at 09.34.06.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2023_10_03_at_09_34_06_be364890dd.png)

**Comment by rpaech** [comment]
Thanks, didn't see that.
