### ISSUE TITLE
Automatically expose ref in setup store (like script setup)

### ISSUE THREAD

**Issue by mrleblanc101** [posva/pinia#2440]
### What problem is this solving

I have a "big" store, and for each ref, computed and function I add in the setup store, I need to remember to add them to the return at the end of the file like so:
```
return {
    // ref
    menuOpened,
    selectedDay,
    filter,
    selectedTabIndex,
    sort,
    weekObjective,
    projects,
    entries,
    priorities,
    // computed
    weekStart,
    weekEnd,
    todaysEntries,
    weekTotal,
    weekRemaining,
    weekSummary,
    weekSummaryColors,
    weeklySummaryByProjects,
    dailySummaryByProjects,
    sortedProjects,
    projectEntriesTotal,
    isLiveClockingEntry,
    isCreatingEntry,
    canCreateEntry,
    // actions
    addEntry,
    updateEntry,
    deleteEntry,
    toggleEntrySynced,
    addProject,
    deleteProject,
    addPriority,
    deletePriority,
    deleteCompletedPriorities,
};
```

### Proposed solution

In vue `setup()`, you also need to do this, but not in `<script setup>`, I wonder if pinia could find a way to do the same.

**Comment by posva** [comment]
This is something I have considered a couple of times but I ended up understanding it creates other problems...

One could write a vite (or unplugin) plugin to transform files in the `stores` folder to add the wrapping code (`defineStore()` + HMR). Differently from Vue files, those are still TS/JS files so **it would change the semantics** of it and what is possible (e.g. **not possible to do `export`** or **refactor code in external functions**). On top of that, the plugin would have to generate the types definition as well (another `d.ts` file). Differently from components, exposed properties are meant to be accessed by others, so it's often important not to return all functions, this means it will also be necessary to include a way to _hide_ properties, a compiler-macro that can wrap things like `hide(...)`. All these make it not worth compared to `script setup`, it also drives away from the similarities to composables and how easy it is to refactor parts of a store into composables within the same file

**Comment by mrleblanc101** [comment]
Honestly I did not understand a single thing 😅
But good to know you already thought about that ! 
I might consider using a regular store instead of setup store in that case, I'm not sure which one is better (if any) yet

**Comment by posva** [comment]
Setup Stores are more powerful, just like Composition API
