### ISSUE TITLE
State leaking across instances during SSR in Nuxt 3

### ISSUE THREAD

**Issue by justanothersynth** [posva/pinia#2443]
### Reproduction

https://github.com/timelytree/reproduction_pinia-middleware-ssr

### Steps to reproduce the bug

**Setup**
Follow the [README](https://github.com/timelytree/reproduction_pinia-middleware-ssr#readme) in the reproduction repo to set it up

**Reproduction**
1. Navigate to https://localhost:3000/. You should see the the word `tabby` printed on the screen.
2. Open `@/middleware/cat.js`
3. Comment out `store.setCat('tabby')` on line 6 to disable further saving of state to the store
4. Refresh or hard refresh the page → `tabby` is still printed even though it should not be. The default `shabby` should be visible.
5. Navigate to https://localhost:3000/ _in a different browser_ → `tabby` is still printed even though it should not be. The default `shabby` should be visible.

### Expected behavior

- Refreshing the page should display the default value from the store (`shabby`)
- Opening https://localhost:3000/ in a different browser should display the default value from the store (`shabby`)

### Actual behavior

`tabby` is still visible following a page refresh or when opening https://localhost:3000/ in a different browser. Seems like the value is saved server-side and leaks across instances + persists across refreshes.

### Additional information

**Package versions used in reproduction**:
- nuxt: 3.7.4
- @pinia/nuxt: 0.4.11

**Note on `https`**
I run localhost in `https` with some self-signed certificates. Before `npm run dev`, be sure to comment out the `devServer` block in `nuxt.config.ts` in order to run the server in the default `http`.

**Other**
I've been moving from Vuex for a few months now so I may be missing some core concept. But I've read the pinia docs and all related issues/discussions so many times now I think I've memorized them 😬

This is a _minimal_ (and sync) reproduction. I initially ran into this when attempting to implement an async route middleware that has a try/catch and await(s) while also using several composables. Seems that that's a whole other can of worms with a multitude of open issues and a `callWithNuxt` rabbit hole. I'll probably be asking about that next 😅

Thanks in advance for your help!!

**Comment by posva** [comment]
This is actually not related to pinia but rather solved by it 😄 , your `ref()` is just globally shared across your app, move it within the store:

```ts
export const useCatStore = defineStore('cat', () => {
	const cat = ref('shabby')
	return { cat }
})
```

**Comment by justanothersynth** [comment]
Oh wow that's embarrassing, can't remember the last time I overlooked something like this hahah 😅 thanks for the speedy reply!!
