### ISSUE TITLE
@pinia/nuxt Auto import does not work when using `srcDir`

### ISSUE THREAD

**Issue by suzukey** [posva/pinia#2447]
### Reproduction

https://stackblitz.com/edit/nuxt-pinia-autoimport-repro1?file=nuxt.config.ts

### Steps to reproduce the bug

You can see the error when you open the reproduction link.

1. Set the `srcDir` option in nuxtConfig.
2.  Define store in `src/stores/[name].ts`
3. Use store from `app.vue` 

### Expected behavior

It should be automatically imported from `~~/src/stores/[name].ts` = `~/stores/[name].ts`.

but, it tries to resolve imports from `~~/stores/[name].ts` = `~/../stores/[name].ts`.

#### `stores` directory in `srcDir` (not work)
https://stackblitz.com/edit/nuxt-pinia-autoimport-repro1?file=nuxt.config.ts

#### `stores` directory in root (it work)
https://stackblitz.com/edit/nuxt-pinia-autoimport-repro2?file=nuxt.config.ts

### Additional information

`srcDir` Option: https://nuxt.com/docs/api/configuration/nuxt-config#srcdir

Auto-importing directories without any configuration is an attractive feature for me.
I hope it will be resolved.

Note: Sorry, I'm using Google Translate, so my English may be difficult to understand.

**Comment by suzukey** [comment]
https://github.com/vuejs/pinia/blob/3eee3352c9fcabd9043df39380328c393d94ac3b/packages/nuxt/src/module.ts#L97

My guess is that this line should be `srcDir` ([default: rootDir](https://nuxt.com/docs/api/configuration/nuxt-config#srcdir))
```diff
if (options.storesDirs) {
  for (const storeDir of options.storesDirs) {
-   addImportsDir(resolver.resolve(nuxt.options.rootDir, storeDir))
+   addImportsDir(resolver.resolve(nuxt.options.srcDir, storeDir))
  }
}

```

**Comment by posva** [comment]
I think what you are suggesting is the right direction. Worth doing a few extra tests
