### ISSUE TITLE
isAuthenticated is a reserved state property

### ISSUE THREAD

**Issue by ShuiTaCode** [posva/pinia#2448]
### Reproduction

https://play.pinia.vuejs.org/#eNqNVMFuGjEQ/RVrLwE12I3S5kABQasc0kNbNT1aqpbdAUy8tmV7gQjtv3dssxvYRlFOa4/fPL83ntljtjCG7mrIxtnEFVYYTxz42hCZq/WUZ97xbMaVqIy2nhxJ7eDRawukISurK3JFWaFr5cFS76644qrQyiFJBE07/GDI1YSlG5APNx4qI3MPuCNksqy914rMHlRhoQKFdx0TCRVuUfsNhkSB8LJpJiyhMXPCOprsOksqR1Vu6NZphZ6OgZyfDtDKmMRIiBmhRB4iPNt4b9yYMSR6pjEeSrJ1VNs1S3tw1Whp9d6h0S0SXbc0c0SyEnZea+lGuRGXlEWpEF+CFDtLFXimTMX+y5nf0c/0hkmxZHgRE6qEw+U1mDEqoXoPewudf6Q3n+gd+4CUPAtEDVcNlsk7fKOVWPeKVOjKCAn2p/EC3/CiWLmUev89xrytoZNVbKB4eiW+dYek9JcFLNkOzqz43K7Bp+P7xx9wwHV3WOmyloh+4/A3OC3roDHBvtaqRNlnuKj2Ib65UOs/7v7gQbnWVBAaqxHxsbTf3rD+IveW3p5V8aXtsYTtfJSwEip1/GlAukb7ErqeKzhEZJqSbpqm5CxzwDM8WKD4QqYIekuCGMOhwG4P67gYk8GQTGdkcNLbG5ZQn1zu82dHsErxirIt1N9XsHttn9q2a4bxg+bRpusq0s8aRB3D6ex0TqI3LYFKvUYrPTxxG13LkijtyRIuVEWi/rjjfyOxBu8Wf01WJee0rx8BeyElCR7apIuEHj5hUheENx3iC2XNP8A0uWk=

### Steps to reproduce the bug

1. Create a pinia store
2. Create a property called isAuthenticated
3. Create a getter in which you log the state.isAuthenticated
4. Use the getter somewhere in your app to rigger the console.log
5. See that the isAuthenticated property is always undefined
6. Change isAuthenticated to _isAuthenticated to see that spelling change solves the bug

### Expected behavior

isAuthenticated should be a valid name for a pinia store state property or should otherwise be listed as a reserved property name in the docs

### Actual behavior

isAuthenticated is somehow reserved and is always undefined (falsy)

**Comment by posva** [comment]
you can’t have a state and getter named the same. Just remove the getter if it doesn’t do anything as state is readable
