### ISSUE TITLE
`watch` in inactive Pinia instance keeps running after setting a new active Pinia

### ISSUE THREAD

**Issue by visualjerk** [posva/pinia#2453]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-nirjtr?file=src%2Fstore.spec.ts&view=editor

### Steps to reproduce the bug

- In the terminal run `vitest`
- observe the second test is failing, as `saveCount` is called twice instead of once

### Expected behavior

For the second test `saveCount` should only be called once, as only the watcher from the new Pinia instance should be triggered.

### Actual behavior

For the second test `saveCount` is called twice, once by the watcher from the Pinia instance of the previous test and once by the watcher from the new Pinia instance.

### Additional information

This happens, because the `effectScope` of the currently active Pinia instance is not stopped once a new Pinia instance is set as active, which results in the watcher being kept alive as well. However I am unsure if this is by design, in order to keep inactive Pinia instances up-to-date. In that case it would be helpful to offer a way to manually stop the `effectScope` of an inactive Pinia instance to avoid tests leaking into the following ones.

**Comment by posva** [comment]
This would be useful indeed

**Comment by posva** [comment]
I will wait a bit before releasing it but you can always manually copy the function to test it out

**Comment by visualjerk** [comment]
Big thanks for the super fast response and this new feature ❤️

**Comment by posva** [comment]
If you can try it out (by copying the function) to test in real world scenarios, it would be nice 😊

**Comment by visualjerk** [comment]
Tested the function and in our case (which is similar to the stackblitz example from above) and it works like a charm. Thanks again!

Are you open for a PR to add tests for this function? If so, I would be happy to create one.

**Comment by posva** [comment]
That would be great, yes! 🙌

**Comment by posva** [comment]
BTW, in your example stackblitz, using a global state is redundant with what pinia does. You might want to reconsider that usage in your app

**Comment by visualjerk** [comment]
`useGlobalState` in this example was used as a substitute for `useStorage`, which we use in our case to persist data across multiple tabs.

However without `useGlobalState` the watcher does not trigger in the first store instance. If it should, I can create a new issue for that.

**Comment by posva** [comment]
If you use `useStorage()` you should probably call it within the store (like any other composable). But I see how in that case the store needs to be disposed of (`store.$dispose()`) to stop its effect. Overall, I think stopping the active pinia on each test is useful

**Comment by visualjerk** [comment]
Here is the test PR: #2454
