### ISSUE TITLE
I'm was getting error on installing pinia from DevTools.

### ISSUE THREAD

**Issue by abrahimzaman360** [posva/pinia#2456]
### Reproduction

Ch

### Steps to reproduce the bug

Install Pinia from Devtools

### Expected behavior

Should Install Pinia and Pinia Nuxt Package.

### Actual behavior

Error in Modules

### Additional information

Fix by adding @pinia and @pinia/nuxt package.

**Comment by posva** [comment]
Open in the dev tool repo.
