### ISSUE TITLE
First parameter of getters should be the state

### ISSUE THREAD

**Issue by MartinMalinda** [posva/pinia#249]
The object in the first param in a getter used to be a state. Now (in 0.1.0) it seems to be the whole store, yet the TS type for it still is `DataState`. Readme suggests using `this` in getters but I still like the shorthand arrow functions:

```
getters: {
  admins: state => state.users.filter(user => user.role === 'admin'),
}
```

<img width="511" alt="Screenshot 2020-10-03 at 18 15 26" src="https://user-images.githubusercontent.com/9468793/94996523-783df080-05a5-11eb-9b7a-aae229e5fa39.png">

**Comment by posva** [comment]
I pushed a new test at 40d0996 but I remember it wasn't possible to type `this` and the first argument at the same time. On top of that, `this` can be typed with other getters while the argument cannot.

In my tests, `state` has type `any`, so not sure how you manage to get that one but I don't think there is a way to support both `this` and the argument types. If you want to give it a try or TS end up somehow supporting it, feel free to give it a try and open a pull request

**Comment by MartinMalinda** [comment]
I tried to do a quick hack of `G extends Record<string, (this: { state: S } & A & G, state: S) => any>` but it doesn't work well, maybe because `G` references itself there. It is indeed strange how `this` stops being inferred once an argument type is declared.

**Comment by posva** [comment]
I gave this a try to at least have the state as the first parameter but couldn't make all the existing type tests pass. It's on https://github.com/posva/pinia/tree/types/getters-state if anyone can help.

Ideally, one should be able to have an automatically inferred type for a getter like this:

```js
double: state => state.count * 2
```
