### ISSUE TITLE
An issue with Deno

### ISSUE THREAD

**Issue by bitsnaps** [posva/pinia#2490]
### Reproduction

Create a new Vue project using the Deno template, then try to replace Vuex with Pinia

### Steps to reproduce the bug

Hi,

This is obviously an issue with [Deno](https://github.com/denoland/deno/issues/20375) when using Pinia, but I'm just curious if Pinia is using any specific Node API where it can adhere to the Standard Web API in this case? if that's the case why it works with Vuex and not with Pinia?

### Expected behavior

A running project without an issue.

### Actual behavior

A working Deno project with Vuex (without using Pinia)

**Comment by posva** [comment]
> but I'm just curious if Pinia is using any specific Node API [...]?

Normally, no
