### ISSUE TITLE
$reset may not always generate rawStore

### ISSUE THREAD

**Issue by qz1543706741** [posva/pinia#2497]
### Reproduction

https://play.pinia.vuejs.org/#eNqdVU1rE0EY/ivD4iGhyW6T1B7SpFSlBz1YsR4XZLs7SSfuziw7s2lKyEGoVZFKQU9FL+JJoSKIta3in+km9eRf8J3ZbLJJ2toEQsi8H8/7Ps9Onm1rt3xfb4ZYK2sVgT3ftQReNilCFYc0lyuG/DZpxUjl4MjtgPgCcSxCH7kWrVdNTXBTgyzxfBYI1EYOrhGK1wULMOqgWsA8ZGo+ocQytSWJYjPKBWKAU0VtOZILGFBGmSyqLqNMG9kspKKM5lEnm5N5yxYEespxNUKE2gH2MBUZsUkgbNHtbJJDSMZ0BTE3B/NkqKNg5HdHbWAYqHf65vzw5O/Pg/S60fH37rtP0ZdjtV309AB1j752Xx2df3tvRLun0IOijzu9/d0hjZD3e6tp4hlTe8zlD1PLSaxsiriKQ3nSmRkmmYt1l9WhG+QSslcVx2yySwj2lgk0Lxvi1FALCTMKYtUEDoZqFSSgqaUgy3C8YMZ4X7qijFAhmX0jwHATLh2sslMOjXvGBs5Gtzgj3eIkXSiKnr04+33YfauuRg5Fu3vxriN46PzD5z/P93q/Ds9+nMTl0f7r3sFOfKVNurbRwLbQLc5JnWYUUvuy61+E6w8foHl9tafkHPeM8S3OpHZpRrVLY9NLidqJvKB0Wvj/qP1yL6X2hG7TyL8wkP9StafkHPdMql0xYlvtW6zYdjHiNvOxAz6sjpDRclrssHnP8vUGZxScW3kemIVKgA0PHHJguHKhTSF8XjYM8PFtXcWl8Te4zoK6EZ8x9/IbAdviOABs4JDArECl4eCmYMzlecsno5C2Q6HewS5pBjrFwqC+Z0z0rCzqN/WC4ZINAwYZhDq4NToGOvIO9q6DnpSuzOuFBX3RmANIU1P+DvYOMgnQjtZIfUwkm3k+cXGw5quXyYhYluuyrXsqJoIQD9ayN7H95IJ4g7fiTR/IZxo0pc0nOWEFdQzeLdOr6/dxS/p4kvSYE7pQfUXyIYbLFsod47LbIXVg7VSd2vaueuaE1h/x1ZbAlCek5KLJ264v7Z0rqA/XLenw3+ur2PkHoyrpag==

### Steps to reproduce the bug

![x24FgWzYrd](https://github.com/vuejs/pinia/assets/49976933/30d2653b-c384-4833-add6-6414cd0e6173)
![ZFC1iY9PLP](https://github.com/vuejs/pinia/assets/49976933/b44888eb-2c88-4788-9964-20d75cf8ab42)

### Expected behavior

whatever change opt before reset or not，pinia reset wiil always generate raw opt `count: 0`

### Actual behavior

if I assign opt before reset, store.count will be reset as assigned state

### Additional information

may deepclone raw opt in defineStore or cache raw opt and patch it before $reset handling newState

**Comment by posva** [comment]
You are supposed to pass the object directly to `defineStore()`. In a way, defineStore takes ownership of that object, so you are not supposed to touch it. Passing an object like that **and** changing it afterwards seems like an anti-pattern in general. You can't know if the library clones the object or not unless they specify in the docs.
