### ISSUE TITLE
storeToReadonly

### ISSUE THREAD

**Issue by lin52025iq** [posva/pinia#2509]
### What problem is this solving

store.ts
```ts
const countStore = createStore('count', () => {
    const count = ref(1)
    return {
        count: readonly(count),
        updateCount(value) {
            count.value = value
        }
    }
})
```

index.ts
```ts
const { count } = storeToRefs(countStore())

count.value = 2
```

在 `count.value = 2` 这里修改 count 的值，在浏览器的控制台中出现 `[Vue warn] Set operation on key "value" failed: target is readonly. `，并不会修改成功，这是符合预期的。
但并没有出现编辑器错误提示，也不会出现编译报错，不能很好的推断从 `store` 中获得的值的类型，而是都转成了 `ref`，在开发过程中可能很容易忽略从 `store` 中获取到的是一个 `readonly` 类型的值。

### Proposed solution

使用 `readonly` 的目的是确保这个值在除 `store` 外不会被修改，是否可以设计一个 `storeToReadonly` 的方法，使得在开发过程中能及时发现 `store` 的值不能在外部修改。
```ts
const { count } = storeToReadonly(countStore())

count.value = 2 // 无法为“value”赋值，因为它是只读属性。
```

### Describe alternatives you've considered

或者是否有办法可以在结构后保留 store 中 return 时的类型？

**Comment by posva** [comment]
You can't return readonly state, it must be writable. You can however use [a private store](https://masteringpinia.com/blog/my-top-5-tips-for-using-pinia#private-state-with-nested-stores) to hide state and return a getter in the actual store. `storeToReadonly()` can be written in userland. Note that most of the time you don't need to use `storeToRefs()` at all either
