### ISSUE TITLE
docs(fa): add persian documentation

### ISSUE THREAD

**Issue by Saman-Safaei-Dev** [posva/pinia#2514]
### What problem is this solving

Adding a Persian document will help Persian speakers learn better. Currently, many Persian language programmers still use vuex. I think that the Persian documentation will help Persian programmers to use pinia.

### Proposed solution

I want to add persian language to pinia docs. If anyone can give me a hint of how I get started I would appreciate it.

**Comment by posva** [comment]
Already in discussions
