### ISSUE TITLE
pinia running Browser extensions not work

### ISSUE THREAD

**Issue by IF-tiger** [posva/pinia#2561]
### Reproduction

no

### Steps to reproduce the bug

create Browser extensions project
use pinia in chrome-popup module
not work

### Expected behavior

Everything works fine

### Actual behavior

error

**Comment by posva** [comment]
If you want help, open a discussion and provide more information.

**Comment by IF-tiger** [comment]
> 如果您需要帮助，请发起讨论并提供更多信息。

ok
