### ISSUE TITLE
The document file "/interfaces/pinia.SetupStoreDefinition.md" is missing.

### ISSUE THREAD

**Issue by niceplugin** [posva/pinia#2577]
### Reproduction

none

### Steps to reproduce the bug

check the github repository

### Expected behavior

`/package/docs/api/interfaces/pinia.SetupStoreDefinition.md` file is not missing.

### Actual behavior

`/package/docs/api/interfaces/pinia.SetupStoreDefinition.md` file is missing.

### Additional information

There is no such file in the official repository.
However, you can view the document through a link on the official website.
I've searched the branch, but it doesn't seem like the file has been added or removed.

**Comment by posva** [comment]
This is normal. They are generated at build. Some were committed at some point as a backup but that's not the case and I haven't removed them yet
