### ISSUE TITLE
Composition API documentation

### ISSUE THREAD

**Issue by desvandev** [posva/pinia#2653]
### What problem is this solving

I have been trying to use most of the features with Composition API but I'm having a hard time.
Almost every example in the docs are using Options Api.
As far as I can tell Pinia is very limited in functionality when using Composition API, at least that's my impression.

### Proposed solution

Doc examples with Composition API, including plugins.

**Comment by posva** [comment]
It's indeed lacking and it's planned in #829.
I need time and funding to port some of the content of https://masteringpinia.com to docs but Mastering Pinia will always have more content and in-depth and practical explanations. I think it have the content you are looking for 😃
