### ISSUE TITLE
Composing Store lose typescript type

### ISSUE THREAD

**Issue by defghy** [posva/pinia#2664]
### Reproduction

placeholder

### Steps to reproduce the bug

In defineStore composing function, type is right
![image](https://github.com/vuejs/pinia/assets/5386958/6e832c87-554c-4729-b6d9-9c9f60c54042)

The ReturnValue of defineStore(), type transfer to specific object, which is not right
![image](https://github.com/vuejs/pinia/assets/5386958/16f64f46-53db-49d6-819f-76da6bccf2af)

I cannot use the object as `BoardData`
![image](https://github.com/vuejs/pinia/assets/5386958/ed120129-dd8c-481e-acb8-0d499fe93b27)

### Expected behavior

`BoardData` type not change.

### Actual behavior

why `BoardData` transfer to specific `{ boardId: ''...}` ?

**Comment by posva** [comment]
Open a question with the code in discussions or on Discord if you want help
