### ISSUE TITLE
Nuxt3 useRoute update

### ISSUE THREAD

**Issue by gyxoBka** [posva/pinia#2670]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-h3pnwf?file=stores%2Flocation.ts

### Steps to reproduce the bug

1. Go to Other page id 1
You'll see that all id's are 1

2. Then go to Main Page

3. Then go to Other page id 2
You'll see that all id's are 2 except first. Location Outside wiill be still 1

### Expected behavior

The query should be updated when router defined outside a method

### Actual behavior

it is updated only when declaring a variable inside the method during auto-import or when importing from vue-router

**Comment by posva** [comment]
This seems related to Nuxt, not pinia. BTW, the _inside_ usage is not correct, `useRoute()` shouldn't be called within methods (like any composable)
