### ISSUE TITLE
current use vscode vue3.2+pinia project, Mouse click can not jump

### ISSUE THREAD

**Issue by web-shenjin** [posva/pinia#2671]
### Reproduction

current use vscode vue3.2+pinia project, Mouse click can not jump

### Steps to reproduce the bug

![image](https://github.com/vuejs/pinia/assets/52124289/0e59d4f1-ee88-414a-8ea1-7f7e8a1b729c)
Clicking on the pinia method for that login does not enter？
how resolve?

### Expected behavior

Clicking on the pinia method for that login does not enter？
how resolve?

### Actual behavior

Clicking on the pinia method for that login does not enter？
how resolve?

### Additional information

Clicking on the pinia method for that login does not enter？
how resolve?

**Comment by posva** [comment]
Cannot reproduce with latest TS and other packages
