### ISSUE TITLE
After entering the route, the first v-model binding value cannot be captured and updated.

### ISSUE THREAD

**Issue by chttiu** [posva/pinia#2678]
### Reproduction

https://codesandbox.io/p/live/e6de1200-2ca6-4ca2-87f9-bc45bbb2a5c6

### Steps to reproduce the bug

1. After entering the routing, after binding the input to v-model in component A

 2. In the component B setup function, modify the state in the pinia store

3. Component A input cannot display the updated status.

### Expected behavior

 Component A  Show the updated value.

### Actual behavior

 Component A still shows the value before the update.

### Additional information

1. If you change the order in their template, it can work correctly.
2. In the template, it is correct to display the status in the pinia store.

**Comment by posva** [comment]
This will happen without pinia too. The workaround/fix: change the value within onMounted.

**Comment by chttiu** [comment]
> This will happen without pinia too. The workaround/fix: change the value within onMounted.

Thank you for your reply.

**Comment by OuYangJie167** [comment]
@posva I am curious why this is, is it a problem with Vue itself?

**Comment by posva** [comment]
I can't know anymore but probably related to rendering. If you are also facing this, change the value within onMounted or after the initial render

**Comment by OuYangJie167** [comment]
> I can't know anymore but probably related to rendering. If you are also facing this, change the value within onMounted or after the initial render

Yes, I have encountered it too, but it makes me confused. Thank you anyway.
