### ISSUE TITLE
Could add a destructuring method contains actions and non reactive property?

### ISSUE THREAD

**Issue by Sorryhx** [posva/pinia#2680]
### What problem is this solving

In my opinion, it's messy when I want to destructure acitions  from  store at the same time as state. Because, I need to add a alone constant for `storeToRefs ` and action destructuring. Why not destructure from `useXXXStore` direcly.

### Proposed solution

const {  aciton, reactiveState } = someDestructureMethod(useXXXStore())

**Comment by posva** [comment]
Most of the time, it’s shorter to my déstructure.  This would add  new method to reduce from two lines to one. It’s something that can be built in user land for projects that need it thought
