### ISSUE TITLE
disposePinia missing types

### ISSUE THREAD

**Issue by roydukkey** [posva/pinia#2698]
### Reproduction

https://play.pinia.vuejs.org/#eNqNU0Fu2zAQ/Aqhix3EJhO4SAHXDtwWOaSHNmh61EWW1g4dckmQlCPA0N+7Im1ZSYsgN3J3dnY4xByyr9byfQ3ZPFv40kkbmIdQW6YK3C7zLPg8u81RamtcYAdWe3gMxgFr2cYZzUZclKbGAI4HPxoAK+mt8fAgURY92Ha30ZcccywNetoVuZY97fgix4VIQmgtXQJoq4oAdGNssa5DMMhWpZLlM8mL8xwvL0nlPZYONCBtPyRijqxtFyINEcFCDNiySZbETnVh+c4bJA8O3Zb82KCnz1msdLWovavkmYhnDl5P1868eHr8jsCTE3RFhooK9sEY5aeFlWnsKQTr50KUFRK+AiX3jiMEgVaLf2ZWN/yGXwsl14IWCYkVNK/X0MS0Av0R9hN0dcWvP/HPkXU/O5LqjrUjbXNsyZbg6XM2cvvGlNJoKxW4XzZI+rxX5hRKmZcfsRZcDb3E8gnK5//Ud75Jqh8ckH17GDwrFG4LIbXvHn9CQ+e+qU1VK0K/0/wN3qi605hg32qsSPYAF9Xexz+WuP3j75oA6E+P6oRGNyI+2vz9naef5c74bODiORZk4TkWsJH4JkIpFYPsONj0TdpOrRyhic0Umz6FyyHheHTcOZqw8QVb3iaRaQQJS7zjK0pYV3WUcoe0jDJCgqmatX8BmYJeeQ==

### Steps to reproduce the bug

```
import { disposePinia } from 'pinia';
```

### Expected behavior

Should be able to import `disposePinia`.

### Actual behavior

![Screenshot 2024-06-18 at 16 01 41](https://github.com/vuejs/pinia/assets/1509616/995437ce-ef53-4249-8225-152fa5733ce9)

**Comment by posva** [comment]
It’s just not published yet

**Comment by PindaPixel** [comment]
I have a an interval that is set and cleared through `onScopeDispose` (`useCookies` from `vue-use`: https://github.com/vueuse/vueuse/blob/main/packages/integrations/useCookies/index.ts#L63) in a setup store. In tests the composable often still tries to access document after the test, meaning the interval wasn't properly cleared. Will calling `disposePinia` in `afterEach` make sure the store's scope is stopped before the test environment is torn down?
