### ISSUE TITLE
Disable console log "x store installed" messages

### ISSUE THREAD

**Issue by martinszeltins** [posva/pinia#2702]
### What problem is this solving

I can't find anywhere how to disable these console.log messages:

````
🍍 "session" store installed 🆕
🍍 "app" store installed 🆕
🍍 "printer" store installed 🆕
````

It would be nice to be able to turn these notifications off about installed stores. They are just spamming my console.

### Proposed solution

Perhaps a config options to turn them off?

**Comment by posva** [comment]
IIRC there is an option in the devtools options for it. If not, i will add this to the list of the devtools issue
