### ISSUE TITLE
ref takes Object inheriting Map and returns Map object

### ISSUE THREAD

**Issue by jmarshall9120** [posva/pinia#2704]
### Reproduction

https://play.pinia.vuejs.org/#eNqNVG1r2zAQ/ivCX+xAIq90dBCS0L10sEG3se7bPIprXVJ18klIsput5L/vJMeum4VSCM757rm75x759JC8NYa3DSTzZOEqK41nDnxjmCpxsywS74pkVaCsjbaePbDGwZXXFtiOra2uWcrzSjfowXLv0hFQ42X0ix5ITSheYKXRUZNYZDnUyyYhNiRl2WS5eiiQdUDuwflrC+vrtlTNHryLzwIXeUecaNKLh9qo0gO9MbYQsl0t8vAMuFEsmSYd1VldGn7nNJICsWGxD9DgcxY9wWckyjJ4iiSPNgdXz26svnc0+h2Bpz30nCbNBbRea+VmpZFd2q33xs3zvBJIeAFKtpYj+BxNnf+Xc37Gz/hJruRNTo1yiQK2T9tQxkxA/ZLqPfT8FT95zd/Equ3pvmgdqoaiO5KUZPGOTmgtNweiVLo2UoH9arykE3wiTqmUvv8cfd42MFCsbqH6fcR/57Yd628WSL4WRmP50m7Ad+GLqy+wJXsI1lo0itDPBL+D06oJHDvYuwYF0R7hIttP8Ywlbn64i60HdP1QgWhUI+KjzO+fGf2R7ik/Han4uBQk4bAUAtYSDxYofk3jzaHPfAgOS6NK59iH0peXpWE0N6BwLNiRSdwp21RUOOOcEyc3L/HPz1+TnqlrDAwxWpxIlLG11tlkzlotRY8MtbQCrvQmSz9qzSoSDASlpn0e/QqEbeTbrfNwLSzHM2bpXoZ0yrIJW65GbBkSlkZd7IdaZQj3/YTZJO428WuwCqKzwwvgGFmcs3SKkeRhhMc0CrO9eRzl5F9IWQAF6zgmShYadVavSfizdHNapCPE6QHhqBpBk90/QvnTzA==

### Steps to reproduce the bug

Check the console output and the typescript errors in the reproduction. 

### Expected behavior

Doing this:
```
class DataObject extends Map{
    constructor(){
        super()
    }
}
const MyRef = ref(new DataObject())
console.log(MyRef.value)
```

Should return a `DataObject` not a `Map` object.

### Actual behavior

The passed in `DataObject` is lost an a `Map` object is returned.

**Comment by posva** [comment]
[You are just missing a `.value`](https://play.pinia.vuejs.org/#eNqNVG1r2zAQ/ivCDOxAIq90dBCS0L10sEG3se7bPIprX1J18klIspMt5L/vJL/UzUIZGFu6e+7uuUc+7aM3WvOmhmgeLWxhhHbMgqs1kzlullnkbBatMhSVVsaxPast3DhlgB3Y2qiKxTwtVI0ODHc2HgEVXgd72QOpCPkzLBRaKhKSLId8ycT7hqAkmSxX+wxZC+QOrLs1sL5tcll34EN4Z7hIW+JEkzYOKi1zB7RjbFGKZrXftzleWEd2djgsUm/2gSNwNI1a7rMq1/zBKiRJAoOsc5AScxYs3qYFitxbsigNaw62mt0ZtbWkxQOBpz30klpPS2icUtLOci3asHvntJ2naVEi4UuQojEcwaWoq/SfmMsLfsHPUinuUiqUCixh97QMRcxKqP4new+9fMnPXvHXIWtz3iWtfFaf9EAakyzO0pGtxeZIlEJVWkgwX7QTdKRPxMmlVNtPweZMDQPF4h6KXyfsD3bXsv5qgORrYNSWy80GXOu+uvkMO1oPzkqVtST0M85vYJWsPccW9rbGkmiPcIHtx3DGAjff7dXOAdq+KU80qBHwQeZ3z7T+SPecn49UfJwSknCYkhLWAo8mKvxN41Gi/35wDlMkc2vZ+9zl17lm1DdgaZlfByZhyExdUOKEc06c7DzH3z9+TnqmttYw+GiSAlHG1kolkzlrlCh7pM+lJHCpNkn8QSlWkGBQUmjcx9GTIewC33a+h3tiOe4xiTsZ4ilLJmy5GrFlSFhqddE1tUoQtn2HySQMO/GrsfCis+Mb4RRZnLN4ioHksYeHMHKzbnkaZcUfiNkACvvTyCCcL9chw77Xx38MXasG6ThxekQ+KEjQ6PAX8JPfEg==).
Note that if you do SSR, you will need a custom serialization to handle custom types with devalue: https://github.com/Rich-Harris/devalue (in Nuxt payload plugins). BTW I go through both in depth in my [Mastering Pinia course](https://masteringpinia.com/lessons/complex-state-in-nuxt-with-payload-plugins)

**Comment by jmarshall9120** [comment]
@posva - The missing `.value` is a typo on my part.  I see with it, the reproduction works, but my local repo still does not.  Very inconvenient typo to make the reproduction and my actual project line up when they don't.  I'm gonna see if it is the devalue issue.  It could be that the parent Map serializes and deserializes back to a map.  That's a good thought.  Will test that now.
