### ISSUE TITLE
Cannot find module 'pinia/dist/pinia.mjs'

### ISSUE THREAD

**Issue by suityou01** [posva/pinia#2720]
### Reproduction

Reproduction

### Steps to reproduce the bug

Install nuxt
Install pinia using the instructions on https://pinia.vuejs.org/ssr/nuxt.html
Try to start nuxt
Get error ERROR  Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs'

### Expected behavior

Nuxt starts

### Actual behavior

Nuxt doesn't start

**Comment by Janmuixi** [comment]
I couldn't reproduce the error, I followed these steps:

· npx nuxi@latest init <project-name>
· added the following on package.json
`"overrides": {
  "vue": "latest"
}`
· npm install pinia @pinia/nuxt
· npm run dev
