### ISSUE TITLE
Tree-Shaking does not work when using multiple stores in Nuxt

### ISSUE THREAD

**Issue by serkodev** [posva/pinia#2738]
> [!NOTE]  
> I’m not sure if this issue is related to Pinia, Nuxt, Vite or Rollup, but since the problem occurs specifically when using `defineStore` exports, and not with other composables or exports so I’m opening the issue here.
> 
> Please let me know if I should open it issue on the right repo.

### Reproduction

https://stackblitz.com/edit/github-dylldh?file=app.vue

### Steps to reproduce the bug

1. Go stackblitz link above, run `nuxt generate`
2. Go `./output/_nuxt/Dz77aYJ1.js`
3. Search `foofoofoo`
4. If found, that means the store is not tree-shaken

<img width="641" alt="pinia" src="https://github.com/user-attachments/assets/78bdd212-c1f0-438c-80c2-5bd86374eaa8">

### Bug Description

When using Pinia in a Nuxt project and creating more than one store, tree-shaking does not work as expected. Here's an example to illustrate the issue:

```ts
// store/foo.ts
export const useFooStore = defineStore('foo', () => ({ foo: ref('foofoofoo') }));

// store/bar.ts
export const useBarStore = defineStore('bar', () => ({ bar: ref('barbarbar') }));
```

```html
<!-- app.vue -->
<script setup lang="ts">
if (false) {
  // cannot tree-shake
  console.log(useFooStore());
  console.log(useBarStore());
}
</script>
```

After running `nuxt generate`, both the `foo` and `bar` stores are bundled into the output, even though they are inside a conditional block that should never run.

However, if I use only one store within the `if (false)` block, tree-shaking works as expected:

```html
<!-- app.vue -->
<script setup lang="ts">
if (false) {
  // can tree-shake
  console.log(useFooStore());
}
</script>
```

In this case, the unused store is successfully tree-shaken and not included in the bundle.

### Expected behavior

Tree-shaking should exclude unused stores from the final bundle, even when multiple stores are defined.

### Actual behavior

When more than one store is defined, tree-shaking fails to exclude unused stores, resulting in unnecessary code being bundled.

**Comment by posva** [comment]
Yeah, this shouldn’t be related to pinia itself, rather to the library doing the tree shaking. It could be mixed to how the auto imports are done or could even be a limitation of the lib handling the minification
