### ISSUE TITLE
docs: provide a `DefaultTheme.AlgoliaSearchOptions['locales']` template for translators

### ISSUE THREAD

**Issue by nazarepiedady** [posva/pinia#2744]
### What problem is this solving

I believe that this feature will help to better the translators' work, because this will allow serving a translation that is paring the Chinese version that goes a little beyond translating the text of buttons and interface's instructions.

### Proposed solution

I think we could provide a version of the object below with English content to give a starting point for those who are dedicated to translating the documentation content:

```ts
export const zhSearch: DefaultTheme.AlgoliaSearchOptions['locales'] = {
  zh: {
    placeholder: '搜索文档',
    translations: {
      button: {
        buttonText: '搜索文档',
        buttonAriaLabel: '搜索文档',
      },
      modal: {
        searchBox: {
          resetButtonTitle: '清除查询条件',
          resetButtonAriaLabel: '清除查询条件',
          cancelButtonText: '取消',
          cancelButtonAriaLabel: '取消',
        },
        startScreen: {
          recentSearchesTitle: '搜索历史',
          noRecentSearchesText: '没有搜索历史',
          saveRecentSearchButtonTitle: '保存至搜索历史',
          removeRecentSearchButtonTitle: '从搜索历史中移除',
          favoriteSearchesTitle: '收藏',
          removeFavoriteSearchButtonTitle: '从收藏中移除',
        },
        errorScreen: {
          titleText: '无法获取结果',
          helpText: '你可能需要检查你的网络连接',
        },
        footer: {
          selectText: '选择',
          navigateText: '切换',
          closeText: '关闭',
          searchByText: '搜索供应商',
        },
        noResultsScreen: {
          noResultsText: '无法找到相关结果',
          suggestedQueryText: '你可以尝试查询',
          reportMissingResultsText: '你认为该查询应该有结果？',
          reportMissingResultsLinkText: '点击反馈',
        },
      },
    },
  },
}
```

### Describe alternatives you've considered

I believe the solution proposed is good enough to be considered to be implemented.

**Comment by nazarepiedady** [comment]
@Jinjiang, what you think about the point I raised? It is not a big thing, but I believe to be worth of consideration.

**Comment by posva** [comment]
Feel free to add it to the contribution guidelines

**Comment by Jinjiang** [comment]
Agree. I think it's a good idea to provide a template for translations.

**Comment by nazarepiedady** [comment]
> Feel free to add it to the contribution guidelines

Of course, I will edit the contribution guidelines soon. I just created the issue to know what you people think about this improvement for the documentation.
