### ISSUE TITLE
Provide/inject in @pinia/nuxt broken

### ISSUE THREAD

**Issue by tdekoning** [posva/pinia#2745]
### Reproduction

https://stackblitz.com/edit/github-ptqlwv-b7gmky?file=app.vue

### Steps to reproduce the bug

Just load up the application and see the difference between the injected value from the store and the directly injected value in the component.
The value injected into the store is empty, while the component has the correct value

### Expected behavior

I expect provide/inject to work in pinia stores.

### Actual behavior

The injected value in the store is empty.
Also note the `[Vue warn]: injection "myKey" not found.` warning in the console.

### Additional information

This is using the @pinia/nuxt package inside of a nuxt 3.12.4 application.

This injection pattern used to work with nuxt 3.11.2 and @pinia/nuxt 0.5.1 and pinia 2.1.7

**Comment by bperel** [comment]
Reproduced on vanilla Vue as well:

https://stackblitz.com/edit/vitejs-vite-l2tkb3?file=src%2FApp.vue

**Comment by rhelling** [comment]
+1 have the same issue

**Comment by posva** [comment]
This is the intended behavior, it was broken before. See https://github.com/vuejs/core/issues/11602

**Comment by tdekoning** [comment]
@posva thanks for the explanation, I wasn't aware of that.

**Comment by bperel** [comment]
@posva Is there a place in the docs where instructions about how to achieve provide/inject using the app instance can be performed? I tried the following but [it didn't work either](https://stackblitz.com/edit/vitejs-vite-l2tkb3?file=src%2FApp.vue): 
```javascript
getCurrentInstance().appContext.app.provide('myGlobalKey', 'my-global-value');
```

**Comment by posva** [comment]
yes, [that works](https://play.pinia.vuejs.org/#eNqNVMFu2zAM/RXBlzhoIrXo0AFdUmQriqEbsA3rjr44NpMqlSlBot0UQf59tNwkbjIUu1nk4+Pjk+hN8tk52dSQXCeTUHjtSASg2gmT43KaJRSy5CZDXTnrSWzEEui29h6Q7jFQjgWIrVh4W4kBswx6yDrAA1l/yEtV2BoJvKTAwAxPudKhzJ27tYxaU/spnbeNLiEdVC9fjZ3n5ju8DEaCj+NlPI+b3HDj4aeWsbBMJEJsO90rSIcZTlQ3Hc/CB4LKmZyAT0JM5jWRRTErjC6eeOZYL/HsjEe/x8JDxRLFZtMRSxTb7UR1RUwwUT22ZJR0Boyr3MlVsMjGbtou2WuC/bwWMdLGnEadt5EsUfFbQqjGc2+fA/u0YvBoB52xv6qEhqw1YZw73ZU9ErlwrVRRIuNLMLrxEoEUukqd1Myu5JW8UEbPFTdSGktYv23DFeMSqv9h30Fn5/Lig/wYWZvLV9KqZW1Jtxlu2RYKfDkLvTwypbCV0wb8T0eaL++NObkx9vlbjJGvYS+xeITi6R/xVVh3qn95YPsa6I1Fuefn1qXvHn7w8+olK1vWhtHvJH9DsKZuNXawLzWWLLuHi2rv4x1rXP4Jd2sCDLuhWqHRjYiPNt++M/pB7qW87Ll42CC2cL9qJSw0Hm1bfE39ffSwGAmNKyjoaGUzhHUEdeuzX9xpnzgdvPbm7UuHYnrTiW1LrAFp7DLtyE9WFS2JBdeWgyEvYldCApmeJaXnHGujnv86HlknrxfPytFk+xf765Hg). I wouldn't do it that way though, I would only use `app.provide()` directly after creating the app.
