### ISSUE TITLE
Memory Leak - Nuxt3

### ISSUE THREAD

**Issue by dissy123** [posva/pinia#2762]
### Reproduction

https://github.com/dissy123/nuxt-pinia-memory-leak

### Steps to reproduce the bug

The Repository i posted is just a blank Nuxt3 Project, i have added a Pinia Store like in the Documentation here:
https://nuxt.com/docs/getting-started/state-management

Have i done something wrong? Or is this a memory leak?

The Strings from the json objects are stored each request in the HEAP but not deleted again. 

I tried it without the Code of the Store and no memory leak happens. 

```
pnpm i

pnpm build

node --inspect .output/server/index.mjs

ab -n 50 -c 10 "http://localhost:3000/"
```

Sorry i am a little bit confused already hunting this for a few weeks now.

When you comment out the line in app.vue

`await useAsyncData("todos", () => store.fetchIconsData());`

no memory leak is happening!

### Expected behavior

no memory leak

### Actual behavior

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/d8e5a3b9-72d2-4d91-a707-a21ef5c45045">

**Comment by henk23** [comment]
Can confirm. Memory is slowly filling up.
Between each Snapshot I ran

- 700 requests
- garbage collection

Looks like roughly 20 MB memory increase per 700 requests.

![leak](https://github.com/user-attachments/assets/467a9467-7997-4d7c-98aa-dafe66dbc324)

Is this a leak? Or is there a restriction like "You can't use fetch inside a store when in SSR"?

**Comment by posva** [comment]
Given that the method is from Nuxt, please open a discussion or issue in Nuxt.
~~The usage doesn’t seem wrong at first glance~~ It needs [callOnce](https://nuxt.com/docs/api/utils/call-once#usage)

**Comment by TheAlexLichter** [comment]
I wonder if the same can be observed when not setting pinia state.

Also, `useAsyncData` should not be used to trigger side effects. `callOnce` is preferred when working with pinia stores and e.g. fetching data "once".

(Though @posva I think there might be some room for improvements to have sth. similar to `useAsyncData` but for pinia stores, but that's a different topic.)

**Comment by posva** [comment]
Does the leak disappear with `callOnce`? If so, adding this to docs would be enough. I think we talked about this with Atinux

**Comment by dissy123** [comment]
hey i also tried it with callOnce the leak is also there!

I also tried it with https://vueuse.org/shared/createGlobalState/ and it also didn't change. 

I also tried useFetch when fetching and $fetch

**Comment by danielroe** [comment]
If the memory leak can only be reproduced with pinia then it is probably something to be tracked here. It could be an issue with the Nuxt module implementation.

I’ll take a look, but if you could try to reproduce without pinia that would be helpful too.

**Comment by dissy123** [comment]
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/b097e294-5a5d-478e-9ba8-b1e21538013f">

https://github.com/dissy123/nuxt-pinia-memory-leak/tree/without-pinia

yes it also happens without pinia!

when just using useAsyncData haven't tried callOnce now

**Comment by danielroe** [comment]
The issue is that you are logging those values. Because they are logged to the devtools when you are inspecting the server, they can't be GCed. Removing your `console.log` statement removes the 'memory leak'.

**Comment by dissy123** [comment]
omg... okay never thought about that... true... 
sorry!

thanks for pointing that out!

**Comment by danielroe** [comment]
Here's a reproduction with `pinia` + express (and without Nuxt) - it does seem to leak: https://github.com/danielroe/pinia-ssr-repro.

Steps to reproduce:

```
pnpm i
node --inspect server.js
ab -n 3000 -c 50 "http://localhost:3000/"
# GC + snapshot from devtools
ab -n 3000 -c 50 "http://localhost:3000/"
# GC + snapshot from devtools
```

**Comment by posva** [comment]
I will have to take a deeper look later this month or in October. Feel free to take a deeper look in the meantime

**Comment by dissy123** [comment]
hey guys, sorry the leak i had in my bigger project was in nuxt-booster, it is duplicating the pinia store on each request (the snapshot looked like the one in the reproduction with the console.log ;) ), so i thought it would have to do something with pinia ;) ! 

see here:
https://github.com/basics/nuxt-booster/issues/1121

**Comment by PanMisza** [comment]
For the moment I found out that this array keeps growing with every request:
https://github.com/vuejs/pinia/blob/df80a5e7e065cb7737f0e7149060db17845d8085/packages/pinia/src/createPinia.ts#L44

**Comment by PanMisza** [comment]
It looks like the memory leak is caused by this: https://github.com/vuejs/pinia/blob/df80a5e7e065cb7737f0e7149060db17845d8085/packages/pinia/src/createPinia.ts#L61
Here is how it looks in dist files:
```js
if ((((process.env.NODE_ENV !== 'production') || (typeof __VUE_PROD_DEVTOOLS__ !== 'undefined' && __VUE_PROD_DEVTOOLS__)) && !(process.env.NODE_ENV === 'test')) && typeof Proxy !== 'undefined') {
        pinia.use(devtoolsPlugin);
    }
 ```
 After commenting out `pinia.use(devtoolsPlugin);` on my env, memory leaks are gone.
 As a temporary fix on your environments you can run app with `NODE_ENV=production`.

**Comment by posva** [comment]
That's interesting. Devtools shouldn't be use in production besides for inspection, so it's expected to remove that part when building for production. Usually, the code is stripped out when bundling for production. I tested with CJS and esm and it seems that the memory leaks are internals (weird) when using `NODE_ENV=production`. So this doesn't seem to be a problem

![Screenshot 2024-09-06 at 09.45.20.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2024_09_06_at_09_45_20_313c7a18aa.png)
