### ISSUE TITLE
pinia action is not dispatched properly

### ISSUE THREAD

**Issue by stavrosdro** [posva/pinia#2768]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-8cwfty?file=src%2Fstores%2FcounterV2.spec.ts

### Steps to reproduce the bug

- open a new terminal and run `npm run test`
- there are 2 failing tests

### Expected behavior

- I should be able to put a spy on a store action and understand when this action is called.
- I should be able to subscribe with `$onAction` and execute my callback when the logger action is dispatched.
- I expected option stores and setup stores have the same behavior when action1 dispatches action1 (both actions live in the same store)

### Actual behavior

When action1 dispatches action2 (and both actions are in the same store) I cannot:
- unit test that action2 is called
- execute a callback with `$onAction`

### Additional information

I made a workaround to make the behavior of setup store and option store equal, I don't know if it is correct, but it makes a lot of sense. Check lines 10, 11 in the file `counterV2.ts`

**Comment by posva** [comment]
This is a spy limitation. You can find other code organizations to get around the issue but it's inherent to function closures in JS

**Comment by stavrosdro** [comment]
Ι searched a lot and didn't find any other workaround. Is my approach correct? Can you see any potential issues?

**Comment by stavrosdro** [comment]
@posva the `$onAction` is not working as well. Is it intended?

**Comment by posva** [comment]
@stavrosdro https://github.com/vuejs/pinia/discussions/1400#discussioncomment-10134368
