### ISSUE TITLE
incorrect types for nested refs in storeToRefs with Vue 3.5

### ISSUE THREAD

**Issue by Glandos** [posva/pinia#2769]
### Reproduction

https://play.pinia.vuejs.org/#eNqNVU1z2jAQ/SsaXyAMSGFI0xkKDG0nh/aQdpIcfTH2AqLWx0gyoUP5711Lxqg0ZPDJ2n2772l3vd4nn7Wm2wqScTKxueHaEQuu0qTM5GqaJs6mySyVXGhlHNmTysKzUwbIgSyNEqRDWa4q6cBQZzsR0NaoF/UES9tiNZc8Q1AqcyUtMvlM0zZp9yaVrNdLZVcbpcG43zeIyVxlx2SfSoIPHxNZiQWYT+G8ic4H8ucqWCp7LEV+ZKQhfS3JEx91BU4UP7kmYT+irWOCp98gZqeQt53X6sY+1MKDxrrCtUos7jQudvdUTKzmhIWmYigeHAhdZg7wRMhkUTmn5OxRuTWXqwlrznVQBEz6SejpQGSabqySOCpebdo4cELa9qQJzlJ9TpO1c9qOGcsLiWEFlHxrqATHpBZsjjBmcG64gEGhxHxEP9A7VnDrYjMFKwYLo14tztcGifoRDUPjFszAgCzAgLmW9iwspj5zXab3kxwImX+/DPWcBWydUqUdZJpfqzOOmd/TezpkJV8wJGIc9e3+K8igAHFN9iN0fkuHd/Sjz7odNUlFnbVOip/JAZvvLM7bkq/OWp8roXkJ5od2HOfxnxHIylK9fvc2ZypoJeZryH+9Yd/YXVD904DvQHQtl5kVuOB+eH6EHb63TqGKqmzG7YLzCawqq1pjgH2pZIGyI5xX+81PMn4GL/Zh50Da46Vqob4aHu/L/PWdq5/kjugoquJpR2IJ2x1ZwJLLs3163JEtyMCydSK7X5+w886wCdqVPI0TdjsNZ6dPujdkOgsiQwhHLObt3uKKONo2jW2ItpO1WTLBted9sjk0foO/CSOjPYQ3RVdy+Aty8yL7

### Steps to reproduce the bug

Using `storeToRefs` returns a type with both a `Ref` and `UnwrapRef`.

### Expected behavior

It should only returns `UnwrapRef`

### Actual behavior

Both are returns, and Typescript throws some errors.

### Additional information

Maybe linked to #2767 

Maybe caused by https://github.com/vuejs/core/pull/11442

**Comment by posva** [comment]
Fixed with 623e5a0
