### ISSUE TITLE
storeToRefs with nested reactive State with provided generic

### ISSUE THREAD

**Issue by Flashantik** [posva/pinia#2784]
### Reproduction

https://codesandbox.io/p/devbox/nostalgic-babycat-6pjz9l?workspaceId=5fdcd9ef-08c0-4212-af67-1efc2f3fec23

### Steps to reproduce the bug

open app.vue

### Expected behavior

no typescript errors

### Actual behavior

This comparison appears to be unintentional because the types 'number' and 'Ref<number | undefined> | undefined' have no overlap.ts-plugin

### Additional information

Related #2659.

Typing (and typecheck) still does not work if generic is passed to reactive. 

```ts
export const useSecondStore = defineStore("secondStore", () => {
  // if generic provided break typings
  const state = reactive<{ data?: number }>({
    data: 2,
  });

  return {
    ...toRefs(state),
  };
});


const { data } = storeToRefs(secondStore)

data.value.value
```

**Comment by posva** [comment]
The type of `data` being _possibly not_ defined makes the state possible not there, but that's not a correct type for pinia as the type should always be defined. The correct code would be:

```ts
export const useSecondStore = defineStore('secondStore', () => {
  // if generic provided break typings
  const state = reactive<{ data: number | undefined }>({
    data: 2,
  })

  return {
    ...toRefs(state),
  }
})

const { data } = storeToRefs(useSecondStore())

data.value
```

Note the `data: number | undefined` instead of `data?: number`
