### ISSUE TITLE
Common state between stores is lost if type is different

### ISSUE THREAD

**Issue by Q16solver** [posva/pinia#2785]
### Reproduction

https://play.pinia.vuejs.org/#eNqtVUtv20YQ/isDXkgDElnXRQqokmMnTdH2kBa2L0GYA0WOxLXIXWJ3SSkQ9N8zu8un/EgOsSGC3Pnmm8fO4+jdVlXY1OgtvKVKJas0KNR1BUXCt6vY0yr2rmPOykpIDUeoFd5rIRFOsJGiBD+MUlFzjTLUyp8C3zvBbUGPF5Ss7ExTGeiDuMON6hRir2KcJbEX85ingisN9MyYZoIvYC1EgQmHFWhZ4x9PEEnhrK+GI3jbRxJcwOJZb4MLoooiuF0XCFpAhhpTTQ7VTKt3idoh5SopSfa1Qotc1xq40LBOOP0r2OcszYEpkLgBxkFwdNFBwjPYS6YTw52Ksqo1Zh0sIY4cZRfHcWJy1rOfKKBRroLzeI37y8hdKl0hfWgsqyLRSF8Ay4w1159ELVt64jX8CzhODcLptIwMtlOCZs42VBqtH2GBfKtzWyZAf5b377KcATO1hKWCr6KGPGnQUE+1iLw/gT8F9zUUbEcpzbF8O5glVsqtpnu7SQuW7gbrlANfSKpV9MmDO6T4UhwugJEJJ1bLyFG4OCYRXX+kS0Mu6m3eqY6MPzE9zk5Y1SoPfKflX5APt1nWkYxMLqNR8r2Z56p9XiZV+KgEp/Y7GltxK6Cuo4twoffFv6DXyL6HqMr5Woq9ou55JPCsg95QL0cZNpp6Qs2Tijm1XOtKLaIozTjhMyxYI0OOOuJVGT3RuXkTvgkvo4KtIzIUMZ7hYWqGNOYZlj/C3kFvfgkvfwt/t6zNVUtaGlZDeor5idKiFVXxhm3PkmI6hBUo/6tMfU+TkxSF2P9rz0z79y6mOaa7Z84f1cF5/b9ESl+Do7B0IreonfjD/Uc80HsvLEVWF4R+RXiHShS18dHB3tU8I7dHOOvtP/aOGd8+qA8HjVx1QRlHbTYs3qb5/SuhD+5ehVejLA4TmVLYz9UMN4yfTW9bTePhSyNoNgykDkZ+ECjmeLAwN5f6VbAaUwd+a92fAY3W1bVz16lM5srKGAs+d70zAz+pqgLNy3DU9vYXM8w6lqH1O0eDNiWUjUVrddKkTVLUGG6Yme1BYEUDCFYrGiJdB7c3RUuQmDju/zKQBQ1aSff1AjN58ow56u3XbdES6gzQCnJIa/7kou0GY2fDz5GqxwfaNA/3IHYGI2lZS/7yjqCCuLAD52zh/mBh0BIal8a0IEhofudF8XTtP18gFjCqEqL6KXUy4hkqxVJ0W+OSGpLax338Gnu91nezSSjKJz290zfAdCsR

### Steps to reproduce the bug

TS error in App.vue

### Expected behavior

Should be able to detect common state (bananas in reproduction)

### Actual behavior

Unable to detect common state even though we are able to use it in the application

**Comment by rylanharper** [comment]
I am seeing this as well since the latest update `^2.2.4`... This is should be a bug tag, not an enhancement tag (this is a major TS bug). I can use all my state variables, but get TS errors saying that no such variables exist.
