### ISSUE TITLE
Type of computed property is not correctly inferred in pinia 2.2.3 / 2.2.4 + vue 3.4

### ISSUE THREAD

**Issue by madeofsun** [posva/pinia#2797]
### Reproduction

https://play.pinia.vuejs.org/#eNqNVG1v4jAM/itRvwykkd7EtDsxQHDSPtxJ96LbfVv3IbSGZde8KHEZCPHfz0lLVWCTqFQpsR/bj+3Yu2RuLV9XkIySsc+dtMg8YGVZKfRqkiXos2Saaamscch2rPLwY/uIxgHbs6Uzil3xNDeVRnBXmc50brQnHxEx6cB7/fugjgouuBK2J9hkygTXQkE/6MZpzYDi0QVB2VIg0I2x8CN4DKBWkVwnNa8BeeOv3mjKYhfhjYLIj1iUBJmVWoogyZI0njl4NVg48+bBkX2WXB+gMypJWsAajSn9QFhZm70gWj9K07zQhC+glGvHNWCqrUrPbGZ3/I7fpKVcpBQolbqAzXEYshgUoC7xfoDOPvGbW/45el0PG6fq1OuldB01TirybNRsyG/58EtaSI9d+cdFCg5IuAY3cEA8HLhL456YHcU+0Z3FD+H3md5T+9HTc1vK1Unzc6OsLMH9sijpOR49AlGW5u17lKGroE0mf4H83ztyj07meCZ+9Zs6198OIuFOXVC4FUSTLHl4/AkbOrdKZYqqbPrzgfIPeFNWgXoN+1rpgrLp4GIS3+ITl3r11z9sELQ/5BqIdorUTCdHTxVqB7mApdRwPMlxKGiKW1AoZIVQtAjqXZzyTMMmYnBrgc1p0psCh2Ee0fg74lVLYvgR05VaUA6aSLXG9a7orJRJl1aP6rGlpFmvHxZFE6C2odXRkhvPn56nvRr09Bw3SQA6WmNOH8zCJ+rjnhbRvn+f7P8Dn++suA==

### Steps to reproduce the bug

! In demo select version of vue 3.4.38

If I define a store with a `computed` property

```ts
export type A = {
    name: string
    count: number
}

const useMyStore = defineStore("my", () => {
    const a = computed<A[]>(() => [])

    return {
        a
    };
});
```

Type of that property is `any`
```ts
const store = useMyStore()

store.a.map(a => a.name)
      ^ any 
```

### Expected behavior

pinia 2.2.3 / 2.2.4 + vue 3.5.x - ok
pinia 2.2.3 / 2.2.4 + vue 3.4.x - ok
pinia 2.2.2 + vue 3.4.x - ok

### Actual behavior

pinia 2.2.3 / 2.2.4 + vue 3.5.x - ok
pinia 2.2.3 / 2.2.4 + vue 3.4.x - described error
pinia 2.2.2 + vue 3.4.x - ok

**Comment by posva** [comment]
If you can't update to Vue 3.5 yet, pin pinia to `2.2.2`. I updated the peer dep for correctness

**Comment by jnoordsij** [comment]
This also applies to Vue 2 it seems (at least on my setup), which formally is still part of the peer deps. Now I guess Vue 2 is not formally supported anymore, but maybe this doesn't warrant removing it from the peer deps altogether?
