### ISSUE TITLE
Add class support to pinia

### ISSUE THREAD

**Issue by 0centos** [posva/pinia#2807]
### What problem is this solving

Currently, Pinia is a rare state management library that supports Setup APIs, but it does not have <script setup> like Vue SFC. Therefore, if there are thousands of pieces of data in a store, they need to be returned one by one. I hope this Issue can solve this problem.

### Proposed solution

I hope Pinia can add support for classes and class decorators in the future, so that there is no need to return data and methods one by one in the future, such as:
``` typescript
import { ref } from 'vue'
import { Store } from 'pinia'

@Store
export class myStore {
  count = ref(0)
  increment() {
    this.count.value++
  }
}
````
Use in components:
```vue
<script setup>
import { myStore } from '@/stores/counter'

const counter = new myStore()

counter.count++
counter.$patch({ count: counter.count + 1 })
counter.increment()
</script>

<template>
  <div>Current Count: {{ counter.count }}</div>
</template>
```

**Comment by cannap** [comment]
https://pinia.vuejs.org/core-concepts/#Option-Stores

**Comment by posva** [comment]
This has been proposed before but it's not technically doable

**Comment by 0centos** [comment]
There's a corresponding implementation
[pinia-class-component](https://github.com/PentaTea/pinia-class-component)
