### ISSUE TITLE
Nuxt module @pinia/nuxt version 0.6.0 produce error

### ISSUE THREAD

**Issue by januszj** [posva/pinia#2814]
### Reproduction

https://stackblitz.com/edit/github-hp3ech?file=package.json

### Steps to reproduce the bug

Just start application, error:

### Expected behavior

no error

### Actual behavior

error
Cannot start nuxt:  (0 , _kit.isNuxtMajorVersion) is not a function

### Additional information

version 0.5.5 works fine

**Comment by posva** [comment]
It should be good in 0.6.1. Running a [nuxt upgrade](https://nuxt.com/docs/getting-started/upgrade#upgrading-nuxt) should also work out
