### ISSUE TITLE
The type inference error of `mapActions` causes `vue-tsc` to fail to detect the undeclared action.

### ISSUE THREAD

**Issue by wuchen092832** [posva/pinia#2815]
### Reproduction

none

### Steps to reproduce the bug

All projects can reproduce the issue.

### Expected behavior

```typescript
mapActions(useStore, ['action1'])
// vue-tsc can detect the undeclared action，and build fail
this.action2()
```

### Actual behavior

build success with no error

### Additional information

Location of the problematic code.

https://github.com/vuejs/pinia/blob/128f4352d2c18c0992cbab67b1a9261ff8a766ca/packages/pinia/src/mapHelpers.ts#L376

I suggest changing it to

```typescript
export declare function mapActions<Id extends string, S extends StateTree, G extends _GettersTree<S>, A, K extends Array<keyof A>>(useStore: StoreDefinition<Id, S, G, A>, keys: K): Pick<A, K[number]>
```

**Comment by posva** [comment]
Don't open issues without reproductions, we can't check it...
