### ISSUE TITLE
`initialState` is not getting set by createTestingPinia for `testingStore.state.value["X"]`

### ISSUE THREAD

**Issue by sceee** [posva/pinia#2816]
### Reproduction

https://stackblitz.com/edit/github-pw6tjs-mbqc38?file=src%2Fstores%2Fcounter.spec.ts

### Steps to reproduce the bug

1. Stop execution
2. Execute `npm i`
3. Execute `npm test`

### Expected behavior

The test passes as `testingStore.state.value['counter'].n` is defined because it is being set in the `initialState` object provided to `createTestingPinia`.

### Actual behavior

The test fails as `testingStore.state.value['counter']` is not defined even though it was set in the `initialState` object provided to `createTestingPinia`.

(And obviously then also `testingStore.state.value['counter'].n` cannot be accessed.

### Additional information

I found this `testingStore.state.value['counter']` possibility to set the `initialState` in various comments in the discussion section.
Probably it's outdated and should no longer be used.

**Comment by posva** [comment]
The initial state is only used once the store is instantiated the first time, this allows to partially set the state instead of just replacing it. You can manually set the `state.value.counter` if you want.
