### ISSUE TITLE
$subscribe misses event when several mutations happen synchronously one after another

### ISSUE THREAD

**Issue by dimitri-grablow** [posva/pinia#2819]
### Reproduction

https://play.pinia.vuejs.org/#eNqNU01vGjEQ/SvWqhIbBWwoVSJRiGijHNpDWzU97mXZHcDEX7K9BAnx3zu2l2WTVlEOK61n3sy8efY7Zl+MofsGslk2d5XlxhMHvjFElGqzKDLviuyuUFwabT05ksbBo9cWyImsrZZkQFmlG+XBUu8GhSpUpZXDJhG06PD5VcjFKP3gmlWYtYI8l40vPdfqiizuyLFQhIR6LYAKvckH29IYUFAPhqRDfi7UKXZLk7S6F7x6wln5pUkaZKw2k+trLOhHPsbICb85SyvjgnjwII0oPeCJkPmq8V4rsqxCcxSiHYNqpHES5ixhED9nveJsmCW5RrI0dOe0QnEjq6JNoKazxDPEDFe8DJEiY/GfgpOjldXPDlXdIXh4hi7xplgNe6+1cKPS8FS29d64GWNVrRBfg+B7SxV4poxk/9Qsb+gNnTDBVwwHMa5qOLwcgxWjGuR7up+hyzGdfKK3set+2jaVoWtoekK9URbv8MrWfPNKlEpLwwXYnybc70txSiH08/cY87aBjmK1herpP/GdOyTWvyygfHvoreVLuwGf0g+PP+CA/11S6roRiH4j+RvwYTaBY4J9bVSNtHu4yPZbvGOuNn/cw8GDcuelAtGoRsRHme/fWP1Cd0qnPRUvfkMJO2PWsObqlTfja4qmhEOEJcd0Hl70q/JB2xi91noI3/OsdVXe0oqWmpHJeNwuHR01I7dtIDgzfNnpL7afdGw=

### Steps to reproduce the bug

The store defines 2 properties on state. The click handler increments both of them simultaneously.
The $subscribe callback prints to the console the resulting mutation

Open the playground and open the browser console.
Click on the button

### Expected behavior

either 2 log statements in the console with respective mutations
or 1 event in the console with 1 mutation, but 2 events inside, one for each changed property

### Actual behavior

there is only one entry with one mutation event, for prop1.
prop2 is unreported

### Additional information

If the change happened on different ticks, as shown [here](https://play.pinia.vuejs.org/#eNqNU01v2kAQ/SsrqxKOgF1oqkRyIaKNcmgPbdXk6IuxB1ji/dB+ECTEf+/srjEkraIeLHln3sy8ebvvkH3Rmu48ZEU2s7Xh2hELzmvSVnI9LzNny+yulFxoZRw5EG/h0SkD5EhWRgkyoKxWXjow1NlBKUtZK2mxSQTNe3x+FXIxSj9YvwyzlpDnwrvKcSWvyPyOHEpJSKhXLdBWrfPBptIaJDSDEemRn0t5jN3SJCXvW14/46z83CQN0kbp6XCIBRgB98QFKO/yhDtDPg6HIzLBlkdEzliSAZfGgwOh28oBngiZLb1zSpJFHQaiON1oVChREDBjCYP4GbsozkZZknAsKk23VkkUPDItuwTqXCTuIaa55FWIlBmL/xSsGC+NerGo9BbBoxN0gbfHGtg5pVo7rjRPZRvntC0YqxuJ+AZavjNUgmNSC/ZXzeKG3tApa/mS4SDGZQP712OwYtyA+J/uJ+hiQqef6G3survumorQNTQ9ot4oi7N4jSu+fiNKrYTmLZifOtz5a3GqtlUv32PMGQ89xXoD9fM/4lu7T6x/GUD5dnCxlqvMGlxKPzz+gD3+90mhGt8i+p3kb8DH6gPHBPvqZYO0L3CR7bd4x1yun+zD3oG0p6UC0ahGxEeZ799Z/Uz3ml5fqHj2IErYm7WBFZdv/BpfUzQq7CMsuaj39fyyKh90jdF/na/wPRed0/KOVrRZQaaTSbd0NFVBbrtAcGv4suMfZ4p6PQ==) , both events will be reported. 

This is probably similar to https://github.com/vuejs/pinia/issues/992 , but I find the problem more generic.

Basically it means if I have an action that alters several state elements as shown [here](https://play.pinia.vuejs.org/#eNqNU11v2jAU/StWNIlUBRvK1EoZVGxVH7aHbVr3mJeQXMDUX7IdioT477u2Q0rZVO0lia/PPT73OOeQfTaG7lrIimzmasuNJw58a4io1HpeZt6V2X2puDTaenIgrYMnry2QI1lZLcmAslq3yoOl3g1KVapaK4ckETTv8flV2ItV+sG1y3DWEvJctr7yXKsrMr8nh1IREvq1ACr0Oh9sKmNAQTMYkh75qVTHyDZjSTHqw4UHaUTlAVeEzJat91qRRS14/YxzpJO1eghrHCm+iYQZS0jsmrEzimyYpZlHsjJ067RCh6K+sttAY4qkONQMV7wKlTJj8ZuCk6Ol1S8OrdkieHiCLtBu1sDOay3cqDI8tW28N65grG4U4hsQfGepAs+UkeyvnsUtvaUTJviS4UGMqwb2b4/BjlED8n/YT9DFmE4+0rvIupt2pDKwBtIj+o62eIc3tOLrC1NqLQ0XYH+YcElvzamE0C/fYs3bFnqJ9Qbq53/Ut26fVP+0gPbt4GwsX9k1+LT9+PQd9vjdb0rdtALR72z+Avy72qAxwb60qkHZZ7io9mu8Y67Wv93j3oNyp6GC0OhGxEebH94Z/VXulE7PXHwNDVrYp6uBFVcXAYt/U0wW7CMsBawP4vy8Kx90xBiYqMFhaKAgecxX3skyVptJQSbjcTd0KNwU5K4rHK/iq6rjPP00XXqQqysQ4jfc0Uh3fY25vCje9MXkVniG6GbHPykOex4=), my subscribers will miss some of the mutations.

**Comment by posva** [comment]
This is because `$subscribe` are watchers under the hood. You can get the behavior you want by using `flush: 'sync'`. It's slightly less performant but that won't matter in 99% of the cases.

**Comment by dimitri-grablow** [comment]
thank you for the hint
