### ISSUE TITLE
Nuxt/Pinia "Proxy set handler returned false for property" upon hydration

### ISSUE THREAD

**Issue by Jamie4224** [posva/pinia#2825]
### Reproduction

https://github.com/Jamie4224/pinia-hydration-bug-repro

### Steps to reproduce the bug

1. Open the minimal reproduction.
2. Run `pnpm i && pnpm run dev`
3. Open the app

### Expected behavior

The app works as intended and shows the value "abc".

### Actual behavior

The value "abc" is shown and then the error `proxy set handler returned false for property '"testComputed"'` appears.

### Additional information

I found out that this error appeared in v2.2.5 due to https://github.com/vuejs/pinia/commit/254eec764ecccd120ab9dbc31352d76ffd6ecfa3. 

It happens when re-exporting a non-writable ref from a store while using storeToRefs. 

It is also reproducible with a single store. To test this, uncomment the `toRef()` block and switch the exports. 

This behaviour seems to be the problem.
```
const test = toRef(reactive({
     'alttest': computed(() => '')
}), 'alttest');
```

I noticed that this error does not happen on vue@3.5.0-alpha.2 but it does on vue@3.5.0-alpha.3. I don't know if this is expected behaviour or not.

A workaround is using `skipHydrate()` on these properties.

**Comment by posva** [comment]
If you return a ref, it must be writable. So here, the solution is to not use toRef to extract the data. Use a computed instead and it will be reflected as a getter too, which is the correct version

**Comment by Jamie4224** [comment]
@posva The example code in my issue was an illustration of what I think is happening under the hood. This is the actual code in my reproduction that is causing an issue:

```
export const useTestStore = defineStore('testStore', () => {
    const testComputed = computed(() => {
        return "abc";
    })

    return {
        testComputed
    }
})

export const useSecondaryStore = defineStore('secondaryStore', () => {
    const testStore = useTestStore();
    const {testComputed} = storeToRefs(testStore)

    return {
        testComputed, 
    }
})
```

I am only using computed and storeToRefs here. Is this not a valid use case? If so, would you highlight the part that should is incorrect?
