### ISSUE TITLE
Pinia nuxt causes "error 500 vueDemi2.effectScope is not a function" on `nuxt start` on version 0.7.0.

### ISSUE THREAD

**Issue by JuanAndresAlborada** [posva/pinia#2826]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-zenkzj?file=app.vue

### Steps to reproduce the bug

Build and start the app.
```bash
pnpm build
pnpm start
```
This only happens with SSR active.

### Expected behavior

The page loads normally

### Actual behavior

The page throws error 500
![image](https://github.com/user-attachments/assets/779cc82a-f017-4129-8227-cda4eae50081)

### Additional information

This problem doesn't happen in dev mode.
This problem doesn't happen with version 0.5.5

**Comment by posva** [comment]
Update your dependencies, they are outdated

**Comment by JuanAndresAlborada** [comment]
> Update your dependencies, they are outdated

I have all the dependencies updated, it fails. Also the reproduction only has the last nuxt version and the last @pinia/nuxt version and it fails.

**Comment by enduity** [comment]
I can confirm the same issue with my project. I have updated all the dependencies.

Please consider reopening this issue.

Update: The issue is caused by [this commit](https://github.com/vuejs/pinia/commit/65031ee77ed46a34bc2359223e24c7944e840819), which lets Nuxt use the .prod.cjs version of Pinia. Subsequently, Vite fails to properly resolve the exports of vue-demi, generating this code:
<details>
  <summary>Show collapsed code</summary>
  
  ```javascript
  var pinia_prod = {};
  const install = () => {
  };
  function set(target, key, val) {
    if (Array.isArray(target)) {
      target.length = Math.max(target.length, key);
      target.splice(key, 1, val);
      return val;
    }
    target[key] = val;
    return val;
  }
  function del(target, key) {
    if (Array.isArray(target)) {
      target.splice(key, 1);
      return;
    }
    delete target[key];
  }
  const Vue2 = void 0;
  const isVue2 = false;
  const isVue3 = true;
  const vueDemi = /* @__PURE__ */ Object.freeze(/* @__PURE__ */ Object.defineProperty({
    __proto__: null,
    Vue2,
    del,
    install,
    isVue2,
    isVue3,
    set
  }, Symbol.toStringTag, { value: "Module" }));
  const require$$0 = /* @__PURE__ */ getAugmentedNamespace(vueDemi);
  (function(exports) {
    /*!
     * pinia v2.2.6
     * (c) 2024 Eduardo San Martin Morote
     * @license MIT
     */
    var vueDemi2 = require$$0;
  ```
</details>

Perhaps a fix could be to also generate a `.prod.mjs` version of Pinia?

**Comment by KevinLeneschmidt** [comment]
Why is it closed already? I have the same issue

**Comment by fatihtkale** [comment]
i have same issue why is this closed?

**Comment by KevinLeneschmidt** [comment]
If you set "ssr: false" in your nuxtconfig it will work, but that is not a real solution.

**Comment by fatihtkale** [comment]
yes but i depend on SSR for my SEO so thats a bumper...

**Comment by fatihtkale** [comment]
@KevinLeneschmidt 
 i found a better fix downgrade to "@pinia/nuxt": "0.5.5",

**Comment by posva** [comment]
I gave this an extra look, there are upcoming changes to the module and Pinia to improve compatibility but for the moment, install `pinia` alongside `@pinia/nuxt` and it will fix the build error

**Comment by ivryb** [comment]
Had the same problem today. It fails if the Node.js version is 22, works fine on Node v20.
On node v22, adding `pinia` to the dependencies doesn't help.
I also used pnpm.

**Comment by hmingv** [comment]
I had the same issue, I updated all my dependencies to the latest version except @pinia/nuxt which I needed to downgrade to 0.5.5 to avoid this issue.

**Comment by posva** [comment]
Install pinia too (ser changelog)
