### ISSUE TITLE
storeToRefs broken in some edge cases since 2.2.5

### ISSUE THREAD

**Issue by DaleMckeown** [posva/pinia#2829]
### Reproduction

working on it

### Steps to reproduce the bug

working on it

### Expected behavior

Upgrading from pinia 2.2.4 to 2.2.5 should not cause storeToRefs to throw errors.

### Actual behavior

When upgrading from 2.2.4 to 2.2.5, the following error message is displayed and the page white screens, doesn't show any content.

```
 Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 
```

### Additional information

If I revert back to pinia 2.2.4 this issue goes away entirely. I suspect that this issue is caused by the changes made in https://github.com/vuejs/pinia/pull/2795, which changes the way the ref is referenced.

**Comment by posva** [comment]
Open a new issue once you have a repro. Please don’t open issues without repros as asked in the form
