### ISSUE TITLE
Error when loading app, but only when pinia tab in vue devtools is open on pinia tab

### ISSUE THREAD

**Issue by garfunkel** [posva/pinia#2840]
### Reproduction

https://github.com/garfunkel/vue-pinia-devtools-bug

### Steps to reproduce the bug

1. Start app in dev mode
2. Open vue devtools
3. Click on the pinia tab in devtools
4. hard refresh app page
5. See error traceback in browser console

### Expected behavior

No error/traceback.

### Actual behavior

In Firefox:
`Uncaught (in promise) TypeError: U is null`

In Chrome:
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'state')`

**Comment by garfunkel** [comment]
Just found a recent issue on the devtools repo which may be related: https://github.com/vuejs/devtools/issues/707

**Comment by posva** [comment]
Let’s keep it in devtools for the moment since the devtools code here hasn’t changed
