### ISSUE TITLE
SSR Memory Leak on pinia >= 2.2.0

### ISSUE THREAD

**Issue by jacobfrantz1** [posva/pinia#2843]
### Reproduction

https://github.com/jacobfrantz1/pinia-issue-repro

### Steps to reproduce the bug

I'm using the quasar framework in ssr mode. 

There are several circumstances that must be made to experience the bug. It only occurs on the ssr server when the bundler externalizes pinia in the ssr build (not bundle it in, so it doesn't replace NODE_ENV) (this is what quasar does for the ssr server). A store also needs to be used on the page being requested. Did not occur before 57914b5.

It occurs on pinia versions 2.2.0-2.2.6 (latest at time of writing)

Screenshot of memory leak
![image](https://github.com/user-attachments/assets/85b0dd0c-5003-4cf6-ad70-4ad81276a71e)

### Expected behavior

Devtools is disabled on the ssr and doesn't leak memory with every request, even if process.env.NODE_ENV is not set. There used to be a IS_CLIENT check on all uses of devtools before 57914b5. This check got moved around so it does check in some places (https://github.com/vuejs/pinia/blob/31fbff1262324c6e98a2f8ce786e786683f26df8/packages/pinia/src/createPinia.ts#L32C1-L35C1) but not in this one (https://github.com/vuejs/pinia/blob/31fbff1262324c6e98a2f8ce786e786683f26df8/packages/pinia/src/createPinia.ts#L60C1-L62C4)

Here's the old USE_DEVTOOLS flag for reference: https://github.com/vuejs/pinia/blob/0d67b84d52e989af3eca94497c1f266837834eef/packages/pinia/src/env.ts#L9C1-L10C67

### Actual behavior

Pinia appends to __VUE_DEVTOOLS_PLUGINS__ global on every request to the ssr server under certain circumstances.

**Comment by posva** [comment]
Thanks, it seems like the `IS_CLIENT` check was just forgotten
