### ISSUE TITLE
However, when I pass a null value for a certain key into storeToRefs, it will throw an error.

### ISSUE THREAD

**Issue by Jv-Juven** [posva/pinia#2848]
### Reproduction

-

### Steps to reproduce the bug

In the function definition within the file "pinia/packages/pinia/src/storeToRefs.ts", if the property value of the object rawStore obtained from `const rawStore = toRaw(store)` might be null, an error will occur.
![image](https://github.com/user-attachments/assets/822d5cfc-d335-47ed-972b-b79f44b20fb1)
![image](https://github.com/user-attachments/assets/91983964-3e6b-431c-90f9-abe024112550)

### Expected behavior

When the final computed value of rawStore is `{ projectId: null, name: null }`, the program can execute normally.

### Actual behavior

![image](https://github.com/user-attachments/assets/47467d56-3c96-4831-8132-0dc1618f5d34)

**Comment by posva** [comment]
This simply sounds like wrong usage but you didn’t provide a repro like asked… open a discussion for help or use the discord, please

**Comment by posva** [comment]
To help others who might have this issue. This comes from code like this:


```ts
export const useStore = defineStore('counter', () => {
  let thing = null

  return { thing }
})
```

This should be changed to

```ts
export const useStore = defineStore('counter', () => {
  let thing = ref(null)

  return { thing }
})
```

Otherwise, **things don't work**: the `thing` variable used inside of the store is different from the one exposed through `useStore().thing`. This is worth adding as an eslint rule.

---

Another scenario that wasn't meant to work (and actually breaks with some plugins) is this:

```ts
interface UserStore {
  userList: string[]
  user?: string
}

export const useUserStore = defineStore('user', {
  state: (): UserStore => ({
      userList: [],
      // user is omitted, needs to be `user: undefined` after this commit, to be able to use storeToRefs
  }),
})
```

The correct version would be:

```ts
interface UserStore {
  userList: string[]
  user: string | undefined // or `null`
}

export const useUserStore = defineStore('user', {
  state: (): UserStore => ({
      userList: [],
      user: undefined
  }),
})
```
