### ISSUE TITLE
Missing GitHub releases due to missing `pinia@*` tags

### ISSUE THREAD

**Issue by ezio-melotti** [posva/pinia#2850]
### Steps to reproduce the bug

Go on https://github.com/vuejs/pinia/releases -- the last release is `2.2.6`.
Go to https://github.com/vuejs/pinia/tags -- the last release is `2.3.0`.

### Expected behavior

`2.2.7`, `2.2.8`, `2.3.0` should be listed in the releases page.

### Actual behavior

`2.2.7`, `2.2.8`, `2.3.0` are missing from the releases page.

### Additional information

By looking at the workflow, it's triggered by commits tagged with `pinia@*`:
https://github.com/vuejs/pinia/blob/1d8f3411deae55cd7987785bd286005fe86566be/.github/workflows/release-tag.yml#L1-L4

In https://github.com/vuejs/pinia/tags the releases up to `2.2.6` were tagged as e.g. `pinia@2.2.6` and were triggering the workflow.  The following releases are tagged as e.g. `v2.2.7`.

If the changes in the tagging format was intentional, the GitHub workflow should be updated accordingly.  If not, the tags for `2.2.7`, `2.2.8`, `2.3.0` should be fixed and the `pinia@*` format should be used for new releases.

Note that because of this, `dependabot` release notes are stuck at `2.2.6`.

**Comment by posva** [comment]
Yes, you are right! Since you found the culprit, do you want to send a PR to fix the workflow?

**Comment by ezio-melotti** [comment]
If you are planning to use `v*` moving forward, I can make a PR to fix the workflow!
