### ISSUE TITLE
There may be problems with the introduction method in the document

### ISSUE THREAD

**Issue by kcgithub2014** [posva/pinia#2856]
### Reproduction

N/A

### Steps to reproduce the bug

In the [https://pinia.vuejs.org/zh/core-concepts/plugins.html](https://pinia.vuejs.org/zh/core-concepts/plugins.html) documentation

import debounce from 'lodash/debounce'

In some projects there may be problems, in production there will be Canot read properties of undefined (reading 'now')

It is proposed instead:

import { debounce } from 'lodash';

### Expected behavior

You should not prompt Canot read properties of undefined (reading 'now')

### Actual behavior

Page throws exception: Canot read properties of undefined (reading 'now')

**Comment by posva** [comment]
This depends on your project but it's unrelated to pinia. As of today, the lodash docs still show examples of importing like that, so this might be an issue in your project. I personally use https://github.com/chodorowicz/ts-debounce or write my own debounce
