### ISSUE TITLE
`watch` on object triggered on page load during SSR

### ISSUE THREAD

**Issue by OnePixelOffset** [posva/pinia#2859]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-u6kyiryz?file=stores%2Fuser.ts

### Steps to reproduce the bug

See stackblitz link. Some notes:

1. `user` needs to be object (primitive values work as expected)
2. `watch` needs to be inside store (watch within `app.vue` works as expected)
3. `ssr` needs to be `true` (with `false` works as expected)

### Expected behavior

`watch` is not triggered on initial page load

### Actual behavior

`watch` triggers on initial page load

**Comment by posva** [comment]
This happens due to hydration setting the `user` and is needed for correctness. You could skip it in multiple ways:

- `skipHydrate()` the `user`
- skip the watch code until hydration is complete
