### ISSUE TITLE
Persist store throughout page reloads

### ISSUE THREAD

**Issue by tno2007** [posva/pinia#309]
### What problem is this solving

To completely eliminate the need for Vuex, since Vuex has session persistence support via a plugin.

### Proposed solution

Accept an extra object in the createStore initialization:

```javascript
export const usePiniaStore = createStore({
	id: "simpleStore",
	state: () => ({
		simpleVariable: "",
	}),
	persistence: {
		enable: true,
		mode: "localSession"
	}
});

// type definition
interface IPiniaPersistence {
	enable: boolean,
	mode: "localSession" | "localStorage";		
}

```

### Describe alternatives you've considered

There does not seem to be any Vuex-less alternatives out there that supports the vue-composition-api.

**Comment by posva** [comment]
Vuex doesn't have persistence support, it comes from a plugin. For Pinia, it would be the same. This can be implemented by using ~~`store.$subscribe`~~ a `watch(pinia.state, handler, { deep: true })` to write to local storage (or anything else) and watching localStorage for changes and writing back to the store.

Something along the lines of

```js
// save the whole state
watch(pinia.state, (state) => {
  localStorage.setItem('state', JSON.stringify(state)
}, { deep: true })

// save cart store
watch(() => pinia.state.value.cart, (state) => {
  localStorage.setItem('cart', JSON.stringify(state)
}, { deep: true })
```

You can inspire yourself from https://github.com/robinvdvleuten/vuex-persistedstate/blob/master/src/index.ts to create it

There is also https://github.com/posva/pinia/issues/191 going on to discuss plugins, they will probably be similar to Vuex 5 plugins once that is discussed too

**Comment by michelwaechter** [comment]
Where do i have to insert the watch command? Dont understand that answer..

**Comment by posva** [comment]
An updated and simpler version is to use something like https://vueuse.org/core/uselocalstorage/#uselocalstorage:

```js
defineStore('store', {
  state: () => ({
    count: useLocalStorage('count', 0)
  })
})
```

**Comment by wdlnydhcg** [comment]
> An updated and simpler version is to use something like https://vueuse.org/core/uselocalstorage/#uselocalstorage:
> 
> ```js
> defineStore('store', {
>   state: () => ({
>     count: useLocalStorage('count', 0)
>   })
> })
> ```

sorry,if count key is Obeject type, how should it be written?

**Comment by jaybo** [comment]
I tried this solution:
```
defineStore('store', {
  state: () => ({
    count: useLocalStorage('count', 0)
  })
})
```
And it seems to work, EXCEPT, $reset() doesn't appear to actually reset to the default value (seems to be a NoOp).

**Comment by sea-lanya** [comment]
how about https://github.com/prazdevs/pinia-plugin-persistedstate ?

**Comment by nohehf** [comment]
If you prefer to use the ref() syntax you can just do:
`const count = ref(useLocalStorage('count', 0))`
inside your defineStore function !
Works out of the box :)

**Comment by septatrix** [comment]
> I tried this solution:
> 
> ```
> defineStore('store', {
>   state: () => ({
>     count: useLocalStorage('count', 0)
>   })
> })
> ```
> 
> And it seems to work, EXCEPT, $reset() doesn't appear to actually reset to the default value (seems to be a NoOp).

I am not sure if I would call that a bug because if we interpret "reset" as "set to the same state we would get from re-initializing the app" then that would be the correct behaviour. Question is if that is actually what happens or if the state is simply not touched at all.
The behaviour would differ in whether or not custom parsers are run (to deserialize the stored local storage) and also when manually clearing the local storage and then resetting the store.

**Comment by FossPrime** [comment]
I managed to save it with a full action I call early... such as onBeforeMount or on the first component

```js
async fill() {
      for (const [key, store] of Object.entries(this.$state)) {
        this[key] = useStorage(NS + ':' + key, store)
      }
    },
```

**Comment by ShlomoCode** [comment]
For those looking for a solution in the future - this is what I did at my place, inside the store (Based on @posva's answer above):
```js
import { defineStore } from 'pinia'
import { reactive, watch } from 'vue'

export const useUserStore = defineStore('user', () => {
    const user = reactive({
        name: '',
        email: ''
    })
    
    const userInStorage = localStorage.getItem('user')
    if (userInStorage) {
        const { name, email } = JSON.parse(userInStorage)
        user.name = name
        user.email = email
    }

    watch(() => user, (state) => {
        localStorage.setItem('user', JSON.stringify(state))
    }, { deep: true })

    // setUser simple function
    // function setUser ({ email, name }) {
    //     user.email = email;
    //     user.name = name;
    // }

    return {
        user,
        // setUser
    }
})
```
Happy coding!

**Comment by cotufaloschiflones** [comment]
> I tried this solution:
> 
> ```
> defineStore('store', {
>   state: () => ({
>     count: useLocalStorage('count', 0)
>   })
> })
> ```
> 
> And it seems to work, EXCEPT, $reset() doesn't appear to actually reset to the default value (seems to be a NoOp).

@jaybo If you want to work with $reset, you should be able to do it with this magnific approach from lobo tuerto: https://lobotuerto.com/notes/til-how-to-reset-all-stores-in-pinia 

But you should overwrite the store $reset method like follows:

```
  pinia._s.forEach((store, storeName) => {
    store.$reset = () => {
      Object.keys(store.$state).forEach((key) => {
        Reflect.set(store.$state, key, null)
      })
    }
    resetStores[storeName] = () => store.$reset()
  })
```

**Comment by jarrodhroberson** [comment]
> For those looking for a solution in the future - this is what I did at my place, inside the store (Based on @posva's answer above):
> 
> ```js
> import { defineStore } from 'pinia'
> import { reactive, watch } from 'vue'
> 
> export const useUserStore = defineStore('user', () => {
>     const user = reactive({
>         name: '',
>         email: ''
>     })
>     
>     const userInStorage = localStorage.getItem('user')
>     if (userInStorage) {
>         const { name, email } = JSON.parse(userInStorage)
>         user.name = name
>         user.email = email
>     }
> 
>     watch(() => user, (state) => {
>         localStorage.setItem('user', JSON.stringify(state))
>     }, { deep: true })
> 
>     // setUser simple function
>     // function setUser ({ email, name }) {
>     //     user.email = email;
>     //     user.name = name;
>     // }
> 
>     return {
>         user,
>         // setUser
>     }
> })
> ```


It looks like this overwrites the entire JSON blob on every property update.
For something this small, and granted stuff in local storage should not be very big, it generates a lot redundant writes. Also, if something is updated fairly often, then you do not have any granular control over the writes.

I am struggling with wanting to have my application state in a single object for organization but having granular control over the persistence of the individual properties lifecycles.

I have a few solutions right off the top of my head, none of them are ideal from an effort standpoint.

1. create a watch(() => app.<property>,) watcher for every property individually. And store them individually with a flat name space.
2. create a watch(app,) watcher that somehow detects what changed and acts accordingly. This implies that I need to version my app state data so I can compare current to old. not trivial to code up and could be brittle if the object has nested objects that I want to track properties individually.
3. write a generic framework that takes any object and allows me to attach arbitrary watch functions based on a flattened key name.

I am looking at leveraging `useLocalStorage` if it can save me time and effort.
 
#3 ironically is probably the least amount of work if I theory craft them all out.

Anyone have any ideas or have any implemenations.

**Comment by NaturalDevCR** [comment]
I know this wasn't on Vuex by default but it would be a really nice to have integrated with Pinia, it's very very common to persist the state, and having to depend on external plugins makes it a little overkill.

Hopefully you could reconsider this, as this would definitely make pinia a whole solution.

Anyway, thanks for pinia!

**Comment by eqoram** [comment]
Can only agree with the last comment! Also it works be nice to also have this working with SSR (local storage might be an issue here) :)

**Comment by robertrosman** [comment]
> An updated and simpler version is to use something like https://vueuse.org/core/uselocalstorage/#uselocalstorage:
> 
> ```js
> defineStore('store', {
>   state: () => ({
>     count: useLocalStorage('count', 0)
>   })
> })
> ```

Really like this approach! In case you want to persist the whole store, this variant seems to work as well:

```js
defineStore('store', {
  state: () => useLocalStorage('store', {
    count: 0
    // All your other values as usual in here
  })
})
```

**Comment by sudosean** [comment]
> > An updated and simpler version is to use something like https://vueuse.org/core/uselocalstorage/#uselocalstorage:
> > ```
> > defineStore('store', {
> >   state: () => ({
> >     count: useLocalStorage('count', 0)
> >   })
> > })
> > ```
> 
> Really like this approach! In case you want to persist the whole store, this variant seems to work as well:
> 
> ```js
> defineStore('store', {
>   state: () => useLocalStorage('store', {
>     count: 0
>     // All your other values as usual in here
>   })
> })
> ```

@robertrosman I like this setup, how did you reset the state back to the defaults with this?
