### ISSUE TITLE
TS Error 4023 - Exported variable 'useMainStore' has or is using name 'StoreWithState'

### ISSUE THREAD

**Issue by kingkong404** [posva/pinia#315]
### Reproduction

**Error**: ```Exported variable 'useMainStore' has or is using name 'StoreWithState' from external module "/Users/steven/Documents/New Documents Dec 2020/boilerplate/versiontwo/node_modules/pinia/dist/pinia" but cannot be named.ts(4023)```

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/4363358/102345593-a2c80480-3f6b-11eb-9595-f8c2406ef9ab.png">

### Steps to reproduce the behavior

Installed pinia@next and added it to main.ts and created a new file with the example code. 

**main.ts**
``` main.ts
import { createApp } from "vue";
import "./assets/main.css";
import App from "./App.vue";
import { routes } from "./routes";
import { createRouter, createWebHistory } from "vue-router";
import { store } from "./store";
import { createPinia } from "pinia";

const app = createApp(App);
app.use(createPinia());
app.use(store);

export const router = createRouter({
  history: createWebHistory(),
  routes,
});

app.use(router);
app.mount("#app");
```

**piniaStore.ts**
```ts
import { defineStore } from "pinia";

export const useMainStore = defineStore({
  // name of the store
  // it is used in devtools and allows restoring state
  id: "main",
  // a function that returns a fresh state
  state: () => ({
    counter: 0,
    name: "Eduardo",
  }),
  // optional getters
  getters: {
    doubleCount() {
      return this.counter * 2;
    },
    // use getters in other getters
    doubleCountPlusOne() {
      return this.doubleCount * 2;
    },
  },
  // optional actions
  actions: {
    reset() {
      // `this` is the store instance
      this.counter = 0;
    },
  },
});
```

**Comment by posva** [comment]
Provide a minimal editable reproduction, thanks

**Comment by kingkong404** [comment]
Hey @posva I copied the code provided in the read me to an existing project. I've added my relevant code / the two files I changed to my first comment. Although in order to provide a full repo I'd have to provide my entire project. 

I am also using Vuex and was planning to transition over to Pinia. (not sure if that matters) 

Any advice to what I could try or what the error means would be great! Very excited to get this working.

**Comment by kingkong404** [comment]
@posva I think I know why its happening 

`Exported variable 'useMainStore' has or is using name 'StoreWithState' from external module ".../versiontwo/node_modules/pinia/dist/pinia" but cannot be named.`

My file structure is set up as
Main folder <-- I's looking for Pinia here in the main (/versiontwo/node_modules/)
 - Packages
 -- Frontend 
--- node_modules <-- Pinia is installed here (/versiontwo/packages/frontend/node_modules/)

<img width="252" alt="image" src="https://user-images.githubusercontent.com/4363358/102480829-d7e95b00-402e-11eb-9943-a0439aa6c66b.png">

Note: I have VSCode set to hide Node modules folders but each package folders has it's own node modules.

**Comment by kingkong404** [comment]
Actually it seems all my modules are coming from the main folder even Vue. So there goes that theory :/

<img width="575" alt="image" src="https://user-images.githubusercontent.com/4363358/102481682-09165b00-4030-11eb-8779-e492ab919ba8.png">
