### ISSUE TITLE
state set inside `serverPrefetch` isn't transferred from server to client

### ISSUE THREAD

**Issue by MartinMalinda** [posva/pinia#332]
Main issue: https://github.com/nuxt/nuxt.js/issues/8620

**Comment by posva** [comment]
What do you mean? can you elaborate...

**Comment by MartinMalinda** [comment]
@posva sorry if it wasn't clear, there is a description and link to a repro in the linked issue. I've identified the issue to be a Nuxt issue rather than Pinia issue. I just thought creating an issue also here might be useful.

But the point of the issue is: `beforeNuxtRender` is called too soon and the pinia store state might not be saved to `nuxtState` at all or it's saved too early, so latest state might not be passed to client. Even if server properly waits for server prefetches and other things and renders correct SSR HTML.

**Comment by posva** [comment]
Thanks, now it's clear

**Comment by MartinMalinda** [comment]
If anyone is looking for a workaround, this works for my particular version of Nuxt (2.12).

```ts
export function usePiniaPrefetch(cb: () => Promise<any>) {
  const root = useRoot() as any; // this is my own util, `getCurrentInstance()` could be used instead probably
  onServerPrefetch(async () => {
    await cb();
    const ssrContext = root.context.ssrContext;
    ssrContext.nuxt.pinia = getRootState(root.context.req);
  });
}
```

It's a patch function over `onServerPrefetch` that also passes latest state to nuxtState. Unfortunately `nuxtState` seems to be present on different places in different versions of nuxt. It took me some time to find it:))

**Comment by posva** [comment]
I tested with the current version of pinia, adding @nuxt-composition api and it works. I'm sending you a PR so you can check it but this should work now.
