### ISSUE TITLE
v1 can't see pinia store in devtools

### ISSUE THREAD

**Issue by pavellzubkov** [posva/pinia#333]
### Reproduction

i trying to examine pinia in existing project with vue 2.6.12, vuex 3.6.0 , @vue/composition-api: 1.0.0-beta.25 . i can see state in console, but not see in dev tools. Should i some register in main.ts (App.use) or dev tools support not work with existing vuex?

**Comment by posva** [comment]
For vue 2, devtools support can only happen in place of vuex, so you can't use both
