### ISSUE TITLE
Export StoreWithState interface

### ISSUE THREAD

**Issue by LadislavBohm** [posva/pinia#339]
### What problem is this solving

I am trying to create generic function for creating base stores. Something like this
```
interface BaseState {
  baseData: ""
};

function defineEnumerationStore<TEnumeration, TAdditionalState, TAdditionalActions>(id: string, additionalState?: TAdditionalState, additionalActions?: TAdditionalActions) {
  return defineStore({
    id: "...",
    state: () => ({
      baseData: "",
      ...additionalState
    } as BaseState & TAdditionalState),
    actions: {
      baseMethod() {
        return this.baseData;
      },
      ...additionalActions
    } //here I can't type actions object like StoreWithState<> & TAdditionalActions
  })
}
```

I want to be able to provide additional actions and state data to this generic function. My problem is that I can't type my extended actions object like shown in the code above. Maybe I am doing it wrong way, but I think it would help if StoreWithState interface was exported so I can use it to type my actions object.

### Proposed solution

Export type:
interface StoreWithState<Id extends string, S extends StateTree>

**Comment by posva** [comment]
PR welcome! v2 already does that

**Comment by posva** [comment]
I will have to release a version soon for v2 for the exposed types

**Comment by LadislavBohm** [comment]
I completely missed 2.0.0-alpha.6 version that already has them exported :man_facepalming: as I was using 2.0.0-alpha.5, will try to make a PR for version one today at least.

**Comment by LadislavBohm** [comment]
I don't understand what happened but in my 2.0.0-alpha.5 types were not exported but I can see that they were exported in both v1 and v2 branches long time ago. So I believe there is no need for PR, sorry for the confusion.

**Comment by posva** [comment]
I pushed a commit to expose the types to v1 and will release the next week or so after adding other changes to align as much as possible with v2
