### ISSUE TITLE
Does it support "Method-Style Access" getter?

### ISSUE THREAD

**Issue by yaquawa** [posva/pinia#342]
Hi, thanks for the great work!!
I have a question for the getters in pinia.
Can I pass arguments to getters just like the vuex's getter? https://vuex.vuejs.org/guide/getters.html#method-style-access

Thanks.

**Comment by posva** [comment]
Yes! Just return an arrow function inside of the regular one and it should work

**Comment by yaquawa** [comment]
coool!! thanks!

**Comment by J3m5** [comment]
Is the getter result still cached ? Or is it like with Vuex ?
If not, is there any solution that could make it cached when called with params ?
I've thought about setting the params in the state dynamically or maybe memoize the getter result ?

**Comment by posva** [comment]
It's not cached, like Vuex, it basically becomes a function call. You can cache some stuff by calling it outside of the returned. I added some comments at https://github.com/posva/pinia/pull/633

**Comment by J3m5** [comment]
OK, thank you for the tip!
