### ISSUE TITLE
interested in redux devtools support?

### ISSUE THREAD

**Issue by james2doyle** [posva/pinia#364]
![Screen Recording 2021-02-17 at 02 37 54 PM](https://user-images.githubusercontent.com/1425304/108277400-32d22800-712e-11eb-86e1-d3df7b620338.gif)

I wrote a plugin that allows you to manage the Pinia store/state using the redux devtools. Is there any interest in this? Is it worth making a plugin for?

**Comment by posva** [comment]
This is pretty neat! Yes, I'm definitely interested in adding support directly to pinia as long as it doesn't affect the final bundle.
Can you also replace the state with Redux devtools? That's something currently missing with vue-devtools 6

**Comment by james2doyle** [comment]
I think this can be done as a plugin if there is a small change to the `pinia.use` code. Right now, [because `bind` is used with `null`](https://github.com/posva/pinia/blob/502a32832cfdb1a27a033ba2b7be578b090697de/src/rootStore.ts#L138) you can't properly watch the state of the store or access the `pinia` object within the plugin.

The approach I took still uses `pinia.use` but only as an "init" and not because it actually gives me what I need. Here is the code I used right now:

```js
// setup all the watchers for each store
const createStateWatcher = (state) => {
  Object.keys(state).forEach((store) => {
    watch(
      state[store],
      () => {
        // push changes when they are made
        ReduxTool.send({ type: `${store}-change`, payload: state }, state);
      },
    );
  });
};

// handles the jumps forward and backwards from the tools
ReduxTool.subscribe(message => {
  if (message.type === 'DISPATCH' && message.state) {
    // comes in as a string
    const state = JSON.parse(message.state);
    // sets the state to the new one
    pinia.state.value = state;
    // because we replaced it all, we need to setup the watchers again
    createStateWatcher(pinia.state.value);
  }
});

// not required but used as "init"
pinia.use(() => {
  createStateWatcher(pinia.state.value);

  // start with the raw state
  ReduxTool.init(pinia.state._rawValue);

  return {};
});
```

Maybe I'm wrong but is there a way to get the `pinia` instance from the `app` argument in the plugin?

**Comment by posva** [comment]
You can access `pinia` with `app.config.globalProperties.$pinia` but if it makes sense exposing it (more than `app`), we can just add it as an argument.

**Comment by james2doyle** [comment]
Ah ok. But yeah I think binding the current `pinia` instance as `this` (which makes the most sense to me honestly) will help a clean up the API and also not break existing plugins out there. It could be another arg too if that’s easier

**Comment by posva** [comment]
It has to be a second argument because `this` could not be set (arrow functions)
I'm still interested in exposing the redux plugin natively or linking to the github repo

**Comment by james2doyle** [comment]
Can't you [remove the bind call](https://github.com/posva/pinia/blob/502a32832cfdb1a27a033ba2b7be578b090697de/src/rootStore.ts#L145) here and just call the function normally?

**Comment by posva** [comment]
It won't change anything for arrow functions. I prefer the argument to changing the context anyway 😄

**Comment by james2doyle** [comment]
Oh yeah well you still need to call `pinia.use` with a full closure and not an arrow function. Ok well I can work on that and I'll submit a PR

**Comment by posva** [comment]
Hey, I'm still figuring out the plugin API to make it more powerful than just adding things to stores so the syntax will definitely change with breaking changes. It will be documented in the changelog and I'm still interested in adding redux support. I'm also working on docs and will love to point to your package if you prefer to keep the code in your own package

**Comment by james2doyle** [comment]
I haven't had a lot of time to work on this. The code above should work as a plugin for anyone looking for an immediate solution. Personally, I don't mind waiting as I'm not using pinia in anything that is in production at the moment. After spending additional time with Vue 3, I actually think the code could be cleaned up even more by using a deep watcher on the top level state - but anyway I personally can wait for the refactor

**Comment by posva** [comment]
The api for this should now be available. I think this should exist as an external plugin but i will gladly add a link in docs once i add a section about devtools

**Comment by james2doyle** [comment]
@posva I'm not using pinia at the moment but I will try to make time to make the plugin in the next little while

**Comment by posva** [comment]
Given the state of Vue Devtools 6, I prefer recommending using those when developing Vue apps but I'm open to linking to the redux devtools in docs since they offer a different approach
