### ISSUE TITLE
(v1) Deploy changes to NPM

### ISSUE THREAD

**Issue by maartenvn** [posva/pinia#387]
Currently the latest NPM version is 0.1.0, which still uses the old API for creating and registering stores. Following the README tutorial gives errors since these changes have not yet been published to NPM.

If these changes are something you are still working on, sorry for this issue, but I wanted to create this in case it was missed.

### Details
* **Version**: 0.1.0
* **Vue Version:** 2.6.12

**Comment by posva** [comment]
It wasn't missed, I'm doing a few changes and checks and had planned to release a 0.2.0 today 😅 
Thanks for the concern though
