### ISSUE TITLE
Piña = Peenya en Inglés

### ISSUE THREAD

**Issue by midlantica** [posva/pinia#393]
Micro issue, you say:
"Pinia is is the most similar English pronunciation of the word pineapple in Spanish: piña."

"Pinia" would sound phonetically like 'peen-ee-aah', or Pin-ee-ya'.

May I suggest 'peenya' as a replacement.

It might read like this:
"Piña means pineapple in Spanish, in English it would sound like 'peenya'.

Thank you for your work.

**Comment by posva** [comment]
Thanks 🙂

**Comment by angelhdz** [comment]
**Pinya**... hmmm 🤔

**Comment by aldencolerain** [comment]
:smile:  That little Pineapple icon gets me every time.  I must have typed "Pina" a hundred times trying to bring up this library.  I think many English speakers in the US know the Spanish word, but sounds like that ship has sailed.
