### ISSUE TITLE
[BUG] 'Pinia' type missing required property 'install' 

### ISSUE THREAD

**Issue by angelhdzmultimedia** [posva/pinia#401]
### Reproduction

If possible, provide a boiled down editable reproduction using a service like JSFiddle, Codepen or CodeSandbox. A failing unit test is even better! Otherwise provide as much information as possible to reproduce the problem.
If no reproduction is provided and the information is not enough to reproduce the problem, we won't be able to give it a look

### Steps to reproduce the behavior

1. Running Ionic/TypeScript/Vue 3 web application using Pinia.

### Expected behavior
App running without errors.

### Actual behavior
Error:
![image](https://user-images.githubusercontent.com/10191085/112118288-99fe5480-8b92-11eb-8e98-d7a887f82d2d.png)

### Additional information

I **solved** this by creating an interface extending Pinia type and adding the missing 'install' property, but I'm not sure if this is the correct approach or if I have to wait for a new version of Pinia to solve this.

My main.ts file where I create the Vue application and install Pinia:
![image](https://user-images.githubusercontent.com/10191085/112118813-20b33180-8b93-11eb-9b06-4446b6015266.png)

Implementing my solution:
![image](https://user-images.githubusercontent.com/10191085/112120342-7e944900-8b94-11eb-8376-32d4177861cd.png)

Now there's a "silent" error in Chrome's console only, that doesn't break the app:
![image](https://user-images.githubusercontent.com/10191085/112120498-adaaba80-8b94-11eb-859a-8a7b441443b7.png)

**Comment by posva** [comment]
Please read what is said:

> If possible, provide a boiled down editable reproduction using a service like JSFiddle, Codepen or CodeSandbox. A failing unit test is even better! Otherwise provide as much information as possible to reproduce the problem.
If no reproduction is provided and the information is not enough to reproduce the problem, we won't be able to give it a look

I can't help without a boiled down repro. Having Ionic shouldn't change anything. Just make sure you are using the correct version of Pinia: https://pinia.esm.dev/getting-started.html#installation. In your case you probably need `pinia@next`

**Comment by angelhdzmultimedia** [comment]
> Please read what is said:
> 
> > If possible, provide a boiled down editable reproduction using a service like JSFiddle, Codepen or CodeSandbox. A failing unit test is even better! Otherwise provide as much information as possible to reproduce the problem.
> > If no reproduction is provided and the information is not enough to reproduce the problem, we won't be able to give it a look
> 
> I can't help without a boiled down repro. Having Ionic shouldn't change anything. Just make sure you are using the correct version of Pinia: https://pinia.esm.dev/getting-started.html#installation. In your case you probably need `pinia@next`

package.json dependencies:

```
    "vue": "^3.0.0-0",
    "vue-decorator": "^1.1.2",
    "vue-property-decorator": "^10.0.0-rc.3",
    "@vue/composition-api": "^1.0.0-rc.5",
    "vue-router": "^4.0.0-0",
    "pinia": "^2.0.0-alpha.7"
```
main.ts:

```ts
import {createPinia} from 'pinia';


const app = createApp(App)
  .use(IonicVue)
  .use(router)
  .use(createPinia());


  
router.isReady().then(() => {
  app.mount('#app');
});
```

### More Info

I'm just trying Pinia because I just heard of it and it seemed simple to try. I'm not going to use it in production. I'm just reporting that it is throwing that error at runtime.
Already have Vue 3, pinia@next and @vue/composition-api, as per the package's requirements.

Also downgraded to pinia@2.0.0 and same error. This is the only package failing.

### Solved
After installing pinia@next (2.0.0-alpha.7) **again**, now the error that used to break the app's execution is gone.
The only error remaining is the one printed in the browser's console at runtime: **TS2345: Argument of type 'Pinia**
But after restarting Vue's development server, and navigating to the server's address in a new browser tab, that error went away, so that last error surely was a Cache Issue.

Working now. Thanks.

**Comment by posva** [comment]
BTW you should not use `@vue/composition-api` since you are using Vue 3

**Comment by angelhdzmultimedia** [comment]
> BTW you should not use `@vue/composition-api` since you are using Vue 3

Yes I'm very aware. I installed it after I installed pinia, because I got an error requesting it to be installed. So it's possible npm installed an old version. 🤝
