### ISSUE TITLE
Nuxt/Vuex TypeError: Cannot read property 'X' of undefined

### ISSUE THREAD

**Issue by sondh0127** [posva/pinia#415]
### Reproduction
https://codesandbox.io/s/festive-gauss-5knqo?file=/pages/index.vue
![image](https://user-images.githubusercontent.com/62163604/113121891-4ef0db00-923d-11eb-81c2-4d59a458d944.png)

### Steps to reproduce the behavior

1. add computed state with mapState from vuex store.
2. use computed variable in template

### Expected behavior
Can work with existing Nuxt+Vuex project
### Actual behavior
Nuxt return error
![image](https://user-images.githubusercontent.com/62163604/113121673-15b86b00-923d-11eb-98ce-de8b81f887ad.png)

### Additional information

**Comment by posva** [comment]
You need to tell pinia not to disable Vuex:

```js
// nuxt.config.js
export default {
  buildModules: [
    '@nuxtjs/composition-api',
    ['pinia/nuxt', { disableVuex: false }],
  ],
  // ... other options
}
```

I forgot to add it to the docs so I'm pushing it to the docs 🙂
