### ISSUE TITLE
Add store or state as first parameter for getters

### ISSUE THREAD

**Issue by Melchyore** [posva/pinia#418]
### What problem is this solving

Hello!

When splitting store into multiple files (i.e: state, getters, actions), we have no longer access to "this" inside actions. I find it redundant to call every action with store.$state as first argument.

### Proposed solution

Add "store" or "state" as first parameter for actions so we don't have to type it manually.

This is how it looks for now:

Store index:
![image](https://user-images.githubusercontent.com/6685773/113579559-c602e680-9624-11eb-919f-9f7f78aa22a7.png)

State:
![image](https://user-images.githubusercontent.com/6685773/113579658-e763d280-9624-11eb-8148-3f0340072c0a.png)

Getters:
![image](https://user-images.githubusercontent.com/6685773/113579695-f3e82b00-9624-11eb-9c49-a2f2118efbbe.png)

Actions:
![image](https://user-images.githubusercontent.com/6685773/113579737-fea2c000-9624-11eb-9881-03cf2e5af9c3.png)

How I call the action:
![image](https://user-images.githubusercontent.com/6685773/113579782-0f533600-9625-11eb-8ad5-0d8c984d9b0d.png)

**Comment by posva** [comment]
This is something I intended to add as a workaround for #249 because most of the time you only use the getter and it also enables writing getters as arrow functions:

```js
double: state => state.count * 2
```

Note you still have access to `this`, it's just not typed. In general one should avoid splitting a store into multiple files because of the inferred typing and instead split into multiple stores (each in one file) when one file contains too much logic

**Comment by Melchyore** [comment]
@posva I think that would be a great feature!

I agree that breaking the inferred typing is not the desired behavior but I also think that it should not be a determining criterion when deciding on an architecture, especially when the app grows more and more.

Thanks for your answer!

**Comment by posva** [comment]
I forgot to say it won't be possible to add to actions, only to getters. Parameters are already set in actions

**Comment by posva** [comment]
Closing in favor of https://github.com/posva/pinia/issues/249
