### ISSUE TITLE
Dark mode glitch on docs

### ISSUE THREAD

**Issue by ghost** [posva/pinia#427]
Hi. I have bookmarked https://pinia.esm.dev/introduction.html and it's in dark mode by default.
When I visit the main page from there (click logo) then it changes to light mode automatically.

The toggle to switch modes works right only for dark mode. Light mode is not saved properly I think.

**Comment by posva** [comment]
That's normal, the docs are static, I had to choose a theme by default. I don't think there is a way to handle the rendering without server-side logic, but I'm open to reasonable proposals (e.g. not something about including a service worker 😆 )

**Comment by posva** [comment]
ooh I see what you mean now: the pages stays in dark mode. Yeah, the ~~dark~~ light mode is a WIP currently it only loads on the main page

**Comment by posva** [comment]
I think I will focus on integrating dark mode directly into vitepress rather than hack further the layout to add the toggle

**Comment by ghost** [comment]
There's a toggle but it kinda in a strange place

![2021-04-09_130909](https://user-images.githubusercontent.com/11320080/114165281-f30d0d00-9934-11eb-873b-1a65efd477f9.png)

**Comment by posva** [comment]
It will be on the navbar

**Comment by ghost** [comment]
Is that helpful? https://vueuse.org/core/useDark/
