### ISSUE TITLE
No typing/autocomplete for store's own properties

### ISSUE THREAD

**Issue by syropian** [posva/pinia#431]
### Reproduction

When writing a store, I noticed I'm not actually getting any type info/autocompletion for internal state/getters/actions accessed on `this`, however, I do get completion for imported stores. I'm not 100% sure if this is intentional or not.

### Steps to reproduce the behavior

A simple example:

```ts
import { useOtherStore } from '@/stores/useOtherStore'
import { Fruit } from '@/types'

export const useSampleStore = defineStore({
  id: 'sample',
  state() {
    return { fruits: [] as Fruit[] }
  },
  getters: {
    computedFruits() {
      const otherStore = useOtherStore()
      const otherData = otherStore.someData // has typing/autocomplete
      this.fruits.push(otherData) // this.fruits is showing as "any" type
    }
  }
})
```
### Expected behavior

Referenced state/actions/getters inside a store on `this` would have correct typings

### Actual behavior

Internal state/actions/getters shows up as `any`

### Additional information

- Using the latest stable version of VSCode with Vetur
- Pinia version: `2.0.0-alpha.10`

**Comment by posva** [comment]
Can you provide a reproduction? The tests are passing: https://github.com/posva/pinia/blob/v2/test-dts/store.test-d.ts#L8

**Comment by syropian** [comment]
No problem @posva , do you happen to have a Vue 3 + TS compatible CodeSandbox template you like? I'm having trouble finding one that works 😓

**Comment by posva** [comment]
A starter with vite should do

**Comment by syropian** [comment]
@posva Here you go: https://codesandbox.io/s/hello-vite-forked-jc660?file=/src/store/useFruitsStore.ts

If you hover over `this.fruits` in `computedFruits` it just shows the type as `any`.

**Comment by posva** [comment]
![Screenshot 2021-04-09 at 23 54 11](https://user-images.githubusercontent.com/664177/114244505-e3baad80-998e-11eb-9638-1add80130b7d.png)

It seems to work

**Comment by syropian** [comment]
@posva Hm, what version of Pinia are you trying here? When I hover over it in the CodeSandbox I provided it just says `any` 🤔 

Edit: Actually I just tried again and now I'm seeing `(property) fruits: Fruit[]` which is definitely better. Maybe this is just an IDE issue? 😅

**Comment by posva** [comment]
Maybe it is 😅
Try restarting the ts server. Closing for now

**Comment by syropian** [comment]
No problem, I'll try it again tomorrow, sorry for the hassle! Really loving Pinia so far 😍

**Comment by maxtomczyk** [comment]
Hi,
I faced this issue with nuxt 3 project created via nuxt cli. Restarting TS server doesn't resolve this issue. VS Code still shows any for own store properties (typing works outside store). Is there any update on this?

**Comment by dsvgl** [comment]
@maxtomczyk 
you need to set strict to true in your tsconfig.json.
If you use the generated tsconfig by nuxt, it reads like this:
```json
{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "strict": true
  }
}
```

**Comment by me-v2** [comment]
still not autocomplete
