### ISSUE TITLE
Allow getters to have a setter defined

### ISSUE THREAD

**Issue by posva** [posva/pinia#447]
Like computed properties

```js
getters: {
	stuff: {
		get() {}
		set() {}
	},
	otherStuff() {
		// only getter
	}
}
```

**Comment by hi-reeve** [comment]
does this mean we can add parameter to our getter?

**Comment by posva** [comment]
@zynth17 no, this is like computed setter (like in the vuejs docs)

Use an action if you need parameters

**Comment by Fanna1119** [comment]
this would be cool.
At the moment i just use a computed getter/setter, which works as expected.

//vue component
```js
        const themes = useThemes();
        const activeTheme = computed({
            get: () => themes.getTheme,
            set: val => {
                themes.setTheme(val)
            }
        })

```

//store

```js
export const useThemes = defineStore({
    id: 'themeSelect',
    state: () => (
        {
            ActiveTheme: useStorage("active-theme", "emerald"),
            availableThemes: ['emerald', 'dark', 'forest', 'synthwave']
        }
    ),
    getters: {
        getTheme() {
            return computed(() => this.ActiveTheme)
        }
    },
    actions: {
        setTheme(val) {
            this.ActiveTheme = val;
        }
    }

})

```

**Comment by dospunk** [comment]
I feel like at this point naming the section `getters` would be misleading to new users, since its properties wouldn't just be for *get*ting things anymore

**Comment by posva** [comment]
That's true. I think at this point, with the new function syntax in the beta where one can directly use a `computed`, this is no longer needed

**Comment by andrei-gheorghiu** [comment]
Is this implemented? I have this use case:

```js
import { titleCase } from 'lodash-es';

export const useDataSource = defineStore('some-store', {
  state: () => ({
    _name: "",
    lcid: ""
  }),
  getters: {
    name: {
      get(): string {
        return this._name || titleCase(this.lcid);
      },
      set(value: string) {
        this._name = value;
      },
    }
  }
})
```
I tried both the above and with `computed()` wrapper. TypeScript quite upset.
@posva , what do you mean by _"the new function syntax"_?

Would it work if I used a `computed({ get, set })` on a state prop?

Edit: nope, not really...
![image](https://user-images.githubusercontent.com/7866021/153965110-a79ca3ba-f540-463c-a44a-11377b4bc7d4.png)
___

Ok, so here's what works, as far as TS is concerned:
```ts
    getters: {
      name() {
        return computed({
          get(): string {
            return (
              useDataSource()._name ||
              titleCase(useDataSource().lcid)
            );
          },
          set(value: string) {
            useDataSource()._name = value;
          },
        });
      },
    }
```
P.S: TS still gets upset when I try to assign to `name`: I can't assign to a 'read-only' property. For what it's worth, this is in a Vue2 using `@vue/composition-api`. 

If you were to add setters to a pinia store, I find an appropriate name for a collection of such `getter/setter`s would be `computed`, which matches the OptionsAPI. But it could also have a different name, since `data: () => reactiveObj` is called `state` here, which is, IMHO, appropriate.

**Comment by tintin10q** [comment]
A computed section would be nice to have in the store as they are computed anyways and otherwise the ui has to deal with it.

**Comment by dmolesUC** [comment]
@posva @andrei-gheorghiu I'm also not clear on what's meant by "new function syntax". Is that the Pinia 2.x syntax with `(state) => {}`?

```js
getters: { 
  foo: (state) => { ... } 
}
```

Is the idea that one should write something like this?

```js
getters: { 
  foo: (state) => computed({
    get: { return state.bar },
    set(v): { state.bar = v }
  })
}
```

**Comment by jd-solanki** [comment]
Can we have setter with pinia getter? I am unable to achieve it.

**Comment by dmolesUC** [comment]
@jd-solanki I don't know if this is the preferred syntax now, but what I've been doing is this:

```js
import { defineStore } from 'pinia'
import { computed, ref } from 'vue'

// note 'options' argument is an arrow function, not an object literal
export const useStore = defineStore('myStore', () => { 

  // state
  const foo = ref(null)

  // ordinary (if contrived) Vue computed property w/getter and setter
  const isBar = computed(() => {
    get() {
       const fooVal = foo.value
       return (!!fooVal) && (!!fooVal.bar)
    },
    set(v) {
       const fooVal = foo.value || {}
       fooVal.bar = !!v
       foo.value = fooVal
    }
  })

  return { foo, isBar }
})
```

I assume this is the "new function syntax" mentioned above, but I don't really know -- it doesn't seem to be documented anywhere in the [Guide](https://pinia.vuejs.org/introduction.html). It's less structured than the `state`/`getters`/`actions` syntax but much more flexible.

**Comment by lalmat** [comment]
It will be very cool to get the get/set pattern available in pinia getters.

We work with dexie (indexedDb) and we wish to use the liveQuery of Dexie to have a property updated as soon as the indexedDb is updated. It work well, but when we wish to update an item of an array, LiveQuery doesn't update database (it's readonly).

Being able to update the db in a set statement (while the get is linked to the liveQuery) can be very useful.

**Comment by dmolesUC** [comment]
@lalmat if you switch to the ["setup stores"](https://pinia.vuejs.org/core-concepts/#setup-stores) functional store definition syntax using ordinary Vue computed properties (see contrived example [above](https://github.com/vuejs/pinia/issues/447#issuecomment-1176557293)) you should be able to do this.

**Comment by reynard80** [comment]
We've tried the example [above](https://github.com/vuejs/pinia/issues/447#issuecomment-1176557293), but it does not work. Maybe because the getter is import as a `ref` in the Vue component, using `storeToRefs`?

**Comment by dmolesUC** [comment]
@reynard80 is your code somewhere I can look at it? Here's a non-contrived example, if that helps: [store](https://github.com/BerkeleyLibrary/galc-ui/blob/3b894f4/src/stores/search.ts#L80-L92), [component](https://github.com/BerkeleyLibrary/galc-ui/blob/3b894f4/src/components/Suppressed.vue#L6)

**Comment by reynard80** [comment]
@dmolesUC Thanks for your example, that's what I'm trying to achieve indeed.

We don't have the code easily available somewhere. The difference I'm seeing is that we're using Vue 2.7, and there seem to be more problems with using Pinia in Vue 2.7 components.

For example, this `page` is imported as a `ref`, not a `WritableComputedRef`, which it is. The setter doesn't work. (It's part of a DataTable component.)

![afbeelding](https://user-images.githubusercontent.com/32482953/216269586-a2534b8a-feac-4b63-a076-c588160ea220.png)

![afbeelding](https://user-images.githubusercontent.com/32482953/216269767-7f52e11f-e4bf-4ee6-a53d-70a2f894f340.png)

![afbeelding](https://user-images.githubusercontent.com/32482953/216269384-5bfdda75-2db3-440b-b0b3-cc7835977370.png)

**Comment by reynard80** [comment]
@dmolesUC We got it working. We made an unrelated mistake in the component. Thanks for your reply, and confirming that it should work.

**Comment by djeikyb** [comment]
The [syntax above](https://github.com/vuejs/pinia/issues/447#issuecomment-1176557293) doesn't work with today's pinia. The interface to write against is:

```ts
export declare interface WritableComputedOptions<T> {
    get: ComputedGetter<T>;
    set: ComputedSetter<T>;
}
```

Rewriting the example (without compiling it 😬..)

(redacted, cause i screwed it up. see: https://github.com/vuejs/pinia/issues/447#issuecomment-1455285437)

**Comment by bonafideduck** [comment]
@djeikyb , your "rewritten" code doesn't use WritableComputedOptions.

**Comment by djeikyb** [comment]
I knew I should've taken the extra few minutes to contrive a compiling example..

So here's a typescript example of a public (computed) getter and setter that wrap a private reactive variable:

```ts
import { defineStore } from "pinia";
import {
  computed,
  ref,
} from "vue";

export const useStore = defineStore("myStore", () => {

  const _innerName = ref<string | null>(null);
 
  const name = computed<string | null>({
    get: () => {
      return _innerName.value;
    },
    set: (v) => {
      _innerName.value = v;
    },
  });

  return { name };
});
```

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/794743/222998438-7ab5e2ce-9c00-48d1-8151-f38f97e18a11.png">

**Comment by timolson** [comment]
So the official answer is "rewrite all your store code in order to be able to add one setter?"  OMFG

**Comment by andrei-gheorghiu** [comment]
It's an alternative syntax.
Don't forget you have Composition available. So you can do a component
level mapper in a file and then call it in any number of components,
without even touching the store.

**Comment by Snipeye** [comment]
Sorry to necro, but I can't seem to find a way to make the getter/setter work when using the "options API" version of defining a store (call me old-fashioned).  Could I get an example?

```
getters: {
  computedValue: {
    get() {
      return this._someVal;
    },
    set(newVal) {
      this._someVal = newVal;
    }
  }
}
```

(Obviously not necessary for the given example) doesn't seem to work - I get a `TypeError: getters[name].call is not a function`.

**Comment by andrei-gheorghiu** [comment]
For what it's worth, this **_can_** be achieved using the _"classic"_/Options API store syntax, by placing a reactive reference outside the store and using a computed setter/getter in the store's state:

```typescript
import { someValidation } from '@utils/validators'
import { defineStore } from 'pinia'
import { ref, computed} from 'vue'

const local= ref(0)

export const useSomeStore = defineStore('some-store', {
  state: () => ({
    someThing: computed({
      get() {
        return local.value
      },
      set(val) {
        if (someValidation(val)) {
          local.value = val
        } else {
          console.warn(`${val} is not a valid value for some-store.someThing!`)
        }
      }
    })
  })
})
```
I've placed a more detailed answer [on StackOverflow](https://stackoverflow.com/a/79361885/1891677). Please read the note at the bottom about the slightly different behavior between the two syntaxes. If direct access to the *"local"* state is not a concern (as it is in the case of the SO question), the slight difference can also be fixed by placing the local state in the store's state, besides the computed value using validation.

**Comment by ratijas** [comment]
@andrei-gheorghiu 

Local can be placed inside the state factory lambda:

```ts
  state: () => {
    const local = shallowRef(0);
    someThing: computed({
      get() {
        return local.value;
      },
      set(newValue) {
        local.value = newValue; // <- type error: newValue is Ref<number, number>
      },
    }),
  }
```

However, regardless of scoping concerns, TypeScript is unhappy with `someThing`'s type, because apparently Pinia is unable to flatten `Ref<number>`, so in the setter you kinda can't assign a `newValue: Ref<number>` to a `local.value: number`
