### ISSUE TITLE
$set(ting) property of an object 

### ISSUE THREAD

**Issue by delcon** [posva/pinia#452]
In Vue 2 you sometimes need to do a vm.$set  to declare a reactive property.  
Reading Pinia documentation, my best guess was to $patch.
### Reproduction
```javascript
export const Store = defineStore({
   id: "Store",
   state() {
      return {
         myArray: [
            { foo: "fooValue"},
         ],
      };
   },
   actions: {
      arrayUpdate(index, key, value) {
         this.myArray[index][key] = value
         this.$patch({
            myArray: this.myArray
         })
      },
   },
});
```

### Steps to reproduce the behavior
```javascript
arrayUpdate( 0, 'bar', 'barValue')
```

### Expected behavior

Adding reactive `bar` - Property

### Actual behavior

This did not work reliably

### Workaround

```javascript
export const Store = defineStore({
   id: "Store",
   state() {
      return {
         myArray: [
            { foo: "fooValue"},
         ],
      };
   },
   actions: {
      arrayUpdate(index, key, value) {
         this._p.Vue.set(this.myArray[index], key, value)
      },
   },
});
```
### Proposal
Make this.$set, this.$delete available (feels like vue).  
Or maybe this is already handled, then it would be helpful to have it in documentation

**Comment by posva** [comment]
You have to use `Vue.set()` like with Vuex 3 for Vue 2. I guess we could add a note like a warning in the state page, like the note on Vuex docs: https://vuex.vuejs.org/guide/state.html#single-state-tree

**Comment by Sjoerd82** [comment]
Hint: add `import Vue from 'vue'` to the store. Note to the documentation writers, things like importing Vue within a vue project are not really standard so would be nice to mention that.
