### ISSUE TITLE
Typescript doesn't recognize properties on `this` in standalone ts file

### ISSUE THREAD

**Issue by shayneo** [posva/pinia#453]
### Reproduction

We're working on a stand-alone lib of "common" pinia stores that we can re-use across different front end projects within our team. Kinda like a library of pinias. It's working, but we seem to be losing type detection on `this` when we setup pinia in a stand alone project. I've attached an example of how we have things setup.

### Steps to reproduce the behavior

1. Open `shared-stores` example project attached
2. go to `cool-store.ts`
3. See error

### Expected behavior

properties added to `state` would be recognized when accessing `this` in `actions` or `getters`

### Actual behavior

these properties are not recognized

### Additional information
<img width="413" alt="Screen Shot 2021-04-26 at 3 59 36 PM" src="https://user-images.githubusercontent.com/1341253/116150178-aa7d7f80-a6a8-11eb-83b4-2a6686a44de9.png">

[shared-stores.zip](https://github.com/posva/pinia/files/6380298/shared-stores.zip)

**Comment by posva** [comment]
Can you provide a github reproduction? I don't take zip files for security reasons

**Comment by kruebling** [comment]
@posva, working on this with @shayneo, went ahead and created that github repo for ya 👍🏻 

https://github.com/kruebling/shared-stores

**Comment by posva** [comment]
Remove that store-shim.d.ts, it's removing all existing types from pinia

**Comment by posva** [comment]
How did you find yourself adding that declare module 'pinia'? 🤔

**Comment by kruebling** [comment]
@posva, adding that to store-shim.d.ts resolves this error when importing


```
import { defineStore } from 'pinia'
Cannot find module 'pinia' or its corresponding type declarations.
```

Unfortunately, deleting that file didn't resolve the issue though.
![Screen Shot 2021-04-26 at 2 54 25 PM](https://user-images.githubusercontent.com/26529792/116155727-591cc280-a69f-11eb-8282-a0cf12bdfc9b.png)

**Comment by kruebling** [comment]
Ah! Restarting VSCode fixed it, thanks for your help!

**Comment by posva** [comment]
No worries, remember there is a [Discord chat](https://vue-land.js.org/) to ask quick questions! 
You can also use <kbd>cmd + shift + p</kbd> and search for _restart ts_

**Comment by shayneo** [comment]
Thanks for the quick response @posva and the amazing work on this lib!

We'll jump in the discord chat first if we hit other snags. @kruebling and I are working on a mono-repo setup for multiple vue 3 apps, which is also our first big jump into typescript. Maybe we'll write a blog if it works out 😄
