### ISSUE TITLE
ORM like Vuex ORM

### ISSUE THREAD

**Issue by vincentcordel** [posva/pinia#457]
Do you plan on building an ORM on top of Pinia?
Similar to Vuex-ORM would be awesome!

**Comment by posva** [comment]
I don't plan on building it but the WIP plugin API should allow anybody needing it to build their own or even to build a connection layer for the existing vuex-orm 🙂

**Comment by CodeDredd** [comment]
@musixite @posva A bit later but done. Made a custom plugin based on vuex-orm-next. 😉 
See https://github.com/CodeDredd/pinia-orm.
Feedback welcome ❤️ 
And thanks @posva for the code insperations 😃
