### ISSUE TITLE
Docs - Nuxt buildModules entry

### ISSUE THREAD

**Issue by charlie17** [posva/pinia#463]
The [docs](https://pinia.esm.dev/ssr/nuxt.html) say to add `'@nuxtjs/composition-api'` to the `buildModules` section of nuxt.config.js, but this caused an error:

`Nuxt Fatal Error - TypeError: Module should export a function: @nuxtjs/composition-api`

Once replacing with `'@nuxtjs/composition-api/module'` as shown [here](https://composition-api.nuxtjs.org/getting-started/setup/), all is well.

While I'm here and thinking of the docs: It might be helpful on [the Intro page](https://pinia.esm.dev/introduction.html) to include `import { useCounterStore } from "/xxx";` in the second code block. I know that seems obvious but for the less initiated it could help to be explicit...given the advice further on to `define each store in a different file`.

Thanks for the great work

**Comment by posva** [comment]
Thanks, I added the suggestion!
