### ISSUE TITLE
Plugin doesn't show in vue dev tools

### ISSUE THREAD

**Issue by slauzinho** [posva/pinia#471]
### Reproduction

Trying to debug a pinia store but it doesn't seem to show in the vue dev tools anymore.

Example repo: https://github.com/slauzinho/pinia-plugin-example

### Steps to reproduce the behavior

1. Go to `Vue Dev Tools`

### Expected behavior

Pinia store being loaded

### Actual behavior

No store gets loaded

### Additional information

Vue Dev tools - 6.0.0 beta 8

![image](https://user-images.githubusercontent.com/445345/117031813-da580300-acf8-11eb-94f6-ddca7de44161.png)

**Comment by posva** [comment]
Fixed in 8e6a9ec3f519fb14319e17598800fe64315c92e1 and released in alpha.15
