### ISSUE TITLE
Displaying multiple stores in Vue dev tools (beta) fails

### ISSUE THREAD

**Issue by piscis** [posva/pinia#472]
### Reproduction

Hi I noticed that if you have multiple stores registered in pinia only the first one gets displayed in dev tools.

### Steps to reproduce the behavior

1. Go to the pinia example at: https://j4qzw.csb.app/
2. Open Vue Dev Tools (Vue.js devtools 6.0.0 beta 8)
3. Open the Dev Tools Inspector and check for the pina stores entries
4. Only the first store initialized is shown (in this case its user)

### Expected behavior
If a user registers multiple stores all stores should be listed in the vue dev tools when inspecting a component.

### Actual behavior

Only the first store that gets initialized is show. Example:

Two stores are registered:

![screen1](https://user-images.githubusercontent.com/326163/117051533-f1a5e900-ad16-11eb-8006-52df345e1862.png)

---------

Only the first is listed in the inspector:
![screen2](https://user-images.githubusercontent.com/326163/117051554-f79bca00-ad16-11eb-827e-cf74ab8cabd8.png)

It seems like only the first store, that is registered, is listed in the vue dev tools inspector.

### Additional information

- Vue.js devtools 6.0.0 beta 8
- pinia 2.0.0-alpha.15

**Comment by posva** [comment]
fixed and released 🙂
