### ISSUE TITLE
Better documentation of Shared Getters

### ISSUE THREAD

**Issue by yannick-milanetto** [posva/pinia#48]
Hello, 

I noticed in the doc one very important point:

> There is one important rule for this to work: the useMainStore (or any other useStore function) must be called inside of deferred functions

Further in the doc, when speaking about **shared getters**, we have this example:
```
import { computed } from '@vue/composition-api'
import { useUserStore } from './user'
import { useCartStore } from './cart'

export const summary = computed(() => {
  const user = useUserStore()
  const cart = useCartStore()

  return `Hi ${user.state.name}, you have ${cart.state.list.length} items in your cart. It costs ${cart.price}.`
})
```

I tried it, by importing this shared getter from a component (note: i'm using TS):
```
import { createComponent } from '@vue/composition-api';
import { summary } from '@/store/shared-getters';

export default createComponent({
  name: 'Home',
  setup() {
    ...
    return { summary };
  }
});
```

and get an error : `Error: [vue-composition-api] must call Vue.use(plugin) before using any function.`

I guess it's because as soon as we import summary it gets evaluated and we fall right into the rule above : we must call it inside a deferred function

So what i had to do (but i'm not sure if this is the right way to do it) is to export summary as a function:
```
export default function summary() {
  return computed(() => {
    ...
  });
}
```

After that it worked properly. If this is intended behavior, i would recommend to document it because it may not be obvious how to implement shared getters based on the current documentation. If this is not intended behavior, i would appreciate any guidance on how to make it work 😎 

Cheers
Yannick

**Comment by posva** [comment]
> I guess it's because as soon as we import summary it gets evaluated and we fall right into the rule above : we must call it inside a deferred function

Yes, and your workaround is the way to go for the moment. This won't be an issue with Vue though.
I think that going with something like the function `pinia`  would also replace the shared getters sections once it's fully implemented

**Comment by posva** [comment]
The readme was updated but I forgot to notify here
