### ISSUE TITLE
Export StoreDefinition type

### ISSUE THREAD

**Issue by shayneo** [posva/pinia#480]
### What problem is this solving

I want to write a function that generates a StoreDefinition based on some arguments, but I can't set the proper return type on the function in ts because `StoreDefinition` is not exported.

### Proposed solution
Export `StoreDefinition` so we can do stuff like...
```
import { defineStore, StoreDefinition } from 'pinia'

export const storeBuilder = (coolLevel:string): StoreDefinition =>  {
  let coolPercent = 0
  if (coolLevel === 'max') {
    coolPercent = 1
  }

  const s =  defineStore({
    id: `cool-store-${coolLevel}`,
    state: () => ({
      coolPercent,
    })
  return s
}
```
This is a silly example, but the goal is to write a function that generates the store that works differently when different arguments are passed in.

### Describe alternatives you've considered
Could try typing as `any` 😢

**Comment by posva** [comment]
why not omit the return type and let TypeScript infer it?

StoreDefinition has 4 generics that must be typed (Id, State, Getters, and Actions). It's going to be way more troublesome

**Comment by shayneo** [comment]
good idea 😄
