### ISSUE TITLE
Can't reset state when passing a reference object as the initial value

### ISSUE THREAD

**Issue by slauzinho** [posva/pinia#484]
### Reproduction

I'm not 100% sure if this is the expected behaviour but when I define the store like this:

```typescript
export const counterInitialState = {
  counter:  0,
};

const useCounter = defineStore({
  id: 'counterStore',
  state: () => counterInitialState,
  actions: {
    increment() {
      this.counter++;
    },
    decrement() {
      this.counter--;
    },
  },
});
```

If I do `counterStore.$reset()` it doesn't reset the store.

I can fix it by not using the initial state variable or by making a copy of the initial state using object spreading like:

`state: () => {...counterInitialState}` 

or if the state is too nested:

`state: () => JSON.parse(JSON.stringify(counterinitialState))`

### Expected behavior

Should reset the store to the initial state

### Actual behavior

Nothing happens

### Additional information

Demo repo: https://github.com/slauzinho/pinia-reset-store-example

**Comment by posva** [comment]
This is expected. Reset only calls the function to create a new object. If possible, build the object inside of the state method

**Comment by Blackfaded** [comment]
A little addition from me:

If you have deep nested states like

```ts
const deepState = {
someField: "",
someOtherField: ""
}

const state = {
deep: { ...deepState},
someField: ""
}
```

you cant write your state like

```ts
state: () => ({...state})
```
because the deepState does not get copied and only the reference is used.

I ended up using lodashs `cloneDeep` function like so:

```ts
const deepState = {
someField: "",
someOtherField: ""
}

const state = {
deep: deepState,
someField: ""
}

state: () => cloneDeep(state),


```

**Comment by quantuminformation** [comment]
even state: () => ({...state})
 doesn't work for me

**Comment by Blackfaded** [comment]
You should use deep cloning. The rest operator only copies top level state.

**Comment by quantuminformation** [comment]
ah great thx
