### ISSUE TITLE
Support ref unwrapping in `state`

### ISSUE THREAD

**Issue by posva** [posva/pinia#491]
Currently, passing a ref to the state is unwrapped because the store is a reactive object but the types do not reflect it:

```ts
const useStore = defineStore({ state: () => ({ n: ref(0) }) })

const store = useStore()
store.n // Ref<number> instead of number (the actual type)
```

This is useful to use external _use*_ functions: https://github.com/posva/pinia/discussions/485#discussioncomment-718096

**Comment by philippedasilva-orizone** [comment]
Any hint @posva where to look at exactly so that I don't get to understand the whole project but just focus on this part of the code? Or do you believe it'd have impacts on multiple parts?

**Comment by posva** [comment]
I think this should be a possible contribution, using a type UnwrapRef from vue or inspiring yourself from the typing of `reactive` should help. It should be a typescript only change
