### ISSUE TITLE
An option to create a non-reactive state?

### ISSUE THREAD

**Issue by songololo** [posva/pinia#494]
### What problem is this solving

At the moment I am trying to store an object instance (a Mapbox map instance created using "new" syntax) inside a store's state so that I can share this map instance in various components. However, it doesn't appear possible to use methods associated with this map instance because they seem to be hidden by the proxy object. I am assuming this is intended and a side-effect of how the new reactivity system works (though this used to work in Vue 2 / Vuex)

### Proposed solution

Assuming there is no workaround to access the nested method (e.g. `myStore.mapInstance.getZoom()`) then it would be nice to have a way to turn-off reactivity for a specific item in the state, or else to have a separate non-reactive state where it is possible to store and share complex objects which otherwise wouldn't work.

### Describe alternatives you've considered

Vuex 4.

**Comment by posva** [comment]
Isn't markRaw from Vue what you're looking for?

https://v3.vuejs.org/api/basic-reactivity.html#markraw

**Comment by songololo** [comment]
I wasn't aware of `markRaw` and it is exactly what I needed. Everything is working perfectly now.

Thanks so much 👍
