### ISSUE TITLE
[Vue2] State as default Action parameters

### ISSUE THREAD

**Issue by jordypereira** [posva/pinia#520]
### Steps to reproduce the behavior
https://codesandbox.io/s/fast-river-jmtl3?file=/src/store.js

I was calling this action in a regular `js` file.
Having state as default parameters gives a silent error. Had to debug to find out why the function was not getting called.

```js
async fetchNotifications({page = this.notifications.page, limit = this.notifications.limit}) {
 // fetch
}
```
![Screenshot 2021-05-31 at 16 04 10](https://user-images.githubusercontent.com/14983205/120205121-e1a3fb00-c229-11eb-866f-7566a25f0841.png)

**Comment by jordypereira** [comment]
Actually can't use destructuring either

![Screenshot 2021-05-31 at 16 10 40](https://user-images.githubusercontent.com/14983205/120205868-bff74380-c22a-11eb-9764-f6f7865a9629.png)

**Comment by jordypereira** [comment]
This works:
```js
async fetchNotifications({page, limit} = {}) {
````

**Comment by posva** [comment]
I will need a boiled down repro to check further. You can use the demo codesandbox

**Comment by jordypereira** [comment]
Made a small repro https://codesandbox.io/s/fast-river-jmtl3?file=/src/App.vue

Let me know if you need some more examples

**Comment by posva** [comment]
Ah yeah, this is not related to Pinia, it's about optional parameters with destructuring. This is the correct version:

```js
setNameFromState({ firstName = this.firstName, lastName = this.lastName } = {}) {
      this.name = firstName + ' ' + lastName;
    },
```
