### ISSUE TITLE
Use `@vue/devtools-api` in Pinia v1

### ISSUE THREAD

**Issue by posva** [posva/pinia#521]
Right now, pinia v1 uses an internal API of the devtools that is used by Vuex to take its spot, but the [beta channel of vue-devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg) ([Links from docs](https://devtools.vuejs.org/guide/installation.html#chrome)) now supports Vue 2 applications, allowing us to drop the current implementation and **maybe even join v1 and v2 branches** but it seems unsure due to some features not existing in Vue 2.

## Existing problems

These would be solved by using the `@vue/devtools-api`:

- Can only detect mutations/patch but no actions
- Therefore: no grouping of mutations per action call

These cannot be solved directly due to differences between Vue 3/2 but could maybe patched in a different way. Still unsure if they are worth the effort:

- No concrete payload of changes for direct mutations (lacking DebuggerEvent in watchers in Vue 2)

**Comment by bmacher** [comment]
We could maybe update the [documentation](https://pinia.esm.dev/core-concepts/state.html#mutating-the-state) to tell the user that there is a payload in the mutation when using `$patch()` but not when accessing state directly.

If so, do you mind if I update the documentation?

**Comment by posva** [comment]
Thank you but I dont think it's a good idea because one should not prioritize using patch just because of devtools

**Comment by posva** [comment]
Pinia v2 now supports Vue 2 🎉 . It's using the latest versions of pretty much everything, so it might be a bit harder to test for newcomers until Vue Devtools release a new version on their beta channel but instructions are available in the changelog
