### ISSUE TITLE
Disable console log

### ISSUE THREAD

**Issue by anncwb** [posva/pinia#524]
### Reproduction

After the project runs, the log will be printed in the console, can it be closed?

![image](https://user-images.githubusercontent.com/28132598/120737349-82433500-c520-11eb-9e3c-fb2f13b37b53.png)

### Actual behavior

A clear and concise description of what actually happens.

**Comment by posva** [comment]
Oops! Forgot about this debug log

**Comment by anncwb** [comment]
@posva Can the beta.3 version be released? This print log will always be output on my console😂
