### ISSUE TITLE
Type optimization

### ISSUE THREAD

**Issue by anncwb** [posva/pinia#525]
### Reproduction

As shown in the screenshot below, I must pass in parameters in the function to ensure that the type verification passes. Even if my `state` is not used, I still need to pass it

![image](https://user-images.githubusercontent.com/28132598/120737489-ba4a7800-c520-11eb-9549-8ef031fc3b5f.png)

### Actual behavior

A clear and concise description of what actually happens.

**Comment by posva** [comment]
add a return type to the getter when using `this` inside it or use the `state` parameter: https://pinia.esm.dev/core-concepts/getters.html#getters
