### ISSUE TITLE
$patch method mutates the state property while trying to update another one

### ISSUE THREAD

**Issue by Oleksii14** [posva/pinia#528]
### Reproduction

Clone repo https://github.com/Oleksii14/pinia-bug
`yarn`
`yarn serve`

### Steps to reproduce the behavior

1. Click on the items, see the error in the console about vue keys
2. See that when you click on the items, I don't change the array. I update only selected property
3. See that when I am trying to update one state property, $patch mutates another too

### Expected behavior

$patch mutates only the property that I am passing in the state object

### Actual behavior

I think $patch is not working properly because it updates the state properties that were not requested

### Additional information
-

**Comment by posva** [comment]
As a workaround, directly set the property:

```js
store.selectedItem = ...
store.$patch(state => {
  state.selectedItem = ...
})
```

**Comment by Oleksii14** [comment]
@posva can you clarify, was this commit included in the vue2 version? Currently, I am using 0.5.2

**Comment by posva** [comment]
yeah, it's fixed: https://github.com/posva/pinia/commit/581bd08d978050fc5b9e8c6b32147cf3798b33cb#diff-bc88fe45113de76e465408cc245572d27de83d31216672b06d1d2c16ccac7801R130

do you have a new failing test case? There are a few cases that cannot be achieved with the object syntax for `$patch` but they revolve around partial nested objects

**Comment by Oleksii14** [comment]
No, just asking for clarification 👍 

All works
