### ISSUE TITLE
Infinite loop when re-opening Vue Devtools

### ISSUE THREAD

**Issue by rijkvanzanten** [posva/pinia#532]
### Reproduction

When I close and re-open the Vue Devtools, it starts an infinite loop with an error `backend.js:1604 Inspector pinia not found`. As of right now, I have no clue what causes it, but it seems to happen consistently.

### Steps to reproduce the behavior

https://user-images.githubusercontent.com/9141017/121444255-2d0e8580-c95d-11eb-9cf0-214f134e44f0.mp4

### Additional information

* Microsoft Edge Version 91.0.864.41 (Official build) (x86_64)
* vue-devtools v6.0.0-beta.14
* pinia@2.0.0-beta.2
* vue@3.1.1

**Comment by posva** [comment]
Do you have a boiled down repro so I can check?

**Comment by rijkvanzanten** [comment]
Here you go!

https://github.com/rijkvanzanten/pinia-devtools-example/

This is the default output from `npm init @vitejs/app` with Pinia installed, using the basic example from the docs.

**Comment by posva** [comment]
I imagine something changed in the api and broke this so forcing an older version of the devtools api could do but I'm not sure.

Will have to investigate. I wonder if it has anything to do with https://github.com/vuejs/vue-devtools/issues/1475

**Comment by philippedasilva-orizone** [comment]
Hi @posva 

I got the same behavior and I believe I may introduce another clue on what might going wrong:

As I change the state of my stores (adding/removing fields), it seems vue-devtools or your current support implementation doesn't live well with undefined values while other fields may already exist... when using some kind of local or session storage. 
Maybe this just needs a simple check on the passed state and see if it matches the expected types. If not, a simple `$reset` call might do the trick. Still feels like a hack but that might work (sry, don't know much about vue devtools)

**Comment by posva** [comment]
This got fixed in vue-devtools next branch (https://github.com/vuejs/vue-devtools/commit/3752c89d3fbd8b77b35114ea020682a7a7f542c8)
