### ISSUE TITLE
Maxmium recursive updates exceeded

### ISSUE THREAD

**Issue by slauzinho** [posva/pinia#541]
### Reproduction

Repro example see master branch: https://github.com/slauzinho/pinia-bug-repro

When rendering a value returned by an action that uses another store that has already been initialised it get:
`Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.`

### Steps to reproduce the behavior

```typescript
const useCounterStore = defineStore({
  id: "counterStore",
  state: () => ({
    currentValue: 0
  }),
  actions: {
    increment() {
      this.currentValue++;
    },
    decrement() {
      this.currentValue--;
    }
  }
});
```

```typescript
const useWarningStore = defineStore({
  id: "warningStore",
  actions: {
    isBigger(value: number) {
      const counterStore = useCounterStore();
      return counterStore.currentValue > value;
    }
  }
});
```

My Warning Page is like this:

```vue
<template>
  <div>Is Value bigger then 4 {{ warningStore.isBigger(4) }}</div>
</template>
```

My homepage:

```vue
<template>
  <div>Hello from home</div>
  <div>Current count value is: {{ counterStore.currentValue }}</div>
  <div>
    <button @click="counterStore.increment">Increment</button>
    <button @click="counterStore.decrement">Decrement</button>
  </div>
  <router-link to="/warning">Go to warning screen</router-link>
</template>
```

On the homepage we initialise the `counterStore` and on the Warning page we initialise the useWarningStore.

If I go from Homepage to the Warning page I get the following warning:
`Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.`

- If I go directly to the Warning page I don't get an error.
- If I initialise the `useWarningStore` on the homepage I don't get the error
- If I use computed instead of calling `warningStore.isBigger(4)` directly I don't get the error (see this [branch](https://github.com/slauzinho/pinia-bug-repro/tree/computed))

This seems to happen only on certain cases, for instance this [example](https://github.com/slauzinho/pinia-bug-repro/tree/works) is very similar but doesn't cause the cursive warning.

### Expected behavior

No recursive issues

### Actual behavior

Gives recursive warning crashing the page in production.

**Comment by posva** [comment]
This is an interesting one, not sure if it's possible to fix it as the correct way of doing it would be with a getter:

```js
  getters: {
    isBigger() {
      const counterStore = useCounterStore()
      return (value: number) => counterStore.currentValue > value
    },
```

Maybe I need to add the `stores` API like in Vuex 5 RFC and deprecate that usage.

**Comment by slauzinho** [comment]
Yeah I end up fixing it by using `computed` inside my component, but I think your approach is better.  
Just a question, for the cases where I use an action like a getter but I need to pass it a value I should use a getter that returns a function like you suggested right?

**Comment by posva** [comment]
yes

**Comment by posva** [comment]
BTW, even outside of Pinia, you can use `toRaw()` to read some reactive object without having Vue tracking it (https://v3.vuejs.org/api/basic-reactivity.html#toraw)

**Comment by posva** [comment]
I found a bit more about this. It's caused by the Proxy used in the devtools plugin (https://github.com/posva/pinia/blob/v2/src/devtools/plugin.ts#L389). I couldn't manage a way to suppress the warning but at least, **it doesn't affect production code**.

**Comment by slauzinho** [comment]
I _think_ it's also happening in prod.

I uploaded the initial repro to netlify: https://hopeful-aryabhata-22a5f7.netlify.app/

You can see if you navigate to the `warning` screen it crashes the page, but it doesn't show any warnings on the console.

**Comment by posva** [comment]
I tested with the repro with updated deps, and both dev and prod work 🎉

**Comment by slauzinho** [comment]
Awesome, thanks for your help 🙏
