### ISSUE TITLE
Allow both Vuex and Pinia states being shown in vue-devtools

### ISSUE THREAD

**Issue by agualis** [posva/pinia#551]
### What problem is this solving

I have a big legacy `Vue 2 + Vuex` project and I want to migrate to pinia in small increments. It would be very important to have both states available in devtools during the migration process but I see that just Vuex state is shown. 

I created this [repo](https://github.com/agualis/vuex-and-pinia) with a simple counter example implemented in both Vuex and Pinia to reproduce the issue. In this image below you can see how Pinia direct mutations are shown but the state is not:   

![Screenshot 2021-06-23 at 11 44 06](https://user-images.githubusercontent.com/1316240/123075238-57117e80-d418-11eb-8b3f-027062640f0c.png)

### Proposed solution

I didn't check the old Vue-devtools API in detail so I cannot tell how complex this fix would be.

**Comment by posva** [comment]
Unfortunately, this is not possible. A better solution would be to make Pinia v1 use the new devtools API like v2 does (#521).

For the time being, maybe adding a check on a global property like `window.DISABLE_PINIA_DEVTOOLS` could help you. Try out changing the dist file in node_modules and see if this helps. It could still be very manual to switch between Vuex and Vue devtools.

Another possibility is having both devtools installed v5 and v6 (beta). The beta wolud show the Vuex devtools while the v5 would show you Pinia

**Comment by agualis** [comment]
Yay! Using both devtools and directly updating the `Vuex node_modules` will be handy enough during the transition period. 

<img width="679" alt="Screenshot 2021-06-23 at 16 22 30" src="https://user-images.githubusercontent.com/1316240/123114396-8daebf80-d43f-11eb-8911-d3c9db032fb7.png">

In my case (using Vuex 3 with ESM imports) I just needed to add `useDevtools = false` in `vuex.esm.js`:

```javascript
  var useDevtools = options.devtools !== undefined ? options.devtools : Vue.config.devtools;
  useDevtools = false; // Manually disabling Vuex to see pinia state in devtools 5.X
```

Thanks for your amazing work. Pinia rocks! 🍍🤘

**Comment by KicKerBNU** [comment]
For those who want or need  to use VueEx and Pinia at the same time on Vue 2.7:

```javascript
import { createPinia, PiniaVuePlugin } from 'pinia';
import store from './store';


Vue.use(PiniaVuePlugin);
const pinia = createPinia();
new Vue({
  ...,
  store,
  pinia,
  ...
});
``` 

Credits: [clancy-john](https://www.reddit.com/user/clancy-john/)
