### ISSUE TITLE
Vue warning when using store in child component with `v-for`

### ISSUE THREAD

**Issue by arnoson** [posva/pinia#552]
### Reproduction
I have an App component and multiple child components that I render with `v-for`. When the child components use my pinia store I get the following warning: 
```
[Vue warn]: The `compilerOptions` config option is only respected when using a build of Vue.js that includes the runtime compiler (aka "full build"). Since you are using the runtime-only build, `compilerOptions` must be passed to `@vue/compiler-dom` in the build setup instead.
- For vue-loader: pass it via vue-loader's `compilerOptions` loader option.
- For vue-cli: see https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-loader
- For vite: pass it via @vitejs/plugin-vue options. See https://github.com/vitejs/vite/tree/main/packages/plugin-vue#example-for-passing-options-to-vuecompiler-dom
```

This only happens when I expose the store to the template.

The warning is shown two times at the beginning. In the project I'm using this setup I sync a draggable div's position with the store and get hundreds of these messages which makes it unusable.

### Steps to reproduce the behavior

Here is repository to reproduce the warning: https://github.com/arnoson/pinia-warn-issue

### Additional information

I use vue 3 with vite, typescript.

**Comment by arnoson** [comment]
It seems that the behaviour is somehow related to the dev tools. The warnings only occur if I have the vue dev tools inspector tab open.

**Comment by posva** [comment]
I tried your repro with updated deps and it doesn't show any warning. But Pinia doesn't add any component so it cannot cause that warning
