### ISSUE TITLE
Vue Devtools memory and CPU usage

### ISSUE THREAD

**Issue by ljcremer** [posva/pinia#562]
### Reproduction
I created a video of the symptoms. [Link to video](https://www.loom.com/share/5c6674469d1944a38b914f749c96ab77)

### Steps to reproduce the behavior
When trying to inspect the Pinia store the memory usage goes up significantly and the CPU usage goes to 100%. 
This happens when switching between the Pinia stores. At the time of the video the stores and still quite empty but sometimes the app becomes unusable and I have to restart the tab. 

### Expected behavior
Inspect and view Pinia store contents

### Actual behavior
Very slow and sometimes locks up the application

### Additional information
    "pinia": "^2.0.0-beta.3"
Vue.js devtools : 6.0.0 beta 15

**Comment by posva** [comment]
I will need a boiled down reproduction to see if I can do anything 🙂

**Comment by ljcremer** [comment]
Can I invite you to our private repo?

**Comment by posva** [comment]
you can, but I really need a boiled down repro with only pinia and vue

**Comment by ljcremer** [comment]
Hi Posva

While we where working on a boiled down repo we found the problem with the memory usage. 

The issue was that one of the data object we wrote into the Pinia store was quite big(around 3MB) and it seems like this is what was causing the issue. 

Thanks for the help and quick response. 

We can close this issue.
