### ISSUE TITLE
[Docs] Improve the "Using the store" section.

### ISSUE THREAD

**Issue by wujekbogdan** [posva/pinia#563]
### What problem is this solving

The "Using the store" section starts from explaining the gotchas. Usually docs are written in a different way - the very first example is usually dead simple, but yet complete, code snippet that explains how do do things right - a code snippet that a user can just copy/paste without analyzing it.

In Pinia docs it's the opposite - the sections starts from an examples that tell the user how **not to** use Pinia - these are all valid and necessary information but the most important piece information is at the very bottom of the page. 

### Proposed solution

I would start from a very basic example:

``` js
export default defineComponent({
  setup() {
    const store = useStore();

    return {
      firstName: computed(() => store.firstName),
      lastName: computed(() => store.lastName),
    }
  },
})
```

It might be also a good idea to include the source code for the `useStore()` function.

Then I would explain that destructuring will break reactivity, that `useStore()` needs to be called in `setup()`, etc.

---
BTW, I would also consider moving the "Using the store" section outside the "Defining a store" section. I think that a better Idea would be to put it after "Actions" but before "Plugins".  The reason for it is that first the user needs to learn how to define state/getters/actions before they can import the store and use it.

**Comment by posva** [comment]
Yeah, thanks for the feedback. I will

- Put the component example first
- Still explain why we have 2 functions (define vs use)
- Move the example for SSR somewhere else and still link it there
