### ISSUE TITLE
Accessing store getters outside component setup fail

### ISSUE THREAD

**Issue by gagarine** [posva/pinia#564]
I try to access the getters `isLoggedIn()` defined in my store from a JS class and it fail with a `TypeError: isLoggedIn is not a function`

```js
import http from '../services/http-middleware'
import { useAuthStore } from "./../store/auth";

class apiService {
  constructor() {
    // Axio request interceptor
    http.interceptors.request.use(
      function (config) {
        const auth = useAuthStore()
        console.log(auth.token) // Correctly return the value defined in the state
        auth.isLoggedIn()  // <===== TypeError: auth.isLoggedIn is not a function
        return config;
      }
  }
}

export default new apiService()
```

```js
import { defineStore } from 'pinia'

export const useAuthStore = defineStore({
  // id is required so that Pinia can connect the store to the devtools
  id: 'auth',
  state: () =>({
      accessToken: 'faketoken'
  }),
  getters: {
    isLoggedIn() {
      if(this.accessToken) {
        return true;
      }
      return false;
    }
  }
})
```

console.log(auth) in apiService constructor give this

<img width="652" alt="Screenshot 2021-07-07 at 19 36 21" src="https://user-images.githubusercontent.com/164074/124804462-9ed8ef80-df5a-11eb-872c-dce63c088350.png">

**Comment by wujekbogdan** [comment]
You're getting an error because `auth.isLoggedIn` is not a function. It's a getter - [it's a reactive ref](https://v3.vuejs.org/api/refs-api.html#ref) (it acts as a computed property). So you should do `auth.isLoggedIn` instead of `auth.isLoggedIn()`

**Comment by gagarine** [comment]
Thanks for the reply. I think calling them getter is then a bit misleading. I reread the doc "Getters are exactly the equivalent of computed values for the state of a Store." so why not call them "computed" instead of getters?

Getter/Setter refer habitually to [mutator methode](https://en.wikipedia.org/wiki/Mutator_method) so a function.

**Comment by wujekbogdan** [comment]
I think that naming them getters is a consequence of Pinia being an evolution of Vuex where getters work the same way so the author wanted to maintain some API compatibility so that devs that migrate from Vuex to Pinia feel comfortable.

**Comment by gagarine** [comment]
I opened a feature request https://github.com/posva/pinia/issues/566
