### ISSUE TITLE
Rename getters in computed and actions in methods

### ISSUE THREAD

**Issue by gagarine** [posva/pinia#566]
From the doc "getters are exactly the equivalent of computed values for the state of a Store."

So why not call them "computed" instead of getters? Especially as getter/setter refer habitually to [mutator methode](https://en.wikipedia.org/wiki/Mutator_method) and in that case are functions.

Same go with actions: "Actions are the equivalent of methods in components.". So why not call them methods?

I understand now this is probably because Vuex use this terminology. But what is Vuex in comparison of decades of programming history ;)?

In my opinion it seem to make more sens to maintain consistency with vuejs  instead of vuex. I will not use pinia with vuex but with vuejs.

**Comment by posva** [comment]
Thanks for the proposal but this is the state management terminology and it's to make it different from component data (which is local instead of global). There has been more to the conversation before and it would be a breaking change.
