### ISSUE TITLE
Accessing other stores getters: getter function will be re-executed

### ISSUE THREAD

**Issue by xuzuodong** [posva/pinia#568]
Getters function will be re-executed when accessing from other stores, idk if it's by design, if it is, just close this issue. 

### Reproduction

https://codesandbox.io/s/delicate-surf-b4fsz?file=/src/App.vue

### Steps to reproduce the behavior

Check console integrated in code-sandbox

### Expected behavior

'uppercase called!' only been printed once. 

### Actual behavior

'uppercase called!' been printed twice. 

### Additional information

Getters function will also be called when accessing it in other store's action.

**Comment by posva** [comment]
This is by design until the next version with Vue 3.2 🥳

**Comment by posva** [comment]
Oh a temporary workaround is importing and calling useStore on a common ancestor comcopnent
