### ISSUE TITLE
Add check for duplicate Id in different stores

### ISSUE THREAD

**Issue by AlgoTrader** [posva/pinia#575]
### What problem is this solving

When two stores have identical id, stores are interchanged silently

### Proposed solution

Add a warning or error when new store is created with existing id

### Describe alternatives you've considered

Learn to live in world with pain and debug for hours

**Comment by posva** [comment]
Ah yeah, I wanted to add a dev check but never did!

> Learn to live in world with pain and debug for hours

Lol, quite an exaggeration

**Comment by posva** [comment]
I realized this is not possible when doing HMR as editing any store would mistakenly yield a warning
