### ISSUE TITLE
vue3项目，使用pinia，运行起来提示找不到这个EffectScope 方法

### ISSUE THREAD

**Issue by zhanghailong1993** [posva/pinia#589]
![image](https://user-images.githubusercontent.com/22762892/127482191-1691b595-54d7-4124-93bf-401fe71167a2.png)
![image](https://user-images.githubusercontent.com/22762892/127482251-b846abba-73fb-4fb8-934c-f96742d8f2b3.png)

**Comment by posva** [comment]
You need Vue 3.2.0-beta. Check the Changelog.md 🙂

**Comment by posva** [comment]
https://github.com/posva/pinia/issues/592
