### ISSUE TITLE
Pinia installation instructions while Vue 3.2.0 is in beta

### ISSUE THREAD

**Issue by posva** [posva/pinia#592]
Starting from v2.0.0-rc.0, pinia requires at least Vue 3.2.0, which **is currently in beta**.

If you came across an error like

```
export 'effectScope' (imported as 'effectScope') was not found in 'vue'
```

You are still on Vue 3.1.x. Read the instructions below to upgrade.

- If you are **starting a new project**, it is safe to use the beta of Vue until a stable version is released (one or two weeks from now). Change any `@vue/*` and `vue` versions in your package.json file to `3.2.0-0`:
  ```diff
  -    "vue": "^3.2.0-beta.7",
  +    "vue": "^3.2.0-0",
  -    "@vue/compiler-sfc": "^3.2.0-beta.7",
  -    "@vue/server-renderer": "^3.2.0-beta.7",
  +    "@vue/compiler-sfc": "^3.2.0-0",
  +    "@vue/server-renderer": "^3.2.0-0",
  ```
  This should install the latest beta versions of Vue.
- If you are **upgrading an existing project**
  - If you want to upgrade pinia, upgrade Vue first using the instructions above and then, upgrade pinia
  - If you don't need to or can't upgrade Vue yet, stay on `pinia@2.0.0-beta.5` until Vue 3.2.0 is released as stable

To use pinia@2.0.0-rc.0, use the `beta` dist tag:

```bash
yarn add pinia@beta
# or
npm i pinia@beta
```

**Comment by thespacedeck** [comment]
Thanks for sharing this @posva!

**Comment by joseluisgs** [comment]
Tank you for the post @posva

**Comment by gagarine** [comment]
But why running `npm update` update pinia to a version incompatible with my current vuejs?

**Comment by posva** [comment]
> But why running npm update update pinia to a version incompatible with my current vuejs?

The truth is I should have published a `beta` dist tag instead of releasing it to `next`. The real problem I'm worried about is people getting started with Pinia in a new project. People updating a package between majors should always read the changelog anyway.

I changed the dist tags so `pinia@next` still points to the last beta and added a `beta` dist tag that points to the rc that requires Vue 3.2.0-0

**Comment by francoism90** [comment]
Is this related?

```
 App •  WARNING  •  UI  in ./node_modules/pinia/dist/pinia.esm-browser.js

export 'effectScope' (imported as 'effectScope') was not found in 'vue'
```

I'm using Quasar.

**Comment by posva** [comment]
Yes, it's the same as described above, you need Vue 3.2.0

**Comment by joseluisgs** [comment]
Thank you very much @posva. For me, it is the first time with Pinia, but it 's excellent I like very much. very easy with TS.
I read and follow every change. Probably mi error was that, install without read before.
Thank you again for you work in Vue team and Pinia.

**Comment by posva** [comment]
Vue 3.2.0 is published 🎉 

For those using Vue 2, make sure you have at least `@vue/composition-api` `1.1.0` ~~(which is currently installed with `npm install @vue/composition-api@next`)~~.
