### ISSUE TITLE
aboute yarn install pinia change version

### ISSUE THREAD

**Issue by dlbqianduan** [posva/pinia#596]
### Reproduction

If possible, provide a boiled down editable reproduction using a service like JSFiddle, Codepen or CodeSandbox. A failing unit test is even better! Otherwise provide as much information as possible to reproduce the problem.
If no reproduction is provided and the information is not enough to reproduce the problem, we won't be able to give it a look

### Steps to reproduce the behavior

in package.json, appoint any version and run yarn install. you can find in yarn.lock, the pinia resolve version is latest version rather than you appoint version. I try yarn install other jslib，no this problem(英文太差，我用中文再说一次。我用yarn安装指定版本的pinia之后，我发现在yarn.lock文件中，pinia reslove的竟然是最新的版本，而不是你指定的那个版本。我试了安装其他指定版本的js库，他们不会有这个问题)  

### Expected behavior

expected install right version。(希望安装正确的版本，而不是无论怎么改都是安装最新的版本，因为你知道的，安装最新的pinia需要最新的vue版本)

**Comment by posva** [comment]
https://github.com/posva/pinia/issues/592
