### ISSUE TITLE
How can I make Pinia RC working when build for production with Vite

### ISSUE THREAD

**Issue by pakornv** [posva/pinia#598]
### Reproduction
I am using Vue v3.2  with Pinia v2.0.0-rc.2. with script setup It works fine when I run locally with vite dev, but when build for production I got error in console
![Screenshot 2021-08-05 185958](https://user-images.githubusercontent.com/18078609/128346422-7036f87b-55be-48a1-9f2c-cd3448614870.png)

### Steps to reproduce the behavior
1. vite build
2. vite preview

### My Repo
https://github.com/pakornvs/vite-pinia-test

**Comment by posva** [comment]
Thanks! Fixed and released
