### ISSUE TITLE
Major Performance Regression from  2.0.0-rc.0 and after

### ISSUE THREAD

**Issue by jeremydiviney** [posva/pinia#609]
Give the below basic store, that has a reasonable number of items in the state.items (say 1000 or so)
the measured time to initially set the state.items and to modify the state.items with splice, push, etc....  is orders of magnitude slower 2.0.0-beta.5 onward.

### Reproduction
```
type Item = {
 id: number;
 ItemName: string;
 ItemDescription: string;
}


export const useItemStore = defineStore({
  id: 'items',
  state: () => ({
    items: [] as Item[],
  }),
  getters: {
     getItems(state){
        return state.items
     }
  },
  actions: {
      setItems(items: Item[]) {
        console.time('setItems')
        this.items = [...items]
        console.timeEnd('setItems')
      },
       updateItem(item: Item) {
            const index = this.items.findIndex(i => i.id === item.id)
            console.time('updateItem')
            this.items.splice(index, 1, { ...item })
            console.timeEnd('updateItem')
      },
  }
})

```
### Steps to reproduce the behavior

1. call ```const itemStore = useItemStore() ``` in a vue component setup()
2. call ```itemStore.setItems(initItems)``` where initItems is an array of 1000 Item objects
3. call ```itemStore.updateItem(changeItem)```
4. observe the console.time output for 'updateItem'

### Expected behavior

the measured time pre rc.0 was typically about .1 ms 

### Actual behavior

on and post rc.0 the measured time is now 50-100 ms for each splice operation  (500-1000 times slower!)

this may not be noticeable for small collections, however, for larger state collections, it severely affects the UI responsiveness

### Additional information

running Vue 3.2.1, and Typescript 4.3.5

**Comment by posva** [comment]
Do you have a runnable repro on an html file so I can check?

**Comment by jeremydiviney** [comment]
I will work on that, and try to get it posted in the next day or so

**Comment by posva** [comment]
The repro is important here as the place where the data comes from is relevant. I doubt the problem comes from pinia as the performance improved after beta.5 thanks to Vue, but you could always test with different versions of Vue.

You can also do

```js
this.items = [...toRaw(items)]
```

To avoid tracking items if it comes from a reactive source

**Comment by jeremydiviney** [comment]
I was initially mistaken, the change occurred between beta.5 (fast) and rc.0 (slow)
here is a public repo that demonstrates the issue:

[https://github.com/jeremydiviney/pinia-performance-repro](https://github.com/jeremydiviney/pinia-performance-repro)

the main branch should be 'fast' and uses pinia beta.5

the slow branch should be 'slow' and uses pinia rc.0

everything else is identical

it is a full vue project that uses vue-cli 5 and vue 3.2.1

just launch the project and click anywhere on the data table that prints out and it will randomly update the store and console.time the splice operation in updateItem.

the **main** branch times are generally around **_.1 ms_**
the **slow** branch times are around **_15 ms_**, so about 150 times slower, I think it gest worse as the object sizes increase, but this example uses a rather small object for testing

makes sure to delete pinia from node_modules and ```npm install``` when switching branches

**Comment by posva** [comment]
Closing this in favor of https://github.com/posva/pinia/issues/610. There is indeed something off but I still don't know what is causing this speed regression
