### ISSUE TITLE
it was wrong when i use createPinia method

### ISSUE THREAD

**Issue by xie219205** [posva/pinia#616]
```js
//package.json
 "dependencies": {
        "@vue/babel-plugin-jsx": "^1.0.6",
        "axios": "^0.21.1",
        "classnames": "^2.3.1",
        "core-js": "^3.6.5",
        "dotenv": "^10.0.0",
        "element-plus": "^1.0.2-beta.55",
        "pinia": "^2.0.0-rc.4",
        "vue": "^3.0.0",
        "vue-router": "^4.0.0-0"
    },
    "devDependencies": {
        "@vue/cli-plugin-babel": "~4.5.0",
        "@vue/cli-plugin-router": "~4.5.0",
        "@vue/cli-plugin-vuex": "~4.5.0",
        "@vue/cli-service": "~4.5.0",
        "@vue/compiler-sfc": "^3.0.0",
        "babel-plugin-import": "^1.13.3"
    },
```
```javascript
import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.jsx";
import router from "./router";
const app = createApp(App);
app.use(createPinia()).use(router).mount("#app");
```
error:
Uncaught TypeError: Object(...) is not a function
    createPinia pinia.esm-bundler.js:870
    <anonymous> main.js:26
    js app.js:1041
    __webpack_require__ app.js:854
    fn app.js:151
    1 app.js:1089
    __webpack_require__ app.js:854
    checkDeferredModules app.js:46
    <anonymous> app.js:994
    <anonymous> app.js:997
pinia.esm-bundler.js:870
    createPinia pinia.esm-bundler.js:870
    <anonymous> main.js:26
    js app.js:1041
    __webpack_require__ app.js:854
    fn app.js:151
    1 app.js:1089
    __webpack_require__ app.js:854
    checkDeferredModules app.js:46
    <anonymous> app.js:994
    <anonymous> app.js:997

**Comment by posva** [comment]
I can't help without a boiled down repro or more information

**Comment by xie219205** [comment]
I'm sorry. Maybe just a simple demo with vue3.js + ***@***.***/babel-plugin-jsx),and can't use pinia.js。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eduardo San Martin ***@***.***&gt;; 
发送时间: 2021年8月16日(星期一) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [posva/pinia] it was wrong when i use createPinia method (#616)






我不能帮助没有一个精简 repro 或更多的信息

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或安卓.

**Comment by posva** [comment]
I can't reproduce... Open a new issue witha boiled down repro. You have a working demo at https://codesandbox.io/s/github/posva/pinia-vue-3-demo-codesandbox?file=/src/App.vue and a repo here https://github.com/posva/pinia-vue3-example

Remember to use the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by xie219205** [comment]
[codesandbox](https://codesandbox.io/s/wonderful-brattain-4e7st?file=/src/App.jsx)

**Comment by posva** [comment]
You are using Vue 3.0.0 in that cdb, use 3.2.2
