### ISSUE TITLE
I can't watch the changes of store.$state when I write a simple persist plugin

### ISSUE THREAD

**Issue by AllenForward** [posva/pinia#618]
### Reproduction

export default  function piniaPersist(conext: PiniaPluginContext): void  {

        watch(
            () => conext.store.$state,
            () => {
                if (conext.options.persist?.strategies) {
                    conext.options.persist?.strategies.forEach((strategy) => {
                        updateStorage(conext.store, strategy);
                    });
                } else {
                    updateStorage(conext.store);
                }
            },
            { deep: true }
        );
  
};

### Steps to reproduce the behavior

 store.use(piniaPersist);

### Expected behavior

watch will be effective

### Actual behavior

when I mutated the state, watch was not effective

**Comment by posva** [comment]
You should use `store.$subscribe()` but `watch` should work too anyway. Do you have a boiled down repro? I tested on https://codesandbox.io/s/y4dfi?file=/src/stores/index.js:172-198 and it worked.

**Comment by 94ashui** [comment]
> You should use `store.$subscribe()` but `watch` should work too anyway. Do you have a boiled down repro? I tested on https://codesandbox.io/s/y4dfi?file=/src/stores/index.js:172-198 and it worked.

thanks.`store.$subscribe()` resolved my problem.
