### ISSUE TITLE
 './nuxt' is not defined 

### ISSUE THREAD

**Issue by productdevbook** [posva/pinia#626]
"nuxt": "2.15.8",
 
pinia 2.0.0-rc.6

`yarn dev`
 Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './nuxt' is not defined by "exports" in

**Comment by posva** [comment]
You need to install `@pinia/nuxt`: https://pinia.esm.dev/ssr/nuxt.html

**Comment by productdevbook** [comment]
yarn add pinia@next @pinia/nuxt @nuxtjs/composition-api

iam install

some problem.

**Comment by productdevbook** [comment]
`pinia/nuxt` -> `@pinia/nuxt` fixed nuxt config. Thank you

**Comment by productdevbook** [comment]
how to used  this.$nuxt ? new version because error `Property '$nuxt' does not exist on type ` 

https://pinia.esm.dev/ssr/nuxt.html#using-the-nuxt-context-in-stores ✅

**Comment by vinayakkulkarni** [comment]
Yep, facing the same issue as $nuxt is inaccessible via `this` within Pinia `defineStore()` I guess?

<img width="1912" alt="Screenshot 2021-11-27 at 10 36 36 PM" src="https://user-images.githubusercontent.com/19776877/143690458-18452708-2662-4164-a119-936e2ce44c4f.png">
