### ISSUE TITLE
getInspectorState registered by plugin dev.esm.pinia

### ISSUE THREAD

**Issue by productdevbook** [posva/pinia#627]
Vue devtools - v6.0.0-beta.15
Nuxt 2.15.8
"pinia": "2.0.0-rc.6",
"@pinia/nuxt": "0.0.1",

### Steps to reproduce the behavior

1. Chrome refresh and terminal bug see

![CleanShot 2021-08-24 at 07 06 02](https://user-images.githubusercontent.com/38668796/130554145-51d72719-81a2-4117-b93b-6402e7835376.png)

![CleanShot 2021-08-24 at 07 06 29](https://user-images.githubusercontent.com/38668796/130554171-f1e927ef-26e1-461c-906a-3f66b8dce966.png)

**Comment by posva** [comment]
This is explained in the Changelog. It is fixed in devtools but it isn't released yet. You will have to build the devtools from source
