### ISSUE TITLE
@posva/pinia runs unit tests properly, but throws jest warnings and ts errors

### ISSUE THREAD

**Issue by Oleksii14** [posva/pinia#629]
### Reproduction

```
yarn add @posva/pinia
```

test.spec.ts
```
it("calls a function from store", () => {
    // eslint-disable-next-line
    // @ts-ignore <--- by the way, the typescript error happens here: global does not exist on type...
    const wrapper = shallowMount(App, {  global: { plugins: [createTestingPinia()] } });

    // defined outside
    const store = useStore();

    wrapper.vm.$router.onReady(async () => {
      expect(store.fetchList).toHaveBeenCalled();
      // test succeeded
    });
  });
```

Warnings from @vue/test-utils

```
[Vue warn]: Injection "Symbol(pinia)" not found
```

TS error for `global` property:
```
Object literal may only specify known properties, and 'global' does not exist in type 'FunctionalComponentShallowMountOptions<Vue>'
```

### Steps to reproduce the behavior

1. Define a store using `defineStore`
2. Define an action in `actions`
3. Create a testing file `test.spec.ts`
4. Write a test similar to above using Vue 2 environment that is described above
5. See the warning/ts-error

### Expected behavior

No TS error, no jest warnings

### Actual behavior

TS throws an error on using `global` prop within `shallowMount` method from `@vue/test-utils`
Jest throws warnings `[Vue warn]: Injection "Symbol(pinia)" not found`

### Additional information

Env:

"@pinia/testing": "0.0.2",
"pinia": "0.5.4",
"vue": "2.6.14",

**Comment by Oleksii14** [comment]
Let me know if example repo is needed

**Comment by posva** [comment]
Currently, `@pinia/testing` only _officialy_ supports Vue 3. 
For Vue 2, You need pinia@2 (it works with Vue 2 but devtools need an upstream fix) and to adapt your tests to use the vue-test-utils for Vue 2 too.

I added this to my list of things to document for the testing pinia but I haven't even tested it yet so it might require some changes to `@pinia/testing`. Based on https://vue-test-utils.vuejs.org/api/options.html#other-options, you probably need

```js
localVue.use(PiniaPlugin)
const pinia = createTestingPinia()
const wrapper = mount(Component, {localVue, pinia})
```

Feel free to PR if you find anything missing/broken.

**Comment by Oleksii14** [comment]
@posva I have just added pinia v2 in Vue 2 project, and I receive TS errors in my tests like `Object literal may only specify known properties, and 'pinia' does not exist in type 'FunctionalComponentShallowMountOptions<Vue>'` . Maybe you removed some types from the new version?

**UPD**: solved by module augmentation

**Comment by Oleksii14** [comment]
@posva the issue above has a workaround

```
// @types/vue-pinia.d.ts

/* eslint-disable */

import utils from "@vue/test-utils";
import { Pinia } from "pinia";

declare module "@vue/test-utils" {
  interface MountOptions {
    pinia?: Pinia;
  }
}
```

and in tsconfig:

```
{
"complierOptions": {
  ...
  "typeRoots": ["@types"],
 }
}
```

**Comment by Oleksii14** [comment]
@posva I have completely integrated `@pinia/testing` package in Vue 2 app using `@vue/composition-api`. It works without any additional changes, apart from the type issue mentioned above (but it has a workaround).

Should I add a unit test example somewhere?

**Comment by posva** [comment]
Oh well, that's pretty neat it just works! The type issue needs to be fixed #630, it shouldn't be a necessary step for users. Ideally without any extra type file, mixing Vue 3 and Vue 2 types together, if that's not an issue for TypeScript. If that's not possible, having a separate file for Vue 2 types would be enough `pinia/vue-2-types`. I will still have to think about it but I'm open to proposals

**Comment by theolavaux** [comment]
@Oleksii14 I'm using Jest along with @testing-library/vue that encapsulates vue-testing-library, I also have this warning `[Vue warn]: Injection "Symbol(pinia)" not found.`, how did you manage to solve it?

For Jest, I have a setup files that runs before the tests (using `setupFilesAfterEnv`) called `setupTests.ts`, and it contains this.

```ts
config.mocks.pinia = createTestingPinia({
  createSpy: jest.fn(),
});
```
Installing `@pinia/testing` and setting this global pinia instance to the return value of `createTestingPinia` allowed my tests not to fail, but now I don't know how to get rid of this remaining warning.

**Comment by ajitsinghkamal** [comment]
> @Oleksii14 I'm using Jest along with @testing-library/vue that encapsulates vue-testing-library, I also have this warning `[Vue warn]: Injection "Symbol(pinia)" not found.`, how did you manage to solve it?
> 
> For Jest, I have a setup files that runs before the tests (using `setupFilesAfterEnv`) called `setupTests.ts`, and it contains this.
> 
> ```ts
> config.mocks.pinia = createTestingPinia({
>   createSpy: jest.fn(),
> });
> ```
> 
> Installing `@pinia/testing` and setting this global pinia instance to the return value of `createTestingPinia` allowed my tests not to fail, but now I don't know how to get rid of this remaining warning.


Using `@testing-library/vue`, I was able to get it working by providing `createTestingPinia` in renderOptions.
```ts

localVue.use(PiniaPlugin) // for vue 2

test('component using pinia state', () => {
  render(ComponentUnderTest, {
     ...,
     pinia: createTestingPinia()
  })
})
```

**Comment by theolavaux** [comment]
This didn't work for me, I created a `setup` function in my test file instead, and it finally works: 

```ts
const setup = () =>
  render(
    ComponentUnderTest,
    { pinia: createTestingPinia({ createSpy: jest.fn() }) },
    (vue) => {
      vue.use(PiniaVuePlugin);
    }
  );
```
