### ISSUE TITLE
support use pinia in electron main process

### ISSUE THREAD

**Issue by bayun2** [posva/pinia#632]
### What problem is this solving

use pinia in electron main process like https://www.npmjs.com/package/@kasvith/electron-vuex

**Comment by posva** [comment]
Interesting, this should definitely be an external plugin, not something inside's Pinia. The simplest form of it would be to share the `pinia.state` among electron processes and then everything would work.

Maybe being able to do

```js
const pinia = createPinia()
pinia.state = useProcessSharedRef({})
```

is enough. The real challenge is creating `useProcessSharedRef()` (probably worth having a better name too). Looking at the repo, this file should be a good place where to start: https://github.com/kasvith/electron-vuex/blob/main/src/createSharedState.js. If that doesn't work, a pinia plugin that keeps the store's state in sync could also do

I won't work on this myself as I don't use electron so feel free to create something and link it here.

**Comment by bayun2** [comment]
Thanks for your answer. @posva 
I don‘t know how to proxy action. In electron-vuex can override dispatch function, but in pinia every action used without dispatch function. https://github.com/kasvith/electron-vuex/blob/main/src/createSharedMutations.js#L45.
Another problem is only use ```app.use(pinia)``` can active, but in node (main processer) there is no ``` app.use```
