### ISSUE TITLE
nuxt build and start lib.Vue2.use

### ISSUE THREAD

**Issue by productdevbook** [posva/pinia#642]
### Steps to reproduce the behavior

1. yarn build
2. yarn start

"pinia": "2.0.0-rc.6",
 "@pinia/nuxt": "0.0.1",
 "nuxt": "2.15.8",
 
 
![CleanShot 2021-08-31 at 07 09 46](https://user-images.githubusercontent.com/38668796/131440407-f1b2def3-f51f-44e1-8962-d5eac02b8224.png)

![CleanShot 2021-08-31 at 07 09 56](https://user-images.githubusercontent.com/38668796/131440552-ad606475-e139-4757-844d-11862efa89ee.png)

**Comment by posva** [comment]
Upgrade your dependencies and provide a repro of this still happens

**Comment by productdevbook** [comment]
> Upgrade your dependencies and provide a repro of this still happens

yarn lock delete and install some problem

**Comment by posva** [comment]
Here you have a working example with Nuxt: https://github.com/posva/pinia-example-nuxt
I won't be able to do anything without a repro or further information

**Comment by posva** [comment]
Closing until a repro is provided

**Comment by productfrontenddeveloper** [comment]
I'm recreating it but when it's empty it's fine.  I don't know how to create you this error

but project 
@pinia/nuxt@0.0.2
"pinia": "2.0.0-rc.9",

![CleanShot 2021-09-13 at 21 43 37](https://user-images.githubusercontent.com/38668796/133139208-3de08680-d6c1-432b-bdd0-9235151a0389.png)

![CleanShot 2021-09-13 at 21 44 51](https://user-images.githubusercontent.com/38668796/133139353-22100b49-5c23-4ec6-b3ca-da30337b28a4.png)

**Comment by productdevbook** [comment]
> Closing until a repro is provided

https://github.com/productfrontenddeveloper/pinia-ssr-bug

**Comment by posva** [comment]
That's probably because of the transpile option. Remove Vue from there.

**Comment by productdevbook** [comment]
thank you
