### ISSUE TITLE
Nuxt error toRefs()

### ISSUE THREAD

**Issue by bashess** [posva/pinia#648]
### Reproduction

In your Nuxt example and in my project, i get some vue warnings on reload at your store page on devserver.
Vue warn]: toRefs() expects a reactive object but received a plain one.

### Steps to reproduce the behavior

1. npm run dev in your pinia-example-nuxt project
2. go to store page 
3. reload
4. toRefs() error occur

### Expected behavior

No error should show

**Comment by posva** [comment]
This [was fixed in `@vue/composition-api`](https://github.com/vuejs/composition-api/pull/795) and it will likely be picked up in the next release of `@nuxtjs/composition-api`.

The error is actually a harmless warning and you can safely ignore it.

**Comment by thisVioletHydra** [comment]
me to 
![image](https://user-images.githubusercontent.com/11839238/133742397-da4b46e1-8ab4-43be-b85e-5fd88f89dab8.png)
