### ISSUE TITLE
Show Options API example in Introduction

### ISSUE THREAD

**Issue by TheJaredWilcurt** [posva/pinia#651]
### What problem is this solving

I have no interest in using the Composition API.

There should be an example of how to use Pinia with the far superior Options API, or at least an explanation that it doesn't work with the Options API if that's the case (though I would be surprised if it was).

**Comment by posva** [comment]
It's right there lol

Pinia can be used in Option Components with the map helpers, like with Vuex: https://pinia.esm.dev/introduction.html#basic-example
