### ISSUE TITLE
storeToRefs not working with primitive types

### ISSUE THREAD

**Issue by bashess** [posva/pinia#654]
### Reproduction

If i want to use storeToRefs in Nuxt 2, it won't work on primitive types for state.
It won't recognize that this is a reactive or ref.   

### Steps to reproduce the behavior

```
state: () => ({
	cart: null,
	loading: false,
}),

...

const store = useStore();	
const { cart, loading } = storeToRefs(store);
```

### Expected behavior

Primitive types should also converted to refs on storeToRefs

### Actual behavior

StoreToRefs only works with init as empty object or array and not with null or false

### Additional information

Maybe you can iterate through the hole store and check if its reactive or ref and additionally add store.$state to ref

**Comment by posva** [comment]
This works on Vue 3, so it's probably a bug in `@vue/composition-api` regarding `isRef()`, `isReactive()` when passing refs to a reactive object. I haven't taken the time to reproduce it, so if anybody wants to give it a try and submit an issue to vue composition API, go ahead!

**Comment by posva** [comment]
This is now fixed with the latest versions of pinia and composition api.
