### ISSUE TITLE
New defineStore api with latest version of Vue (3.2.7)

### ISSUE THREAD

**Issue by slauzinho** [posva/pinia#655]
### Reproduction

When upgrading to the latest version of Vue if I use the new `defineStore` api I get the following typescript error:

```
Object is of type 'unknown'.

17   <h1>You counter is: {{ counterStore.counter }}</h1>
```

Looking at the type returned by the `useCounterStore` it seems to be:
```
const counterStore: never
```
### Steps to reproduce the behavior

1- go to repo https://github.com/slauzinho/new-pinia-setup-api
2- run `yarn lint`
3- see typescript errors

### Expected behavior

Should work the same as the options API

### Actual behavior

The return type is `never`

### Additional information

I added a repro [here](https://github.com/slauzinho/new-pinia-setup-api)

Dependancies:
```json
"dependencies": {
    "pinia": "^2.0.0-rc.6",
    "vue": "^3.2.7"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.6.0",
    "@vue/compiler-sfc": "^3.2.7",
    "typescript": "^4.4.2",
    "vite": "^2.5.3",
    "vue-tsc": "^0.3.0"
  }
```

**Comment by posva** [comment]
This is probably because Pinia is not yet compatible with TS 4.4. It only works with TS 4.3 yet

**Comment by slauzinho** [comment]
Hi @posva changing to `"typescript": "^4.3.5",` doesn't seem to fix it. I still get the same warning.

**Comment by posva** [comment]
Try `"typescript": "~4.3.5",`

**Comment by slauzinho** [comment]
Yeah I removed the `node_modules` and `yarn.lock` tried again with `4.3.5` and it's working.
