### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'options') (Nuxt)

### ISSUE THREAD

**Issue by sondh0127** [posva/pinia#657]
### Reproduction

Please look at the below repo
[https://github.com/sondh0127/nuxt-pinia
](https://github.com/sondh0127/nuxt-pinia
)
### Steps to reproduce the behavior
Setup setup: 
1. `yarn create nuxt-app`
2. `yarn add pinia@next @pinia/nuxt @nuxtjs/composition-api`
3. setup nuxt config + add sample pinia in `pages/index.vue`

### Start dev server
1. yarn dev
2. The `counter ref` does not unref in template, and the `increase` function are not working properly.

![Screenshot_1](https://user-images.githubusercontent.com/62163604/132115331-498c1932-8f08-4d1f-8479-9f252f619473.png)
![Screenshot_2](https://user-images.githubusercontent.com/62163604/132115341-72a309bb-55d8-46e6-b814-ea00061b0e65.png)

![Screenshot_4](https://user-images.githubusercontent.com/62163604/132115380-7056b93d-1a74-4f73-ac11-0e9d2cd49f18.png)

### Expected behavior

store work with nuxt (2)

### Actual behavior

A clear and concise description of what actually happens.

**Comment by posva** [comment]
This is mentioned in the changelog. The error comes from devtools and is absent in production. Check the changelog for more

**Comment by sondh0127** [comment]
The error is not the problem. But the reproduction does not work

**Comment by posva** [comment]
Ah, now I see where the problem comes from. I just pushed a fix
