### ISSUE TITLE
2.0.0-rc.7 update broke the state access

### ISSUE THREAD

**Issue by Oleksii14** [posva/pinia#659]
### Reproduction

While accessing the store state props in v2.0.0-rc.7, it returns the Ref object instead of value.

```
console.log(store.stateProp)
// RefImpl {}
```

### Steps to reproduce the behavior

1. Create a store via `defineStore`
2. Add prop to `state`
3. Acces it

### Expected behavior

Should return raw value

### Actual behavior

described above

**Comment by sondh0127** [comment]
I think related to my issue. It was fixed, just w8 for next rc https://github.com/posva/pinia/issues/657#issuecomment-913201758
