### ISSUE TITLE
getters not working with 2.0.0-rc.7 and 2.0.0-rc.8 in nuxt 2

### ISSUE THREAD

**Issue by bashess** [posva/pinia#660]
### Reproduction

Getters working correctly on server side, but not on client. 
State get correctly hydrated but getters stay undefined

### Expected behavior

Getters working on client

### Actual behavior

getters stay undefined after hydration

**Comment by maxdzin** [comment]
I've recognized the same issue.

**Comment by posva** [comment]
This one needs a bit more investigation. Not being able to have a proper test suite for both Vue 3 and Vue 2 makes it complicated to avoid regressions on Vue 2. It probably related to cda3658

**Comment by Oleksii14** [comment]
I am having the same issue using Vue 2 without nuxt. Waiting for a fix 🙏🏻

**Comment by posva** [comment]
This should be fixed with 3d4080b and a few other commits. Let me know on the next release if it works properly. I also have a round of tests going on

**Comment by Oleksii14** [comment]
@posva getting those errors
![image](https://user-images.githubusercontent.com/36737084/133048249-3be4987d-98b6-42f2-b7b2-c46ee60322ae.png)


UPD: rc 9

**Comment by maxdzin** [comment]
@posva Thank you so much for the update.
However, after the update, there are still errors.
I've tried using this repo to check (with dependencies update, of course): https://github.com/posva/pinia-example-nuxt.
And got these errors:
![nuxt-pinia-issue](https://user-images.githubusercontent.com/6406412/133053832-a37101eb-3585-405b-b069-f7c84634e10b.png)

**Comment by maxdzin** [comment]
Ah! I just saw this issue last comment:
https://github.com/posva/pinia/issues/648
So really hope it would be fixed soon.
@posva thank you! :pray:

**Comment by posva** [comment]
> @posva getting those errors
> 
> ![image](https://user-images.githubusercontent.com/36737084/133048249-3be4987d-98b6-42f2-b7b2-c46ee60322ae.png)
> 
> 
> 
> 
> 
> UPD: rc 9

Do you have a boiled down repro of that?

**Comment by Oleksii14** [comment]
> > @posva getting those errors
> > ![image](https://user-images.githubusercontent.com/36737084/133048249-3be4987d-98b6-42f2-b7b2-c46ee60322ae.png)
> > UPD: rc 9
> 
> Do you have a boiled down repro of that?

Yes, but it is private. I will try to set up a new one and provide it here

**Comment by ziaadini** [comment]
thanks it works,  when i upgrade all of my versions nuxt , nuxt-composition-api and pinia this issue has gone.
but this warning steal exist 
```
 [Vue warn]: toRefs() expects a reactive object but received a plain one.

```

**Comment by maxdzin** [comment]
> thanks it works, when i upgrade all of my versions nuxt , nuxt-composition-api and pinia this issue has gone.
> but this warning steal exist
> 
> ```
>  [Vue warn]: toRefs() expects a reactive object but received a plain one.
> ```

Same for me...
