### ISSUE TITLE
error when building with vite-ssg

### ISSUE THREAD

**Issue by mrweiner** [posva/pinia#665]
Attempting to run `npm build` on my [vitesse](https://github.com/antfu/vitesse)-based project and I'm seeing the following error:

```
...
[vite-ssg] Build for server...
vite v2.5.6 building SSR bundle for production...
✓ 78 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.38 KiB
.vite-ssg-temp/main.js                     137.98 KiB
.vite-ssg-temp/assets/style.1bff94d7.css   22.56 KiB
TypeError: Cannot read property '_s' of undefined
    at useStore (/home/weiner/Sites/hc_project/handcrafted/vue/node_modules/pinia/dist/pinia.cjs.js:1544:20)
    at Module.<anonymous> (/home/weiner/Sites/hc_project/handcrafted/vue/.vite-ssg-temp/main.js:2673:19)
    at Module.o._compile (/home/weiner/Sites/hc_project/handcrafted/vue/node_modules/jiti/dist/v8cache.js:2:2778)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at __require (/home/weiner/Sites/hc_project/handcrafted/vue/node_modules/vite-ssg/dist/chunk-3FHQZVYO.js:22:12)
    at build (/home/weiner/Sites/hc_project/handcrafted/vue/node_modules/vite-ssg/dist/node/cli.js:140:52)

```

Any idea if the issue is with pinia or with vite-ssg? The only ticket I can find that references both is https://github.com/antfu/vite-ssg/issues/72. Here's the app init in my `main.ts`

```
// https://github.com/antfu/vite-ssg
// https://github.com/antfu/vite-ssg/issues/72
export const createApp = ViteSSG(
  App,
  {routes},
  (ctx) => {
    // install all modules under `modules/`
    Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx));
    const pinia = createPinia()
    pinia.use(({store}) => {
      store.router = markRaw(ctx.router)
    })

    ctx.app.use(pinia)
  },
)
```

**Comment by userquin** [comment]
@mrweiner take a look at this example updated a few days ago here https://github.com/antfu/vite-ssg/tree/main/examples/multiple-pages-with-store

Anyway,  why are you storing the router on the store?

**Comment by mrweiner** [comment]
Yeah the store on the router was actually just in that other ticket, so that's just what I dropped in. I couldn't find any references at the time on how to properly implement this.

I did just try the example that you provided and I'm still seeing the same error. I should note that I removed the `router.beforeEach()` section because I don't really have any sort of initialize method on my stores that I could call in there. For instance, one is just an auth store to help store/manage access and refresh tokens, so the store isn't really "initialized" locally unless somebody uses the login form. Maybe I'm misunderstanding why that bit is there.

**Comment by userquin** [comment]
@mrweiner this store is for ssr/ssg initialization to avoid a roundtrip to the server. To use your stores just use pinía on the app. You should read this on vite-ssg docs https://github.com/antfu/vite-ssg#initial-state

**Comment by mrweiner** [comment]
Fwiw I'm seeing the error on build with just this as well. This seems like the minimum needed, right? My app in general breaks without this.
```
export const createApp = ViteSSG(
  App,
  {routes},
  (ctx) => {
    // install all modules under `modules/`
    Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx));
    const pinia = createPinia()
    ctx.app.use(pinia)
  },
)
```

**Comment by userquin** [comment]
If you are not using the pinia plugin there you dont need to create it on the callback.

I mean, if you dont use pinia stores you dont need to register the plugin, if you are using it on the app then this is the way to initialize it or you can create another module to register it.

If you need to initialize some build initial state then configure pinia as the docs explain.

**Comment by mrweiner** [comment]
> if you are using it on the app then this is the way to initialize it or you can create another module to register it.

I guess that's what I'm saying. I'm using pinia stores throughout the app so I'm initializing pinia here. The app runs as expected on localhost, but `npm run build` errors out. 

That said, I did just try adding the above ViteSSG with pinia to a clean instance of https://github.com/antfu/vitesse and the build ran fine, so there must be something else going on with my implementation. I'll need to dig around to figure out what's causing the issue.

**Comment by mrweiner** [comment]
It looks like the cause of this is using my store outside of a vue component.

/~/store/auth.ts 
```
export const useAuthStore = defineStore({ ... })
```

/~/modules/cart.ts
```
import { useAuthStore } from "~/store/auth";
const authStore = useAuthStore();
...
export const cartApi = { ... }
```

Then `cartApi` is used around the app. Removing all of the store-related code from carts.ts allows the build to run fine, but `useAuthStore()` causes the build to break. Maybe I need to open a new issue over in vite-ssg to see how I should deal with this. I'd assume that the stores just don't exist yet when the ssg is looking at the module or something.

**Comment by isokosan** [comment]
I'm having the same issue with the code below. When I remove the `useAuthStore` the build runs fine. I just can't find the best practice of setting up global middleware with the store. In development mode I have no issues like the rest here.

```
import { createPinia } from 'pinia'
import type { RouteParams } from 'vue-router'
import { ModuleInstall } from '~/types'
import { useAuthStore } from '~/stores/auth'

// Setup Pinia
// https://pinia.esm.dev/
export const install: ModuleInstall = ({ isClient, initialState, app, router }) => {
  const pinia = createPinia()
  app.use(pinia)
  // Refer to
  // https://github.com/antfu/vite-ssg/blob/main/README.md#state-serialization
  // for other serialization strategies.
  if (isClient) {
    pinia.state.value = (initialState.pinia) || {}
  } else {
    initialState.pinia = pinia.state.value
  }

  // eslint-disable-next-line @typescript-eslint/no-invalid-void-type
  router.beforeEach((to, from): boolean | void | RouteParams => {
    const auth = useAuthStore()
    if (to.meta.middleware) {
      if (to.meta.middleware === 'auth' && !auth.user) {
        return { name: 'login' }
      }
      if (to.meta.middleware === 'guest' && auth.user) {
        return { name: 'index' }
      }
    }
  })
}

```

**Comment by posva** [comment]
Do you have a boiled down repro I can check?

**Comment by isokosan** [comment]
@posva, you can just clone the [vitesse](https://github.com/antfu/vitesse) repo that uses vite-ssg, and update the `main.ts` file with a reference to the store:

If you await `router.ctx.isReady` before using a store this error is not thrown, then, however, `vite-ssg` skips page generation.

```
// register vue composition api globally
import { ViteSSG } from 'vite-ssg'
import generatedRoutes from 'virtual:generated-pages'
import { setupLayouts } from 'virtual:generated-layouts'
import App from './App.vue'

// windicss layers
import 'virtual:windi-base.css'
import 'virtual:windi-components.css'
// your custom styles here
import './styles/main.css'
// windicss utilities should be the last style import
import 'virtual:windi-utilities.css'
// windicss devtools support (dev only)
import 'virtual:windi-devtools'
import { useUserStore } from './stores/user'

const routes = setupLayouts(generatedRoutes)

// https://github.com/antfu/vite-ssg
export const createApp = ViteSSG(
  App,
  { routes },
  async (ctx) => {
    // install all modules under `modules/`
    await Promise.all(Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx)))
    // if enabled, the error is not thrown but vite-ssg does not generate pages.
    // await ctx.router.isReady()
    const userStore = useUserStore()
    console.log(userStore.savedName)
  },
)
```

**Comment by posva** [comment]
I would be easier to check with something smaller.
I'm worried the problem comes from the changes using cjs and mjs files

**Comment by mrweiner** [comment]
I was able to solve this differently than @isokosan since (at the moment) I'm not trying to use my stores in `main.ts`, but instead in an arbitrary .ts file that's being imported around the app. I just added this above `useMyStore()`:

```
if (!getActivePinia()) {
  const pinia = createPinia();
  setActivePinia(pinia);
}
```

**Comment by mrweiner** [comment]
I just switched over to using vite-ssr instead of vite-ssg and encountered a different error from the same problem, so just figured I'd document my fix in here in case anybody stumbles across it. Initially I was defining my stores before the export, whereas now I do it in the export (which fixes my problem). This helps to ensure that pinia exists at that point, otherwise the stores may attempt to be defined before the application initializes and pinia is actually available:

Before
```
const authStore = useAuthStore();

export const cartApi = {
  // stuff
} 

```

After
```
export const useCartApi = () => {
  const authStore = useAuthStore();
  return {
    // stuff
  }
}
```

**Comment by mediator-accused** [comment]
https://stackdev.space/questions/is-it-possible-to-utilize-an-imported-function-within-the-global-routerbeforeeach-in-vuejs Here’s a concise reply
