### ISSUE TITLE
I can't use pinia outside of component setup

### ISSUE THREAD

**Issue by rangeldor** [posva/pinia#666]
### Discussed in https://github.com/posva/pinia/discussions/664

<div type='discussions-op-text'>

<sup>Originally posted by **rangeldor** September 10, 2021</sup>
When I try to use it in the api.ts I get this error: 
TypeError: Object(...) is not a function

api.ts
![image](https://user-images.githubusercontent.com/51749346/132924662-0b9846fd-7d31-409d-8f1c-c9bafd50ca5a.png)

When I try to use it in the router.ts I get this error:  
Uncaught Error: [🍍]: getActivePinia was called with no active Pinia. Did you forget to install pinia?

const pinia = createPinia()
app.use(pinia)

router.ts
![image](https://user-images.githubusercontent.com/51749346/132924820-6aec68b7-93b9-429b-baec-14a38de86df7.png)

</div>

**Comment by posva** [comment]
Have you checked the documentation about usage outside of setup ?

**Comment by rangeldor** [comment]
Yes! I checked here: https://pinia.esm.dev/core-concepts/outside-component-usage.html#single-page-applications

The example you give is the use in main.ts, when you're creating the app and right after giving .use in pinia I should call the store, but I want to do this in api.ts, it's the file where I'll make the requests and if the token is invalid, I refresh the token using an action or logging out if it is invalid.

I tried to use this example: https://github.com/posva/pinia/discussions/512
But I could not.

I would like to do anything like store.dispatch('signOut') of the Vuex.

**Comment by posva** [comment]
Have you checked https://pinia.esm.dev/ssr/#using-the-store-outside-of-setup?
You need to pass the pinia instance

**Comment by rangeldor** [comment]
It works when I use in my router file:

![image](https://user-images.githubusercontent.com/51749346/132952966-32c69f93-5877-435b-9962-db98bd45f2fa.png)

But, if I use in my api.ts:

![image](https://user-images.githubusercontent.com/51749346/132952993-7e354808-0b04-4be5-9fd3-f59ac71a7b01.png)

I get this error:

![image](https://user-images.githubusercontent.com/51749346/132953017-7f8597d2-27f3-4e0f-84bf-8791b0f6907d.png)

**Comment by rangeldor** [comment]
I don't know why, but works if I use it inside my axios request like this:

![image](https://user-images.githubusercontent.com/51749346/132953486-1cb1d48f-d860-41cf-8816-d0e9813e1070.png)

However, I need to declare it in everywhere that I want to use.

**Comment by posva** [comment]
Probably because of the deferred call but I won't be able to take a look without a boiled down repro. Open a new issue with one if you manage to reproduce it.

**Comment by rangeldor** [comment]
Thank you so much posva! I will try to make a boiled for you take a look.

Great job you do in this project!

Pinia is pretty good with typescript.
