### ISSUE TITLE
vueDemi.effectScope is not a function

### ISSUE THREAD

**Issue by ziaadini** [posva/pinia#667]
hello
### Reproduction
here is my versions:
``` "@nuxtjs/composition-api": "^0.29.0",
"@pinia/nuxt": "^0.0.2",
"pinia": "^2.0.0-rc.8",
```
and it's my nuxt.config
```
buildModules: [
    '@nuxtjs/composition-api/module',
    ['@pinia/nuxt', { disableVuex: false }],
    'nuxt-font-loader',
    '@nuxtjs/tailwindcss',
    [
      'nuxt-compress',
      {
        gzip: {
          threshold: 8192,
        },
        brotli: {
          threshold: 8192,
        },
      },
    ],
    'nuxt-typed-vuex',
 
 
  ],
```
and this is my console error
```
client.js?06a0:103 TypeError: vueDemi.effectScope is not a function
    at createPinia (pinia.cjs.js?ebc1:878)
    at PiniaNuxtPlugin (templates.plugin.2ad125d6.js?9bdf:13)
```
my node version is : 
```v12.20.0```

**Comment by posva** [comment]
This means you have an outdated version of nuxt composition api. If that's not the case opens new issue with a reproduction so I can't check

**Comment by ziaadini** [comment]
after some hours debugging  it was my nuxt version upgrade from ```2.15.4``` to ```2.15.8``` solved issue for me, i hope it helps some one

**Comment by ghost** [comment]
vue2 use pinia


Uncaught TypeError: (0 , vue_demi__WEBPACK_IMPORTED_MODULE_0__.effectScope) is not a function
    at createPinia (pinia.mjs?b318:955:1)
    at onlyRender (main.js?fbea:25:1)
    at eval (main.js?fbea:59:1)
    at ./src/main.js (app.js:6223:1)
    at __webpack_require__ (app.js:9041:33)
    at app.js:10175:413
    at __webpack_require__.O (app.js:9090:23)
    at app.js:10176:53
    at app.js:10179:12
    at webpackUniversalModuleDefinition (app.js:17:28)
