### ISSUE TITLE
Can't import the named export from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by MycroftHolmes1989** [posva/pinia#675]
### Steps to reproduce the behavior

1. Use Vue-cli to create a Vue 3 app with Typescript.
2. Run `yarn add pinia@next`.
3. Edit the `main.ts`:

```
import { createApp } from "vue";
import App from "./App.vue";
import { createPinia } from "pinia";

const app = createApp(App);
app.use(createPinia());
app.mount("#app");
```
4. Run `yarn serve`.

### Expected behavior

The compilation goes without an error

### Actual behavior

Throws error:

```
ERROR  Failed to compile with 18 errors                                                                                                           

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'computed' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'del' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'effectScope' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'getCurrentInstance' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'inject' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'isReactive' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'isRef' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'isVue2' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'markRaw' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'onUnmounted' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'reactive' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'ref' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'set' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'toRaw' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'toRef' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'toRefs' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'unref' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'watch' from non EcmaScript module (only default export is available)
```
### Additional Information:

 ```
 "dependencies": {
    "core-js": "^3.6.5",
    "pinia": "^2.0.0-rc.9",
    "primeflex": "^3.0.1",
    "primeicons": "^4.1.0",
    "primevue": "^3.7.1",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.0.0",
    "lint-staged": "^9.5.0",
    "node-sass": "^4.12.0",
    "prettier": "^2.2.1",
    "sass-loader": "^8.0.2",
    "typescript": "~4.1.5"
  },
```

**Comment by Liwoj** [comment]
Same problem here. Using `"typescript": "~4.3.5"`.
Downgrading back to `2.0.0-rc.8` fixes the issue...

**Comment by Liwoj** [comment]
Seems [related](https://github.com/intlify/vue-i18n-composable/issues/9) and also the workaround mentioned in the discussion works. 

But it's strange as all the issues I found ([here](https://github.com/apollographql/react-apollo/issues/1737), [here](https://github.com/webpack/webpack/issues/6699)) describe this problem as "unable to do named import from CJS into ESM module". But VueDemi provides ESM build and after checking Webpack 4 docs (as Vue CLI is still on WP4), it has also correct settings in `package.json` (`"module"` field pointing to `.mjs` file). 

So I  still don't understand why it is treated as "non EcmaScript module"

**Comment by posva** [comment]
Can someone provide a boiled down repro with only Vue and pinia (no router, or other unnecessary steps)

**Comment by jhony-v** [comment]
I had the same problem  but I solved editing my **vue.config.js** file with the following webpack rule:

```javascript
// vue.config.js
module.exports = {
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.mjs$/,
          include: /node_modules/,
          type: "javascript/auto"
        }
      ] 
    }
  }
}
```

With this configuration it worked.

**Comment by predragnikolic** [comment]
> Can someone provide a boiled down repro with only Vue and pinia (no router, or other unnecessary steps)

@posva  I created a vue-cli project with a repro. Hope it helps.

> https://github.com/predragnikolic/pinia-bug-repro

And when I try to import pinia:
https://github.com/predragnikolic/pinia-bug-repro/commit/d9810039d701d30d58f11688f3081fe14545db4a

I get errors when running `yarn serve`:

<details>

```
yarn serve
yarn run v1.22.11
warning ../package.json: No license field
$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 18 errors                              5:09:52 PM

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'computed' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'del' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'effectScope' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'getCurrentInstance' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'inject' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'isReactive' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'isRef' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'isVue2' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'markRaw' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'onUnmounted' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'reactive' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'ref' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'set' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'toRaw' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'toRef' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'toRefs' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'unref' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'watch' from non EcmaScript module (only default export is available)

No issues found.
```

</details>

**Comment by posva** [comment]
@predragnikolic that's a lot of projects 😓 

@MycroftHolmes1989 can you create a boiled down reproduction please?

**Comment by timpulver** [comment]
Here is the chained Webpack config if someone else needs it:

_vue.config.js:_
```
/**
 * @type {import('@vue/cli-service').ProjectOptions}
 */
module.exports = {
  chainWebpack: (config) => {
    config.module
      .rule("mjs")
      .test(/\.mjs$/)
      .type("javascript/auto")
      .include.add(/node_modules/)
      .end();
  },
};

```

**Comment by posva** [comment]
I reproduced the issue on a simple project. This should be fixable by changing the extensions of the generated files. I still need to test it out a bit more.

**Comment by tobiasdiez** [comment]
I get this error now when trying to upgrade from `@pinia/nuxt v 0.0.4` to version `0.0.6`, see https://github.com/JabRef/JabRefOnline/pull/551. The reason might be https://github.com/posva/pinia/commit/438b16dfd3dd5052be437d2e7382f9f4f497eea3 ?

**Comment by 4Kazelot** [comment]
> I had the same problem but I solved editing my **vue.config.js** file with the following webpack rule:
> 
> ```js
> // vue.config.js
> module.exports = {
>   configureWebpack: {
>     module: {
>       rules: [
>         {
>           test: /\.mjs$/,
>           include: /node_modules/,
>           type: "javascript/auto"
>         }
>       ] 
>     }
>   }
> }
> ```
> 
> With this configuration it worked.

For NuxtJS:
```
export default {
  build: {
    extend(config) {
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      })
    },
  },
}
```

**Comment by Kooklen** [comment]
> I had the same problem but I solved editing my **vue.config.js** file with the following webpack rule:
> 
> ```js
> // vue.config.js
> module.exports = {
>   configureWebpack: {
>     module: {
>       rules: [
>         {
>           test: /\.mjs$/,
>           include: /node_modules/,
>           type: "javascript/auto"
>         }
>       ] 
>     }
>   }
> }
> ```
> 
> With this configuration it worked.

It works

**Comment by qrtp** [comment]
> > I had the same problem but I solved editing my **vue.config.js** file with the following webpack rule:
> > ```js
> > // vue.config.js
> > module.exports = {
> >   configureWebpack: {
> >     module: {
> >       rules: [
> >         {
> >           test: /\.mjs$/,
> >           include: /node_modules/,
> >           type: "javascript/auto"
> >         }
> >       ] 
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With this configuration it worked.
> 
> For NuxtJS:
> 
> ```
> export default {
>   build: {
>     extend(config) {
>       config.module.rules.push({
>         test: /\.mjs$/,
>         include: /node_modules/,
>         type: 'javascript/auto',
>       })
>     },
>   },
> }
> ```
@4Kazelot For the NuxtJS what file does this config go in?

**Comment by AzimovAzimDev** [comment]
[[[> > > I had the same problem but I solved editing my **vue.config.js** file with the following webpack rule:
> > > ```js
> > > // vue.config.js
> > > module.exports = {
> > >   configureWebpack: {
> > >     module: {
> > >       rules: [
> > >         {
> > >           test: /\.mjs$/,
> > >           include: /node_modules/,
> > >           type: "javascript/auto"
> > >         }
> > >       ] 
> > >     }
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > With this configuration it worked.
> > 
> > 
> > For NuxtJS:
> > ```
> > export default {
> >   build: {
> >     extend(config) {
> >       config.module.rules.push({
> >         test: /\.mjs$/,
> >         include: /node_modules/,
> >         type: 'javascript/auto',
> >       })
> >     },
> >   },
> > }
> > ```
> 
> @4Kazelot For the NuxtJS what file does this config go in?

https://nuxtjs.org/docs/features/configuration/#extend-webpack-config](https://nuxtjs.org/docs/features/configuration/#extend-webpack-config)](https://nuxtjs.org/docs/features/configuration/#extend-webpack-config)](https://nuxtjs.org/docs/features/configuration/#extend-webpack-config)

**Comment by taidaid** [comment]
Hello, we are trying to use Pinia alongside Vuex in a Nuxt 2 project in order to smooth our eventual migration to Nuxt 3. However, even after adding 
```
    extend(config) {
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      })
    },
```
to our build config, we are still seeing the `Can't import the named export 'isVue2' from non EcmaScript module (only default export is available)`. The error comes from our `./.nuxt/dist.plugin.209980bd.mjs` file which seems to be the `@pinia/nuxt` plugin setup.

Here is some of our `package.json`
```
// dependencies
"nuxt": "2.15.8",
"vue": "2.6.14",
"@nuxtjs/composition-api": "^0.23.2" ,
"@pinia/nuxt": "^0.1.9",
"pinia": "^2.0.14

// devDependencies
"@nuxt/typescript-build": "2.1.0"
```
We tried some experiments such as deleting ths `.cjs` file from `vue-demi`, but it seems that no matter what we do, the file is not reading the `.mjs` file correctly.

**Comment by andreisucman** [comment]
If nothing worked you can try importing differently.

Instead of 

`import {a, b} from "c"; `

try

`import * as q from "c";`

and then 

`const {a, b} = q;`

**Comment by Kameecoding** [comment]
> If nothing worked you can try importing differently.
> 
> Instead of
> 
> `import {a, b} from "c"; `
> 
> try
> 
> `import * as q from "c";`
> 
> and then
> 
> `const {a, b} = q;`

the problem here is not usage, this error is caused by the file generated by @pinia/nuxt, specifically the import at the start

```
import { isVue2, install, Vue2 } from 'vue-demi';
import { PiniaVuePlugin, createPinia, setActivePinia } from 'pinia';

if (isVue2) {
  install();
  const Vue = "default" in Vue2 ? Vue2.default : Vue2;
  Vue.use(PiniaVuePlugin);
}
const PiniaNuxtPlugin = (context, inject) => {
  const pinia = createPinia();
  if (isVue2) {
    context.app.pinia = pinia;
  } else {
    context.vueApp.use(pinia);
  }
  if (isVue2) {
    inject("pinia", pinia);
  } else {
    context.provide("pinia", pinia);
  }
  context.pinia = pinia;
  setActivePinia(pinia);
  pinia._p.push(({ store }) => {
    Object.defineProperty(store, "$nuxt", { value: context });
  });
  if (process.server) {
    if (isVue2) {
      context.beforeNuxtRender(({ nuxtState }) => {
        nuxtState.pinia = pinia.state.value;
      });
    } else {
      context.nuxtState.pinia = pinia.state.value;
    }
  } else if (context.nuxtState && context.nuxtState.pinia) {
    pinia.state.value = context.nuxtState.pinia;
  }
};

export { PiniaNuxtPlugin as default };

```

Workaround here:

1. take the code above generated by @nuxt/pinia and create your own pinia.js in your plugin folder,
2. use it in nuxt.config.js
3. remove @pinia/nuxt

**Comment by yudhishthir-siterecon** [comment]
If you are using CRACO for react app, add the following webpack configuration to your craco.config.js:

```
  module.exports = {
    webpack: {
      configure: (webpackConfig, { env, paths }) => {
        // Add a rule to handle .mjs files
        webpackConfig.module.rules.push({
          test: /\.mjs$/,
          include: /node_modules/,
          type: 'javascript/auto',
        });
  
        return webpackConfig;
      },
    },
  };
```
