### ISSUE TITLE
Wrong next link in the docs.

### ISSUE THREAD

**Issue by qwe12e** [posva/pinia#676]
### Steps to reproduce the behavior

1. Go to [https://pinia.esm.dev/ssr/](https://pinia.esm.dev/ssr/)
2. Scroll down to bottom of the page
3. See the next link defined as "Vue and Vite". Which is the current page.

### Expected behavior

next link should be [Nuxt](https://pinia.esm.dev/ssr/nuxt.html)

### Actual behavior

next link is the same with the current page.

**Comment by posva** [comment]
This might be a bug in vitepress.
