### ISSUE TITLE
Can you provide an option similar to shallowprops so that state does not convert deep attributes

### ISSUE THREAD

**Issue by sh-winter** [posva/pinia#692]
### What problem is this solving
This can save considerable consumption in some cases

**Comment by posva** [comment]
I don't understand, can you elaborate?

You can still use `shallowReactive()` in `state()` if that's what you want:

```js
state: () => ({ object: shallowReactive(...) })
```

**Comment by posva** [comment]
Closing as it doesn't seem to be any need of new API.
Use `shallowReactive()` and `markRaw()` when needed to let Vue know to skip reactivity.
