### ISSUE TITLE
Document testing configuration

### ISSUE THREAD

**Issue by rijkvanzanten** [posva/pinia#72]
I was looking for a way to reset all stores completely in order to write tests for my store, and found that [you use `setActiveReq({})` in the tests for Pinia itself](https://github.com/posva/pinia/blob/e49b0463a7ccff87657ecdde522bc07276cfcbde/__tests__/store.spec.ts#L6-L8). Is this the recommended way of testing stores created with Pinia?

The following works exactly as needed, but I'm not sure what `setActiveReq` is doing in this case or if I should be using it to begin with.

```js
import Vue from 'vue';
import VueCompositionAPI from '@vue/composition-api';
import { useMainStore } from '@/stores/main';
import { setActiveReq } from 'pinia';

describe('Stores', () => {
	beforeAll(() => {
		Vue.use(VueCompositionAPI);
	});

	beforeEach(() => {
		setActiveReq({});
	});

	describe('Actions / reset', () => {
		it('Sets counter to 0', () => {
			const store = useMainStore();
			store.state.counter = 25;
			store.reset();
			expect(store.state.counter).toBe(0);
		});
	});
});
```

**Comment by posva** [comment]
you shouldn't be using it.
Pass an empty object to `useMainStore({})` to request a new store. This is not something I want to document yet because it can change based on how SSR works in Vue 3
