### ISSUE TITLE
Performance issue with Pinia extension in devtools

### ISSUE THREAD

**Issue by joakimriedel** [posva/pinia#721]
### Reproduction

1) Add a very complex and heavy object such as a MapBox instance to a store. Use markRaw to prevent proxying.

`store.mapInstance = markRaw(new Map(...))`

2) Enjoy that everything works fine.

3) Open Vue DevTools and choose the Pinia plugin from the menu. Select the store with the complex object.

### Expected behavior

Performance should not degrade.

### Actual behavior

Browser is almost not responding, performance is down to a crawl.

Need to close devtools and reload page to get performance back to normal.

### Additional information

My guess is that the Pinia devtools starts watching the complex object deep, even though it's marked with `markRaw`?

It would be nice if Pinia detected that an object is marked raw, and skip any processing on it. 

Suggestion would be to show the object in devtools as "raw object - expand to start watching" to make it possible to watch on demand.

Reason to add the complex object in a store is to make it survive through HMR, workaround could perhaps be to store it somewhere else.

**Comment by posva** [comment]
Pinia doesn't watch properties added to the store and it cannot control what devtools watch.

You can however make that `mapInstance` not enumerable to hide it from devtools:

```js
Object.defineProperty(store, 'mapInstance', {
  value: new MapBox(...)
})
```

**Comment by joakimriedel** [comment]
Thanks @posva for the workaround. Unfortunately that won't round-trip automatically during HMR which was my intention by putting them in the store from the start. 

However, I exposed the object from the store in the `setup()` method of a component, and I get the same behavior in devtools just by browsing the component. So I can confirm it's not Pinia related.

Researching further I found the following issues:

https://github.com/vuejs/vuex/issues/1847
https://github.com/vuejs/vue-next/issues/2380

I'll link them here if anyone else run into the same problem.

**Comment by joakimriedel** [comment]
@posva found out a workaround, see the following https://github.com/vuejs/devtools/issues/1585#issuecomment-944227489

If I disable the "Components" permissing of the Pinia devtools extension, all is good!

![image](https://user-images.githubusercontent.com/429478/137481086-9f146f27-1217-4d78-b109-9a117621a15b.png)

Do you know why this might be happening? I can live without the components in the Inspector of devtools, but it would be nice to have them back.

**Comment by IIFelix** [comment]
I had the same problem with Openlayers instances and was able to fix it by using getters.
Example: 

```typescript
// your complex object
const layer = new VectorLayer({...})
return {
  layer: () => layer
}
```
