### ISSUE TITLE
npm i pinia

### ISSUE THREAD

**Issue by twotree** [posva/pinia#725]
### Reproduction

PS C:\Code\e> npm i pinia

### Steps to reproduce the behavior

1. npm i pinia

### Expected behavior

install

### Actual behavior

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! pinia@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @vue/composition-api@1.2.4
npm ERR! node_modules/@vue/composition-api
npm ERR!   peerOptional @vue/composition-api@"^1.2.4" from pinia@2.0.0-rc.13
npm ERR!     pinia@"*" from the root project

### Additional information

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.16.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.81
    Edge: Spartan (44.19041.1266.0), Chromium (94.0.992.47)
  npmPackages:
    @intlify/vue-devtools:  9.1.9
    @vue/compiler-core:  3.2.20
    @vue/compiler-dom:  3.2.20
    @vue/compiler-sfc:  3.2.20
    @vue/compiler-ssr:  3.2.20
    @vue/devtools-api:  6.0.0-beta.19
    @vue/reactivity:  3.2.20
    @vue/ref-transform:  3.2.20
    @vue/runtime-core:  3.2.20
    @vue/runtime-dom:  3.2.20
    @vue/server-renderer:  3.2.20
    @vue/shared:  3.2.20
    typescript:  4.4.2
    vue:  3.2.20
    vue-eslint-parser:  7.11.0
    vue-i18n: ^9.0.0-beta.0 => 9.1.9
    vue-loader:  16.5.0
    vue-router:  4.0.11
    vue-style-loader:  4.1.3
  npmGlobalPackages:
    @vue/cli: Not Found
    @quasar/cli - 1.2.1

  quasar - 2.1.4 
  @quasar/app - 3.1.3 
  @quasar/extras - 1.11.2 
  eslint-plugin-quasar - Not installed
  vue - 3.2.20 
  vue-router - 4.0.11

**Comment by posva** [comment]
Already reported and this looks more like an npm issue

**Comment by hermit99** [comment]
I had the same issue trying to install pinia under quasar 2.1.4, vue 3.2.20.
`npm i --legacy-peer-deps` seemed working

**Comment by posva** [comment]
Duplicate of https://github.com/posva/pinia/discussions/727
