### ISSUE TITLE
[SSR] Error transforming ./node_modules/@pinia/nuxt/templates/plugin.js

### ISSUE THREAD

**Issue by matthewhardern** [posva/pinia#733]
### Steps to reproduce the behavior

`npx nuxi init test-nuxt3`

`npm i pinia`

`npm i @pinia/nuxt`

add nuxt config

```
export default defineNuxtConfig({
    modules: [
        '@pinia/nuxt',
    ]
})
```

I get ` WARN  [SSR] Error transforming ./node_modules/@pinia/nuxt/templates/plugin.js: Error: Missing "./templates/plugin.js" export in "@pinia/nuxt" package`

### Expected behavior

Not to error

### Actual behavior

SSR error

**Comment by posva** [comment]
It has to be put in BuildModules

**Comment by matthewhardern** [comment]
I still get the same error if I do
