### ISSUE TITLE
Uncaught TypeError: r.Vue2.use is not a function

### ISSUE THREAD

**Issue by darthf1** [posva/pinia#742]
Hi!

With `"@pinia/nuxt": "0.0.9",` I get an error on the `production` environment. `development` works fine. When I downgrade to `"@pinia/nuxt": "0.0.7",`, the `production` environment works again.

Sorry for the another strange error. Also perhaps the core issue is not related to pinia, but I can't tell.

---

In the console, the following error is displayed: 

```
Uncaught TypeError: r.Vue2.use is not a function
```

Looks like its coming from these lines in the [plugin](https://github.com/posva/pinia/blob/v2/packages/nuxt/src/templates/plugin.ts#L5).

![image](https://user-images.githubusercontent.com/17253332/138690233-85340fc1-bfc0-4301-8d3c-776db7716e6a.png)

![image](https://user-images.githubusercontent.com/17253332/138690325-58e7cd7c-5a0d-455d-a964-bcd5d8369bf4.png)

**Comment by posva** [comment]
Same as before, I need a boiled down repro to check.

**Comment by maxdzin** [comment]
The same for me. Production is failed with both, `"@pinia/nuxt": "0.0.9"` and `"@pinia/nuxt": "0.1.0"`.
For now only downgrade helps.

**Comment by posva** [comment]
This is not enough info for me to check. The plugin runs in Nuxt 2, Nuxt Bridge and Nuxt 3. A boiled down repro will really help
