### ISSUE TITLE
Plugins are duplicated for every createApp(...).use(pinia) call

### ISSUE THREAD

**Issue by jessevanassen** [posva/pinia#744]
When creating a new store, [all the plugins in the `_p` list are executed](https://github.com/posva/pinia/blob/pinia%402.0.0-rc.15/packages/pinia/src/store.ts#L648-L677). The `_p` list is filled in the `Pinia.install` function, by [pushing all the plugins from the `toBeInstalled` list into the _p list](https://github.com/posva/pinia/blob/pinia%402.0.0-rc.15/packages/pinia/src/createPinia.ts#L38).

This means that, if the install function is executed multiple times (e.g. by re-initializing the Vue app with the same Pinia instance), the registered plugins end up in the `_p` list multiple times as well, and will be executed repeatedly when a new store is created.

### Reproduction
```js
import { createApp } from 'vue';
import { defineStore, createPinia } from 'pinia';

const plugin = (context) => {
	context.store.count++;
};

const pinia = createPinia();
pinia.use(plugin);

const useStore = defineStore('my-store', {
	state: () => ({ count: 0 }),
});

createApp({}).use(pinia);
createApp({}).use(pinia);
createApp({}).use(pinia);

const store = useStore();
console.log(store.count); // Expected '1', but prints '3'
```

**Comment by jessevanassen** [comment]
**Suggestion**

Rewriting [the line in the install function](https://github.com/posva/pinia/blob/pinia%402.0.0-rc.15/packages/pinia/src/createPinia.ts#L38) to the following should solve it:
```js
toBeInstalled.forEach((plugin) => {
	if (!_p.includes(plugin)) {
		_p.push(plugin));
	}
});
```

It's `O(n^2)`, but considering that the setup isn't called frequently (for most applications, once). and the amount of plugins is probably low, it's probably acceptable performance wise.

Otherwise, at the cost of more code, it's also possible to do a `_p.push(...plugins)` if the `_p` array is empty, and only do the proposed check if it's not.

**Comment by posva** [comment]
Nice catch. I think the best would be to just empty the toBeInstalled array if you want to create a PR

**Comment by jessevanassen** [comment]
Cool, thanks!

I've made a pull request at https://github.com/posva/pinia/pull/745
