### ISSUE TITLE
Pinia v2 doesn't work with vue@2 & @vue/composition-api@1.2.4

### ISSUE THREAD

**Issue by floydjones1** [posva/pinia#750]
### Reproduction

Not sure what went wrong, attached are screenshots of my package.json and the terminal output after upgrading to piniav2. It was working find prior.

<img width="602" alt="Screen Shot 2021-10-27 at 11 32 44 PM" src="https://user-images.githubusercontent.com/43974214/139182275-4d58adc2-4f1e-4335-98f8-eaf1355334ef.png">
<img width="768" alt="Screen Shot 2021-10-27 at 11 33 06 PM" src="https://user-images.githubusercontent.com/43974214/139182302-bd63a44d-9452-4dd4-ae72-3ef3a27635e5.png">

**Comment by jokay** [comment]
We face the same problem 🧐 

But we already had `@vue/composition-api` @ **1.2.4**.

![image](https://user-images.githubusercontent.com/18613935/139189004-8834025b-3bd0-4a49-ae20-e791e83d3ff9.png)

```sh
-  Building for production...
Starting type checking service...
Using 1 worker with 2048MB memory limit
 ERROR  Failed to compile with 17 errors12:23:28 AM

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'computed' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'effectScope' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'getCurrentInstance' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'inject' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'isReactive' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'isRef' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'isVue2' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'markRaw' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'onUnmounted' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'reactive' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'ref' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'set' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'toRaw' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'toRef' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'toRefs' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'unref' from non EcmaScript module (only default export is available)

 error  in ./node_modules/pinia/dist/pinia.mjs

Can't import the named export 'watch' from non EcmaScript module (only default export is available)

 ERROR  Build failed with errors.
error Command failed with exit code 1.
```

**Comment by edifierx666** [comment]
vue.config.js 
add alias
resolve 
![image](https://user-images.githubusercontent.com/39356752/139200614-a4e9c7ec-be22-4f32-9a86-7c83a0bc3c0b.png)

**Comment by posva** [comment]
@jokay You should update to the latest RC before updating directly to 2.0.0. It will show a few deprecations. There is https://pinia.esm.dev/cookbook/migration-v1-v2.html to help

**Comment by posva** [comment]
You need to add https://github.com/posva/pinia/issues/675#issuecomment-919544784 to make it work with webpack 4

I will update the docs with more hints.

I'm unsure if it's possible to make the package exports work with webpack 4, webpack 5, vite, nuxt 2, bridge, and nuxt 3 at the same time. Having to add that little piece of configuration to webpack 4 projects seems like a fair trade off and will likely be necessary with other libraries.

**Comment by jokay** [comment]
@posva thx will give it a try an report back :+1:

**Comment by jokay** [comment]
@posva confirmed working by adding the following to the `vue.config.js`:

```js
module: {
  rules: [
    {
      include: /node_modules/u,
      test: /\.mjs$/u,
      type: 'javascript/auto'
    }
  ]
},
```

Thank you very much.

**Comment by zigzaggin** [comment]
> vue.config.js add alias resolve ![image](https://user-images.githubusercontent.com/39356752/139200614-a4e9c7ec-be22-4f32-9a86-7c83a0bc3c0b.png)

This corrected the issue for me. Thank you.

**Comment by posva** [comment]
Upgrading you vue cli plugin should include this webpack rule by default: https://github.com/vuejs/vue-cli/commit/15b1e1b6bfa40fe0b69db304a2439c66ff9ba65f

**Comment by floydjones1** [comment]
@jokay @posva  I'm getting this in my console after upping pinia now

<img width="535" alt="Screen Shot 2021-10-28 at 10 53 33 AM" src="https://user-images.githubusercontent.com/43974214/139281723-b9dbe83d-d645-41e2-9970-0db101db4843.png">
<img width="201" alt="Screen Shot 2021-10-28 at 10 55 44 AM" src="https://user-images.githubusercontent.com/43974214/139282018-9d467dae-5ae6-4bb0-ac9f-ff2a31b0019f.png">

**Comment by posva** [comment]
You are likely calling a `useStore()` before the application is mounted. If you want to get help, you should open a discussion sharing more sections of your code or a runnable reproduction.

**Comment by floydjones1** [comment]
Seems like I can't use pinia store inside `router.beforeEach` ? I use to be able to do it before. Not sure how to add gaurds with pinia other than adding it to before each

**Comment by posva** [comment]
https://pinia.esm.dev/ssr/#using-the-store-outside-of-setup

**Comment by floydjones1** [comment]
Okay it works not. Should have read that 😅 🙏
