### ISSUE TITLE
npm build fail with pinia v2.0.0 and vue2.6.14(@vue/composition-api 1.3.0)

### ISSUE THREAD

**Issue by SD-Gaming** [posva/pinia#758]
### Reproduction

run 'npm run build', see error.

### Expected behavior

build success

### Actual behavior

build fail with error below:
![image](https://user-images.githubusercontent.com/25575589/139626486-d167dab3-785e-42dd-87a9-e1eefe32116c.png)

### Additional information

![image](https://user-images.githubusercontent.com/25575589/139619748-46ccd61e-3e93-46c5-b1b5-9b6b42ac2787.png)
![image](https://user-images.githubusercontent.com/25575589/139619756-f60557bf-a810-4264-b3c4-fe946f5cfe9d.png)
![image](https://user-images.githubusercontent.com/25575589/139619777-660a21b9-ae35-4a6e-976f-d46e0adedb42.png)

**Comment by baixiaoyu2997** [comment]
@SD-Gaming  你没有按照1.3.0的要求进行更改？https://github.com/vuejs/composition-api/releases/tag/v1.3.0
1.3.0中使用`.mjs`替代了`.esm.js`的引用

**Comment by SD-Gaming** [comment]
> @SD-Gaming 你没有按照1.3.0的要求进行更改？https://github.com/vuejs/composition-api/releases/tag/v1.3.0 1.3.0中使用`.mjs`替代了`.esm.js`的引用

上面最后一张图已经配置了, vue 审查也有，可是还是同样的错误，请问哪里还没有配置对

**Comment by baixiaoyu2997** [comment]
@SD-Gaming 不好意思昨天网很差，没有加载出来图片，出1.3.1版本了，你看看有没有修复。不行就降级吧 😂

**Comment by SD-Gaming** [comment]
> @SD-Gaming 不好意思昨天网很差，没有加载出来图片，出1.3.1版本了，你看看有没有修复。不行就降级吧 😂

没有，非常感谢你的帮助🤭，我试试

**Comment by posva** [comment]
You need to add `skipLibCheck: false` to your tsconfig. The type only exists in Vue 3 but maybe it should be shimmed in `@vue/composition-api`

**Comment by SD-Gaming** [comment]
I have no problem, it can close this issue.

**Comment by Shinigami92** [comment]
Setting `skipLibCheck: false` is not acceptable option for our project
This would disable type-safety for the whole project 😱 And type-safety is literally the reason why I want to switch from vuex v3 to pinia...

Is there another workaround?

**Comment by SantanderAuhAuh** [comment]
> Setting `skipLibCheck: false` is not acceptable option for our project This would disable type-safety for the whole project 😱 And type-safety is literally the reason why I want to switch from vuex v3 to pinia...
> 
> Is there another workaround?

I have the same problem.Is there any solution?
