### ISSUE TITLE
Plugin Doc Ambiguity

### ISSUE THREAD

**Issue by nVitius** [posva/pinia#761]
I was reading the new docs for Pinia's plugin API and I ran into a section that probably needs a little clarification:
![image](https://user-images.githubusercontent.com/3804041/139787841-7d00bb87-25a7-4a30-810d-5a5ae29c28d6.png)

The first example there doesn't return anything (the example is for how to use the "return version").
It's also not clear how setting `'secret'` on `_customProperties` lets devtools see the new property `hello`.

**Comment by posva** [comment]
Please open a PR with your proposal.

**Comment by nVitius** [comment]
@posva I'm happy to open a PR. I'm just not clear on what the doc is intending.

Should the second example be: `store._customProperties.add('hellow')`?
Can you clarify what the "return version" is?

Thanks!

**Comment by posva** [comment]
Aaah, I see it now! I think I missed the comment under the image. It should indeed be hello instead of secret, I just pushed the change. Thanks!
