### ISSUE TITLE
 Cannot access 'useUserStore' before initialization

### ISSUE THREAD

**Issue by AlanMi** [posva/pinia#775]
### Reproduction

If possible, provide a boiled down editable reproduction using a service like JSFiddle, Codepen or CodeSandbox. A failing unit test is even better! Otherwise provide as much information as possible to reproduce the problem.
If no reproduction is provided and the information is not enough to reproduce the problem, we won't be able to give it a look

### Actual behavior

A clear and concise description of what actually happens.

**Comment by sunpu007** [comment]
I also encountered this problem while using it, but did not find the problem. Then try to initialize it in the state file, and import the initialized state value directly into the component
```js
// store.ts
export const useUserStore = defineStore({...})

export const userStore = useUserStore()

// component.vue
import { userStore } from '@/store/user'
...
```


demo：https://github.com/sunpu007/vite_vue3_ts/tree/b7c27ea43bdabe64a80aaa23d42c720d6a1bf9b2
Report an error in this version
