### ISSUE TITLE
Bundling breaks things

### ISSUE THREAD

**Issue by Rigo-m** [posva/pinia#778]
### Reproduction
https://github.com/Rigo-m/pinia-issue-repro

### Steps to reproduce the behavior

1. `yarn generate`
2. `yarn start`'
3. See error in console (Vue2.use is not a function)

### Expected behavior

Should compile correctly 

### Actual behavior

Development environment works correctly, bundling nuxt2 with nuxt generate breaks the website.

### Additional information

The reproduction repo is the same as issue #767 , so pull new version if you hadn't.
Also, in the repo you can see issue #767 fixed by using `@nuxtjs/composition-api#fix/transpile-server-vue`.
Also, in the repo you can switch between official `@pinia/nuxt` module and a local module (line 33/34 `nuxt.config.js`) which has been stripped from Vue Demi logic (thanks to @nash403 ) and shows that the culprit is Vue Demi itself somehow.

I thought of creating a new issue since this problem is now reproducible with the latest `@pinia/nuxt` module.

**Comment by posva** [comment]
What is that custom composition api dependency? Please give more details

**Comment by Rigo-m** [comment]
As I stated in `Additional information` it's a branch that fixes issue #767 that @danielroe crafted this morning.

**Comment by posva** [comment]
aah, the issue was blank on mobile lol

**Comment by posva** [comment]
@danielroe Is https://github.com/nuxt-community/composition-api/commit/a5f54601ea3c7af8b9cf97d0493d917ed71ee08c something planned on being released or was it a test maybe?
@Rigo-m Thanks for looking into it! We don't know yet what the proper fix will be but it's great you found a workaround!

**Comment by Rigo-m** [comment]
@posva thanks to you for pinia, it really helped me with development. I'm sorry about all the fuss of the last week. I wish I could do more about fixing the issues but I am really struggling with a project and I don't have much spare time. If you need anything just ask, I will make a donation for sure ;)

**Comment by eMeRiKa13** [comment]
A fix has been pushed on Nuxt https://github.com/nuxt/framework/pull/1779

but quoting pi0:

> Thanks! LGTM however this doesn't fix latest pinia module since they reverted back from using kit. We also need to normalize in template utils

**Comment by posva** [comment]
I pushed a new version that seems to work. Make sure to remove pinia from transpile option if you still have it and let me know if it doesn't work (I tested with your repro and now it works)

**Comment by nash403** [comment]
Thank you ! Just had to also update @nuxtjs/composition-api and now it works 😃 

And also thanks for this amazing package ! 👌
