### ISSUE TITLE
objects/arrays in getters not reactive?

### ISSUE THREAD

**Issue by xvaara** [posva/pinia#780]
Hiyah. Not sure if this is a bug or intended behaviour.

On vue 3 I have array of options. I just wanna get the "default one".
`getOption: state => state.options[0],`
Doesn't seem to be updating if I update options.

both of these work:
`getOption2: state => computed(() => state.options[0]),`
`getAllOptions: state => state.options,`

docs say:
> Getters are exactly the equivalent of computed values for the state of a Store

so should it work without wrapping it in computed?

**Comment by Rigo-m** [comment]
Add a reproduction repository please

**Comment by xvaara** [comment]
https://codesandbox.io/s/pinia-vue-3-demo-forked-hou3o?file=/src/App.vue

**Comment by posva** [comment]
You need to write:

```vue
<div id="app">
    <h1>Hello Pinia 🍍!</h1>

    <p>getOption: {{ store.getOption }}</p>
    <p>getOptionComputed: {{ store.getOptionComputed }}</p>

    <p>getOption -> foo: {{ store.getOption.foo }}</p>
    <p>getOptionComputed -> foo: {{ store.getOptionComputed.foo }}</p>

    <footer>Using Vue v{{ vueVersion }} and Pinia v{{ piniaVersion }}.</footer>
  </div>
```

or use `storeToRefs()`.

A store is a reactive object and, like in Vue, you can't just destructure properties from it.
