### ISSUE TITLE
Add a Vuex-to-Pinia Migration Guide to documentation

### ISSUE THREAD

**Issue by BenShelton** [posva/pinia#793]
### What problem is this solving

Looking at this discussion https://github.com/posva/pinia/discussions/787 highlights that a lot of people are converting Vuex stores to Pinia stores. A common thing to do in Vuex is write getters that return state of the same name, of course this is pointless in Pinia. There are a few other gotchas like that when converting from Vuex to Pinia that aren't always obvious.

### Proposed solution

Include a section in the documentation, something like "Vuex Migration Guide", which highlights some of the main steps to do and some of the common gotchas. A rough idea of what a step-by-step guide could look like:

1. Namespacing, usage of id instead, if using other stores with rootState/rootGetters convert those first
2. Convert state, now a function (if it wasn't already)
2. Convert getters, remove useless getters (as in the above discussion), link to type gotchas already documented
3. Convert actions, using `this` instead of context
4. Convert mutations, replace with actions or just assign directly to the store
5. Convert usages of store within components, using helpers or in setup (already documented)

### Describe alternatives you've considered

There are some notes at https://pinia.esm.dev/introduction.html#comparison-with-vuex-3-x-4-x and in other places too, but a more step-by-step guide could be beneficial, even if most of it links to already existing documentation.

Another alternative would be to add warnings for these edge cases (for example in the above discussion, when adding getters do a check that it doesn't name collide with any of the state, and warn if it does)

I'd be happy to help in either case, I'm interested in your thoughts on the best approach for handling things like this @posva

**Comment by posva** [comment]
I think this is a very good idea and I will definitely welcome a PR on this 💚 It's also something that could be used for Vuex 5 docs.
I do have thoughts on how to approach it but I will probably give this a look in a few weeks. I see you already worked on some sections and I think a good way to push this forward is to write up the different sections as isolated ones so they can be reorganized and reused later
