### ISSUE TITLE
why not set the property of store as readonly, can only be set by wrapper function?

### ISSUE THREAD

**Issue by coader** [posva/pinia#808]
### What problem is this solving

const store = useXXXStore()
store.counter++
thus we can't know where and when it changed

### Proposed solution

store's property will be all readonly reactive object

**Comment by posva** [comment]
This is intentional design and there is already an open issue about read only state

**Comment by yoyo837** [comment]
> This is intentional design and there is already an open issue about read only state

Could you tell me more about the reason for this design? Such as documentation or a link to an issue?
