### ISSUE TITLE
get multi store instance with same structure and no unique id

### ISSUE THREAD

**Issue by impeiran** [posva/pinia#809]
### What problem is this solving

We have a complicated component which would be instanced many times.
Each instance should have its own store. But these stores also have the same structure.

### Proposed solution

![image](https://user-images.githubusercontent.com/32994681/142585070-17c4169e-dcc9-4c39-a6fd-f032c008834a.png)

**Comment by posva** [comment]
Then they shouldn’t be stores, there should be entries in your list array
