### ISSUE TITLE
HMR not working + demo not working in Safari and Chrome (M1)

### ISSUE THREAD

**Issue by hipertracker** [posva/pinia#843]
### Reproduction

I have downloaded the demo example project from the home page (https://stackblitz.com/github/piniajs/example-vue-3-vite) and run it on my local machine. **Changing the store state is not reflected in the browser. HMR does not work.** 
I tested it on macOS 12.0.1 MBP 16" M1Max with Firefox Developer Edition 95.0b12 (64-bit). 

❯ node -v
v16.13.0

The project also is not working at all in Safari 15.1 (17612.2.9.1.20) where it fails with "Failed to load resource: the server responded with a status of 500 (Internal Server Error)
<img width="565" alt="Screenshot 2021-11-28 at 06 18 27" src="https://user-images.githubusercontent.com/649/143731937-5e17531e-3a79-4764-a5ab-1f3de7f047d6.png">

There is the same error in Chrome  96.0.4664.55 (Official Build) (arm64) - a blank screen with the same "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" 
<img width="1138" alt="Screenshot 2021-11-28 at 06 22 09" src="https://user-images.githubusercontent.com/649/143731998-46697d37-405c-4168-bf57-b03000896395.png">

**Comment by hipertracker** [comment]
I checked 3 more browsers. It displays the same blank screen and 500 internal server error in Opera 81.0.4196.60 (arm64) and Brave browser 1.32.113 Chromium: 96.0.4664.45 (Official Build) (arm64).... but it works in Firefox 94.0.2 (64-bit).

**Comment by hipertracker** [comment]
I did one more test on MacBook Pro 15" with Intel chip. This time the project was opening in Safari but HRM still was not working. :(

**Comment by posva** [comment]
I tested locally, same node version, same arch, and couldn't find any issue. The 500 you are seeing must be coming from something else.
I updated the deps of the project but I doubt that's the issue

**Comment by hipertracker** [comment]
This time I was testing it on the desktop Intel i7 PC and Ubuntu Plasma in Firefox and Chromium browsers.

When I change the Pinia store state in the source file this is not updating the store in the running application. Developer Tools is not detecting the change, and the UI is not updating DOM. 

To be clear, here are all my steps:

1. Load and extract the demo project from Pinia web site
2.  Run yarn && yarn dev
3. Open http://localhost:3000
3.  Open src/stores/user.js file in VScode and change the state 'name' value from 'Eduardo' to 'John'
4. In  Chrome Developer Tool Vue extension **the user state has not  been changed**
5.  **The browser has not been updated** in Chromium and in Firefox.

**This must be a bug since I am able to reproduce not working HMR across the different platforms, computers, and operating systems!**

* MBP 16"  M1Max 64GB RAM, macOS 12.0.1, Chrome, FIrefox, Opera, Brave
* MBP 15" Intel I7 16GB RAM, macOS 11.6.1, Chrome, Firefox
* PC Intel i7 32GB RAM, Ubuntu Plasma k86_64, Chromium, Firefox

**Comment by Pijuli** [comment]
Same for me. On the demo and locally. Might be wrong about hmr but I also expected to get the store updated on save.
Am I doing anything wrong? :thinking: 

![hmr pinia](https://user-images.githubusercontent.com/1220004/145815293-d1245fdd-1ecd-4ba0-a495-ccf2b6a0b7e5.gif)

**Comment by AaronBeaudoin** [comment]
HMR doesn't work for me either in the demo or in my own local project.

**Comment by shocolate15** [comment]
Why is this closed? I cant seem to get HMR working either.

HMR works fine when adding new state but if I am updating a value nothing is updated on save exactly the same as the gif image above.

**Comment by yanglei00** [comment]
Why is this closed? I cant seem to get HMR working either.

**Comment by kuntau** [comment]
@posva might want to reopen this? Can't get HMR working either.

**Comment by Zenthae** [comment]
HMR is working for me if you consider the answer given in #898 as the intended behavior

**Comment by posva** [comment]
Yes, the idea is that adding new state should not reset the other values of the state so existing state values are always preserved. This also means that you can change a value, comment the line and save (this removes the state property) then un comment and save again.

**Comment by oneyoung19** [comment]
> Yes, the idea is that adding new state should not reset the other values of the state so existing state values are always preserved. This also means that you can change a value, comment the line and save (this removes the state property) then un comment and save again.

Thanks, I got it! When i delete state or add new state, the client HMR works well. If i modify a state value, the client HMR not work. 
But this design makes me confused, Because if i modify a state value with vuex in a vue-cli project, the client will be reloaded.
