### ISSUE TITLE
When subscribing to the state in Nuxt v3 mutation.events is undefined in production.

### ISSUE THREAD

**Issue by vanling** [posva/pinia#844]
Not entirely sure if this is expected behavior but this is something i came accross today.  

### Steps to reproduce the behavior
in app.vue
```vue
<script setup>
  import { useUserStore } from '~/store/user'
  const user = useUserStore()
  user.$subscribe(async (mutation, state) => {
    // undefined on builded/production
    console.log(mutation.events); 
  })
</script>

<template>
  <div class="h-screen">
    <NuxtPage />
  </div>
</template>
```

### Expected behavior

`mutation.events = {...}` an object with old value, new value and more details

### Actual behavior

`mutation.events = undefined`

### Additional information
Nuxt - 3.0.0-27296423.f3082ca
pinia - 2.0.4
Standard nuxt build and run with `node .output/server/index.mjs `

### production vs dev build
![Schermafbeelding 2021-11-28 om 10 36 22](https://user-images.githubusercontent.com/50699657/143762835-a180ec76-022b-45c9-b32f-fac1d866afea.png)
![Schermafbeelding 2021-11-28 om 10 36 37](https://user-images.githubusercontent.com/50699657/143762836-ad0b5a4b-8685-4236-ad9d-ce614c838697.png)

**Comment by vanling** [comment]
Looking at https://pinia.esm.dev/core-concepts/state.html#subscribing-to-the-state again. Shouldn't there be a `mutation.payload` property too?

**Comment by posva** [comment]
This is expected and your ide should show you the documentation explaining when holding over that events property.

**Comment by vanling** [comment]
@posva ah! I see now Thank you and I'm sorry, i'm not working so much with all those fancy IDE features (yet). _( im a console log and documentation user. )_

**Comment by posva** [comment]
I understand 😆 
They’re also in the docs where the search should be quite accurate https://pinia.esm.dev/api/interfaces/pinia.SubscriptionCallbackMutationPatchFunction.html#events

**Comment by ahmedelatab** [comment]
@vanling @posva 
If the IDE isn't showing you the actual properties of the **mutation** object, and if you're facing TypeScript issues saying that **payload is not a known property of...** Then you can simply do like this: (mutation **as any**).payload
