### ISSUE TITLE
Permit to specify the State structure when using createStore

### ISSUE THREAD

**Issue by edimitchel** [posva/pinia#85]
## Feature request
_[According to this twitter discussion](https://github.com/posva/pinia/blob/master/src/store.ts#L164)_
### Need
In order to getting more solid store typing, it could be nice to specify the type which will reflect the store. Currently, the state is inferred by the state initialization.
To be honest, it's already possible by this way : 
```ts
type MainStare = {
  counter: number;
  name: string;
}

export const useMainStore = createStore<string, MainState>({
  id: 'main',
  state: () => ({
    counter: 0,
    name: 'Edimitchel',
  }),
  // ...
})
```
As you can see, the current API forced us to specify the first generic type ([see here](https://github.com/posva/pinia/blob/master/src/store.ts#L164)).

### My request
**My simple request is following :** Could it be possible to swap [these two lines](https://github.com/posva/pinia/blob/master/src/store.ts#L163-L164) ?
_If accepted, I would create the PR_

The result would be like this (with a better usage if we have nested or optional state) : 

```ts
export type MainStare = {
  counter: number;
  name: string;
  team?: {
    name: string;
    createdAt?: Date;
  }
}

export const useMainStore = createStore<MainState>({
  id: 'main',
  state: () => ({
    counter: 0,
    name: 'Edimitchel',
    team: {
      name: 'Vue Community'
    }
  }),
  // ...
})
```
_______
I guess, following could be subject to another issue by amending the `createStore` signature :

```ts
export type MainStare = {
  counter: number;
  name: string;
  team?: {
    name: string;
    createdAt?: Date;
  }
}

export const useMainStore = createStore<MainState>('main', {
  state: () => ({
    counter: 0,
    name: 'Edimitchel',
    team: {
      name: 'Vue Community'
    }
  }),
  // ...
})
```

**Comment by rijkvanzanten** [comment]
> To be honest, it's already possible by this way :

Does that actually work? When I try it on my end I get a `Expected 4 type arguments, but got 2.` error

**Comment by edimitchel** [comment]
I didn't tried because of low bandwidth during the Vue Conference. But yes, it's logical that doesn't work. I've just said it's technically possible, not working ;)

**Comment by rijkvanzanten** [comment]
Oh my bad! I thought you said it was already possible in your original post 🙂  Happy conference!

**Comment by edimitchel** [comment]
@rijkvanzanten You've been right, the PR I proposed add defaults to others generic types

**Comment by MartinMalinda** [comment]
You can do 

```
export const useMainStore = createStore({
  id: 'main',
  state: (): MainState => ({
    counter: 0,
    name: 'Edimitchel',
  }),
  // ...
})
```

This approach works well for me.

**Comment by raphaelkieling-egsys** [comment]
Cool, but do have a way to specify a action? Because the action type is a `actions?: A & ThisType<A & StoreWithState<Id, S> & StoreWithGetters<S, G>>;` and i did:

```ts
// abstractCrudStore.ts

export interface AbsctractActions<T> {
  getList(): Promise<void>;
  deleteItem: (id: number) => void;
  save: (form: T) => void;
  edit: (id: number, form: T) => void;
}

const abstractCrudStore = <T>(params: AbstractCrudStoreParams) =>
  createStore({
    id: params.id,
    state: (): AbstractState<T> => ({
      pageName: params.pageName,
      list: [],
      baseUrl: params.baseUrl,
      loading: false,
      tableFields: params.tableFields,
      paginationControl: {
        currentPage: 1,
        perPage: 7,
      },
    }),
    getters: {
      pagination: (state) => ({
        totalPages: state.list.length / state.paginationControl.perPage,
        totalRows: state.list.length,
      }),
    },
    actions: {
      async getList() {
        this.state.loading = true;
        const { data }: any = await request.get(this.state.baseUrl);
        this.state.loading = false;
        this.state.list = data.params;
      },
      async deleteItem(id: number) {
        await request.delete(`${this.state.baseUrl}/${id}`);
        this.getList();
      },
      save(form: T) {
        return request.post(`${this.state.baseUrl}`, form);
      },
      edit(id: number, form: T) {
        return request.put(`${this.state.baseUrl}/${id}`, form);
      },
    } as AbsctractActions<T>,
  });

export default abstractCrudStore;
```

To type a state is as @MartinMalinda did but i a have a problem to type the actions, some ideia?

**Comment by posva** [comment]
I added https://github.com/posva/pinia/issues/85#issuecomment-631473019 to the documentation as a preferred way to do

**Comment by edimitchel** [comment]
Thanks, sorry for lacks of contribution.

**Comment by ghost** [comment]
<s>Weird. The same but with object method syntax does not have type safety even when just inferring (no interface):

```ts
import { createStore } from 'pinia';

export const userStore = createStore({
  id: 'userStore',
  state() {
    return {
      name: 'Pinia'
    };
  },
  getters: {
    // @ts-expect-error ts2339 (no error thrown, type of state param is any)
    nameCapitalized: (state, getters) => state.somethingThatDoesntExist.toUpperCase()
  }
})
```

whereas this has type safety and makes getter throw `ts2339` error

```ts
  state: () => ({
    name: 'Pinia'
  }),
```
</s>

Nevermind, I see the API changed to `getters: {nameCapitalized() { this.name.toUppercase() }}` in pinia 2
