### ISSUE TITLE
Typescript broken on pinia options api with composition-api 1.4.1

### ISSUE THREAD

**Issue by npbenjohnson** [posva/pinia#861]
New issue in composition api 1.4.1 released this morning, does not happen in 1.4.0.

### Steps to reproduce the behavior

1. Install 1.4.1 version of composition api
2. Define a pinia store via a setup function
3. Use mapState to reference the store in Vue 2

### Expected behavior

Mapped members should be regular properties

### Actual behavior

Typescript errors out as if mapped members are refs. Typescript error messages show that the property is believed to have the expected value, but it is nested under a "value" property as in: "{ value: "expected value" } cannot be assigned to "string""

### Additional information

vue@2.6.14
pinia@2.0.4
@vue/composition-api@1.4.1

**Comment by posva** [comment]
It seems to work:

<img width="418" alt="Screenshot 2021-12-03 at 11 43 55" src="https://user-images.githubusercontent.com/664177/144589531-b2b246f8-1576-47b2-b58b-572509acaf44.png">

open a new issue with a reproduction using one of the templates of https://github.com/piniajs/
