### ISSUE TITLE
Can provide a method to remove unreferenced stores at a page ?

### ISSUE THREAD

**Issue by DayDarkDark** [posva/pinia#862]
like vuex provide 'unregisterModule' to remove unreferenced stores?
For now I can do this like  `pinia._s.delete($id)`

why need this?
because i don't want to  unreferenced stores is always at state, cant auto remove , i want to reference count for remove unreferenced stores

**Comment by posva** [comment]
Use [`$dispose`](https://pinia.esm.dev/api/interfaces/pinia._StoreWithState.html#dispose), you still need to manually remove the state with `delete pinia.state.value[storeId]`.

Please, next time, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
