### ISSUE TITLE
TypeScript peer dependency version should be more permissive to avoid breaking changes

### ISSUE THREAD

**Issue by haoqunjiang** [posva/pinia#874]
### Steps to reproduce the behavior

1. Use npm 7+
2.
```sh
npm init vue@3.0.0 issue-reproduction
cd issue-reproduction
npm i
```
3. See error

### Expected behavior

Shouldn't error because `"typescript": "~4.4.4"` was a valid peer dependency of `pinia` 2.0.4.  It shouldn't break with a patch release.

### Actual behavior

See https://github.com/vuejs/create-vue/issues/18

### Additional information

Technically, bumping a peer dependency version is a breaking change.

Renovate supports ignoring peer dependencies by the following configuration:
https://docs.renovatebot.com/presets-default/#disablepeerdependencies

The reason that `create-vue` pins `typescript` to a minor version is because it does not follow semver (https://github.com/microsoft/TypeScript/issues/14116#issuecomment-280410804). New type errors may appear after a minor bump.

So, a good practice of using TypeScript in a library is:
- keeping the devDependencies version up-to-date so that it can catch as many type errors as possible
- but only requiring the lowest possible version of TypeScript to be the peer dependency, as long as it is able to parse the type declarations

**Comment by posva** [comment]
Yeah, this wasn’t intended. Thanks for the link to the renovate config. I’ll add it to my config and change the peer dep version and release a new patch

**Comment by posva** [comment]
seems to work now!
