### ISSUE TITLE
Getters returning null after updating state

### ISSUE THREAD

**Issue by Xexnon** [posva/pinia#881]
### Reproduction

Initialising and empty state then adding data but the getters still returns null after the state has been populated

### Steps to reproduce the behavior

```
export const useLogin = defineStore('login_info', {
  state: () => ({
    
  } as any),
  getters: {
    getUserId: (state) => state.userId
  },
  actions: {
    setUser (params: any) {
      this.$state = {
        ...params
      }
    }
  },
  persist: true
})
```

```
setup () {
  const login = useLogin()
  function addUser () {
    login.setUser({
      name: 'fdd',
      userId: 1
    })
  }
  console.log(login.$state.userId)
  console.log(login.getUserId)
  const user = computed(() => login.getUserId)
  console.log(user.value)
  addUser()
  return {
    login,
    user
  }
}
```

### Expected behavior
`login.$state.userId` returns the state
`login.getUserId` returns the state
`const user = computed(() => login.getUserId)` returns the state

### Actual behavior
`login.$state.userId` returns the state
`login.getUserId` returns null
`const user = computed(() => login.getUserId)` returns null

A clear and concise description of what actually happens.

### Additional information

```
export const useLogin = defineStore('login_info', {
  state: () => ({
    user: {}
  } as any),
  getters: {
    getUserId: (state) => state.user.userId || null
  },
  actions: {
    setUser (params: any) {
      this.$state.user = {
        ...params
      }
    }
  },
  persist: true
})
```
if i do this 

### Expected behavior
`login.$state.userId` returns the state
`login.getUserId` returns the state
`const user = computed(() => login.getUserId)` returns the state

### Actual behavior
`login.$state.userId` returns the state
`login.getUserId` returns the state
`const user = computed(() => login.getUserId)` returns the state

works correctly what could be the problem

**Comment by posva** [comment]
You need to set the initial state to `null` or `undefined`: `state: () => ({ userId: null })`

**Comment by Xexnon** [comment]
> You need to set the initial state to `null` or `undefined`: `state: () => ({ userId: null })`

The issue has not be resolved you cant just close it
 
The reason why the state is empty is because theres so much data coming from the api and i need an empty state first userId is just part of the response

**Comment by posva** [comment]
If you have a response coming from the server and it can have multiple properties that are unknow at build time, you can set a property on the object instead of replacing the whole `$state`:

```js
defineStore('id', {
  state: () => ({ user: null }),
  actions: {
    setUser(user) {
      this.user = user
    }
  }
})
```

**Comment by posva** [comment]
It seems like GitHub is bugging when transforming this into discussion but still locking it 🥲
