### ISSUE TITLE
@pinia/nuxt doesn't work with nuxt bridge

### ISSUE THREAD

**Issue by caikan** [posva/pinia#889]
### Reproduction

https://codesandbox.io/s/brave-danilo-n1de5

### Steps to reproduce the behavior

Create a project with nuxt-bridge and @pinia/nuxt.
`npm run dev`
Open in browser.

### Expected behavior

No error.

### Actual behavior

```
500
Cannot read properties of undefined (reading 'install')
at Function.Vue.use (file://./.nuxt/dist/server/server.mjs:7842:23)
at $id_c39524e4 (file://./.nuxt/dist/server/server.mjs:20715:7)
at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:20913:3)
```

### Additional information

N/A

**Comment by posva** [comment]
This is because your app is empty: no app.vue or pages/index.vue. Here is a working example: https://github.com/piniajs/example-nuxt-bridge

**Comment by caikan** [comment]
I tried again. I found that it's because I turned on the `vite` option, not no app.vue or pages/index.vue.

**Comment by posva** [comment]
Can you try out if https://github.com/posva/pinia/pull/781 fixes it for you?

**Comment by caikan** [comment]
I checked out [https://github.com/tobiasdiez/pinia/tree/patch-1](https://github.com/tobiasdiez/pinia/tree/patch-1), and built locally by `yarn run build`, then `npm link @pinia/nuxt` in the repro, but the problem still exists.

**Comment by BobbieGoede** [comment]
I managed to workaround the `Cannot read properties of undefined (reading 'install')` issue by adding an alias to the vite config in `nuxt.config`. This gave me a different error: `[vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.`

Adding the following to `nuxt.config` got rid of both errors for me.
```
vite: {
    optimizeDeps: {
        exclude: ['pinia'],
    },
    resolve: {
        alias: {
            pinia: path.resolve(__dirname, './node_modules/pinia/dist/pinia.mjs'),
        },
    },
}
```

**Comment by psycongaroo** [comment]
same problem

**Comment by psycongaroo** [comment]
with vite is getting the error:

`Cannot read properties of undefined (reading 'install')
at Function.Vue.use (file://./.nuxt/dist/server/server.mjs:7842:23)
at $id_c39524e4 (file://./.nuxt/dist/server/server.mjs:20715:7)
at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:20913:3)`
