### ISSUE TITLE
HMR Not Working, Even in Demo

### ISSUE THREAD

**Issue by AaronBeaudoin** [posva/pinia#898]
### Reproduction

1. Open [demo](https://stackblitz.com/github/piniajs/example-vue-3-vite).
2. Go to `src/stores/user.js` and change `state.name`.
3. Nothing happens in the preview.

### Steps to reproduce the behavior

Above.

### Expected behavior

The state changes (and file is saved) = the preview changes.

### Actual behavior

The state chances, the preview doesn't (until reloaded).

### Additional information

I only realized this after I followed the HMR instructions in the docs for my own project and nothing happened. Then I realized that not even the demo works, so I'm pretty sure HMR is completely broken.

**Comment by posva** [comment]
That's expected because the state was already there. If we change it, it will defeat all purpose of HMR by **always** resetting your state to the initial value. You can change the state at any time within the devtools
