### ISSUE TITLE
[Devtool] An error occurred in hook getInspectorTree registered by plugin org.vuejs.vue2-internal

### ISSUE THREAD

**Issue by mashirozx** [posva/pinia#905]
### Reproduction

https://git.moezx.cc/mashiro/agk-common/src/commit/a83ee7467596978d5d7d41e38b4bd5837d5f6598

Reproduction on commit tree `a83ee7467596978d5d7d41e38b4bd5837d5f6598` 

### Steps to reproduce the behavior
```
    "pinia": "^2.0.6",
    "vue": "^2.6.14",
```

Devtools: 6.0.0 beta 20

`useTagsStore` in a layout component [code here](https://git.moezx.cc/mashiro/agk-common/src/commit/a83ee7467596978d5d7d41e38b4bd5837d5f6598/src/layouts/components/Tabs.vue#L16)

### Expected behavior

No error or warnings in browser console

### Actual behavior

![image](https://user-images.githubusercontent.com/16148054/146484138-0da22b18-5916-43f3-b128-190f0ef9b3ac.png)

### Additional information

I tried to use store with a setTimeout for 200ms, then it works without error, but this is not what I expected.

![image](https://user-images.githubusercontent.com/16148054/146485046-e4f7d88a-f977-40d0-88ae-bfbd63d71e78.png)

Seems there is issue for DevTools to detect Vue app instance when initializing the store.

**Comment by posva** [comment]
As stated in the issue template I need a boiled down repro. Let me know if you find one. Moving this to a discussion.
