### ISSUE TITLE
$subscribe does not unsubscribe when component is unmounted

### ISSUE THREAD

**Issue by Ravadre** [posva/pinia#908]
### Reproduction

Please check a code here: https://stackblitz.com/edit/github-xisbaz-gpblyq?
It's a simple fork of a bug template provided with changes:
Added component that subscribes to store
Added button to mount / unmount a component

### Steps to reproduce the behavior

1. Click increment - observe that console logs a statement "Subscribe called" once (expected)
2. Click show/hide component twice to unmount and mount component again - console logs unmounted to prove that the component did unmount
3. Click increment - observe, that "Subscribe called" is called twice with the same state.
4. You can repeat steps 2 and 3 to multiply duplication further.

### Expected behavior

Based on documentation from https://pinia.esm.dev/core-concepts/state.html#subscribing-to-the-state: 
> By default, state subscriptions are bound to the component where they are added (if the store is inside a component's setup()). Meaning, they will be automatically removed when the component is unmounted.

expected behaviour is that when components unmounts, $subscribe will unmount, so subscribing again will have no duplicate handlers.

### Actual behavior

$subscribe does not unsubscribe on component unmount - leading to duplication of $subscribe handlers.

**Comment by posva** [comment]
As a workaround, you can use `store.$patch()` instead of directly modifying the store

**Comment by Ravadre** [comment]
Hi,

sorry for reopening - I thought it might be worthwhile to let you know. I tried changing direct modification to use $patch, please see:

https://stackblitz.com/edit/github-xisbaz-gpblyq?file=src%2FApp.vue

(I updated template's direct store modifiction to use $patch instead).

It didn't work as a workaround, it actually made it worse for some reason. Now, $subscribe callback is called twice at first for each $patch applied. And the behavior described originally still stands - remaking a component adds +1 handler registered. 

It might be fixed with your commit though, I haven't test it yet with your patch applied.

**Comment by posva** [comment]
~~Maybe a HMR bug?~~

**Comment by Ravadre** [comment]
I just tried vite build + vite serve locally (on my project, not repro linked on stackblitz though) and I can confirm I have the same behavior as presented there, so I assume it's not HMR. Is there a way to inspect live handlers for $subscribe, so really confirm that they are not being disposed?  

Just a reminder - I'm using Pinia 2.0.6, not bleeding edge, so it might be fixed by a9ef6b6 already. I thought it might be useful to point out, that $patch triggers $subscribe twice even at the beginning - it might be something else entirely. 

I will make some experiments and dive deeper after new release and let you know.

**Comment by Ravadre** [comment]
Hi @posva 

checked the bug with Pinia v. 2.0.7 - $subscribe is correctly unsubscribing, so there's no more duplication when components are reattached during app's life, awesome, thank you!

I still though see that $subscribe is called twice if update is done through $patch (but only once if through direct state modification). If this behavior is by design, it might be worth documenting maybe, as if someone is making any side effects in $subscribe (like fetches), it might lead to other bugs.

I've updated sample at https://stackblitz.com/edit/github-xisbaz-gpblyq?file=src%2FApp.vue 
to allow easily changing between 3 possible state update methods for increment button ($patch through object, $patch through method, direct state mutation). For both $patch methods, $subscribe is called twice, for direct state - once.

**Comment by posva** [comment]
Fixed at 3bfe9e5
