### ISSUE TITLE
@pinia/nuxt@0.1.7 does not work with nuxt bridge

### ISSUE THREAD

**Issue by brolnickij** [posva/pinia#912]
### Reproduction

https://codesandbox.io/s/agitated-cdn-cszk6?file=/package.json

### Steps to reproduce the behavior

1. Go to reproduction link
2. Rebuild sandbox
3. See error

### Expected behavior

Application must build without errors

### Actual behavior

Application is build with errors

### Additional information

After updating these dependencies
```
@pinia/nuxt  ^0.1.6  →  ^0.1.7     
pinia        ^2.0.6  →  ^2.0.7 
```

the following error occurred 

<img width="665" alt="Screenshot 2021-12-20 at 21 55 26" src="https://user-images.githubusercontent.com/10180323/146818854-eea3887b-872f-4690-bf07-0609ad5450f7.png">

P.S. @pinia/nuxt@0.1.6 and pinia@2.0.6 work without errors

**Comment by posva** [comment]
This is really weird as that release shouldn't contain any changes. Maybe a bug with one of the dependencies

**Comment by brolnickij** [comment]
@posva thank you!
