### ISSUE TITLE
feat: root state `$reset`

### ISSUE THREAD

**Issue by reslear** [posva/pinia#913]
hi @posva you did not think, about add `$reset` for root state, like forEach all stores and call $reset
but more effective and with simple sugar api like:

```ts
// draft reset any stores 
pinia.$reset()
```

now i'm use:
```ts
profileStore.$reset()
keysStore.$reset()
settingsStore.$reset()
eventsStore.$reset()
```

**Comment by reslear** [comment]
i'am find temp solution

```ts
export const resetPiniaStores = () => {
  pinia._s.forEach((_) => _.$reset())
}
```

 is good?

**Comment by posva** [comment]
Yes, you can add that function on your own. Note setup stores do not have a reset method implemented by default too. That’s why there is no global reset either

**Comment by reslear** [comment]
@posva thx

1. maybe check is have `$reset` method like this?

```ts
export const resetPiniaStores = () => {
  pinia._s.forEach((_) => typeof _.$reset === "function" && _.$reset())
}
```

2. add this to docs?
