### ISSUE TITLE
storeToRefs should accept an array of requested props

### ISSUE THREAD

**Issue by davidmeirlevy** [posva/pinia#916]
### What problem is this solving
Let's say I have a store:

```js
const demoStore = defineStore('demo', () => {
  const foo = ref('foo');
  const bar = ref('bar');
  const baz = ref('baz');

  return {foo, bar, baz};
});
```

Now I want to use this store ,but not all of it, for example:
```js
setup() {
    const {foo, baz} = storeToRefs(demoStore());
    ...
}
```

The `storeToRefs` will still wrap `bar` with the `toRef` wrapper, and i want to avoid it since it's not in use at this component.

### Proposed solution
`storeToRefs` can get second argument of selected props, for example:
```js
setup() {
    const {foo, baz} = storeToRefs(demoStore(), ['foo', 'baz']);
    ...
}
```

### Describe alternatives you've considered
Maybe something like (will update the store changes inside the given reactive);
```js
setup() {
    const neededDataFromStore = reactive({foo: null, baz: null});
    storeToReactive(demoStore(), neededDataFromStore);
    ...
}
```

**Comment by posva** [comment]
I don't think this is necessary for the same reasons there isn't an equivalent version of `toRefs()` with an array parameter. You could still implement your own `storeToRefs()` that does this and compare the perf in production + the size difference

**Comment by Luferov** [comment]
`storeToRefs` does't work with ssr. Value in first time is undefined, then value equals state from pinia.
Now, i use toRefs & toRef and it's work. Maybe it help you.

**Comment by posva** [comment]
Closing this as I don't think it will be implemented.
