### ISSUE TITLE
[DOCS] Websit font

### ISSUE THREAD

**Issue by gaokun** [posva/pinia#928]
Hi, the `font family` of websit is weird.

Is this work as designed?

![image](https://user-images.githubusercontent.com/7044628/147384525-99b68147-db4e-42aa-987e-da715fc06175.png)

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏 this is already being discussed

**Comment by gaokun** [comment]
Sorry for that, Yes, found it in #873.
