### ISSUE TITLE
Weird behavior with SSR

### ISSUE THREAD

**Issue by thierrymichel** [posva/pinia#941]
Hi all,

I am super happy to make our stack evolve and move from `vuex` to `pinia` (as well as moving from `vue2` to `vue3` and  from `webpack` to `vite`) 😁.
Thanks for the great job! 🙏

Almost everything is perfect except one weird behaviour.
Nothing blocking but I would like to have your lights to understand… 😇

Thanks in advance,
Thierry

---

### Reproduction

Clone this repo : [pinia-vite-ssr-issue](https://github.com/thierrymichel/pinia-vite-ssr-issue) and use `yarn dev`

### Steps to reproduce the behavior

Check the logs and the browser.

### Expected behavior

Store instance should have 1 item (as initial state and active pinia instance do).

![image](https://user-images.githubusercontent.com/806883/148369852-440a5d55-89a8-4c4b-99bd-dda7cc6b7601.png)

![image](https://user-images.githubusercontent.com/806883/148369813-ff47b8a8-6dd6-4f0f-a58b-69578b2a3422.png)

### Actual behavior

Store instance is empty.

![image](https://user-images.githubusercontent.com/806883/148369917-126b8ee0-72dd-47db-b89e-5eca0d37b3d3.png)

### Additional information

I've added comments and snippets inside the `README` file.

**Comment by posva** [comment]
I’m glad you like it!
There is too much code for the reproduction, can you remove all the routing part and make the code smaller so I can check?
