### ISSUE TITLE
Allow bypassing getters in `@pinia/testing`

### ISSUE THREAD

**Issue by posva** [posva/pinia#945]
- From https://github.com/vuejs/pinia/discussions/944

There should be a way to bypass any getter when testing components that use a store.

Some Ideas:

- use the `createTestingPinia()` to add a plugin that allows modifying any getter:

  ```js
  // in a test
  const store = useStore()
  store.myGetter // getter computed value
  store.myGetter = newvalue
  store.myGetter // newvalue
  ```

- Maybe a different way to pass options specific to stores:

  ```js
  createTestingPinia({ overrides: [
    [useSomeStore, { getters: { /* autocompletion */ stuff: ... }}]
  ] })
  ```

**Comment by bodograumann** [comment]
This! A thousand times this!

I am in favor of the first variant, because the stubbing might happen in a different place from where the testing pinia was created.

Until today I was using `store.$patch`, which works and passes type-checking as long *all* of the store properties are read-only. (Probably not intended.) (Addendum: when the store only contains actions and getters, type checking for `$patch` is “working” even when overwriting those getter values. When even one of the getters is replaced by a `reactive`–even a `readonly(reactive())`–type checking breaks.)

**Comment by JJBocanegra** [comment]
This isn't working properly with Typescript.

```ts
// store.ts
import { defineStore } from 'pinia';

export const useStore = defineStore('store', {
  getters: {
    foo: () => true,
  },
});
```

```ts
// test.ts
import { createTestingPinia } from '@pinia/testing';
import { useStore } from 'store.ts';

describe('Test', () => {
  const pinia = createTestingPinia();
  const store = useStore(pinia);

  // Error TS2540: Cannot assign to ' foo' because it is a read-only property
  store.foo = false;
});
```

To fix this I needed to add the next line just above each getter modification
```ts
 // @ts-expect-error: Getter is read only
```

## Versions
- typescript: 4.7.3
- pinia: 2.0.16
- @pinia/testing: 0.0.12

**Comment by bodograumann** [comment]
I am doing the following now (latest version 2.0.17):

```typescript
type Mocked<T> = { [P in keyof T]: ReturnType<typeof jest.fn> };
function mocked<Id extends string, S, G, A>(store: Store<Id, S, G, A>): S & UnwrapRef<G> & Mocked<A> {
  /* eslint-disable-next-line @typescript-eslint/ban-ts-comment -- the new type is due to `app.use(createTestingPinia())` */
  //@ts-ignore
  return store;
}

describe('Test', () => {
  const pinia = createTestingPinia();
  const store = mocked(useStore(pinia));

  store.foo = false;
});
```

**Comment by JJBocanegra** [comment]
@posva can this issue be reopened or should I create a new one? I'm still fighting with this issue.

**Comment by Kaperskyguru** [comment]
I'm also struggling with it myself.

**Comment by damafeez** [comment]
> This isn't working properly with Typescript.
> 
> ```ts
> // store.ts
> import { defineStore } from 'pinia';
> 
> export const useStore = defineStore('store', {
>   getters: {
>     foo: () => true,
>   },
> });
> ```
> 
> ```ts
> // test.ts
> import { createTestingPinia } from '@pinia/testing';
> import { useStore } from 'store.ts';
> 
> describe('Test', () => {
>   const pinia = createTestingPinia();
>   const store = useStore(pinia);
> 
>   // Error TS2540: Cannot assign to ' foo' because it is a read-only property
>   store.foo = false;
> });
> ```
> 
> To fix this I needed to add the next line just above each getter modification
> 
> ```ts
>  // @ts-expect-error: Getter is read only
> ```
> 
> ## Versions
> * typescript: 4.7.3
> * pinia: 2.0.16
> * @pinia/testing: 0.0.12

Unfortunately, this doesn't seem to work when your getters are defined as `computed`.

**Comment by sebakocz** [comment]
any workarounds or solutions for this?

**Comment by lbineau** [comment]
If you are using Jest, I've bypassed it like that (probably because Typescript has lost track):
`jest.spyOn(store, 'foo').mockImplementationOnce(() => false)`
Maybe not the best workaround but doesn't trigger any error on my end. 
If you are using another framework there should be something similar to mock object methods.

**Comment by Derasm** [comment]
This is also a problem for me - using the workaround with " // @ts-expect-error: Getter is read only" above only silences the typescript error, it doesn't make the getter actually function.

**Comment by darkychin** [comment]
If you are currently using `vitest`.
You can do something below to stop typescript from complaining when you override its getters.
```
// store.ts
import { defineStore } from 'pinia';

export const useStore = defineStore('store', {
  getters: {
    foo: () => true,
  },
});
```
```
// store.spec.ts
const pinia = createTestingPinia()

const store = vi.mocked(useStore(pinia))

store.foo =  false // no complain
```

**Comment by mediafreakch** [comment]
For parametrized getters this returns `'set' on proxy: trap returned falsish for property 'myGetter'`:

```
defineStore('test', {
 getters: {
  myGetter:
      (state) =>
      (id: string): string => {}
 }
}

// in jest
jest.spyOn(store, 'myGetter').mockReturnValue('foo')
```

**Comment by venux92** [comment]
to bypass the error for me I had to do

```js
let store: Record<string, any>;

beforeEach(() => {
  setActivePinia(createTestingPinia());
  store = useStore();
});
```

then later in a test

```js
// For normal getters 
store.isAvailable = true

// For parametrized getters 
storetore.isAvailableAddOn = jest
  .fn()
  .mockReturnValue(false);

```

And I don't have any errors and the getter is correctly overwritten.
