### ISSUE TITLE
how to resolve refresh the loss?

### ISSUE THREAD

**Issue by zhoufanglu** [posva/pinia#968]
### What problem is this solving

how to resolve refresh the loss? 

### Proposed solution
likeness `vuex-persistedstate` in `vuex`

**Comment by soc221b** [comment]
There are some packages for persistence:
1. https://github.com/Seb-L/pinia-plugin-persist
2. https://github.com/prazdevs/pinia-plugin-persistedstate

If you want, I wrote a package: [pinia-plugin-persistedstate-2](https://github.com/iendeavor/pinia-plugin-persistedstate-2#pinia-plugin-persistedstate-2) for this too, you may take a look.

Hope this helps people who need this.

**Comment by zhoufanglu** [comment]
> There are some packages for persistence:
> 
> 1. https://github.com/Seb-L/pinia-plugin-persist
> 2. https://github.com/prazdevs/pinia-plugin-persistedstate
> 
> If you want, I wrote a package: [pinia-plugin-persistedstate-2](https://github.com/iendeavor/pinia-plugin-persistedstate-2#pinia-plugin-persistedstate-2) for this too, you may take a look.
> 
> Hope this helps people who need this.

Thank you for your answer, which perfectly solves my question
