### ISSUE TITLE
Autocomplete/intellisense/types for "actions" in defineStore() typed as "any" (missing)

### ISSUE THREAD

**Issue by nurdism** [posva/pinia#981]
You can actually see this in the demo projects on [stackblitz](https://stackblitz.com/github/piniajs/example-nuxt-3?file=stores%2Fcounter.ts), when writing a func in actions, `this` is typed as `any` and doesn't provide any autocomplete/intellisense/types

![](https://i.imgur.com/m4AGnZu.png)

```ts
export const useCounter = defineStore({
  id: 'counter',
  state: () => ({
    n: 2,
  }),
  getters: {
    double: (state) => state.n * 2,
  },
  actions: {
    increment(amount = 1) {
      this.n += amount // this is "any", not typesafe
    },
  },
})
```

**Comment by posva** [comment]
It was missing the `strict: true` in the TS config

**Comment by Asarew** [comment]
even with `strict: true` the error is still there.

**Comment by Bornegrim** [comment]
Try setting `noImplicitThis` to `true` in your TS config.

**Comment by realityfilter** [comment]
I was hitting this problem after refactoring a mono repo. The original package had the `strict: true` setting while the new one had not. Why is this necessary? I think this should be in the docs. It is hard to find the origin of this configuration error.

**Comment by dulimarta** [comment]
I had a similar issue in my TypeScript code and was able to get around it by typecasting the actions to `ThisType<MyAppState>` something like:

```ts
type MyAppState = {
  counter: number;
}


export const useCounter = defineStore("xyz", {
  state: (): MyAppState => ({
    counter: 0
  }),
  action: {
    increment() {
    }
  } as ThisType<MyAppState>
});
```
