### ISSUE TITLE
Plugins no longer able to modify action results

### ISSUE THREAD

**Issue by theoephraim** [posva/pinia#995]
Awaiting an action no longer waits for a plugin's $onAction after function to be finished.
This also means that plugins are no longer able to modify action results.

I was previously using v2.0.6 and the issue was present only when opening the vue devtools (I assume due to conflicts from multiple onAction handlers), and when I upgraded to the latest version (2.0.9), it is now consistently happening all the time.

EDIT - Digging through old issues and I see that this change may be intentional?

If that is the case, the [docs](https://pinia.vuejs.org/core-concepts/actions.html#subscribing-to-actions) are now misleading.

I'd say from the way I have been using the onAction after hook, this was quite unexpected and breaks my plugin completely. I would expect multiple onAction/after functions to be called in the order they were registered, each able to modify the result as they please.

### Reproduction

See https://stackblitz.com/edit/github-nxmtgp

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/github-nxmtgp
2. Click on "Open in new window" and open the js console in that window
3. click increment

### Expected behavior

I would expect that awaiting an action would wait for the async after handler to finish and that the plugin modified result would be returned.

This would result in the following logs:
- p2 - onAction start
- increment - raw action result |  increment @ 1
- p2 - onAction after
- p2 - modified result =  (p2) increment @ 1
- increment - returned action result | (p2) increment @ 1

### Actual behavior

The unmodified action result is returned before the after handler is finished.

Observed logs:
- p2 - onAction start
- increment - raw action result |  increment @ 1
- p2 - onAction after
- increment - returned action result | increment @ 1
- p2 - modified result =  (p2) increment @ 1

### Additional information

I've added 2 plugins, one async and one sync, because I wanted to check if that was causing the issue - it is not.

If enabling both plugins, I would expect both to be able to modify the action result, probably in the order they were registered, which would mean the final result should be something like `(p2) (p1) increment @ 1`

**Comment by posva** [comment]
This was indeed [intentional and present in the changelog](https://github.com/vuejs/pinia/commit/4dc1f1bec8f3db508c02fa6bdcc8203f280cbb3e), I've updated the documentation to reflect this. **The old behavior can be achieved through a plugin** when it comes to overriding the returned value for actions but as mentioned in the commit

**Comment by theoephraim** [comment]
@posva thanks for clarifying and updating the docs!

In order to accomplish the same thing, I'll need to override _every_ action with a small wrapper that does what I used to do in my "after" function. From what I can tell, there is not an easy way to get the list of action names to be able to do that, and I think it may take adding a new key, something like `_actionNames` which holds an array of the names of all the actions registered via `defineStore`?

I think a more complete example may be helpful in the docs, as the current debounce example assumes you know the names of the actions you wish to overwrite and specify them explicitly.

And again, thanks for all your work on this tool!

---

Some more context for you, to help in terms of thinking about plugins and the role of something like onAction/after handler.

My plugin helps with making API requests and tracking the status of those requests.
- it adds a new object to the store's state to track each raw request status (requestedAt, completedAt, params, error, etc), with requests either being keyed by a single request name (ex: 'LOGIN') or a name plus some params (ex: 'GET_USER' + 'u123')
- it adds a function to return a computed value which gets the latest status for a given key, in a format that's easier to use in components (isPending, isError, errorMessage, etc)
- an action can return an ApiRequest object, which is essentially a description of the api request (url, method, params, success handler which can modify the store, etc)
- the plugin checks if an action result is an ApiRequest object, and if so, triggers the api request, modifies the status store along the way to mark it pending, successful, handle errors, etc), and handles any other common needs of making api requests
- for example, it will ignore duplicate requests that are already pending

An example simple store using this plugin
```
export const useUsersStore = defineStore('users', {
  state: () => ({
    usersById: {} as Record<string, User>,
    selectedUserId: null as string | null,
  }),
  getters: {
    users: (state) => _.values(state.usersById),
    selectedUser: (state) => (state.selectedUserId ? state.usersById[state.selectedUserId] : null),
  },
  actions: {
    GET_USER(userId: string) {
      this.selectedUserId = userId;
      return new ApiRequest<User>({
        method: 'get',
        url: `/users/${userId}`,
        keyRequestStatusBy: userId,
        onSuccess: (response) => {
          this.usersById[response.id] = response;
        },
      });
    },
    LOAD_ALL_USERS() {
      return new ApiRequest<User[]>({
        method: 'get',
        url: `/users`,
        onSuccess: (response) => {
          this.usersById = _.keyBy(response, 'id')
        },
      });
    },
    ...
  },
})
```


And an example of the helper to get request statuses:
```
const loadUserRequest = usersStore.getRequestStatus('GET_USER', props.userId);
const loadAllUsersRequest = usersStore.getRequestStatus('LOAD_ALL_USERS');
```

Those request statuses have a known shape which can be built into components as well, for example having a button show a loading state and change to a quick success message, or having an error alert that shows only if the request failed, all by passing in the request status object.
`<VButton :request-status="getAllUsersRequest" pending-text="loading users...">Load all users</VButton>`

**Comment by posva** [comment]
You can actually get the actions by looping through options.actions (option stores) of by looping thought the functions on the store that do not start with $ or _ (setup stores).  For example the devtools plugin wraps all actions in option stores.
I hope this helps you find the way! 🙂

**Comment by theoephraim** [comment]
@posva - oh! I  totally overlooked that I have access to the "options" in the plugin. I had it working in the more crude way (looking at the names) but I thought that could create conflicts with other functions added by other plugins. Thanks for the tip!

I'll open a PR to the docs with a small example to hopefully help others in the same situation.
