### ISSUE TITLE
Using `$patch` within a Pinia plugin does not show event in devtools timeline

### ISSUE THREAD

**Issue by Matt-Deacalion** [posva/pinia#996]
### Reproduction

https://github.com/Matt-Deacalion/pinia-devtools-bug

### Steps to reproduce the behavior

1. `git clone git@github.com:Matt-Deacalion/pinia-devtools-bug.git`
2. `cd pinia-devtools-bug`
3. `npm install && npm run dev`
4. go to: http://localhost:3000/
5. open vue devtools, see pinia timeline

### Expected behavior

Using `$patch` within a Pinia plugin would show up in Vue devtools within the Pinia timeline.

### Actual behavior

No `$patch` event is shown.

### Additional information

Vue devtools: **6.0.0-beta.21** 
Firefox: **96**
Chromium: **97.0.4692.71**

**Comment by posva** [comment]
This is intentional: subscriptions are activated [after plugins](https://github.com/vuejs/pinia/blob/v2/packages/pinia/src/store.ts#L713).

Maybe we could add a short note about this at https://pinia.vuejs.org/core-concepts/plugins.html#adding-new-state

**Comment by Matt-Deacalion** [comment]
Ah, I see. Is this to prevent cluttering of the timeline?

[Pull request](https://github.com/vuejs/pinia/pull/1002)
