### ISSUE TITLE
Allow module in setup store

### ISSUE THREAD

**Issue by arnoson** [posva/pinia#997]
### What problem is this solving

I just read about setup stores and I really like the API! But with a complex store returning state, getters and actions can become verbose. It would be great to be able to define a setup store from a module.

### Proposed solution

Pass a module to `defineStore` directly.

```js
// setup.js
export const count = ref(0)
export const increment = () => count.value++
```

```js
// store.js
import * as setup from './setup.js'
export const useStore = defineStore('my-store', setup)
```

### Describe alternatives you've considered

Right now this is possible with a small workaround:
```js
// store.js
import * as setup from './setup.js'
// Destructuring is necessary, because a module is not allowed, only an object.
export const useStore = defineStore('my-store', () => ({ ...setup })
```

**Comment by posva** [comment]
This is not possible because the ref, computed, etc creation **must happen** within the function passed to defineStore

**Comment by arnoson** [comment]
Okay, thanks for the info!
